'use client';
import data from '../content/belonging-sequence.json';
import {CommunityPracticeLinks} from './community-practice';
import './community-practice.css';
export default function BelongingSequence({projector=false}:{projector?:boolean}){
 const mode=projector?'&mode=student':'';
 return <section className="practice-page belonging-sequence"><CommunityPracticeLinks projector={projector}/>
 <header><p>BELONGING &amp; COMMUNITY · OUR LEARNING THREAD</p><h1>{data.question}</h1><p>Connected lessons for several days and weeks. Revisit our commitments after real activities and change what is not working.</p></header>
 <div className="belonging-chapters">{data.chapters.map(c=><article className="practice-teacher" key={c.title}><p><strong>{c.time}</strong></p><h2>{c.title}</h2><p>{c.description}</p><p><b>What we will show:</b> {c.evidence}</p><a href={c.href+(c.href.startsWith('?')?mode:'')}>{c.label} →</a></article>)}</div>
 <section className="practice-teacher"><h2>4 · A fair chance to take part</h2><p><b>Equality:</b> the same thing or rule for everyone. <b>Equity:</b> responding to barriers so people have a fair chance. <b>Accessibility:</b> designing spaces, information and activities so people can use them. These ideas can overlap; planned choices do not replace individual support.</p><p>For the 10-minute opening, read one case below. Compare the plans, explain a barrier each removes, and name what still needs checking. Then open Barrier Detectives for the Access Makeover.</p><div className="belonging-cases">{data.fairness.map(c=><details key={c.title}><summary>{c.title}</summary><p>{c.text}</p><p><b>Discuss:</b> {c.question}</p></details>)}</div></section>
 <section className="practice-teacher"><h2>Use the materials we already have</h2><ul>
 <li><a href="printables/belonging-barrier-redesign.pdf" target="_blank" rel="noreferrer">New companion · mini-poster, barrier cards, fairness cards and class commitment chart (5 pages)</a>. Monday: project or print page 1, choose cards from pages 2–3, and use one class copy of page 5. Save page 4 for lesson 4.</li>
 <li><a href="https://dlwyatt-eng.github.io/equity-hub/downloads/lesson-belonging-builder-black-white.pdf">Existing Belonging Action Studio</a>: page 2 offers a fuller drawing task on another day; page 3 is an alternative commitment chart. Choose one chart.</li>
 <li><a href="https://dlwyatt-eng.github.io/equity-hub/downloads/lesson-barrier-detectives-black-white.pdf">Existing Access Makeover Lab</a>: pages 1–3 for lesson 4, pages 4–5 for the teacher. Read and critique the rushed instructions rather than attempting them if that is more useful.</li>
 <li><a href="https://dlwyatt-eng.github.io/equity-hub/#lesson/belonging-built">Existing Belonging is built lesson</a>: an optional later studio or 7–12 minute check-back, not a second required Monday lesson.</li>
 <li><a href="https://dlwyatt-eng.github.io/equity-hub/#rights">Racism, Human Rights &amp; Freedom of Expression</a> · <a href="https://dlwyatt-eng.github.io/equity-hub/#action">Student action and Leadership &amp; Spirit Club</a>.</li>
 </ul></section>
 <section className="practice-teacher"><h2>Bring the question back across our year</h2>{data.connections.map(c=><div key={c.title}><h3>{c.title}</h3><p>{c.text}</p></div>)}</section>
 {!projector&&<aside className="practice-teacher"><h2>Prepare and check</h2><p>Keep Monday to its six cards and 30 minutes. Use one shared chart; no class set or devices needed. Teach Agreements and NVC in separate later blocks after the specialist schedule is confirmed. Before the next activity, ask what people want to do and what conditions help. Do not infer abilities, ask for diagnoses or require personal stories.</p><p>Offer read-aloud, large print, pointing, drawing, speech, dictation and optional supported writing. Model with fictional examples. Check ideas for a named barrier, a useful change, meaningful contribution to the shared goal and a way to gather feedback. Students can pass publicly and contribute privately. An adult ensures access; a class vote cannot remove it.</p><p>At the next community lesson, spend five minutes checking the two commitments. Keep a class record of actions and what changed, without names or private access needs. Selected learning can later go to SpacesEDU when ready; no upload is required.</p></aside>}
 </section>;
}
