export type CaptainRoute = {
  id: string; title: string; purpose: string; materials: string; finish: string;
  steps: { title: string; action: string; check: string }[];
};
export const captainRoutes: CaptainRoute[] = [
  {id:'chores',title:'Weekly classroom responsibilities',purpose:'Organize a shared job, help the team complete it and leave useful instructions for the next team.',materials:'This week’s teacher-approved classroom jobs, the labelled storage places and paper or the class board.',finish:'A completed job, a check against the agreed standard and a useful handover.',steps:[
    {title:'Agree on the job',action:'Read this week’s assigned chores. Choose who will do each part and when. Ask the teacher to clarify any task you do not understand. Example: equipment return means balls in the labelled basket, cones stacked and the walkway clear.',check:'Everyone knows their part and what finished looks like.'},
    {title:'Do, check and help',action:'Complete the job at the agreed time. Check the result together. If someone is stuck, ask what help is needed or change the division of work with the teacher. Report damaged equipment; leave cleaning chemicals and unsafe repairs to adults.',check:'The shared space or materials meet the agreed standard.'},
    {title:'Hand over',action:'Tell the next team where materials belong, what helped and what still needs adult attention. Finish with: “We changed __ because __. Next time, __.”',check:'Your handover gives one specific instruction or improvement.'},
  ]},
  {id:'werewolf',title:'Werewolf oral storytelling',purpose:'Use a clear story sequence, expressive narration and careful listening while captains lead the class’s familiar game.',materials:'Paper cue cards, a timer, and the teacher-approved rules and role cards your class already uses. The rehearsal below needs only paper and voices.',finish:'A prepared narration, a short retelling and one revision based on listener feedback.',steps:[
    {title:'Prepare the round',action:'Captains confirm the class rules, role cards, ending condition and time limit with the teacher. Share narrator, discussion host and timekeeper jobs. Prepare three cue headings: opening, change, ending. Choose one speaking focus: clear volume, pace, pauses or expressive voice.',check:'The class knows the rules and speaking focus. Your narration will follow the agreed game events.'},
    {title:'Hear and try a model',action:'Rehearse with this original fictional opening: “At dusk, rain tapped the empty square. The village bell rang once, then stopped. A muddy trail crossed the bakery steps. Mira raised her lantern. Someone had moved through the village, but the tracks did not show who.” Pause after “stopped.” Tell it again from three cue words: rain, bell, tracks.',check:'A listener can name the setting, what changed and one unanswered question.'},
    {title:'Build your narration',action:'Write three to five cue words for an original 60–90 second village opening. Include a setting, a change and a question. Rehearse with a partner and adjust one unclear part. For live play, add atmosphere without inventing new evidence or revealing secret roles.',check:'Your partner can retell the opening in order; invented atmosphere is not presented as a new game clue.'},
    {title:'Lead and listen',action:'Use your class’s agreed Werewolf rules for a time-limited round. The narrator describes agreed events; the host invites turns and asks, “What did you hear that supports that?” Players may say, “I think __ because __, but I am not sure about __.” Discuss fictional roles and game events, not classmates’ real personalities. Anyone out of play can track story events and prepare a retelling without revealing secrets.',check:'People can follow the story and respond to one another. Winning or hiding a role is not the speaking assessment.'},
    {title:'Retell and improve',action:'After the round, partners give a 30-second beginning–change–ending retelling. A listener names one clear detail and one confusing moment. The narrator retells 20 seconds of that moment with a useful change in wording, pace or pause.',check:'You can point to a specific change that made the story easier to follow.'},
  ]},
  {id:'teamwork',title:'Lead learning in any subject',purpose:'Help a group plan, include different contributions, check its work and improve.',materials:'The current lesson’s instructions, materials and success criteria; paper for one brief action-and-effect note.',finish:'The subject task plus one example of how your leadership helped.',steps:[
    {title:'Make a small plan',action:'Read the task together and name what the team must finish. Agree on the first action, materials, time and roles. In math, invite more than one method; in Science, check the fair test and safety routine; in Social Studies, ask which source supports a claim; in Arts or ADST, organize a rehearsal or user test.',check:'Each person can explain the goal and contribute to it.'},
    {title:'Notice and adjust',action:'During the actual lesson, ask: “What is working? Who needs a way in? What should we change?” Example: instead of taking over a model, ask a partner to explain an idea, agree on a small test and share the materials.',check:'Your action helps the group’s thinking or participation; it does not replace another person’s work.'},
    {title:'Use the evidence',action:'Finish the subject task and check it against the lesson criteria. Keep one note: “I did __. I noticed __. It helped or did not help because __.”',check:'Your note names something you actually did and observed.'},
  ]},
  {id:'reflection',title:'Career: captain leadership reflection',purpose:'Use a real responsibility to recognize growth and choose a next step.',materials:'One recent example from classroom chores, PE, Werewolf or a subject team; a notebook, paper or a private teacher conversation.',finish:'An action, its effect, one adjustment and a next-step goal.',steps:[
    {title:'Choose one moment',action:'Choose a moment you can describe accurately. What was your responsibility? What did you do? What happened? You can include a difficulty or a plan that did not work.',check:'Your example is specific enough for someone else to understand.'},
    {title:'Explain the effect',action:'Use this example: “During PE I explained the restart twice, but people were still unsure. I demonstrated it with a partner. In the next round, groups restarted without asking. Next time I will demonstrate before we begin.” Write or say your own action, observation and explanation.',check:'You describe evidence of an effect rather than simply calling yourself a good leader.'},
    {title:'Set and revisit a goal',action:'Finish: “Next time I will __ when __. I will know it helped if __.” At your next captain responsibility, try it and briefly revisit the result. Team members can reflect on their own contribution too.',check:'The goal names an action you can try and something you can notice.'},
  ]},
];
export const captainYearProgression = [
  ['September–October','Story order, clear instructions, audible voice; learn chores and handovers.'],
  ['November–December','Pace, pauses and suspense; invite different voices and revise unclear instructions.'],
  ['January–February','Character voice, viewpoint and evidence in discussion; use feedback to improve a plan.'],
  ['March–April','Improvise while keeping events consistent; adapt activities and share responsibilities.'],
  ['May–June','Lead with growing independence, coach the next team and compare an early and recent example.'],
] as const;
