'use client';
import {useState} from 'react';
import lessonData from '../content/community-practice.json';
import {shapeOfDayHref} from './classroom-navigation-state';
import './community-practice.css';
export type PracticeDeck='agreements'|'nvc';
export function CommunityPracticeLinks({projector=false}:{projector?:boolean}){
 const mode=projector?'&mode=student':'';
 return <nav className="practice-links" aria-label="Community activity resources"><a href={`?view=Games+%26+Activities${mode}&deck=similar`}>Conversation cards</a><a href={`?view=Games+%26+Activities${mode}&deck=agreements`}>Five Agreements</a><a href={`?view=Games+%26+Activities${mode}&deck=nvc`}>NVC · feelings &amp; needs</a>{!projector&&<a href="?view=Games+%26+Activities&deck=music">Music for work time</a>}</nav>;
}
export default function CommunityPractice({deck,projector=false}:{deck:PracticeDeck;projector?:boolean}){
 const lesson=lessonData[deck];const [index,setIndex]=useState(0),[showModel,setShowModel]=useState(false);
 const card=lesson.cards[index];
 const move=(next:number)=>{setIndex(next);setShowModel(false);};
 return <section className="practice-page"><CommunityPracticeLinks projector={projector}/><header><p>CLASSROOM COMMUNITY · GRADE 6</p><h1>{lesson.title}</h1><p>{lesson.intro}</p></header>
 {!projector&&<details className="practice-teacher" open><summary>Ready to teach</summary><p>{lesson.prep}</p><ol>{lesson.cards.map((c,i)=><li key={c.title}><button onClick={()=>move(i)}>{c.title}</button> — {c.teacher}</li>)}</ol><p>Source guidance and attribution:</p><ul>{lesson.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.label}</a></li>)}</ul><a href={`?view=Games+%26+Activities&mode=student&deck=${deck}`}>Open projector cards →</a></details>}
 <article className="practice-card" aria-live="polite"><p className="practice-count">{index+1} / {lesson.cards.length} · {card.title}</p><h2>{card.prompt}</h2><p className="practice-action">{card.action}</p><button className="practice-model-toggle" aria-expanded={showModel} onClick={()=>setShowModel(v=>!v)}>{showModel?'Hide example':'Show an example'}</button>{showModel&&<blockquote>{card.model}</blockquote>}</article>
 {!projector&&<aside className="practice-teacher"><strong>For this card</strong><p>{card.teacher}</p></aside>}
 <nav className="practice-controls" aria-label="Practice card controls"><button disabled={index===0} onClick={()=>move(index-1)}>← Previous</button><label>Card <select aria-label="Choose a practice card" value={index} onChange={e=>move(Number(e.target.value))}>{lesson.cards.map((c,i)=><option value={i} key={c.title}>{i+1} · {c.title}</option>)}</select></label><button disabled={index===lesson.cards.length-1} onClick={()=>move(index+1)}>Next →</button><a href={shapeOfDayHref()}>Back to our day</a></nav>
 {deck==='agreements'&&<p><a className="practice-next" href={`?view=Games+%26+Activities&deck=nvc${projector?'&mode=student':''}`}>Optional next activity: NVC · notice, feel, need, ask →</a></p>}
 </section>;
}
export function WorkMusicResources(){return <section className="practice-page"><CommunityPracticeLinks/><header><p>TEACHER RESOURCES</p><h1>Music for a relaxed work block</h1><p>Choose the exact recording before class. These are fixed instrumental album options, not a promise that every playlist labelled “clean” is suitable.</p></header><div className="music-options"><article><h2>Pop · piano and cello</h2><p>Brooklyn Duo’s <em>Brooklyn Sessions 3</em> includes instrumental covers of Photograph, Hello, Clarity and Waiting for Love.</p><a href="https://brooklynduo.bandcamp.com/album/brooklyn-sessions-3" target="_blank" rel="noreferrer">Open the album and track list →</a></article><article><h2>Pop / rock · piano and cello</h2><p>Brooklyn Duo’s <em>Brooklyn Sessions 1</em> is another fixed set of instrumental covers. Use the named album rather than an artist radio station.</p><a href="https://brooklynduo.bandcamp.com/album/brooklyn-sessions-1" target="_blank" rel="noreferrer">Open the album and track list →</a></article><article><h2>K-pop · strings</h2><p>Vitamin String Quartet’s <em>VSQ Performs KPop Demon Hunters</em> offers instrumental arrangements, including Golden. The publisher page includes the album details and previews.</p><a href="https://www.vitaminstringquartet.com/products/vsq-performs-kpop-demon-hunters-mp3" target="_blank" rel="noreferrer">Open the publisher’s album page →</a></article></div><div className="practice-teacher"><h2>What was checked</h2><p>Artist/publisher pages identify these recordings as instrumental or piano/cello/string arrangements. The complete audio and any platform advertisements have not been audited. Streaming or full playback may depend on the service or purchase; no purchase has been made.</p><h2>Brazilian phonk</h2><p>No Brazilian phonk playlist has been verified end to end for classroom use here. Keep it off the ready-to-play list for now. Collect exact song/version suggestions for later checking, including sampled voices and Portuguese lyrics; an “instrumental” or “clean” label alone is not verification.</p><h2>Classroom setup</h2><p>Keep the Shape of the Day on the projector while music plays on the teacher device. Use low volume, pause for directions, and offer quiet time. Turn off autoplay or radio continuation so a chosen album does not turn into an unchecked queue.</p></div><a href={shapeOfDayHref()}>Back to our day →</a></section>;}
