'use client';
import {useState} from 'react';
import lessonData from '../content/community-practice.json';
import {shapeOfDayHref} from './classroom-navigation-state';
import './community-practice.css';
export type PracticeDeck='agreements'|'nvc'|'belonging';
export function CommunityPracticeLinks({projector=false}:{projector?:boolean}){
 const mode=projector?'&mode=student':'';
 return <nav className="practice-links" aria-label="Community activity resources"><a href={`?view=Games+%26+Activities${mode}&deck=belonging`}>Who gets to belong?</a><a href={`?view=Games+%26+Activities${mode}&deck=belonging-sequence`}>Belonging sequence</a><a href={`?view=Games+%26+Activities${mode}&deck=similar`}>Conversation cards</a><a href={`?view=Games+%26+Activities${mode}&deck=agreements`}>Five Agreements</a><a href={`?view=Games+%26+Activities${mode}&deck=nvc`}>NVC · feelings &amp; needs</a>{!projector&&<a href="?view=Games+%26+Activities&deck=music">Music for work time</a>}</nav>;
}
export default function CommunityPractice({deck,projector=false}:{deck:PracticeDeck;projector?:boolean}){
 const lesson=lessonData[deck];const [index,setIndex]=useState(0),[showModel,setShowModel]=useState(deck==='belonging');
 const card=lesson.cards[index];
 const move=(next:number)=>{setIndex(next);setShowModel(deck==='belonging'&&next===0);};
 return <section className={`practice-page ${projector?'practice-projector':''}`}><CommunityPracticeLinks projector={projector}/><header><p>CLASSROOM COMMUNITY · GRADE 6</p><h1>{lesson.title}</h1><p>{lesson.intro}</p></header>
 {deck==='agreements'&&<figure className="practice-infographic"><a href="images/five-agreements-classroom.svg" target="_blank" rel="noreferrer"><img src="images/five-agreements-classroom.svg" alt="Five Agreements with short classroom explanations: speak honestly and kindly; remember your worth and seek help; ask before deciding; take a manageable next step; listen and check evidence." width="1600" height="1000" fetchPriority="high"/></a><figcaption><a href="images/five-agreements-classroom.svg" target="_blank" rel="noreferrer">Open full-size Five Agreements infographic →</a><p>Choose one agreement. What could it look like during a game or group task?</p></figcaption></figure>}
 {deck==='agreements'&&<details className="practice-poster"><summary>Another visual: Butterfly Dreamz’s Four Agreements poster</summary><p>{lessonData.agreements.poster.prompt}</p><a href={lessonData.agreements.poster.image} target="_blank" rel="noreferrer"><img src={lessonData.agreements.poster.image} alt={lessonData.agreements.poster.alt} width="1125" height="1500" loading="lazy" referrerPolicy="no-referrer"/></a><p><a href={lessonData.agreements.poster.image} target="_blank" rel="noreferrer">Open full-size poster →</a> · <a href={lessonData.agreements.poster.source} target="_blank" rel="noreferrer">{lessonData.agreements.poster.credit}</a></p><p>{lessonData.agreements.poster.note}</p></details>}
 {!projector&&<details className="practice-teacher" open><summary>Ready to teach</summary><p>{lesson.prep}</p><ol>{lesson.cards.map((c,i)=><li key={c.title}><button onClick={()=>move(i)}>{c.title}</button> — {c.teacher}</li>)}</ol><a href={`?view=Games+%26+Activities&mode=student&deck=${deck}`}>Open projector cards →</a></details>}
 {deck==='belonging'&&<p className="belonging-routine"><b>Person</b> · what do they want to do? → <b>Barrier</b> · what gets in the way? → <b>Redesign</b> · what could change?</p>}
 <article className="practice-card" aria-live="polite"><p className="practice-count">{index+1} / {lesson.cards.length} · {card.title}</p>{'agreement' in card&&<p className="practice-agreement">{card.agreement}</p>}<h2>{card.prompt}</h2><p className="practice-action">{card.action}</p><button className="practice-model-toggle" aria-expanded={showModel} onClick={()=>setShowModel(v=>!v)}>{showModel?'Hide example':'Show an example'}</button>{showModel&&<blockquote>{card.model}</blockquote>}{'discussion' in card&&<details className="practice-discussion" open={deck==='belonging'}><summary>Talk together</summary><p>{card.discussion}</p></details>}</article>
 {!projector&&<aside className="practice-teacher"><strong>For this card</strong><p>{card.teacher}</p></aside>}
 <nav className="practice-controls" aria-label="Practice card controls"><button disabled={index===0} onClick={()=>move(index-1)}>← Previous</button><label>Card <select aria-label="Choose a practice card" value={index} onChange={e=>move(Number(e.target.value))}>{lesson.cards.map((c,i)=><option value={i} key={c.title}>{i+1} · {c.title}</option>)}</select></label><button disabled={index===lesson.cards.length-1} onClick={()=>move(index+1)}>Next →</button><a href={shapeOfDayHref()}>Back to our day</a></nav>
 <details className="practice-resources"><summary>{deck==='agreements'?'Author resources & optional video':'Source guidance and attribution'}</summary><ul>{lesson.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.label}</a>{'description' in s&&<p>{s.description}</p>}</li>)}</ul></details>
 {deck==='agreements'&&<p><a className="practice-next" href={`?view=Games+%26+Activities&deck=nvc${projector?'&mode=student':''}`}>Later lesson: NVC · notice, feel, need, ask →</a></p>}
 {deck==='belonging'&&<p><a href="printables/belonging-barrier-redesign.pdf" target="_blank" rel="noreferrer">Print the belonging companion · 5 pages</a></p>}
 </section>;
}
const vocalStart='https://www.youtube.com/watch?v=7e5qLfeDJmk&list=PLNsHFWQND3H8b8cNZOWP3WHBYefRN5aXY&index=12';
const vocalTracks=["The Jackson 5 · ABC","One Direction · What Makes You Beautiful","Jason Mraz · Have It All","Meghan Trainor · Better When I’m Dancin’","Anna Kendrick & Justin Timberlake · True Colors","Justin Timberlake and collaborators · Hair Up","Elton John · I’m Still Standing","Stevie Wonder featuring Ariana Grande · Faith","Imagine Dragons · Whatever It Takes","Katy Perry · Roar"];
export function WorkMusicResources(){return <section className="practice-page"><CommunityPracticeLinks/><header><p>TEACHER RESOURCES</p><h1>YouTube music · songs with vocals</h1><p>Pop, pop-rock and familiar soundtrack songs for games, colouring and classroom work.</p></header>
<article className="practice-card"><p className="practice-count">START HERE · ABOUT 34 MINUTES</p><h2>Teacher Edition · vocal section</h2><p className="practice-action">Start at ABC and play through Roar: ten songs with vocals, including One Direction, Meghan Trainor, Elton John and Imagine Dragons.</p><p><a className="practice-next" href={vocalStart} target="_blank" rel="noreferrer">Open the vocal section on YouTube →</a></p><p>This opens an existing playlist at the selected song. Leave shuffle off and stop after Roar.</p><details><summary>See the ten-song order</summary><ol>{vocalTracks.map(track=><li key={track}>{track}</li>)}</ol></details></article>
<div className="practice-teacher"><h2>The full playlist</h2><p><a href="https://www.youtube.com/playlist?list=PLNsHFWQND3H8b8cNZOWP3WHBYefRN5aXY" target="_blank" rel="noreferrer">Teacher Edition · Clean Classroom Playlist 2018 →</a></p><p>The earlier songs include Happy, Brave, I’m a Believer and Can’t Stop the Feeling. The full playlist also contains the instrumental Star Wars theme; starting at ABC skips it.</p><h2>What was checked</h2><p>The visible playlist and exact video links were inspected on September 18, 2026: 21 available entries and one unavailable entry. This is an older vocal mix, not a current-hits or Brazilian phonk playlist. The song list was reviewed, but complete audio, edits, music-video imagery and ads were not audited. It is a candidate to preview, not a guarantee of zero inappropriate content. The playlist owner can change its contents.</p><h2>Play it alongside the day screen</h2><p>Keep Shape of the Day on the projector and YouTube on the teacher device. Keep the volume low, turn off autoplay beyond the playlist, and pause for directions. Preview the exact recordings before classroom use.</p><h2>Brazilian phonk</h2><p>A verified vocal phonk playlist is still needed. Exact song versions and sampled Portuguese lyrics need checking; a “clean” title alone is not enough.</p></div><a href={shapeOfDayHref()}>Back to our day →</a></section>;}
