import type { LearningProgram, ProgramExperience } from "./program-types";
import { bloxelsStoryGame } from "./cross-curricular-program";

const experience = (details: ProgramExperience): ProgramExperience => details;

export const languageArtsProgram: LearningProgram = {
  subject: "English Language Arts",
  studioName: "Story, Media & Language Studio",
  title: "Read widely. Make meaning. Create for real audiences.",
  subtitle: "A year-long workshop spine joins choice reading, shared texts, talk, writing, media, performance, and revision to the questions students are already investigating.",
  cadence: "DAILY READING · 2 CREATION BLOCKS/WEEK",
  northStar: "Language Arts should give students more ways to understand the world and more power to communicate—not a longer trail of worksheets.",
  principles: [
    "Mix written, oral, visual, and digital texts instead of treating one novel as the whole program.",
    "Give every substantial piece a purpose, an audience, and time for meaningful revision.",
    "Use authentic, attributed First Peoples texts and protect student choice, privacy, and multiple ways to participate.",
  ],
  arcs: [
    { id: "ela-belonging", number: "01", title: "Stories, Voice & Belonging", timing: "September", question: "How can stories help us know ourselves, one another, and this place?", promise: "Students listen closely, tell small stories, gather precise observations, and learn that nobody owes the class a private or painful story.", curriculum: ["Oral storytelling", "Active listening", "Reading identity", "Source context and permission", "Writing process"], experienceIds: ["ordinary-object-story", "semiahmoo-story-source-lab", "place-soundwalk"] },
    { id: "ela-media", number: "02", title: "Place, Perspective & Media", timing: "October–early November", question: "How do creators guide what we notice, believe, and feel?", promise: "Students test point of view, captions, crops, order, sound, evidence, and source context through fictional practice scenes and real attributed sources.", curriculum: ["Perspective", "Inference", "Visual texts", "Persuasion", "Source care"], experienceIds: ["three-voices", "edit-room"] },
    { id: "ela-reading-power", number: "03", title: "Reading Power, Choice & Game Story", timing: "November–January", question: "What do stories reveal when people face power, rules, and difficult choices?", promise: "Reading circles, transformations, and the Bloxels story blueprint turn text evidence into discussion and original narrative rather than packets of identical questions.", curriculum: ["Character", "Plot & conflict", "Story structure", "Dialogue", "Text transformation", "Conventions"], experienceIds: ["character-council", "turning-point-remix", "bloxels-story-blueprint"] },
    { id: "ela-research", number: "04", title: "Research, Remix & Teach", timing: "January–February", question: "How can research become something people understand and remember?", promise: "Students learn what different source types can actually tell them, combine evidence into an explanation, test it on an audience, and revise where people get stuck.", curriculum: ["Source evaluation", "Synthesis", "Informational forms", "Audience", "Presentation"], experienceIds: ["source-mosaic", "hook-cold-audience"] },
    { id: "ela-language-lab", number: "05", title: "Language Lab: Poetry & Systems", timing: "March–April", question: "How can exact language make invisible ideas easier to see, hear, and feel?", promise: "Poetry, metaphor, sound, image, and precise vocabulary help students communicate Science without sacrificing accuracy.", curriculum: ["Poetry", "Imagery", "Metaphor", "Sound", "Oral performance"], experienceIds: ["metaphor-with-limits", "precision-poetry"] },
    { id: "ela-worldbuilding", number: "06", title: "Worldbuilding & Public Showcase", timing: "May–June", question: "How can we build a world, explain its rules, and publish work worth sharing?", promise: "Students repair impossible scenes, make fact and invention visible, then curate one piece that genuinely shows growth.", curriculum: ["Narrative design", "Genre", "World rules", "Revision", "Publishing"], experienceIds: ["impossible-scene-repair", "live-anthology"] },
  ],
  experiences: [
    experience({
      id: "ordinary-object-story", arcId: "ela-belonging", title: "The story inside an ordinary object", kind: "Oral story lab", duration: "1–2 × 45 min", question: "How can an ordinary object carry a story?", hook: "A key, ticket, spoon, shoelace, toy wheel, and mystery photograph sit together. Which one seems most likely to hide a story?", studentMission: "Choose an object, build a short story around it, and use a listener's evidence to make the telling clearer.",
      steps: ["Choose a real, photographed, or fictional object and notice five specific details.", "Tell a 60–90 second story without reading a script.", "Listen to a partner and map the beginning, turn, and ending you heard.", "Retell or write the story with one change that makes it easier to follow."],
      product: "A 90-second oral story plus a six-sentence written seed", learningModes: ["Object inquiry", "Oral storytelling", "Active listening", "Quickwrite"], connections: ["Career learning profile", "Arts", "Class community"], materials: ["Object or photo basket", "Three-beat story cards", "Notebook or scrap paper", "Optional teacher-managed recorder for one class capture"], teacherPrep: ["Model with an ordinary object and a short, low-stakes story.", "Offer fictional and observation-only routes; never require disclosure."], lookFors: ["A clear sequence", "Specific detail", "Listening evidence", "One meaningful revision"], spacesUse: "none", spacesPrompt: "No separate post. A student may reuse this as part of the September Learning Story." }),
    experience({
      id: "semiahmoo-story-source-lab",
      arcId: "ela-belonging",
      title: "Listen first: Chief Harley Chappell tells the Story of the Flood",
      kind: "Attributed oral-text source lab",
      duration: "1 × 60–75 min · preview source length",
      question: "How do careful listeners keep a speaker, story, and source together?",
      hook: "Being able to open a story does not make it ours to copy or retell.",
      studentMission: "Listen to Chief Harley Chappell through the Surrey Schools source route, then build a source card that names the speaker and source exactly, records one supported learning, and states one sharing boundary.",
      steps: [
        "Before listening, read the district source card. Record only what it identifies: title, speaker, Semiahmoo context, host or source route, and format.",
        "Read the Surrey Schools storytelling protocol note. Distinguish access to listen from permission to copy, download, transcribe, retell, reenact, remix, or repost.",
        "Listen once without story notes. After it ends, record one learning and one question; leave a gap rather than guessing.",
        "Listen again to the teacher-selected portion. Add one source-supported idea and label any interpretation as your own thinking.",
        "Complete the source card, then ask a partner to check the attribution, supported learning, and sharing boundary.",
      ],
      product: "An attributed listening card with the exact source context, one supported learning, one question or interpretation, and one sharing boundary",
      learningModes: ["Teacher-controlled whole-class source", "First listening without notes", "Second listening with a source card", "Partner attribution check", "Written, oral, or visual response"],
      connections: ["Social Studies source and context", "Local place learning", "Media and information literacy"],
      materials: ["Teacher-opened Surrey Schools source page", "Surrey Schools storytelling protocol page", "Projected or printed source-card frame", "Notebook or plain paper", "Pencil", "Supplied fictional oral-text backup for no-Wi-Fi rehearsal"],
      teacherPrep: [
        "Preview both district pages and the complete video; confirm current sharing guidance, accessibility, length, and suitability before teaching.",
        "Introduce the source exactly as its page does. Do not add unsourced Nation, cultural, historical, or story explanations, and do not treat public access as reuse permission.",
        "If the source is unavailable or its current sharing guidance is unclear, run only the fictional listening rehearsal and reschedule the source. Never reconstruct Chief Chappell's story from memory.",
      ],
      lookFors: ["Title, speaker, Semiahmoo context, and source route are recorded accurately", "A supported learning is separated from an interpretation or question", "The student explains why attribution or permission matters", "The response does not generalize one source into an undefined Indigenous belief"],
      spacesUse: "none",
      spacesPrompt: "Keep the source card in class. Do not upload or reproduce story content. A later reflection may discuss the listening and attribution process without retelling the story.",
    }),
    experience({
      id: "place-soundwalk", arcId: "ela-belonging", title: "School-place soundwalk", kind: "Outdoor field note", duration: "1 × 55–65 min", question: "What can a place tell us when we slow down enough to notice?", hook: "Close your eyes for twenty safe seconds. How many layers of sound were present before anyone named them?", studentMission: "Collect exact details outside, then help an audience experience one small part of the school grounds.",
      steps: ["Walk or observe from a chosen station in silence and collect sound, movement, texture, colour, and light.", "Sort what you truly observed from what you inferred or wondered.", "Create a 100-word place postcard or perform a 45-second soundscape with voice, body percussion, or classroom objects.", "Ask a partner which detail made the place most vivid, then revise one line."],
      product: "A precise place postcard or short performed soundscape", learningModes: ["Outdoor noticing", "Field notes", "Sound performance or writing", "Peer response"], connections: ["Social Studies place", "Science observation", "Arts sound"], materials: ["Clipboard or notebook", "Pencil", "Optional teacher-managed recorder for one class capture", "Stationary observation route"], teacherPrep: ["Choose a safe route and boundaries.", "Prepare a seated, indoor-window, or photo route.", "Clarify that observation does not authorize claims about Indigenous meaning; use attributed sources for that learning."], lookFors: ["Exact sensory language", "Observation separated from inference", "Purposeful selection", "Revision from feedback"], spacesUse: "none", spacesPrompt: "Keep it local or use it in the September learning-with-place display." }),
    experience({
      id: "three-voices", arcId: "ela-media", title: "One moment, three voices", kind: "Perspective studio", duration: "2 × 55 min", question: "How can three people tell the same moment honestly—and differently?", hook: "Three people watch the same fictional event. Each notices something the others miss.", studentMission: "Retell one shared moment through three evidence-based voices, then show what each version selected and left out.",
      steps: ["Study one fictional scene and note only what is visible.", "Read three narrator evidence cards with different locations, goals, and information.", "Retell the moment three ways as prose, comic panels, or spoken monologues.", "Annotate one choice and one omission in each version."],
      product: "A prose, comic, or spoken triptych with evidence notes", learningModes: ["Visual inference", "Role evidence", "Creative writing", "Annotation"], connections: ["Social Studies perspective", "Arts", "Media literacy"], materials: ["Fictional multi-person scene", "Narrator evidence cards", "Choice-format prompts shown on the projector"], teacherPrep: ["Use a scene with multiple plausible viewpoints but no trauma.", "Ensure role differences come from evidence, not stereotypes."], lookFors: ["Consistent point of view", "Evidence-based inference", "Distinct but credible voice", "Awareness of omission"], spacesUse: "none", spacesPrompt: "No post. Keep one strong sample as conference evidence if useful." }),
    experience({
      id: "edit-room", arcId: "ela-media", title: "The edit room", kind: "Media investigation", duration: "2 × 55–65 min", question: "How do image, sound, caption, and order change what an audience believes?", hook: "The same fictional event has two edits: one gives context and one pushes a dramatic conclusion. What changed?", studentMission: "Build a truthful short version of an event and explain how two editing decisions affect the audience.",
      steps: ["Inspect the full fictional event on the shared screen before viewing any edit.", "Compare a fair edit and a pushy edit; mark crops, captions, sequence, and sound.", "Create a truthful four-panel paper or board version for a named audience.", "Explain two choices and identify one context detail that must not be removed."],
      product: "A four-panel media board with a spoken or written creator note", learningModes: ["Media comparison", "Ethical editing", "Storyboarding", "Creator explanation"], connections: ["Maps Make Arguments", "Trace the Claim", "ADST media"], materials: ["Teacher-created fictional event on the shared screen", "Paper or board", "Pencils and markers", "Optional teacher-managed slide or recording tool"], teacherPrep: ["Use a complete fictional event, not a current tragedy or real student footage.", "Provide every group the same facts and source dates."], lookFors: ["Persuasion techniques identified", "Context preserved", "Form fits audience", "Ethical choice explained"], spacesUse: "none", spacesPrompt: "Complete as a class studio. Do not create a separate upload." }),
    experience({
      id: "character-council", arcId: "ela-reading-power", title: "Character council", kind: "Reading-circle hearing", duration: "Recurring 35–45 min", question: "What should this character do next—and what does the text actually support?", hook: "A character reaches a genuine turning point. Two choices are defensible, but neither is easy.", studentMission: "Use the text to recommend a next step, answer a counterargument, and revise if the evidence changes your thinking.",
      steps: ["Read or listen and collect two details that reveal the character's situation.", "Build two possible next moves and predict a consequence for each.", "Hold a 90-second council hearing with evidence keeper, challenger, connector, and facilitator roles.", "Revise or defend the recommendation after hearing a counterargument."],
      product: "An evidence placemat and spoken recommendation", learningModes: ["Choice reading", "Text evidence", "Council discussion", "Counterargument"], connections: ["Power and rights", "Ethical judgment", "Career collaboration"], materials: ["Choice text or excerpt", "Audiobook/graphic option", "Evidence placemat", "Role cards"], teacherPrep: ["Select accessible texts with consequential choices.", "Rotate thinking roles instead of assigning repetitive worksheets."], lookFors: ["Accurate inference", "Relevant cited detail", "Listening across disagreement", "Revision after new evidence"], spacesUse: "none", spacesPrompt: "Use discussion observations and reading conferences as the evidence." }),
    experience({
      id: "turning-point-remix", arcId: "ela-reading-power", title: "Turning-point remix", kind: "Transformation studio", duration: "2–3 × 55 min", question: "What changes when we retell a turning point from another angle or in another form?", hook: "A scene keeps its important truth but changes narrator, form, or audience. Is it still the same story?", studentMission: "Transform a meaningful scene without losing the facts, conflict, or idea that makes it matter.",
      steps: ["Choose one consequential scene and name the facts and meaning that must remain.", "Select a new angle or form: monologue, comic, letter, script, audio, or visual sequence.", "Create the remix and test whether a reader can still recognize the turning point.", "Add a creator note explaining two changes and one meaning you protected."],
      product: "A transformed text plus a concise creator note", learningModes: ["Close reading", "Form choice", "Creative transformation", "Peer test"], connections: ["Arts", "Social Studies perspective", "Drama"], materials: ["Source text", "Format templates", "Citation guide", "Audio or assistive options"], teacherPrep: ["Model transformation without copying a full copyrighted passage.", "Provide format choices that demand comparable thinking."], lookFors: ["Understanding of the original", "Purposeful form and voice", "Meaning preserved", "Conventions support clarity"], spacesUse: "optional", spacesPrompt: "Save only when it adds evidence not already visible in the Fleetwood case file or class reading conferences." }),
    experience({
      id: "bloxels-story-blueprint", arcId: "ela-reading-power", title: "Write the story before building the game", kind: "Bloxels narrative studio", duration: "3 × 55 min + revision during ADST", question: "How can a player experience the story while playing?", hook: "A game can contain beautiful art and still leave the player wondering who they are, what they should do, and why it matters.", studentMission: "Plan an original player character, setting, problem, turning point, ending, and short story blocks that make sense along a playable route.",
      steps: bloxelsStoryGame.elaMoves,
      product: "A story blueprint, paper route map, and revised story-block or dialogue set", learningModes: ["Game-story observation", "Narrative planning", "Paper level map", "Partner story test", "Writing revision"], connections: ["Bloxels Game Studio", "ADST Media Arts", "Arts pixel design"], materials: ["Projectable original pixel-world image", "Story blueprint", "Paper level map", "Story-block planner", "Partner test prompts"], teacherPrep: ["Open the supplied project kit and choose a short teacher example.", "Confirm students use original writing and approved assets; no full names or personal information."], lookFors: ["Clear plot and story sequence", "Story information appears where the player needs it", "Language fits a Grade 6 player audience", "Revision improves clarity or effect", "Conventions support meaning"], spacesUse: "none", spacesPrompt: "Use the single Bloxels Story-Game post. Do not create a second ELA upload." }),
    experience({
      id: "source-mosaic", arcId: "ela-research", title: "Source mosaic", kind: "On-screen research lab", duration: "55–65 min", question: "How could a school make a hot paved outdoor area cooler and more welcoming?", hook: "One source gives temperatures. Another shows the space. Another tells us what students experience. A fourth explains why some changes work. None is enough alone.", studentMission: "Learn the job of each source type, combine evidence from at least two sources into one useful recommendation, and name what we still need to learn.",
      steps: ["Study each source shown in the shared on-screen lab and notice what kind of information it gives.", "Match the temperature data, site sketch, student voices, and public explanation to the job each does best.", "Choose evidence from at least two sources and build one recommendation.", "Name one missing fact or voice before sharing the recommendation."],
      product: "A recommendation supported by two sources and one honest limit", learningModes: ["On-screen or printed source investigation", "Evidence matching", "Recommendation builder", "Class teach-back"], connections: ["Science heat", "Social inquiry", "Arts information design"], materials: ["On-screen Source Mosaic lab", "Built-in printable four-source pack and teacher key", "Plain paper or notebook for the offline evidence organizer"], teacherPrep: ["Run the on-screen fictional case first, or open and print the built-in Static Source Pack when connectivity is uncertain.", "Use a current local issue or student-selected solutionary topic only as a later extension."], lookFors: ["Source jobs accurate", "Evidence connected", "Source credit visible", "Missing information honest"], spacesUse: "none", spacesPrompt: "This is the ELA research layer inside the Social Studies inquiry, not another post." }),
    experience({
      id: "hook-cold-audience", arcId: "ela-research", title: "Hook lab & cold audience", kind: "Audience design lab", duration: "2 × 55–65 min", question: "What makes an audience lean in—and what helps them actually learn?", hook: "The same idea opens as a question, a tiny story, a strong image, and a demonstration. Which earns attention, and which builds understanding?", studentMission: "Test an opening on people who have not seen your project, then revise where their evidence shows confusion.",
      steps: ["Try one idea as a question, story, image, and demonstration.", "Choose an opening that fits the purpose—not merely the loudest option.", "Cold-test the teaching experience using: I understood, I got stuck, and I need proof.", "Revise one content choice and one design choice; record why."],
      product: "An opening storyboard and evidence-based revision log", learningModes: ["Rapid prototyping", "Audience test", "Oral presentation", "Revision"], connections: ["Social Studies expert exchange", "Arts", "ADST"], materials: ["Current inquiry content", "Opening-format cards", "Audience signal cards", "Revision log"], teacherPrep: ["Build a testing rotation with unfamiliar audience pairs.", "Protect accuracy checks before production polish."], lookFors: ["Purpose-audience fit", "Clear organization", "Feedback interpreted accurately", "Substantive revision"], spacesUse: "none", spacesPrompt: "Contribute this revision to the existing Social Studies expert artifact and individual reflection. Do not create a duplicate ELA post." }),
    experience({
      id: "metaphor-with-limits", arcId: "ela-language-lab", title: "Metaphor with limits", kind: "Language & model lab", duration: "1–2 × 55 min", question: "When does a metaphor help—and where does it stop working?", hook: "A nervous system is called wiring, a kidney is called a filter, and a mixture is called a team. Helpful—or misleading?", studentMission: "Build one comparison that helps someone learn, then label the exact place where it breaks.",
      steps: ["Learn the accurate Science idea before inventing a comparison.", "Test several possible metaphors against the evidence.", "Create one visual, oral, comic, or model-based explanation.", "Label Works Here and Breaks Here, then ask a classmate to test it."],
      product: "An illustrated, modelled, or spoken metaphor with a limit warning", learningModes: ["Concept check", "Metaphor testing", "Visual/oral creation", "Peer explanation"], connections: ["Body systems", "Mixtures", "Science models"], materials: ["Accurate Science diagrams", "Metaphor cards", "Creation materials", "Limit labels"], teacherPrep: ["Confirm the scientific idea before language play.", "Treat generated imagery as illustration, never evidence."], lookFors: ["Accurate core idea", "Purposeful figurative language", "Specific model limit", "Audience understanding"], spacesUse: "none", spacesPrompt: "Keep it as formative ELA and Science evidence." }),
    experience({
      id: "precision-poetry", arcId: "ela-language-lab", title: "Precision poetry studio", kind: "Poetry & performance", duration: "3 × 55 min", question: "How can exact science words and vivid images live in the same poem?", hook: "One precise word can be factual and musical at the same time. Build a word cabinet that can do both jobs.", studentMission: "Use observation, sound, image, and accurate vocabulary to make a poem worth hearing twice.",
      steps: ["Gather observation language and study short, legally usable mentor texts.", "Build a word cabinet with exact, sensory, technical, and surprising language.", "Draft a 12–20 line poem, choral piece, visual poem, or sound performance.", "Collect one audience response and revise sound, image, or structure."],
      product: "A poem or spoken-word performance with one documented revision", learningModes: ["Mentor text", "Word play", "Writing studio", "Performance choice"], connections: ["Water and materials", "Earth Day", "Arts sound"], materials: ["Short mentor texts", "Observation/source bank", "Word cabinet", "Quiet and performance routes"], teacherPrep: ["Use brief, licensed or classroom-permitted mentor excerpts.", "Offer private reading, partner, choral, and non-performance routes."], lookFors: ["Precise imagery", "Sound or structural choices", "Technical vocabulary used meaningfully", "Revision after response"], spacesUse: "optional", spacesPrompt: "Save only as a student-choice portfolio piece when the existing evidence is thin or the student values it." }),
    experience({
      id: "impossible-scene-repair", arcId: "ela-worldbuilding", title: "Impossible scene repair", kind: "Storyworld investigation", duration: "2 × 55–65 min", question: "Which parts of this scene are impossible—and which rules could make it believable?", hook: "A fictional action scene breaks the rules of force, scale, and space. Your team can repair reality or declare new rules honestly.", studentMission: "Find the broken rules, choose accurate or deliberately speculative world logic, and rewrite the scene so an audience can follow it.",
      steps: ["Inspect a fictional action or space storyboard and mark scientific or story contradictions.", "Sort details into accurate, uncertain, impossible, and intentionally speculative.", "Repair the scene or write clear fictional world rules that make it coherent.", "Add a creator note separating fact, invention, and one remaining question."],
      product: "A repaired storyboard, scene script, animation plan, or performed audio drama", learningModes: ["Visual error hunt", "Worldbuilding", "Fact/fantasy sorting", "Creator explanation"], connections: ["Forces and motion", "Space", "Arts", "ADST media"], materials: ["Projected fictional storyboard", "Science fact cards", "Board or plain-paper planning route"], teacherPrep: ["Use an original or generated fictional scene with visible contradictions.", "Provide accurate source cards and avoid copyrighted franchise worlds."], lookFors: ["Close viewing", "Coherent rules", "Fact and invention separated", "Clear narrative structure"], spacesUse: "none", spacesPrompt: "Use it to prepare for the Science showcase without adding an upload." }),
    experience({
      id: "live-anthology", arcId: "ela-worldbuilding", title: "Live anthology & curator's note", kind: "Publication studio", duration: "3–5 × 55 min", question: "Which piece best shows the reader, writer, speaker, or maker I became?", hook: "A portfolio is not everything you made. It is an argument made with carefully chosen evidence.", studentMission: "Choose one piece, make one revision that matters, share it in a fitting form, and explain the growth it proves.",
      steps: ["Review the year and shortlist work using learning—not prettiness—as the reason.", "Conference on one meaningful content, craft, or design revision.", "Publish, perform, record, or display for an appropriate audience.", "Write or record a curator's note using two pieces as evidence of growth."],
      product: "One deeply revised choice piece and a two-artifact growth reflection", learningModes: ["Portfolio curation", "Conference", "Publication or performance", "Reflection"], connections: ["Science expert showcase", "Career reflection", "Arts exhibition"], materials: ["Year's work", "Selection criteria", "Revision conference notes", "Privacy-safe sharing routes"], teacherPrep: ["Protect revision time before celebration.", "Confirm family-facing permissions for any public display, face, or voice."], lookFors: ["Defensible selection", "Substantive revision", "Audience awareness", "Specific growth evidence"], spacesUse: "none", spacesPrompt: "Contribute the selected evidence to the existing June Core Competency reflection; do not add a second upload." }),
  ],
  assessment: {
    practice: "Reading conferences, oral stories, discussions, field notes, quick drafts, rehearsals, and peer tests remain local evidence.",
    checkpoints: "Use selected transformations, source explanations, or poetry only when they reveal learning not already visible elsewhere.",
    portfolio: "The September Learning Story, Fleetwood case file, January Bloxels story-game, February expert exchange, and June anthology can carry the main ELA evidence.",
    proficiency: ["Understands, connects, and supports interpretations with relevant evidence", "Creates with a clear purpose, audience, structure, and message", "Communicates clearly across written, oral, visual, and digital forms", "Revises ideas or design because of feedback and evidence", "Uses language and conventions to support meaning"],
  },
  resources: [
    { label: "Learning First Peoples classroom resources", source: "FNESC/FNSA", url: "https://www.fnesc.ca/learningfirstpeoples/", purpose: "Locate authentic, attributed First Peoples resources and planning guidance rather than generic or appropriated material.", gradeFit: "Teacher planning" },
    { label: "Authentic First Peoples Resources, K–9", source: "FNESC/FNSA", url: "https://www.fnesc.ca/wp/wp-content/uploads/2015/06/PUBLICATION-61502-updated-FNESC-Authentic-Resources-Guide-October-2016.pdf", purpose: "Build text sets with authentic written, oral, and visual works for student audiences.", gradeFit: "Teacher planning" },
    { label: "CBC Kids News", source: "CBC", url: "https://www.cbc.ca/kidsnews/", purpose: "Use a current Canadian text, image, or video as one source in media and source-care work; preview the specific item first.", gradeFit: "Core Grade 6" },
    { label: "NFB Education", source: "National Film Board of Canada", url: "https://www.nfb.ca/education/", purpose: "Find Canadian documentary, animation, and media texts that support viewing, interpretation, and creator-choice discussions.", gradeFit: "Supported stretch" },
  ],
};

export const mathematicsProgram: LearningProgram = {
  subject: "Mathematics",
  studioName: "Make Sense, Test & Explain",
  title: "Mathematics 6 · Make sense, test, explain.",
  subtitle: "A year-long mix of explicit teaching, visual models, games, investigations, discussion, practice, and authentic design. Fluency means accurate, flexible, and efficient thinking—not public speed rankings.",
  cadence: "4–5 BLOCKS/WEEK · 3 SHORT FLUENCY OPENERS",
  northStar: "Math is not a race. Students notice patterns, choose useful strategies, test ideas, and explain why they work.",
  principles: [
    "Pair clear modelling and supported practice with games, investigations, movement, and design.",
    "Use exact shared-screen models, board or plain-paper drawings, and manipulatives for numbers, graphs, grids, angles, dimensions, and probability.",
    "Assess recent reasoning, representation, strategy, and revision—not an average of worksheet scores.",
  ],
  arcs: [
    { id: "math-number", number: "01", title: "Number Sense & Operations", timing: "September–mid October", question: "What can a number show us before we start calculating?", promise: "Students place enormous and tiny numbers, try more than one way to multiply or divide, build equal supply kits, and crack the rules behind game scores.", curriculum: ["Place value", "Estimation", "Operations", "Factors & multiples", "Order of operations"], experienceIds: ["magnitude-gallery", "strategy-league", "pack-and-sync", "scoreboard-rules"] },
    { id: "math-fractions", number: "02", title: "Fractions, Decimals & Decisions", timing: "Mid October–December", question: "How can pictures of parts and quick money guesses help us make a better choice?", promise: "Students build fractions with strips and colour, grow ratio batches, catch impossible invoice totals, and plan a fictional event without blowing the budget.", curriculum: ["Mixed numbers", "Ratios", "Decimal operations", "Percents", "Budgeting"], experienceIds: ["fraction-ratio-remix", "decimal-dispatch", "sale-lab"] },
    { id: "math-patterns", number: "03", title: "Patterns & Equations", timing: "January–early February", question: "Can we discover the hidden rule and use it to jump ahead?", promise: "Students grow fantasy paths, draw what changes, record it in a table, and use a physical balance to solve number mysteries.", curriculum: ["Increasing patterns", "Decreasing patterns", "Tables", "Expressions", "One-step equations"], experienceIds: ["pattern-forecast", "equation-balance"] },
    { id: "math-data", number: "04", title: "Data & Probability", timing: "February–mid March", question: "What does our graph or game test really show us?", promise: "Students become the graph, rebuild misleading displays, spin and roll physical games, and learn why a short streak is surprising but not magical proof.", curriculum: ["Line graphs", "Scale", "Data claims", "Theoretical probability", "Experimental probability"], experienceIds: ["graph-story-lab", "probability-game-audit"] },
    { id: "math-geometry", number: "05", title: "Geometry & Measurement", timing: "Late March–mid May", question: "How can measuring, cutting, and moving shapes make a design actually work?", promise: "Students handle rulers, protractors, paper shapes, grids, and cubes before using formulas in an imaginative Zoo plan and coordinate-code challenge.", curriculum: ["Angles", "Triangles", "Polygons", "Complex perimeter", "Area formulas", "Volume & capacity", "Transformations"], experienceIds: ["geometry-field-lab", "zoo-design-studio", "transformation-cipher"] },
    { id: "math-design", number: "06", title: "Design, Apply & Reflect", timing: "Mid May–June", question: "Can your dream space survive a real size limit and budget?", promise: "Students sketch a strange, welcoming pop-up space, build part of it, find the calculation that breaks the first plan, and redesign it.", curriculum: ["Measurement synthesis", "Ratio", "Budget", "Mathematical modelling", "Revision"], experienceIds: ["space-under-constraints"] },
  ],
  experiences: [
    experience({ id: "magnitude-gallery", arcId: "math-number", title: "The magnitude gallery", kind: "Visual inquiry", duration: "2 × 45–55 min", question: "Where does a number belong when the number line changes size?", hook: "The class places 0.008 on three equal-length lines ending at 1, 0.1, and 0.01. The number never changes—but its visible spot does.", studentMission: "Read the endpoints and equal jumps, predict one number's location, change only the scale, and explain why its spot changes even though the number does not.", steps: ["Start with 0.008 on the 0-to-1 line. Read the endpoints and work out one equal jump.", "Point, vote, or sketch where 0.008 belongs. Reveal its spot and repair the prediction if needed.", "Keep 0.008 fixed while changing the endpoint to 0.1 and then 0.01. Predict and test each new view.", "Try 0.8 as a deliberate off-scale challenge, then repeat the routine with one millions-or-billions card and explain what changed."], product: "Two tested scale predictions and a labelled two-line comparison", learningModes: ["Shared-screen number lab", "Class vote and repair", "Board or paper sketch", "Partner explanation"], connections: ["Space scale", "Fleetwood data", "Science measurement"], materials: ["Shared projector", "Board or paper", "Pencils and markers", "Optional number cards"], teacherPrep: ["Open the on-screen number lab and confirm that Tiny decimals begins with 0.008 on 0-to-1.", "Prepare mini-whiteboards, section cards, or scrap paper so every student predicts before the reveal."], lookFors: ["Endpoints and equal jumps read accurately", "Position matches the selected scale", "Prediction revised from evidence", "Scale change explained in plain language"], spacesUse: "none", spacesPrompt: "Keep the class comparison in Math folders or on the board; no upload." }),
    experience({ id: "strategy-league", arcId: "math-number", title: "Strategy league", kind: "Recurring strategy game", duration: "20–25 min recurring", question: "Would you solve 25 × 16 by stacking, splitting, or changing the numbers?", hook: "Three players reach 400 in three different ways. Nobody wins for being fastest; the class decides which move is easiest to follow.", studentMission: "Try a calculation your way, borrow one useful move from someone else, and teach it back with numbers, arrows, or a quick drawing.", steps: ["Work alone for one quiet minute. Write any start—even a drawing or a fact you already know.", "Put two correct ways under the projector. Trace where both ways use the same multiplication facts.", "Draw a challenge card such as ‘no stacking today’ and find another route by splitting or regrouping the numbers.", "Coach a partner one move at a time. Switch roles when your partner can finish without you."], product: "A marked-up calculation showing your first route and one new route you borrowed", learningModes: ["Number talk", "Card game", "Whiteboards", "Peer coaching"], connections: ["Daily fluency", "Career communication"], materials: ["Strategy cards", "Mini-whiteboards or scrap paper", "Multiplication chart option", "Markers"], teacherPrep: ["Choose problems with multiple sensible methods.", "Never use speed leaderboards or elimination."], lookFors: ["Known fact connected", "Method fits numbers", "Thinking explained", "Partner can reuse it"], spacesUse: "optional", spacesPrompt: "A 60-second Strategy Snapshot is optional only when individual evidence is thin." }),
    experience({ id: "pack-and-sync", arcId: "math-number", title: "Pack it / sync it", kind: "Mission lab", duration: "3 × 55 min", question: "Can 24 patches and 36 clips make identical rescue kits with nothing left over?", hook: "First, the supply crate must split into matching kits. Then two warning lights—one flashing every 4 seconds and one every 6—must flash together.", studentMission: "Pack real counters into equal kits, act out two repeating signals, and discover when factors and multiples are the useful names.", steps: ["Use 24 red counters and 36 blue counters. Try making 2, 3, 4, 6, or more identical kits with no leftovers.", "Name the numbers that divide both supplies exactly. Those kit-making numbers are common factors.", "Tap one rhythm every 4 counts and another every 6 counts. Mark the counts when they meet; shared meeting numbers are common multiples.", "Draw one kit problem or signal problem for another team. Include counters, a list, or a number line so they can see why it works."], product: "A rescue-kit layout and a repeating-signal timeline with the new Math words labelled", learningModes: ["Manipulative packing", "Schedule simulation", "Card sort", "Multiple representations"], connections: ["Science grouping", "Schedules", "ADST systems"], materials: ["Counters or small classroom objects", "Mission cards", "Paper plates or hoops", "Timeline strips and markers"], teacherPrep: ["Use fictional quantities that factor cleanly before stretch cases.", "Keep GCF and LCM attached to their meanings."], lookFors: ["Correct idea selected", "Equal groups or repeats visible", "Efficient reasoning", "Representation matches"], spacesUse: "none", spacesPrompt: "No post. Keep reusable boards and teacher notes." }),
    experience({ id: "scoreboard-rules", arcId: "math-number", title: "Scoreboard rules", kind: "Strategy game", duration: "2–3 × 50 min", question: "The screen says 5 + 3 × 4. Is the score 32 or 17?", hook: "Two teams claim different scores from the same four symbols. We need one shared rule so nobody can bend the scoring after the round.", studentMission: "Build score rules with number and bracket tiles, solve them in the agreed order, and invent one rule that another team cannot misread.", steps: ["Build 5 + 3 × 4 with tiles. Calculate both team claims: 32 and 17.", "Learn the shared convention: brackets first, then multiplication or division, then addition or subtraction. Use it to choose 17.", "Move the brackets to make (5 + 3) × 4. Recalculate and point to the exact move that changed the score.", "Invent a score rule with tiles. Trade with another team; if they read it differently, add brackets or rewrite it."], product: "One playable score card with an example round, the correct score, and arrows showing the order", learningModes: ["Prediction", "Score simulation", "Expression redesign", "Peer decoding"], connections: ["Games", "ADST algorithms"], materials: ["Score cards", "Number and operation tiles", "Bracket cards", "Whiteboards or paper"], teacherPrep: ["Keep core cases to whole numbers and grouping symbols.", "Use exponents only as an optional extension."], lookFors: ["Rule followed", "Grouping interpreted", "Expression unambiguous", "Reason justified"], spacesUse: "none", spacesPrompt: "Complete as a game lab; no post." }),
    experience({ id: "fraction-ratio-remix", arcId: "math-fractions", title: "Fraction–ratio remix", kind: "Visual mission lab", duration: "3 × 55 min", question: "If a colour mix uses 2 blue tiles for every 3 gold, how can we make it bigger without changing the look?", hook: "One mosaic path glows blue-and-gold in a 2-to-3 pattern. A repaired section uses 4 blue and 5 gold—and suddenly the pattern feels off.", studentMission: "Build colour batches with tiles and fraction strips, give the same amount two number names, and repair the batch that changed the pattern.", steps: ["Build 2 blue tiles beside 3 gold tiles. Repeat the entire batch twice and then three times.", "Record the growing pairs: 2:3, 4:6, 6:9. The colon is read ‘to’; a ratio tells how two amounts compare.", "Build seven one-quarter strips. Group four quarters as one whole to see why 7/4 and 1 3/4 name the same amount.", "Find the broken colour batch, rebuild it with the original balance, and show the repair with colour and numbers."], product: "A coloured mosaic strip with its ratio batches and a cut-and-build model of an improper fraction", learningModes: ["Fraction models", "Batch simulation", "Ratio table", "Error audit"], connections: ["Mixtures", "Visual Arts", "Budgeting"], materials: ["Coloured tiles or paper squares", "Fraction strips", "Scissors and glue", "Markers and ratio cards"], teacherPrep: ["Use visual repeated batches; general fraction multiplication is not required.", "Avoid real food and allergy complications in the core lesson."], lookFors: ["Equivalent quantity represented", "Mixed/improper forms connected", "Ratio preserved", "Error explained"], spacesUse: "none", spacesPrompt: "No post; save models only when useful for conferencing." }),
    experience({ id: "decimal-dispatch", arcId: "math-fractions", title: "Decimal dispatch", kind: "Invoice simulation", duration: "3 × 55 min", question: "Six notebooks cost $2.35 each. Could the total really be $141.00?", hook: "The fictional invoice looks official, but one decimal point has jumped to the wrong place. The delivery team needs you to catch it before checkout.", studentMission: "Make a quick money guess, calculate the real total, and stamp each invoice ‘makes sense’ or ‘send back.’",
      steps: ["Look only at the dollars first: six items at a little more than $2 must cost a little more than $12. Write that quick guess.", "Find the exact total with a drawing, place-value chart, written calculation, or repeated addition.", "Inspect three fictional invoices. Circle any answer that is wildly larger or smaller than your quick guess.", "Repair one invoice and write: ‘I knew ___ could not be right because ___.’"], product: "A marked-up invoice with the repaired decimal and a plain-language reason", learningModes: ["Estimation", "Decimal calculation", "Invoice audit", "Explanation"], connections: ["Financial literacy", "ADST planning"], materials: ["Fictional invoices", "Price cards", "Place-value chart", "Paper, pencil, and calculator for the final check"], teacherPrep: ["Use Canadian currency notation and fictional organizations.", "Require an estimate before calculator verification."], lookFors: ["Reasonable range", "Decimal method accurate", "Error detected", "Check explained"], spacesUse: "none", spacesPrompt: "Keep as practice or a local checkpoint." }),
    experience({ id: "sale-lab", arcId: "math-fractions", title: "The sale lab", kind: "Consumer simulation", duration: "4 × 55 min", question: "A $48 art kit is 25% off. What comes off—and is it actually the best choice?", hook: "A neon 50%-OFF sign grabs everyone’s attention, but the package may be too small, too expensive after the discount, or full of things the event does not need.", studentMission: "Use hundred grids and easy fractions to find sale prices, then design a fictional pop-up event that stays under budget without becoming boring.", steps: ["Shade 10, 25, and 50 squares on a hundred grid. Connect them to one tenth, one quarter, and one half.", "For the $48 kit, find one quarter by dividing by 4. Subtract the $12 discount to get the $36 sale price.", "Cut out offer cards and build an event plan that includes every required item and stays under the budget line.", "Draw a surprise-change card. Replace, resize, or remix one part of the plan and mark exactly which totals changed."], product: "A colourful event board with sale-price calculations, a running total, and one visible redesign", learningModes: ["Percent models", "Offer comparison", "Budget simulation", "Constraint change"], connections: ["Career", "ADST entrepreneurship", "Civic choices"], materials: ["Fictional sale cards", "Hundred grids", "Scissors, glue, and markers", "Budget sheet and calculator for checking"], teacherPrep: ["Use a fictional context and current-looking but invented prices.", "Never require family spending disclosure."], lookFors: ["Discount calculated", "Budget respected", "Value justified", "Revision follows evidence"], spacesUse: "optional", spacesPrompt: "Use only as the January Mathematics selection when the evidence body needs it; do not create a default post." }),
    experience({ id: "pattern-forecast", arcId: "math-patterns", title: "Pattern forest: reveal the route", kind: "On-screen visual inquiry", duration: "45–60 min", question: "The path has 5 lights, then 8, then 11. How many will glow at Stage 10?", hook: "Each correct answer makes the traveller move deeper into the forest. The trick is finding the growth move so we can leap ahead without drawing every stage.", studentMission: "Build the next forest scene with counters or a sketch, find what repeats, and use that repeating move to unlock Stage 10.", steps: ["Choose a projected path. Build or draw its missing Stage 4 before pressing an answer.", "Count how many new pieces appear from one stage to the next. If the same amount repeats, mathematicians call it a constant change.", "Say the rule in ordinary words first: ‘Start at 5 and add 3 for every new stage.’ Test it on Stage 2 or 3.", "Jump to Stage 10. Show your calculation beside a tiny sketch so another student can see why the answer fits."], product: "A hand-drawn forest-stage card showing the repeating move and the Stage 10 prediction", learningModes: ["Interactive model", "Counters or sketch", "Value table", "Spoken or written proof"], connections: ["Arts patterns", "ADST algorithms", "Fantasy world design"], materials: ["Projected Pattern Forest", "Counters or small blocks", "Paper, pencil, and colours"], teacherPrep: ["Run one route as a whole class before students try another.", "Use decreasing patterns later and stop before values become impossible."], lookFors: ["Constant change identified", "Representations agree", "Variable meaningful", "Forecast justified"], spacesUse: "optional", spacesPrompt: "Save only if another Mathematics checkpoint is needed." }),
    experience({ id: "equation-balance", arcId: "math-patterns", title: "Equation balance room", kind: "Mission lab", duration: "3 × 55 min", question: "A covered cup plus 4 tiles balances 11 tiles. What is hiding in the cup?", hook: "The equals sign is the balance point. If we sneak four tiles off only one side, the whole table tips.", studentMission: "Build number mysteries with cups and tiles, keep both sides balanced while you uncover the mystery number, and make one for another team.", steps: ["Build □ + 4 = 11 with one covered cup and tiles on a balance mat. The two sides must show the same total.", "Remove 4 tiles from both sides. Doing the opposite action to both sides is called using an inverse operation.", "Reveal 7 in the cup. Put 7 back into the first equation: 7 + 4 = 11. This replacement check is called substitution.", "Create a one-step cup mystery. Trade mats, solve it, and tell the designer if any clue could have two answers."], product: "A balance mystery drawn on paper or the board, its solution, and the check using the original numbers", learningModes: ["Concrete balance", "Inverse operation", "Substitution", "Peer mystery"], connections: ["Science formulas later", "ADST logic"], materials: ["Balance mats", "Opaque cups and counters", "Equation cards", "Paper or whiteboards"], teacherPrep: ["Keep core equations to whole-number coefficients and solutions.", "Use examples where the unknown appears in different positions."], lookFors: ["Equality maintained", "Inverse used meaningfully", "Solution checked", "Mystery unambiguous"], spacesUse: "none", spacesPrompt: "No post; teacher observation and exit reasoning are enough." }),
    experience({ id: "graph-story-lab", arcId: "math-data", title: "Graph story lab", kind: "Data investigation", duration: "3 × 55 min", question: "These two graphs show the same temperatures—so why does one look like a disaster?", hook: "Graph A climbs gently. Graph B shoots upward like a cliff. The numbers are identical; only the spacing on the side has changed.", studentMission: "Become a human line graph, expose one graph trick, and draw a graph that tells the truth without pretending it knows everything.", steps: ["Tape time along the floor. Hold data cards and stand at the matching heights so the class can watch the line rise and fall.", "Place the two projected graphs side by side. Circle where each vertical scale starts and how much each step is worth.", "Use a ruler and grid paper to graph one shared Science or schoolyard data set. Label what, when, and the units.", "Write one sentence the numbers clearly show and one question this graph cannot answer."], product: "A ruler-drawn line graph with one ‘we can see…’ note and one ‘we still do not know…’ note", learningModes: ["Human graph", "Scale comparison", "Graph construction", "Evidence claim"], connections: ["Reaction-time data", "Social source literacy", "Science"], materials: ["Painter’s tape or string", "Data cards", "Grid paper, ruler, pencil, and colours", "Projected graph pair"], teacherPrep: ["Use anonymous or fictional data when personal comparison could harm.", "Prepare a misleading-scale pair using the same values."], lookFors: ["Axes and scale correct", "Pattern described", "Claim supported", "Limit named"], spacesUse: "none", spacesPrompt: "Tag an existing Science or Social Studies artifact if useful; do not add a separate post." }),
    experience({ id: "probability-game-audit", arcId: "math-data", title: "Probability game audit", kind: "Design studio", duration: "4 × 55 min", question: "If blue covers one quarter of a spinner, will it land on blue exactly 5 times in 20 spins?", hook: "The spinner says blue has a 1-in-4 chance, but the first player gets blue three times in a row. Lucky streak, broken spinner, or not enough evidence yet?", studentMission: "Predict one result from the game’s shape, test it with real spins or rolls, and remix the game to change the chance on purpose.", steps: ["List every equally sized section or every face of the die. Count how many give the chosen result; this design-based prediction is theoretical probability.", "Spin, roll, or draw 20 times and tally every result. Combine the class totals for a much larger test.", "Compare the design prediction with what actually happened. The fraction from real trials is experimental probability.", "Change one section, face, or counter in the game. Predict the new chance before testing it again."], product: "A handmade chance game with before-and-after designs, tally marks, and one surprising result", learningModes: ["Prediction", "Physical trials", "Data comparison", "Game redesign"], connections: ["Science fair tests", "ADST iteration"], materials: ["Dice, paper spinners, or opaque bags", "Counters and paper clips", "Paper trial table", "Markers, scissors, and tape"], teacherPrep: ["Keep the focus on one outcome at a time.", "Avoid betting, prizes, or gambling language."], lookFors: ["Theoretical probability accurate", "Trials recorded", "Variation explained", "Revision predicted"], spacesUse: "optional", spacesPrompt: "Save only if this is the selected Data & Probability evidence. Do not add a second post when the environmental graph already shows enough learning." }),
    experience({ id: "geometry-field-lab", arcId: "math-geometry", title: "Angle expedition", kind: "On-screen geometry lab", duration: "55–70 min", question: "Does this opening turn less than, exactly, or more than a square corner?", hook: "Hold up the corner of a sheet of paper: that 90° turn is our anchor. Now decide whether the projected cave entrance opens less or more before a protractor settles it.", studentMission: "Spot the corner where the turn begins, make a smart visual guess, line up a protractor, and build a triangle that passes every clue.", steps: ["Point to the vertex—the exact corner where the two rays meet—on the projected angle.", "Compare the opening with a folded 45° corner, a 90° paper corner, and a straight 180° line.", "Put the protractor’s centre mark on the vertex and its zero line along one ray. Read the number that starts from that zero.", "Use a ruler, protractor, and paper to make the mystery triangle. Mark each equal side and angle clue directly on it."], product: "A measured cave-opening sketch and a paper triangle with every clue visibly marked", learningModes: ["Visual model", "Reference-angle estimate", "Interactive protractor", "Triangle construction"], connections: ["Arts composition", "Design and built environments"], materials: ["Projected Angle Expedition", "Paper corners", "Protractors, rulers, paper, and pencils"], teacherPrep: ["Run the complete on-screen lesson first.", "Offer a classroom or outdoor angle hunt later as an optional extension."], lookFors: ["Vertex and rays identified", "Estimate reasonable", "Protractor aligned", "Angle and triangle classified with evidence"], spacesUse: "none", spacesPrompt: "No post; use the on-screen evidence as practice." }),
    experience({ id: "zoo-design-studio", arcId: "math-geometry", title: "Zoo design: area and perimeter", kind: "Partner design studio", duration: "4–5 × 55 min", question: "Can you fit six wildly different habitats without trapping a visitor or shrinking an animal’s space?", hook: "The first zoo sketch looks amazing—until a wheelchair path hits a dead end, a shared fence is counted twice, and the night creature’s habitat is 12 square metres too small.", studentMission: "Cut, arrange, measure, and colour a fictional zoo where every habitat fits, every path connects, and the calculations survive another team’s inspection.", steps: ["Build the shape skills first: sort polygons, trace perimeter, cover area, and cut-and-move triangles and slanted shapes.", "Copy the six simple habitat outlines and dimensions from the shared screen onto ordinary paper, then cut them out and move them around the 1 cm grid before gluing.", "Trace each outside boundary for perimeter and shade each inside surface for area. Mark the 90° height line on every triangle, parallelogram, or trapezoid.", "Trade plans. The visiting team checks one fence length, one area, and one access route with a ruler and pencil.", "Redesign at least one part that failed the check. Use colour or arrows to show the before and after."], product: "A large coloured zoo map with cut-out habitats, visible calculations, a peer inspection stamp, and one redesigned zone", learningModes: ["Cut-and-move models", "Partner grid design", "Calculation clinic", "Gallery check"], connections: ["ADST design", "PHE accessibility", "Career planning"], materials: ["Projectable habitat and surprise cards", "Ordinary paper plus 1 cm grid or chart paper", "Rulers, scissors, glue, and Sharpies", "Coloured pencils and calculator for checking"], teacherPrep: ["Project the three supplied pre-teaching packs in order; students can copy the simple habitat shapes onto ordinary paper.", "Use fictional habitats and needs; this is a Mathematics design, not animal-care research.", "Select the core six-habitat brief or the extension brief."], lookFors: ["Shape properties justified", "Perpendicular height marked", "Perimeter and area units correct", "Constraints checked", "Revision caused by evidence"], spacesUse: "required", spacesPrompt: "Use one April SpacesEDU post: show the plan, one calculation you can explain, the peer-check finding, and the change it caused. Audio, labelled image, short video, or text are all valid." }),
    experience({ id: "transformation-cipher", arcId: "math-geometry", title: "Transformation cipher", kind: "Strategy game", duration: "2–3 × 55 min", question: "Can your partner move the creature to the exact secret location using only your code?", hook: "‘Move it over there’ sends the creature anywhere. ‘Slide every point 4 squares right and 2 up’ creates one exact copy.", studentMission: "Plot a small creature on a grid, slide, flip, or turn it with an exact code, and see whether another team can reproduce it without asking what you meant.", steps: ["Plot the creature in the upper-right part of the grid. Read each ordered pair as across first, then up.", "Choose one move: slide (translation), flip (reflection), or turn (rotation). Trace the old shape and record every new point.", "Near the end of the unit, choose the optional across-zero map. Negative x means move left of zero; negative y means move below zero.", "Hide the final picture and give only the code to another team. Compare pictures, circle the first mismatch, and repair that instruction."], product: "A coded creature-move card, the decoded drawing, and one repaired instruction", learningModes: ["B.C. first-quadrant grid", "Optional four-quadrant bridge", "Ordered-pair encoding", "Peer decoding"], connections: ["Arts pattern", "ADST algorithms"], materials: ["First- and four-quadrant coordinate grids", "Creature point cards", "Tracing paper", "Rulers, pencils, and colours"], teacherPrep: ["Rehearse positive whole-number ordered pairs in the first quadrant before opening the negative-coordinate extension.", "Apply one exact translation, rotation, or reflection in the first quadrant; this is the B.C. Grade 6 evidence.", "After the negative-coordinate bridge, choose whether to extend the cipher into another quadrant.", "Teach and assess the B.C. Grade 6 transformation on the first-quadrant route; treat the four-quadrant route as MathUP/WNCP enrichment.", "Keep artistic decoration separate from the Mathematics assessment."], lookFors: ["Ordered pairs read x first, then y", "B.C. first-quadrant transformation accurate", "Optional negative-coordinate extension plotted accurately", "Ambiguity repaired"], spacesUse: "none", spacesPrompt: "Complete as a partner game; no post." }),
    experience({ id: "space-under-constraints", arcId: "math-design", title: "Space under constraints", kind: "Design studio", duration: "5–7 × 55 min", question: "Can you fit a mini theatre, calm cave, maker table, and storage wall into one pop-up space?", hook: "The first dream plan has a slide, a giant sculpture, and glowing reading pods—but it is wider than the site and spends the entire budget before adding a doorway.", studentMission: "Invent a bold pop-up learning space, draw it to scale, build one storage feature, and let the numbers force one genuinely better redesign.", steps: ["Read the design brief on the shared screen. Copy the exact site size, budget, number of visitors, doorway width, and must-have spaces onto plain paper.", "Sketch freely first. Then redraw on grid paper, where each square represents 1 metre, and label the boundary and area of each zone.", "Build one box, shelf, or container from paper nets or cubes. Calculate how much space it takes up or how much it can hold.", "Trade plans for a ‘break test’: find one size, cost, capacity, or access rule that does not work. Redesign that part and show the old and new versions side by side."], product: "A bold coloured floor plan, one small physical model, a cost/measurement sheet, and a visible before-and-after redesign", learningModes: ["Free sketch", "Exact grid plan", "Paper or cube prototype", "Peer break test and presentation"], connections: ["ADST", "Arts", "Science showcase"], materials: ["Projectable fictional brief and price cards", "Grid and plain paper", "Rulers, scissors, tape, glue, and Sharpies", "Unit cubes or folded paper models"], teacherPrep: ["Put every required dimension and price clearly on the projected brief and cards.", "Offer a reduced-constraint core route and extension constraints."], lookFors: ["Calculations accurate", "Constraints met", "Model matches plan", "Revision follows audit"], spacesUse: "optional", spacesPrompt: "Use only as a teacher-selected alternate when it replaces another substantial Math design artifact; never require it in addition to Zoo Design." }),
  ],
  assessment: {
    practice: "Use games, number talks, whiteboards, notebooks, manipulatives, observations, and conferences. Team work always needs an individual explanation before individual proficiency is assigned.",
    checkpoints: "Use strategy snapshots or pattern forecasts only when more individual evidence is needed; cross-curricular evidence can replace a regular Mathematics block.",
    portfolio: "Use the April Zoo Design as the canonical Mathematics post. January selections and other Math designs are optional only when they fill a real evidence gap; Math thinking may also appear inside the March Science investigation or May design artifact without a duplicate upload.",
    proficiency: ["Represents the Mathematics accurately", "Chooses and uses a reasonable strategy", "Explains and justifies a decision", "Checks, revises, or names a limit", "Transfers an idea to a new situation"],
  },
  resources: [
    { label: "Math Antics videos and practice", source: "Math Antics", url: "https://mathantics.com/", purpose: "Use the clearest matching Math Antics explanation as the main visual teaching spine, pause for class predictions, then move into the on-screen Classroom OS investigation. Use available practice selectively when it helps.", gradeFit: "Core Grade 6" },
    { label: "Number Line web app", source: "The Math Learning Center", url: "https://apps.mathlearningcenter.org/number-line/", purpose: "Use this free open-ended projector tool when the class wants to create another whole-number or decimal scale, add custom ticks, or drag and resize jumps together.", gradeFit: "Core Grade 6" },
    { label: "MathUP British Columbia access and teacher support", source: "Surrey Schools ONE / Rubicon", url: "https://surreyschoolsone.ca/resources/mathup", purpose: "Use MathUP to check Grade 6 topic alignment and choose useful games, centres, assessment checks, or extra practice. It does not have to drive the live lesson.", gradeFit: "Teacher planning" },
    { label: "Polypad virtual manipulatives", source: "Mathigon / Amplify", url: "https://mathigon.org/polypad", purpose: "Use exact fraction bars, algebra tiles, balance scales, grids, coins, dice, spinners, graphs, and other manipulatives on the projector.", gradeFit: "Core Grade 6" },
    { label: "Interactive games and puzzles, ages 11–14", source: "NRICH Mathematics", url: "https://nrich.maths.org/interactive-games-and-puzzles-11-14", purpose: "Choose rich games and investigations that reward strategy, noticing, explanation, and revision rather than speed.", gradeFit: "Core Grade 6" },
    { label: "Factors and Multiples Game", source: "NRICH Mathematics", url: "https://nrich.maths.org/games/factors-and-multiples-game", purpose: "Use a tested two-player strategy game through a shared projector or a hand-drawn plain-paper board during the number unit.", gradeFit: "Core Grade 6" },
    { label: "Learning First Peoples classroom resources", source: "FNESC/FNSA", url: "https://www.fnesc.ca/learningfirstpeoples/", purpose: "Use the Math First Peoples guide to extend practice through relationship, place, story, and culturally responsible approaches.", gradeFit: "Teacher planning" },
  ],
};

export const coreLearningPrograms: Record<string, LearningProgram> = {
  [languageArtsProgram.subject]: languageArtsProgram,
  [mathematicsProgram.subject]: mathematicsProgram,
};
