'use client';
import {useEffect,useRef,useState} from 'react';
import {DAY_ARCHIVE_EVENT,DAY_ARCHIVE_KEY,dayPlanForDate,importDayArchive,listDayPlans,publishedDayPlans,readDayRevisions,saveDayPlan,schoolYear,type DayPlan,type DayRevision} from './day-plan-store';
import {vancouverDateKey} from './morning-screen-state';
import './day-plan-library.css';
import {displayedDayPlan,rememberDisplayedDay} from './classroom-navigation-state';
export {default as DayPlanMorning} from './day-plan-morning';
export function useSelectedDayPlan(){
 const read=()=>{try{const id=typeof window==='undefined'?null:new URLSearchParams(window.location.search).get('dayPlan');return id?listDayPlans().find(p=>p.id===id):displayedDayPlan();}catch{return undefined;}};
 const [plan,setPlan]=useState(read);
 useEffect(()=>{const refresh=()=>setPlan(read());window.addEventListener(DAY_ARCHIVE_EVENT,refresh);window.addEventListener('storage',refresh);const timer=window.setInterval(refresh,60000);return()=>{window.removeEventListener(DAY_ARCHIVE_EVENT,refresh);window.removeEventListener('storage',refresh);window.clearInterval(timer);};},[]);
 return plan;
}
function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function DayPlanLibrary(){
 const [plans,setPlans]=useState<DayPlan[]>(publishedDayPlans),[draft,setDraft]=useState<DayPlan>(structuredClone(publishedDayPlans[0])),[revisions,setRevisions]=useState<DayRevision[]>([]),[status,setStatus]=useState(''),[year,setYear]=useState('All years'),[query,setQuery]=useState(''),[copyDate,setCopyDate]=useState(vancouverDateKey()),[dirty,setDirty]=useState(false);
 const latest=useRef({draft,dirty});latest.current={draft,dirty};
 useEffect(()=>{if(!dirty)return;const timer=window.setTimeout(()=>{try{saveDayPlan(draft);setPlans(listDayPlans());setRevisions(readDayRevisions());setDirty(false);setStatus('Changes saved on this browser. Download a backup to keep them elsewhere.');}catch(e){setStatus(`Saving failed: ${String(e)}. Download or print before leaving.`);}},800);return()=>window.clearTimeout(timer);},[draft,dirty]);
 useEffect(()=>{const flush=()=>{if(latest.current.dirty)saveDayPlan(latest.current.draft);};const before=(e:BeforeUnloadEvent)=>{try{flush();}catch{e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>{window.removeEventListener('beforeunload',before);try{flush();}catch{/* Editor already reports persistence errors. */}};},[]);
 const reload=()=>{setPlans(listDayPlans());setRevisions(readDayRevisions());};
 useEffect(()=>{try{reload();const id=new URLSearchParams(window.location.search).get('plan');const selected=listDayPlans().find(p=>p.id===id)??displayedDayPlan();if(selected)setDraft(structuredClone(selected));}catch{setStatus('Saved plans could not be read. Export or recover your existing browser data before saving.');}},[]);
 const edit=(patch:Partial<DayPlan>)=>{setDraft({...draft,...patch});setDirty(true);};
 const save=()=>{try{saveDayPlan(draft);reload();setDirty(false);setStatus('Saved a revision on this browser. Download a backup for another device or next year.');return true;}catch(e){setStatus(`Save failed: ${e instanceof Error?e.message:'browser storage unavailable'}`);return false;}};
 const open=(p:DayPlan)=>{if(dirty&&!save())return;setDraft(structuredClone(p));setDirty(false);setStatus('Plan opened. Earlier saved versions stay in history.');};
 const copy=()=>{if(!copyDate){setStatus('Choose a date for the copy.');return;}if(dirty&&!save())return;const next={...structuredClone(draft),id:`day-${copyDate}-${crypto.randomUUID()}`,date:copyDate,reflection:''};try{if(listDayPlans().some(p=>p.date===copyDate&&!p.id.startsWith("week-day-"))){setStatus('A plan already exists for this date. Open it to adjust it, or choose another date.');return;}saveDayPlan(next);setDraft(next);setDirty(false);reload();setStatus(`A separate copy was saved for ${copyDate}. The original is preserved.`);}catch(e){setStatus(String(e));}};
 return <section className="page day-library"><header><p className="section-kicker">PLAN · TEACH · KEEP · REUSE</p><h1>Day Plans</h1><p>Keep each day, note what worked, and copy it to a new date next year.</p></header><p className="day-storage-note">Published templates are kept with the website. Your edits and week-plan snapshots stay on this browser; download a backup to keep them across devices or browser resets. Avoid student names or confidential notes.</p>
 <div className="day-tools"><button onClick={()=>{try{if(dirty&&!save())return;const records=readDayRevisions();const ids=new Set(records.map(r=>r.plan.id));download('classroom-day-plans-backup.json',[...publishedDayPlans.filter(p=>!ids.has(p.id)).map(p=>({revisionId:`published-${p.id}`,savedAt:'2026-09-16T00:00:00Z',plan:p})),...records]);setStatus('Backup downloaded. Keep it with your teaching files; import it here on another device.');}catch(e){setStatus(String(e));}}}>Download all plans + history</button><label className="day-import">Import backup<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(dirty&&!save())return;if(file.size>20000000)throw new Error('Backup exceeds 20 MB.');importDayArchive(JSON.parse(await file.text()));reload();setStatus('Backup merged. Existing revisions were preserved. Reopen a plan to see imported changes.');}catch(err){setStatus(String(err));}e.target.value='';}}/></label><a href="?view=Weekly+Plan">Weekly Plan</a></div>
 <p role="status">{status}</p><div className="day-library-grid"><aside><label>School year<select value={year} onChange={e=>setYear(e.target.value)}>{['All years',...new Set(plans.map(p=>schoolYear(p.date)))].map(y=><option key={y}>{y}</option>)}</select></label><label>Find a plan<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Title or date"/></label>{plans.filter(p=>(year==='All years'||schoolYear(p.date)===year)&&`${p.title} ${p.date}`.toLowerCase().includes(query.toLowerCase())).map(p=><button className="day-choice" aria-pressed={draft.id===p.id} key={p.id} onClick={()=>open(p)}><small>{p.date||'Reusable template'}</small><strong>{p.title}</strong></button>)}</aside>
 <main><article className="day-print"><h1>{draft.title}</h1><p>{draft.date||'Reusable template'}</p><p>{draft.greeting}</p><p>{draft.arrival}</p><p>{draft.note}</p>{draft.blocks.map((b,i)=><section key={i}><h2>{b.time} · {b.title}</h2><p>{b.notes}</p></section>)}<h2>If we finish quickly</h2><ul>{draft.backups.map(b=><li key={b}>{b}</li>)}</ul>{draft.reflection&&<><h2>Reflection for next time</h2><p>{draft.reflection}</p></>}</article><div className="day-editor"><div className="day-tools"><button onClick={save}>Save revision{dirty?' *':''}</button><a href={`?view=Morning+Screen&mode=student&dayPlan=${encodeURIComponent(draft.id)}`} onClick={e=>{if(dirty&&!save()){e.preventDefault();return;}rememberDisplayedDay(draft.id);}}>Project this day</a><button onClick={()=>window.print()}>Print day plan</button></div><label>Plan title<input maxLength={160} value={draft.title} onChange={e=>edit({title:e.target.value})}/></label><p>{draft.date?`Teaching date: ${draft.date}`:'Undated template — choose a date below to create your day.'}</p><div className="day-tools"><label>New teaching date<input type="date" value={copyDate} onChange={e=>setCopyDate(e.target.value)}/></label><button onClick={copy}>Copy to this date</button></div><label>Welcome heading<input maxLength={160} value={draft.greeting} onChange={e=>edit({greeting:e.target.value})}/></label><label>Arrival instructions<textarea value={draft.arrival} maxLength={800} onChange={e=>edit({arrival:e.target.value})}/></label><label>Teacher plan notes<textarea maxLength={6000} value={draft.note} onChange={e=>edit({note:e.target.value})}/></label>
 {draft.blocks.map((b,i)=><article className="day-block" key={i}><div className="day-block-fields"><label>When<input maxLength={60} value={b.time} onChange={e=>edit({blocks:draft.blocks.map((x,j)=>j===i?{...x,time:e.target.value}:x)})}/></label><label>Activity<input maxLength={180} value={b.title} onChange={e=>edit({blocks:draft.blocks.map((x,j)=>j===i?{...x,title:e.target.value}:x)})}/></label></div><label>Teaching steps<textarea maxLength={6000} value={b.notes} onChange={e=>edit({blocks:draft.blocks.map((x,j)=>j===i?{...x,notes:e.target.value}:x)})}/></label><label>Projector steps (one per line)<textarea maxLength={4000} value={(b.studentSteps??[]).join("\n")} onChange={e=>edit({blocks:draft.blocks.map((x,j)=>j===i?{...x,studentSteps:e.target.value.split("\n").slice(0,8).map(step=>step.slice(0,500))}:x)})}/></label><div className="day-tools">{b.href&&<a href={b.href}>Open activity →</a>}<button disabled={i===0} onClick={()=>{const blocks=[...draft.blocks];[blocks[i-1],blocks[i]]=[blocks[i],blocks[i-1]];edit({blocks});}}>Move up</button><button disabled={draft.blocks.length===1} onClick={()=>edit({blocks:draft.blocks.filter((_,j)=>j!==i)})}>Remove block</button></div></article>)}<button disabled={draft.blocks.length>=30} onClick={()=>edit({blocks:[...draft.blocks,{time:'Next',title:'New activity',notes:'',href:''}]})}>Add activity</button>
 <h2>If we finish quickly</h2><ul>{draft.backups.map(b=><li key={b}>{b}</li>)}</ul><label>Reflection for next time<textarea maxLength={6000} value={draft.reflection} onChange={e=>edit({reflection:e.target.value})} placeholder="What worked? Actual timing? What should we change next year?"/></label><button onClick={save}>Save revision</button><details><summary>Earlier versions ({revisions.filter(r=>r.plan.id===draft.id).length})</summary>{revisions.filter(r=>r.plan.id===draft.id).reverse().map(r=><p key={r.revisionId}><button onClick={()=>{if(dirty&&!save())return;setDraft(structuredClone(r.plan));setDirty(true);setStatus('Earlier version loaded for review. Save it as a new revision to restore it.');}}>{r.savedAt} — open this version</button></p>)}</details><nav className="day-tools"><a href="?view=Games+%26+Activities">Games &amp; Activities</a><a href="?view=Responsibilities">Responsibilities</a><a href="?subject=English+Language+Arts&experience=werewolf-learn">Werewolf lessons</a><a href="https://dlwyatt-eng.github.io/learn/">Student Hub</a></nav></div></main></div></section>;
}
