'use client';
import {useEffect,useRef,useState} from 'react';
import {DAY_ARCHIVE_EVENT,DAY_ARCHIVE_KEY,dayPlanForDate,importDayArchive,listDayPlans,publishedDayPlans,readDayRevisions,saveDayPlan,schoolYear,isSafeDayHref,type DayBlock,type DayMaterial,type DayPlan,type DayRevision} from './day-plan-store';
import {vancouverDateKey} from './morning-screen-state';
import './day-plan-library.css';
import {displayedDayPlan,editDayHref,rememberDisplayedDay} from './classroom-navigation-state';
import DayPlanPrint from './day-plan-print';
export {default as DayPlanMorning} from './day-plan-morning';
export function useSelectedDayPlan(){
 const read=()=>displayedDayPlan();
 const [plan,setPlan]=useState(read);
 useEffect(()=>{const refresh=()=>setPlan(read());window.addEventListener(DAY_ARCHIVE_EVENT,refresh);window.addEventListener('storage',refresh);const timer=window.setInterval(refresh,60000);return()=>{window.removeEventListener(DAY_ARCHIVE_EVENT,refresh);window.removeEventListener('storage',refresh);window.clearInterval(timer);};},[]);
 return plan;
}
function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function SafeLink({href,children}:{href:string;children:React.ReactNode}) {
 return isSafeDayHref(href)?<a href={href} target={href.startsWith('https:')?'_blank':undefined} rel={href.startsWith('https:')?'noopener noreferrer':undefined}>{children}</a>:null;
}
function MaterialEditor({kind,material,onChange}:{kind:'activity'|'worksheet';material?:DayMaterial;onChange:(value:DayMaterial|undefined)=>void}) {
 const title=kind==='worksheet'?'Student worksheet':'Chosen activity / material';
 const value=material??{label:'',href:'',studentSafe:false};
 const update=(patch:Partial<DayMaterial>)=>onChange({...value,...patch});
 return <fieldset className="day-material-editor"><legend>{title}</legend>
  <p>{kind==='worksheet'?'Choose the actual student file or printable page, not the full workshop or answer key.':'Choose the exact activity or material for this block. Keep the full lesson as an optional reference below.'}</p>
  <label>{title} label<input maxLength={180} value={value.label} onChange={e=>update({label:e.target.value})}/></label>
  <label>{title} URL<input maxLength={2000} value={value.href} placeholder="https://… or ./printables/example.pdf" aria-invalid={!!value.href&&!isSafeDayHref(value.href)} onChange={e=>update({href:e.target.value,studentSafe:false})}/></label>
  {value.href&&!isSafeDayHref(value.href)&&<p className="day-field-error">Use a safe HTTPS link or a site PDF/HTML path. No credentials, access tokens or temporary signed downloads.</p>}
  <label className="day-share-check"><input type="checkbox" checked={value.studentSafe} disabled={!value.label.trim()||!isSafeDayHref(value.href)} onChange={e=>update({studentSafe:e.target.checked})}/>I checked this link: safe to show students, with no private notes or answers</label>
  <div className="day-tools"><SafeLink href={value.href}>Preview {kind==='worksheet'?'worksheet to print':'chosen material'} ↗</SafeLink>{material&&<button type="button" onClick={()=>onChange(undefined)}>Clear {kind}</button>}</div>
 </fieldset>;
}
export default function DayPlanLibrary(){
 const [plans,setPlans]=useState<DayPlan[]>(publishedDayPlans),[draft,setDraft]=useState<DayPlan>(structuredClone(publishedDayPlans[0])),[revisions,setRevisions]=useState<DayRevision[]>([]),[status,setStatus]=useState(''),[year,setYear]=useState('All years'),[query,setQuery]=useState(''),[copyDate,setCopyDate]=useState(vancouverDateKey()),[dirty,setDirty]=useState(false);
 const latest=useRef({draft,dirty});latest.current={draft,dirty};
 useEffect(()=>{if(!dirty)return;const timer=window.setTimeout(()=>{try{saveDayPlan(draft);setPlans(listDayPlans());setRevisions(readDayRevisions());setDirty(false);setStatus('Changes saved on this browser. Download a backup to keep them elsewhere.');}catch(e){setStatus(`Saving failed: ${String(e)}. Download or print before leaving.`);}},800);return()=>window.clearTimeout(timer);},[draft,dirty]);
 useEffect(()=>{const flush=()=>{if(latest.current.dirty)saveDayPlan(latest.current.draft);};const before=(e:BeforeUnloadEvent)=>{try{flush();}catch{e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>{window.removeEventListener('beforeunload',before);try{flush();}catch{/* Editor already reports persistence errors. */}};},[]);
 const reload=()=>{setPlans(listDayPlans());setRevisions(readDayRevisions());};
 useEffect(()=>{try{reload();const id=new URLSearchParams(window.location.search).get('plan');const selected=listDayPlans().find(p=>p.id===id)??displayedDayPlan();if(selected){setDraft(structuredClone(selected));if(selected.id.startsWith('week-day-')&&selected.date)setCopyDate(selected.date);}}catch{setStatus('Saved plans could not be read. Export or recover your existing browser data before saving.');}},[]);
 const edit=(patch:Partial<DayPlan>)=>{setDraft({...draft,...patch});setDirty(true);};
 const editBlock=(index:number,patch:Partial<DayBlock>)=>edit({blocks:draft.blocks.map((block,i)=>i===index?{...block,...patch}:block)});
 const rememberEditor=(id:string)=>{window.history.replaceState(window.history.state,'',editDayHref(id));rememberDisplayedDay(id);};
 const save=()=>{try{saveDayPlan(draft);reload();setDirty(false);setStatus('Saved a revision on this browser. Download a backup for another device or next year.');return true;}catch(e){setStatus(`Save failed: ${e instanceof Error?e.message:'browser storage unavailable'}`);return false;}};
 const open=(p:DayPlan)=>{if(dirty&&!save())return;setDraft(structuredClone(p));if(p.id.startsWith('week-day-')&&p.date)setCopyDate(p.date);rememberEditor(p.id);setDirty(false);setStatus('Plan opened. Earlier saved versions stay in history.');};
 const copy=(targetDate=copyDate)=>{if(!targetDate){setStatus('Choose a date for the copy.');return;}if(dirty&&!save())return;const next={...structuredClone(draft),id:`day-${targetDate}-${crypto.randomUUID()}`,date:targetDate,reflection:''};try{if(listDayPlans().some(p=>p.date===targetDate&&!p.id.startsWith("week-day-"))){setStatus('A plan already exists for this date. Open it to adjust it, or choose another date.');return;}saveDayPlan(next);setDraft(next);rememberEditor(next.id);setDirty(false);reload();setStatus(`A separate copy was saved for ${targetDate}. The original is preserved.`);}catch(e){setStatus(String(e));}};
 return <section className="page day-library"><header><p className="section-kicker">PLAN · TEACH · KEEP · REUSE</p><h1>Day Plans</h1><p>Keep each day, note what worked, and copy it to a new date next year.</p></header><p className="day-storage-note">Published templates are kept with the website. Your edits and week-plan snapshots stay on this browser; download a backup to keep them across devices or browser resets. Teacher references are included in local backups, never on the student board. Teacher-only display is not access control. Keep student names, confidential notes, passwords and temporary access links in approved systems.</p>
 <div className="day-tools"><button onClick={()=>{try{if(dirty&&!save())return;const records=readDayRevisions();const ids=new Set(records.map(r=>r.plan.id));download('classroom-day-plans-backup.json',[...publishedDayPlans.filter(p=>!ids.has(p.id)).map(p=>({revisionId:`published-${p.id}`,savedAt:'2026-09-16T00:00:00Z',plan:p})),...records]);setStatus('Backup downloaded. Keep it with your teaching files; import it here on another device.');}catch(e){setStatus(String(e));}}}>Download all plans + history</button><label className="day-import">Import backup<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(dirty&&!save())return;if(file.size>20000000)throw new Error('Backup exceeds 20 MB.');importDayArchive(JSON.parse(await file.text()));reload();setStatus('Backup merged. Existing revisions were preserved. Reopen a plan to see imported changes.');}catch(err){setStatus(String(err));}e.target.value='';}}/></label><a href="?view=Weekly+Plan">Weekly Plan</a></div>
 <p role="status">{status}</p><div className="day-library-grid"><aside><label>School year<select value={year} onChange={e=>setYear(e.target.value)}>{['All years',...new Set(plans.map(p=>schoolYear(p.date)))].map(y=><option key={y}>{y}</option>)}</select></label><label>Find a plan<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Title or date"/></label>{plans.filter(p=>(year==='All years'||schoolYear(p.date)===year)&&`${p.title} ${p.date}`.toLowerCase().includes(query.toLowerCase())).map(p=><button className="day-choice" aria-pressed={draft.id===p.id} key={p.id} onClick={()=>open(p)}><small>{p.date||'Reusable template'}{p.status==='tentative'?' · Tentative':''}</small><strong>{p.title}</strong></button>)}</aside>
 <main><DayPlanPrint plan={draft}/><div className="day-editor"><div className="day-tools"><button onClick={save}>Save revision{dirty?' *':''}</button><a href={`?view=Morning+Screen&mode=student&dayPlan=${encodeURIComponent(draft.id)}`} onClick={e=>{if(dirty&&!save()){e.preventDefault();return;}rememberDisplayedDay(draft.id);}}>Project this day</a><button onClick={()=>window.print()}>Print teacher day plan</button></div>{draft.id.startsWith('week-day-')&&<p className="day-storage-note">This is an automatic weekly snapshot. Copy it to its teaching date below before choosing daily materials; a later Weekly Plan save can replace this snapshot’s current details. Earlier revisions remain in history. <button type="button" onClick={()=>{const existing=dayPlanForDate(draft.date);if(existing&&!existing.id.startsWith("week-day-"))open(existing);else copy(draft.date);}}>Make dated copy / open existing day</button></p>}<label className="day-share-check"><input type="checkbox" checked={draft.status==='tentative'} onChange={e=>edit({status:e.target.checked?'tentative':undefined})}/>Tentative plan · review before teaching</label><label>Plan title<input maxLength={160} value={draft.title} onChange={e=>edit({title:e.target.value})}/></label><p>{draft.date?`Teaching date: ${draft.date}`:'Undated template — choose a date below to create your day.'}</p><div className="day-tools"><label>New teaching date<input type="date" value={copyDate} onChange={e=>setCopyDate(e.target.value)}/></label><button onClick={()=>copy()}>Copy to this date</button></div><label>Welcome heading<input maxLength={160} value={draft.greeting} onChange={e=>edit({greeting:e.target.value})}/></label><label>Arrival instructions<textarea value={draft.arrival} maxLength={800} onChange={e=>edit({arrival:e.target.value})}/></label><label>Teacher plan notes<textarea maxLength={6000} value={draft.note} onChange={e=>edit({note:e.target.value})}/></label>
 {draft.blocks.map((b,i)=><article className="day-block" key={i}>
  <div className="day-block-fields"><label>When<input maxLength={60} value={b.time} onChange={e=>editBlock(i,{time:e.target.value})}/></label><label>Activity title (English)<input maxLength={180} value={b.title} onChange={e=>editBlock(i,{title:e.target.value,titleKo:undefined})}/></label></div>
  <label>First student action (English)<textarea maxLength={500} value={b.firstAction??''} placeholder="One short action to start this block" onChange={e=>editBlock(i,{firstAction:e.target.value,firstActionKo:undefined})}/></label>
  <details className="day-korean-editor"><summary>Optional Korean support · 한국어 도움말</summary><p>English stays visible. Add a matching Korean title and first action. Changing the English clears its paired Korean text for review.</p><label>Korean activity title<input lang="ko" maxLength={180} value={b.titleKo??''} onChange={e=>editBlock(i,{titleKo:e.target.value})}/></label><label>Korean first student action<textarea lang="ko" maxLength={500} value={b.firstActionKo??''} onChange={e=>editBlock(i,{firstActionKo:e.target.value})}/></label></details>
  <label>Teaching steps<textarea maxLength={6000} value={b.notes} onChange={e=>editBlock(i,{notes:e.target.value})}/></label>
  <label>Projector steps (one per line)<textarea maxLength={4000} value={(b.studentSteps??[]).join("\n")} onChange={e=>editBlock(i,{studentSteps:e.target.value.split("\n").slice(0,8).map(step=>step.slice(0,500))})}/></label>
  <details className="day-material-options"><summary>Choose today’s material / student worksheet{b.activity||b.worksheet?` · ${[b.activity?.label,b.worksheet?.label].filter(Boolean).join("; ")}`:" · none selected"}</summary>
  <MaterialEditor kind="activity" material={b.activity} onChange={activity=>editBlock(i,{activity})}/>
  <MaterialEditor kind="worksheet" material={b.worksheet} onChange={worksheet=>editBlock(i,{worksheet})}/>
  </details>
  <label>Full lesson / reference URL (optional)<input maxLength={2000} value={b.href} aria-invalid={!!b.href&&!isSafeDayHref(b.href)} onChange={e=>editBlock(i,{href:e.target.value})}/></label>
  {b.href&&!isSafeDayHref(b.href)&&<p className="day-field-error">Use a safe HTTPS link or a site route, PDF or HTML path.</p>}
  <p className="day-field-help">The full lesson is separate from your chosen material. Only put student-safe references here.</p>
  <details className="day-teacher-reference"><summary>Teacher reference / answer-key page notes · this browser</summary><p>Use a normal sign-in link to an approved service, never a private download token. Notes and links stay off the student board but are included in your teacher printout and JSON backup. No confidential records.</p>
   <label>Teacher reference URL<input maxLength={2000} value={b.teacherReference?.href??''} aria-invalid={!!b.teacherReference?.href&&!isSafeDayHref(b.teacherReference.href)} onChange={e=>editBlock(i,{teacherReference:{href:e.target.value,notes:b.teacherReference?.notes??''}})}/></label>
   {b.teacherReference?.href&&!isSafeDayHref(b.teacherReference.href)&&<p className="day-field-error">Use a safe sign-in link without credentials or access tokens.</p>}
   <label>Teacher page / answer-key notes<textarea maxLength={2000} value={b.teacherReference?.notes??''} placeholder="For example: student page 2; answer key page 3 in the licensed teacher pack" onChange={e=>editBlock(i,{teacherReference:{href:b.teacherReference?.href??'',notes:e.target.value}})}/></label>
   <div className="day-tools">{b.teacherReference?.href&&<SafeLink href={b.teacherReference.href}>Open teacher reference ↗</SafeLink>}{b.teacherReference&&<button onClick={()=>editBlock(i,{teacherReference:undefined})}>Clear teacher reference</button>}</div>
  </details>
  <div className="day-tools">{b.href&&<SafeLink href={b.href}>Full lesson / reference →</SafeLink>}<button disabled={i===0} onClick={()=>{const blocks=[...draft.blocks];[blocks[i-1],blocks[i]]=[blocks[i],blocks[i-1]];edit({blocks});}}>Move up</button><button disabled={draft.blocks.length===1} onClick={()=>edit({blocks:draft.blocks.filter((_,j)=>j!==i)})}>Remove block</button></div>
 </article>)}<button disabled={draft.blocks.length>=30} onClick={()=>edit({blocks:[...draft.blocks,{time:'Next',title:'New activity',notes:'',href:''}]})}>Add activity</button>
 <h2>If we finish quickly</h2><ul>{draft.backups.map(b=><li key={b}>{b}</li>)}</ul><label>Reflection for next time<textarea maxLength={6000} value={draft.reflection} onChange={e=>edit({reflection:e.target.value})} placeholder="What worked? Actual timing? What should we change next year?"/></label><button onClick={save}>Save revision</button><details><summary>Earlier versions ({revisions.filter(r=>r.plan.id===draft.id).length})</summary>{revisions.filter(r=>r.plan.id===draft.id).reverse().map(r=><p key={r.revisionId}><button onClick={()=>{if(dirty&&!save())return;setDraft(structuredClone(r.plan));setDirty(true);setStatus('Earlier version loaded for review. Save it as a new revision to restore it.');}}>{r.savedAt} — open this version</button></p>)}</details><nav className="day-tools"><a href="?view=Games+%26+Activities">Games &amp; Activities</a><a href="?view=Responsibilities">Responsibilities</a><a href="?subject=English+Language+Arts&experience=werewolf-learn">Werewolf lessons</a><a href="https://dlwyatt-eng.github.io/learn/">Student Hub</a></nav></div></main></div></section>;
}
