export const grade6MathExperienceIds = [
  "magnitude-gallery",
  "strategy-league",
  "pack-and-sync",
  "scoreboard-rules",
  "fraction-ratio-remix",
  "decimal-dispatch",
  "sale-lab",
  "pattern-forecast",
  "equation-balance",
  "graph-story-lab",
  "probability-game-audit",
  "geometry-field-lab",
  "zoo-design-studio",
  "transformation-cipher",
  "space-under-constraints",
] as const;

export type Grade6MathExperienceId = (typeof grade6MathExperienceIds)[number];
export type MathDeliveryModeId = "math-antics-supported" | "hybrid" | "teacher-led-replacement";

export type MathDeliveryMode = {
  id: MathDeliveryModeId;
  label: string;
  bestWhen: string;
  steps: readonly string[];
};

export type MathExperienceModePlan = {
  experienceId: Grade6MathExperienceId;
  title: string;
  curriculum: readonly string[];
  conceptPackIds: readonly string[];
  clipFocus: string;
  explanation: string;
  visualModel: string;
  workedExample: string;
  guidedPractice: string;
  teacherAnswers: string;
  collaborativeTask: string;
  authenticApplication: string;
  independentCheck: string;
  misconceptionMoves: readonly { misconception: string; correctiveMove: string }[];
  differentiation: { support: string; core: string; extension: string };
  printableSupport: string;
  offlineFallback: string;
  spacesEvidence: string;
  mathUpUse: string;
  modes: Record<MathDeliveryModeId, MathDeliveryMode>;
};

type ModePlanSeed = Omit<MathExperienceModePlan, "modes" | "mathUpUse">;

function completePlan(seed: ModePlanSeed): MathExperienceModePlan {
  return {
    ...seed,
    mathUpUse: "Optional after formative evidence: choose a matching game, short check, or extra practice only when it answers a real learner need. MathUP is not the lesson spine.",
    modes: {
      "math-antics-supported": {
        id: "math-antics-supported",
        label: "Math Antics supported",
        bestWhen: "A short visual explanation will make the first model easier to see.",
        steps: [
          `Before viewing, pose the lesson question and prepare ${seed.visualModel.toLowerCase()}.`,
          `Play only the useful Math Antics section. ${seed.clipFocus}`,
          `Rebuild the idea with the Hub model and worked example: ${seed.workedExample}`,
          `Complete the guided practice, ${seed.collaborativeTask.toLowerCase()}, and the independent check.`,
        ],
      },
      hybrid: {
        id: "hybrid",
        label: "Hybrid",
        bestWhen: "Students need one selected clip or replay plus substantial teacher modelling and investigation.",
        steps: [
          `Use a short clip segment or still frame only for this focus: ${seed.clipFocus}`,
          `Teach the explanation directly: ${seed.explanation}`,
          `Model ${seed.workedExample.toLowerCase()}, then release the guided practice one card at a time.`,
          `Move into ${seed.authenticApplication.toLowerCase()} and finish with the independent check.`,
        ],
      },
      "teacher-led-replacement": {
        id: "teacher-led-replacement",
        label: "Teacher-led replacement",
        bestWhen: "The video is unavailable, unsuitable for the group, or unnecessary.",
        steps: [
          `Skip Math Antics. Launch with the printable or projected model: ${seed.visualModel}`,
          `Teach this explanation and worked example aloud: ${seed.explanation} ${seed.workedExample}`,
          `Use the supplied guided cards; reveal ${seed.teacherAnswers.toLowerCase()} only after a first attempt.`,
          `Run ${seed.collaborativeTask.toLowerCase()}, apply it through ${seed.authenticApplication.toLowerCase()}, then collect the independent check.`,
        ],
      },
    },
  };
}

export const mathExperienceModePlans: readonly MathExperienceModePlan[] = [
  completePlan({
    experienceId: "magnitude-gallery",
    title: "Magnitude Gallery",
    curriculum: ["small to large numbers: thousandths to billions", "estimate reasonably", "represent mathematics in concrete, pictorial, and symbolic forms"],
    conceptPackIds: ["magnitude-place-value-pack"],
    clipFocus: "Pause at tenths, hundredths, and thousandths; ask what the 8 is worth before the narrator answers.",
    explanation: "Read the two endpoints, count equal spaces, calculate one interval, and use place value before locating a number.",
    visualModel: "the three-scale 0.008 number lines and decimal/period place-value charts",
    workedExample: "place 0.008 on lines ending at 1, 0.1, and 0.01 while keeping the number fixed",
    guidedPractice: "Four scale and place-value partner cards move from thousandths to billions.",
    teacherAnswers: "the answer under each partner card and the three-item check key",
    collaborativeTask: "partners design and repair a two-scale trap",
    authenticApplication: "choosing an honest scale for a local measurement or data display",
    independentCheck: "Locate 0.008 on a 0-to-0.01 line and compare two large numbers from the first unequal place.",
    misconceptionMoves: [
      { misconception: "Every mark is worth one.", correctiveMove: "Cover the points; label endpoints and divide the interval before placing anything." },
      { misconception: "The value changed because its dot moved.", correctiveMove: "Keep the number card physically fixed while swapping labelled scale strips underneath it." },
    ],
    differentiation: { support: "Use one 0-to-0.01 strip and a colour for each thousandth.", core: "Use all three decimal scales and one large-number comparison.", extension: "Design two honest scales that create different visual impressions of the same change." },
    printableSupport: "Three-scale sheet, decimal place-value chart, large-number period chart, guided cards, and separate teacher key.",
    offlineFallback: "Draw ten equal spaces on chart paper and use handwritten number cards; no video, website, or student device is needed.",
    spacesEvidence: "Keep locally unless an individual scale explanation fills a genuine evidence gap.",
  }),
  completePlan({
    experienceId: "strategy-league",
    title: "Strategy League",
    curriculum: ["multiplication and division facts to 100", "computational fluency with whole numbers", "apply multiple strategies"],
    conceptPackIds: ["operations-fluency-pack"],
    clipFocus: "Stop before the final product or quotient and ask students to predict a useful decomposition.",
    explanation: "Estimate the answer's neighbourhood, choose a method that fits the numbers, calculate accurately, and verify by another route.",
    visualModel: "the estimate → break apart → exact answer → inverse check pathway",
    workedExample: "solve 23×16 as 23×10 + 23×6 and verify 368 from another direction",
    guidedPractice: "Partner cards compare make-100, decomposition, partial quotients, and error analysis.",
    teacherAnswers: "the answer under every partner card and operation check",
    collaborativeTask: "partners borrow one useful strategy move and teach it back without speed ranking",
    authenticApplication: "choosing an efficient calculation route for equal packs, inventory, or event planning",
    independentCheck: "Estimate, solve, and verify 38×24 and 735÷21.",
    misconceptionMoves: [
      { misconception: "The fastest method is always best.", correctiveMove: "Compare accuracy, clarity, and number fit before discussing efficiency." },
      { misconception: "An exact-looking answer needs no estimate.", correctiveMove: "Place the answer inside or outside the predicted range before accepting it." },
    ],
    differentiation: { support: "Use a multiplication chart, smaller card, drawing, or partial product frame.", core: "Show one accurate route and a different check.", extension: "Compare three methods and identify where each becomes inefficient." },
    printableSupport: "Method cards, estimate-exact-check mat, calculation set, error cards, and key.",
    offlineFallback: "Run the same strategy comparison with board problems, mini-whiteboards, and printed cards.",
    spacesEvidence: "An optional one-minute Strategy Snapshot is used only when evidence is otherwise thin.",
  }),
  completePlan({
    experienceId: "pack-and-sync",
    title: "Pack It / Sync It",
    curriculum: ["factors and multiples", "greatest common factor", "least common multiple", "use logic to solve puzzles and games"],
    conceptPackIds: ["factors-multiples-pack"],
    clipFocus: "Pause after the first factor pair and ask whether the story is splitting fixed supplies or finding a repeating meeting.",
    explanation: "Factors divide fixed amounts exactly; multiples mark repeated counts. GCF makes the greatest identical packs, while LCM finds the first shared meeting.",
    visualModel: "counter packing mats beside a two-signal timeline",
    workedExample: "use GCF(24,36)=12 for packs and distinguish it from LCM(24,36)=72 for cycles",
    guidedPractice: "Four cards require pack building, signal timing, tool choice, and error repair.",
    teacherAnswers: "the partner-card answers and independent GCF/LCM key",
    collaborativeTask: "groups build supplies or act out repeating signals, then sort new stories by tool",
    authenticApplication: "designing equal supply kits and synchronizing fictional warning signals",
    independentCheck: "Find GCF(20,32), LCM(5,8), and name the context clue for GCF.",
    misconceptionMoves: [
      { misconception: "Factor and multiple mean the same thing.", correctiveMove: "Put fixed objects in groups for factors and extend a timeline for multiples." },
      { misconception: "Any common number is the answer.", correctiveMove: "Circle the story word greatest or first/least before choosing from the list." },
    ],
    differentiation: { support: "Keep quantities within known facts and build every case with counters.", core: "Solve and explain one GCF and one LCM story.", extension: "Write paired stories using the same numbers but different operations." },
    printableSupport: "Supply mat, factor organizer, signal timeline, story sort, guided cards, and separate key.",
    offlineFallback: "Use counters, two paper strips, claps or taps, and handwritten story cards.",
    spacesEvidence: "Teacher observation and the paper record are sufficient; no post is needed.",
  }),
  completePlan({
    experienceId: "scoreboard-rules",
    title: "Scoreboard Rules",
    curriculum: ["order of operations with whole numbers", "use logic and patterns to solve puzzles and games"],
    conceptPackIds: ["operations-fluency-pack"],
    clipFocus: "Pause when two possible answers appear and have the class mark the operation that the shared convention completes first.",
    explanation: "Use brackets first, then multiplication or division from left to right, then addition or subtraction from left to right.",
    visualModel: "number, operation, and bracket tiles with arrows showing completed moves",
    workedExample: "compare 5+3×4=17 with (5+3)×4=32 and connect each expression to its scoring story",
    guidedPractice: "The printable score-rule set provides build, solve, bracket-change, and repair rounds.",
    teacherAnswers: "the hidden score-card solutions and operation-check answers",
    collaborativeTask: "teams exchange a score rule, solve it independently, and repair ambiguous wording",
    authenticApplication: "writing a fair, reproducible scoring rule for a fictional game",
    independentCheck: "Solve two expressions and explain exactly which move the brackets changed.",
    misconceptionMoves: [
      { misconception: "Always work from left to right.", correctiveMove: "Physically cover operations not yet available and reveal the priority groups." },
      { misconception: "Brackets are decoration.", correctiveMove: "Act out both scoring stories and match each to the expression that repeats the intended event." },
    ],
    differentiation: { support: "Use whole numbers, colour-coded operation tiles, and one move per line.", core: "Solve and author an unambiguous score rule.", extension: "Use exponents only as a clearly optional later challenge." },
    printableSupport: "Expression tiles, bracket cards, score-rule cards, worked examples, and teacher solutions.",
    offlineFallback: "Build every expression from paper tiles and record one move per line on the board.",
    spacesEvidence: "Complete as a classroom game lab; no post is needed.",
  }),
  completePlan({
    experienceId: "fraction-ratio-remix",
    title: "Fraction–Ratio Remix",
    curriculum: ["improper fractions and mixed numbers", "introduction to ratios", "represent quantities in multiple forms"],
    conceptPackIds: ["fraction-ratio-percent-pack"],
    clipFocus: "Pause at the first ratio or fraction rename and have students build the next equivalent model before viewing it.",
    explanation: "Equivalent names preserve the amount: regroup equal fraction parts into wholes and scale every part of a ratio by the same factor.",
    visualModel: "fraction strips, repeated colour batches, and part-to-part/part-to-whole tables",
    workedExample: "build 7/4 as 1 3/4 and grow 2:3 into 4:6 and 6:9",
    guidedPractice: "Partner cards rename, compare, scale ratios, and connect friendly percents.",
    teacherAnswers: "the fraction/ratio partner answers and separate kit answer card",
    collaborativeTask: "partners build equivalent batches and repair one batch whose parts changed by different factors",
    authenticApplication: "keeping the balance of a fictional mosaic or mixture while changing its size",
    independentCheck: "Order three fractions, complete an equivalent ratio, and explain the representation used.",
    misconceptionMoves: [
      { misconception: "A larger denominator makes a fraction larger.", correctiveMove: "Place both fractions on equal-size strips or the same number line." },
      { misconception: "Adding the same number preserves a ratio.", correctiveMove: "Repeat complete physical batches and label the multiplier on both parts." },
    ],
    differentiation: { support: "Use matching-size strips and whole repeated batches.", core: "Connect model, fraction name, ratio table, and repair.", extension: "Compare close ratios using each part's share of the whole." },
    printableSupport: "Fraction strips, batch cards, ratio table, broken-batch repair, and key.",
    offlineFallback: "Cut paper strips and coloured squares; all reasoning and checking works without a screen.",
    spacesEvidence: "Keep the models for conferencing; no default upload.",
  }),
  completePlan({
    experienceId: "decimal-dispatch",
    title: "Decimal Dispatch",
    curriculum: ["multiplication and division of decimals", "estimate reasonably", "financial literacy"],
    conceptPackIds: ["decimal-operations-pack"],
    clipFocus: "Before each exact result, ask for a sensible range and the place value of the final digit.",
    explanation: "Model the decimal as tenths, hundredths, or thousandths; estimate; calculate; and reject a result that cannot fit the context.",
    visualModel: "a place-value mat and base-ten grid linked to written multiplication or division",
    workedExample: "show 7.2÷9 as 72 tenths shared into 9 groups, giving 8 tenths or 0.8",
    guidedPractice: "Invoice cards move through estimation, visible calculation, planted-error diagnosis, and verification.",
    teacherAnswers: "the decimal workshop answers and separate invoice key",
    collaborativeTask: "dispatch teams compare methods and stamp fictional invoices makes sense or send back",
    authenticApplication: "auditing a fictional classroom order before checkout",
    independentCheck: "Estimate and solve one decimal multiplication and division, then diagnose a misplaced decimal.",
    misconceptionMoves: [
      { misconception: "Line up the first digits instead of place values.", correctiveMove: "Place every digit in a labelled ones/tenths/hundredths column before calculating." },
      { misconception: "A calculator-looking result must be reasonable.", correctiveMove: "Compare it with the estimate and unit before checking keystrokes." },
    ],
    differentiation: { support: "Use money, tenths grids, and repeated addition before a compact algorithm.", core: "Model, estimate, calculate, and audit.", extension: "Create a believable decimal error that two different checks can expose." },
    printableSupport: "Invoice, price cards, place-value mat, decimal-grid prompts, practice, and separate key.",
    offlineFallback: "Use printed fictional invoices, graph paper, and place-value charts; calculators are optional final checks.",
    spacesEvidence: "Keep as local practice or checkpoint.",
  }),
  completePlan({
    experienceId: "sale-lab",
    title: "Sale Lab",
    curriculum: ["whole-number percents and percentage discounts", "simple budgeting and consumer math", "use mathematical arguments for choices"],
    conceptPackIds: ["fraction-ratio-percent-pack", "decimal-operations-pack"],
    clipFocus: "Pause before the procedure and find 50%, 25%, or 10% using a familiar fraction or benchmark.",
    explanation: "Identify the whole, decide whether the unknown is the part, percent, or whole, represent the relationship, then interpret the result in the budget.",
    visualModel: "hundred grids, benchmark fraction strips, and a running fictional budget",
    workedExample: "find 25% of $48 as one quarter, subtract the $12 discount, and compare the $36 price with a fixed offer",
    guidedPractice: "Offer cards include part, whole, percent, missing-value, and surprise-fee cases.",
    teacherAnswers: "the percent/decimal pack answers and separate Sale Lab key",
    collaborativeTask: "teams compare offers and revise a fictional event plan after a constraint card",
    authenticApplication: "making a transparent consumer and budget decision without discussing family finances",
    independentCheck: "Solve one missing part, one missing whole, and one missing percent, each with units.",
    misconceptionMoves: [
      { misconception: "25% off means subtract $25.", correctiveMove: "Name and shade the whole, then find 25 of every 100 or one quarter of that whole." },
      { misconception: "The largest-looking discount number is best.", correctiveMove: "Calculate both final prices including equal fees before deciding." },
    ],
    differentiation: { support: "Use benchmark percentages and pre-labelled hundred grids.", core: "Solve part/whole/percent cases and justify one decision.", extension: "Test taxes, fees, or changing constraints without inventing family data." },
    printableSupport: "Hundred-grid routes, offers, fictional budget, surprise cards, and key.",
    offlineFallback: "Use printed offer cards, grids, and a paper running total; a calculator is optional after showing a method.",
    spacesEvidence: "Use only when this authentic budget fills a real Math evidence need.",
  }),
  completePlan({
    experienceId: "pattern-forecast",
    title: "Pattern Forecast",
    curriculum: ["increasing and decreasing patterns", "expressions, tables, and graphs as functional relationships", "test conjectures"],
    conceptPackIds: ["pattern-relations-pack"],
    clipFocus: "Pause after the first stages; ask what changes, what stays fixed, and whether a decreasing route would use the same representations.",
    explanation: "Connect every stage to one table row, graph point, verbal rule, and tested expression; include increasing and decreasing constant change.",
    visualModel: "paired growing and shrinking models with tables, graphs, words, and expressions",
    workedExample: "compare 4n+3 with 42−5(n−1), test Stage 1, forecast, and name the physical stopping point",
    guidedPractice: "Four cards cover increasing, decreasing, graph direction, and context limits.",
    teacherAnswers: "the partner-card solutions and three independent-check answers",
    collaborativeTask: "pairs build, graph, and exchange one increasing or decreasing route for verification",
    authenticApplication: "forecasting stages while identifying when a real count can no longer follow the symbolic rule",
    independentCheck: "Write and verify one increasing and one decreasing rule, including a graph or table connection.",
    misconceptionMoves: [
      { misconception: "The Stage 1 value is always the coefficient.", correctiveMove: "Separate repeated change from fixed pieces with two colours and test n=1." },
      { misconception: "A negative output is always a possible physical stage.", correctiveMove: "Continue the expression but circle the last stage allowed by the story's units." },
    ],
    differentiation: { support: "Use counters and a pre-labelled table before symbols.", core: "Connect both direction types across five representations.", extension: "Compare rules with equal change and different starts or test where routes meet." },
    printableSupport: "Increasing/decreasing stage cards, table-and-graph organizer, rule tester, context-limit prompt, and key.",
    offlineFallback: "Build stages from counters and draw axes on grid paper; the interactive forest is optional.",
    spacesEvidence: "Save one complete representation set only when selected as evidence.",
  }),
  completePlan({
    experienceId: "equation-balance",
    title: "Equation Balance",
    curriculum: ["one-step equations with whole-number coefficients and solutions", "reason and communicate mathematically"],
    conceptPackIds: ["one-step-equations-pack"],
    clipFocus: "Pause before the inverse move; ask what can be done to both sides without breaking equality.",
    explanation: "An equation states equal values. Model both sides, undo the operation while preserving equality, isolate the unknown, and substitute into the original equation.",
    visualModel: "a balance mat with covered cups/counters linked line-by-line to symbols",
    workedExample: "solve x+4=11 by removing four from both sides and verify 7+4=11",
    guidedPractice: "Four cases cover addition, multiplication, division, and the subtraction trap 72−x=29.",
    teacherAnswers: "the answer beneath each teacher partner card and the independent-check key",
    collaborativeTask: "partners author, exchange, solve, and substitution-check one-step mysteries",
    authenticApplication: "representing an unknown equal share or missing quantity in a clear mathematical statement",
    independentCheck: "Solve two equations and diagnose one false inverse move.",
    misconceptionMoves: [
      { misconception: "Equals means the answer comes next.", correctiveMove: "Compare two complete expressions on a physical balance and calculate both sides." },
      { misconception: "Move a number across and change its sign.", correctiveMove: "Write the same equality-preserving operation on both sides before simplifying." },
    ],
    differentiation: { support: "Use cups, counters, and facts with low computation demand.", core: "Solve and check all four one-step structures.", extension: "Create a false solution line for a partner to diagnose." },
    printableSupport: "Balance mat, cup/counter cards, inverse reference, guided mysteries, repair cards, and key.",
    offlineFallback: "Use paper covers and counters on a hand-drawn balance; no clip or interactive lab is required.",
    spacesEvidence: "Keep the balance proof and check locally.",
  }),
  completePlan({
    experienceId: "graph-story-lab",
    title: "Graph Story Lab",
    curriculum: ["line graphs", "interpret data", "estimate reasonably", "communicate limits"],
    conceptPackIds: ["collect-summarize-data-pack"],
    clipFocus: "Pause when axes and scales appear; ask what each interval is worth and what the graph cannot explain.",
    explanation: "Start with a question, identify variables and units, organize the values, choose equal intervals, plot in order, and state only claims the graph supports.",
    visualModel: "same-data line graphs with wide and close vertical scales plus a data table",
    workedExample: "graph 48,50,49,52,53,54 on two valid scales and compare the visual impression",
    guidedPractice: "Cards supply two data sets, labelled and blank axes, a graph checklist, claim, and limit frames.",
    teacherAnswers: "the Graph Story key and support-pack check answers",
    collaborativeTask: "groups become or rebuild a graph, then audit another display's title, axes, intervals, claim, and limit",
    authenticApplication: "representing a safe local or fictional change over time without inventing a cause",
    independentCheck: "Construct one line graph and write one supported claim plus one limit.",
    misconceptionMoves: [
      { misconception: "A steeper-looking line proves a larger change.", correctiveMove: "Place the same values on a second scale and calculate the actual difference." },
      { misconception: "The graph explains why values changed.", correctiveMove: "Separate what the graph measures from a causal question requiring another source." },
    ],
    differentiation: { support: "Use pre-labelled axes and a six-value set.", core: "Choose scale, graph, claim, and limit.", extension: "Defend which of two accurate scales best answers a stated question." },
    printableSupport: "Graph pair, data cards, blank/pre-labelled axes, checklist, claim/limit frames, and key.",
    offlineFallback: "Use grid paper, ruler, printed data, and a floor or board graph.",
    spacesEvidence: "Reuse suitable Science data or select one environmental graph only if useful.",
  }),
  completePlan({
    experienceId: "probability-game-audit",
    title: "Probability Game Audit",
    curriculum: ["single-outcome theoretical and experimental probability", "use experiment data to predict and compare"],
    conceptPackIds: ["single-outcome-probability-pack"],
    clipFocus: "Pause before a result and distinguish the theoretical prediction from what a short experiment must produce.",
    explanation: "List equally likely outcomes, calculate theoretical probability from the design, run and record trials, then compare experimental variation without treating prediction as a promise.",
    visualModel: "an exact-area spinner beside 20-trial and combined-class frequency records",
    workedExample: "compare P(blue)=1/2 with 12 blue results in 20 trials and explain why the difference is possible",
    guidedPractice: "Cards cover equal/unequal spinners, outcome lists, 20/40-trial comparisons, and redesign.",
    teacherAnswers: "the probability partner answers and separate game-audit key",
    collaborativeTask: "teams run and merge trials, then redesign a spinner to meet a stated fairness condition",
    authenticApplication: "auditing whether a fictional game's design meets its claimed probability goal",
    independentCheck: "State theoretical probability, summarize trials, and explain whether the evidence supports the claim.",
    misconceptionMoves: [
      { misconception: "One quarter means exactly one success in every four trials.", correctiveMove: "Run several four-trial batches and compare variation with the long-run prediction." },
      { misconception: "Different colours are automatically equally likely.", correctiveMove: "Measure exact area or count equally likely outcomes instead of appearances." },
    ],
    differentiation: { support: "Use an equal-section spinner and tally icons.", core: "Compare theory with at least 20 trials.", extension: "Compare sample sizes or verify a constrained redesign with fractions." },
    printableSupport: "Spinner cards, outcome frame, trial tables, redesign brief, and separate key.",
    offlineFallback: "Use paperclip spinners, coins, dice, counters, and paper tally tables.",
    spacesEvidence: "One selected audit may be posted if it serves the evidence plan.",
  }),
  completePlan({
    experienceId: "geometry-field-lab",
    title: "Geometry Field Lab",
    curriculum: ["angle measurement and classification", "triangles", "properties of shapes"],
    conceptPackIds: ["angle-triangle-pack"],
    clipFocus: "Pause before measurement; compare the opening with 45°, 90°, and 180° reference angles.",
    explanation: "Estimate first, align the protractor centre and zero ray, measure the opening, and classify angles or triangles from marked properties rather than orientation.",
    visualModel: "reference-angle folds, protractor placement, and rotated triangle property cards",
    workedExample: "measure and classify 35°, 90°, 125°, 180°, and 235°, then retain every true triangle family name",
    guidedPractice: "Angle set, triangle sort, polygon-angle prompt, and full-turn/reflex cases include answers.",
    teacherAnswers: "the angle/triangle pack answers and separate expedition key",
    collaborativeTask: "partners estimate, measure, classify, and defend a rotated shape using marks and properties",
    authenticApplication: "checking angles and triangle constraints in a field or design plan",
    independentCheck: "Measure/classify angles and justify one triangle classification from evidence.",
    misconceptionMoves: [
      { misconception: "Read whichever protractor number appears first.", correctiveMove: "Trace the starting ray to its zero before following the scale." },
      { misconception: "Rotation changes a triangle's type.", correctiveMove: "Mark equal sides, angles, and the right-angle square before turning the card." },
    ],
    differentiation: { support: "Use 45/90/180 reference strips and larger print protractors.", core: "Estimate, measure, and classify angle and triangle sets.", extension: "Construct from constraints or reason about inclusive families and reflex turns." },
    printableSupport: "Reference strip, angle set, rotated triangles, polygon prompts, and key.",
    offlineFallback: "Fold paper reference angles and use printed protractors/shape cards.",
    spacesEvidence: "Keep as practice unless geometry evidence is specifically needed.",
  }),
  completePlan({
    experienceId: "zoo-design-studio",
    title: "Zoo Design Studio",
    curriculum: ["perimeter of complex shapes", "area of triangles, parallelograms, and trapezoids", "properties of polygons"],
    conceptPackIds: ["polygon-classification-pack", "formula-perimeter-pack", "area-recompose-pack"],
    clipFocus: "Pause at each shape model; trace the inside for area, outside for perimeter, and perpendicular height separately.",
    explanation: "Classify from properties, derive area by cutting/recomposing, label every dimension and unit, and test the plan against access constraints.",
    visualModel: "nested polygon families, tiled perimeter/area contrast, and cut-and-move area derivations",
    workedExample: "derive and calculate the area/perimeter of supplied rectangle, triangle, parallelogram, trapezoid, and L-shape habitats",
    guidedPractice: "Three concept packs and habitat cards provide sequenced examples with teacher answers.",
    teacherAnswers: "partner-card answers in all three packs and the Zoo core-answer card",
    collaborativeTask: "design teams place habitats, verify one another's calculations and access route, and request permission before changing work",
    authenticApplication: "building a fictional 30 m×24 m site plan whose geometry and accessible path survive a peer check",
    independentCheck: "Calculate one area, one complex perimeter, and explain the perpendicular height used.",
    misconceptionMoves: [
      { misconception: "Use the slanted side as height.", correctiveMove: "Draw the perpendicular square and recompose the shape before using a formula." },
      { misconception: "Add all outside and shared edges for perimeter.", correctiveMove: "Trace only the boundary requested and mark shared fences once." },
    ],
    differentiation: { support: "Use four core habitats and a pre-gridded smaller site.", core: "Place six shapes, calculate, check access, and revise.", extension: "Solve missing dimensions or compare two feasible layouts by trade-offs." },
    printableSupport: "Exact site brief, habitat cards, formula derivations, calculation record, peer check, revision note, and key.",
    offlineFallback: "All design work runs with grid paper, rulers, shape cards, and optional cut-outs.",
    spacesEvidence: "Use one combined Zoo artifact rather than separate formula uploads.",
  }),
  completePlan({
    experienceId: "transformation-cipher",
    title: "Transformation Cipher",
    curriculum: ["combinations of transformations", "location and movement", "represent spatial reasoning"],
    conceptPackIds: ["first-quadrant-transformations-pack"],
    clipFocus: "Pause before plotting and rehearse x first, then y; the optional negative-coordinate bridge comes only after the Grade 6 core.",
    explanation: "Apply translations, reflections, and rotations to every point in order, label each image, and verify size/shape with an overlay or corresponding measurements.",
    visualModel: "first-quadrant grids, colour-coded coordinate routes, mirror lines, turn centres, and tracing overlays",
    workedExample: "translate a five-point creature 3 right/1 up, then reflect the new image across x=6",
    guidedPractice: "Four cards cover translation, reflection, rotation, and why move order matters.",
    teacherAnswers: "the core transformation partner answers and separate cipher key",
    collaborativeTask: "partners exchange two-move ciphers and revise any instruction that does not reproduce the intended image",
    authenticApplication: "encoding a reproducible route or figure while proving geometric properties were preserved",
    independentCheck: "Complete one translation/reflection case and name two preservation checks.",
    misconceptionMoves: [
      { misconception: "Apply both moves to the starting figure.", correctiveMove: "Use prime and double-prime labels; Move 2 begins only from the primed image." },
      { misconception: "A reflection can be measured diagonally.", correctiveMove: "Draw perpendicular segments from each point to the named mirror line." },
    ],
    differentiation: { support: "Use a triangle, colour-coded x/y arrows, and tracing paper.", core: "Apply and verify two first-quadrant transformations.", extension: "Compare move order; only then open the separately labelled four-quadrant bridge." },
    printableSupport: "First-quadrant grids, point cards, transformation reference, overlays, cipher record, and key.",
    offlineFallback: "Use grid and tracing paper; every core move, check, and cipher works without video or devices.",
    spacesEvidence: "Assess the first-quadrant combination locally before any optional extension.",
  }),
  completePlan({
    experienceId: "space-under-constraints",
    title: "Space Under Constraints",
    curriculum: ["area, perimeter, volume, and capacity", "simple budgeting and consumer math", "mathematical modelling"],
    conceptPackIds: ["polygon-classification-pack", "formula-perimeter-pack", "area-recompose-pack", "volume-capacity-pack"],
    clipFocus: "Pause before formulas; have students cover, outline, or layer the planned space so every number has a visible referent.",
    explanation: "Translate each design requirement into a measurable constraint, calculate with units, keep an itemized budget, test access/capacity, and revise from a failed check.",
    visualModel: "an exact 8 m×6 m gridded site, zone cards, route width, cube layers, and budget table",
    workedExample: "verify a minimum 18 m² work zone, 13.5 m³ combined storage, 1.2 m route, and $2,010 base cost",
    guidedPractice: "Four measurement packs and the exact design cards provide examples, checks, and answers.",
    teacherAnswers: "the measurement-pack answers and separate Space Constraints key",
    collaborativeTask: "teams trade plans, run size/cost/capacity/access break tests, and document one repair",
    authenticApplication: "designing a fictional maker room that serves 18 people within an exact footprint and budget",
    independentCheck: "Submit a labelled plan record proving area, capacity, route, itemized cost, and one evidence-based revision.",
    misconceptionMoves: [
      { misconception: "If the sketch looks open, the access route works.", correctiveMove: "Trace and measure the continuous 1.2 m route from the doorway to every zone." },
      { misconception: "A total without units proves the plan.", correctiveMove: "Attach every value to its constraint, measurement unit, and calculation source." },
    ],
    differentiation: { support: "Use pre-sized zone cards and a partially labelled budget table.", core: "Prove every constraint and repair one failed break test.", extension: "Compare two feasible designs and defend a trade-off with evidence." },
    printableSupport: "Exact site brief, zone/price cards, capacity and doorway rules, break-test sheet, record, and key.",
    offlineFallback: "Use grid paper, rulers, paper zone cards, cubes or sketches, and a handwritten budget.",
    spacesEvidence: "Use only when this replaces Zoo Design or becomes the shared showcase format.",
  }),
] as const;

export function mathModePlanFor(experienceId: string) {
  return mathExperienceModePlans.find((plan) => plan.experienceId === experienceId);
}
