import type { MathSupportPack } from "./math-program-supports";
import type { WordHelp } from "./program-types";

const words = (...items: [string, string, string][]): WordHelp[] => items.map(([term, meaning, example]) => ({ term, meaning, example }));

/**
 * Complete teacher-led replacement packs for the five experiences that already
 * had strong applications but did not yet have a full, printable concept lesson.
 * Math Antics can support these lessons; none of the core learning depends on it.
 */
export const mathCoreDepthPacks: MathSupportPack[] = [
  {
    id: "magnitude-place-value-pack",
    anchorIds: ["magnitude-gallery"],
    title: "Read the scale before placing the number",
    shortTitle: "Magnitude and place-value workshop",
    timing: "September · Weeks 1–2",
    blocks: "2 × 45–55 min + short retrieval",
    role: "BC CORE",
    readinessLevel: "full",
    mathUpTopics: ["Whole Numbers Greater Than One Million", "Representing, Estimating, and Comparing Decimal Numbers"],
    prerequisite: "Read whole numbers to one million and connect tenths and hundredths to equal parts of one whole.",
    learningGoal: "Use place value, endpoints, and equal intervals to locate, compare, and explain numbers from thousandths to billions.",
    whyBefore: "The Magnitude Gallery becomes meaningful only when students can name what one interval is worth. This complete paper-and-projector lesson teaches that idea before the interactive scale changes.",
    background: [
      "A digit has a face value and a place value. In 0.008, the 8 means eight thousandths; in 0.08 it means eight hundredths.",
      "Read a number line in this order: left endpoint, right endpoint, number of equal spaces, value of one space. Do not assume every mark is worth one.",
      "On a 0-to-1 line, 0.008 sits in the first hundredth. On a 0-to-0.01 line, the same number sits eight tenths of the way across. The number stays fixed while the scale changes.",
      "For large numbers, group digits in threes and name the periods: ones, thousands, millions, billions. Compare the greatest place first.",
    ],
    teacherMoves: [
      "Build 0.008 with a place-value chart: 0 ones, 0 tenths, 0 hundredths, and 8 thousandths.",
      "Model a 0-to-1 line divided into ten equal spaces, then subdivide the first tenth so 0.008 can be placed honestly.",
      "Keep 0.008 fixed while changing only the endpoint to 0.1 and 0.01. Narrate how the interval value changes.",
      "Build 3,405,000,000 in a period chart and compare it with 3,450,000,000 from the greatest unequal place.",
      "Repair a scale with unequal-looking jumps or a point placed from digit length instead of interval value.",
    ],
    studentMoves: [
      "Label the endpoints and calculate one equal interval before placing any card.",
      "Build 0.008 in a place-value chart and place it on three differently scaled lines.",
      "Compare two decimals by aligning place values and using a benchmark or number line.",
      "Read two large numbers by periods, locate the first unequal place, and justify the comparison.",
      "Create a two-scale trap for a partner, then revise any label that allowed two interpretations.",
    ],
    supplied: ["Three-scale 0.008 number-line sheet", "Decimal place-value chart", "Millions/billions period chart", "Scale trap cards", "Guided cards and separate teacher answers", "Independent check"],
    gather: ["Board or projector", "Plain paper or printed lines", "Pencils and two colours", "Optional place-value disks"],
    vocabulary: words(
      ["place value", "the value a digit has because of its position", "The 8 in 0.008 means eight thousandths"],
      ["thousandth", "one of one thousand equal parts of a whole", "0.008 is eight thousandths"],
      ["scale", "the values represented by the marks on a line or graph", "A line may count by 0.1, 0.01, or ten million"],
      ["interval", "the equal space between two neighbouring marks", "Ten equal spaces from 0 to 0.1 are worth 0.01 each"],
      ["period", "a group of three digits in a large number", "3 | 405 | 000 | 000 has billions, millions, thousands, and ones periods"],
    ),
    model: {
      label: "SAME NUMBER · THREE SCALES",
      prompt: "Where does 0.008 belong when the right endpoint changes?",
      steps: [
        "Write 0.008 as eight thousandths in the place-value chart.",
        "On 0 to 1, it is 0.008 of the full interval, so it is very close to zero.",
        "On 0 to 0.1, it is 0.008 ÷ 0.1 = 0.08, or 8% of the way across.",
        "On 0 to 0.01, it is 0.008 ÷ 0.01 = 0.8, or 80% of the way across.",
      ],
      conclusion: "The value 0.008 never changes. Its visible position changes because the whole interval represented by the line changes.",
    },
    partnerCards: [
      { title: "TINY DECIMAL", body: "Divide 0 to 0.01 into ten equal spaces. What is each space worth, and where does 0.006 belong?", answer: "Each space is 0.001; 0.006 belongs at the sixth mark after zero." },
      { title: "CHANGE THE ENDPOINT", body: "Place 0.04 on a 0-to-1 line and a 0-to-0.1 line. Describe the change without saying the number grew.", answer: "It is 4% across the 0-to-1 line and 40% across the 0-to-0.1 line; 0.04 stays fixed." },
      { title: "COMPARE BY PLACE", body: "Compare 0.405 and 0.045. Name the first place that decides.", answer: "0.405 > 0.045; the tenths place decides because 4 tenths is greater than 0 tenths." },
      { title: "BILLION VIEW", body: "Compare 3,405,000,000 and 3,450,000,000. Name the first unequal place.", answer: "3,450,000,000 is greater; after equal billions and hundred-millions, the ten-millions digits 5 and 0 decide." },
    ],
    check: [
      { prompt: "On a 0-to-0.1 line split into ten equal spaces, what is one space worth?", answer: "0.01." },
      { prompt: "Place 0.008 on a 0-to-0.01 line and explain the position.", answer: "At the eighth of ten equal spaces, or 80% across, because each space is 0.001." },
      { prompt: "Which is greater: 807,090,000 or 870,009,000? Explain from the first unequal place.", answer: "870,009,000; the ten-millions digits are 7 and 0 after both have 8 hundred-millions." },
    ],
    readinessQuestions: [
      { prompt: "Ten equal spaces run from 0 to 0.1. What is one space?", choices: ["0.1", "0.01", "0.001"], answer: 1, feedback: "Divide the whole interval, 0.1, by ten equal spaces." },
      { prompt: "Which number is eight thousandths?", choices: ["0.8", "0.08", "0.008"], answer: 2, feedback: "The third place to the right of the decimal is thousandths." },
    ],
    likelyMisconceptions: ["Counting tick marks instead of equal spaces", "Assuming every interval is worth one", "Treating a farther-right display as a larger value when the scale changed", "Comparing decimals by digit count"],
    supportRoute: "Use only the 0-to-0.01 line first. Colour each 0.001 interval, build the decimal in a place-value chart, and say the endpoint and one-jump value aloud before placing it.",
    extensionRoute: "Design two accurate scales that make the same change look visually steep and gentle, then explain why neither changes the underlying values.",
    spaces: "Keep the scale comparison in the Math folder; no separate SpacesEDU post is required.",
  },
  {
    id: "factors-multiples-pack",
    anchorIds: ["pack-and-sync"],
    title: "Equal packs or repeating meetings?",
    shortTitle: "Factors, multiples, GCF, and LCM workshop",
    timing: "October · Weeks 7–8",
    blocks: "3 × 45–55 min",
    role: "BC CORE",
    readinessLevel: "full",
    mathUpTopics: ["Factors and Multiples", "BC_Working With Factors and Multiples"],
    prerequisite: "Build equal groups and use multiplication/division facts within 100 with a chart or manipulatives when needed.",
    learningGoal: "Choose factor reasoning for splitting fixed amounts and multiple reasoning for finding when repeating events meet.",
    whyBefore: "Pack It / Sync It asks students to select the idea from context. This workshop makes factors, multiples, greatest common factor, and least common multiple visible before the mission.",
    background: [
      "A factor divides an amount into equal whole-number groups with no leftovers. Factor pairs multiply to make the amount.",
      "A common factor divides two or more amounts exactly. The greatest common factor makes the greatest possible number of identical packs.",
      "Multiples are the results of counting by a number. Common multiples are meeting points shared by two repeating sequences.",
      "The least common multiple is the first positive meeting point. GCF and LCM can use the same numbers but answer different story questions.",
    ],
    teacherMoves: [
      "Arrange 24 red and 36 blue counters into equal packs; test possible pack counts and record the common factors.",
      "Use the greatest common factor, 12, to make 12 identical packs with 2 red and 3 blue in each.",
      "Act out signals every 4 and 6 counts on one timeline; mark 12 as the first shared meeting.",
      "Place two nearly identical stories side by side and underline the clues ‘greatest identical packs’ and ‘first meet again.’",
      "Model a divisibility or skip-counting check instead of requiring prime factorization as the only method.",
    ],
    studentMoves: [
      "Build several exact pack counts and list the numbers that divide both supplies.",
      "Choose the greatest common factor and prove what belongs in each pack.",
      "Tap, step, list, or draw two repeating sequences and circle every meeting point.",
      "Choose the least positive common multiple and connect it to the first meeting time.",
      "Sort new stories into factor, multiple, or not enough information, then justify the clue used.",
    ],
    supplied: ["24-and-36 supply mat", "Factor-pair organizer", "Two-signal timeline", "GCF-or-LCM story sort", "Guided cards with separate teacher answers", "Independent check"],
    gather: ["Two colours of counters or small objects", "Paper plates, hoops, or drawn group circles", "Timeline strips", "Pencils"],
    vocabulary: words(
      ["factor", "a whole number that divides an amount exactly", "6 is a factor of 24 because 24 ÷ 6 = 4"],
      ["multiple", "a number reached by multiplying or skip-counting", "24 is a multiple of 6"],
      ["common factor", "a factor shared by two or more numbers", "6 is a common factor of 24 and 36"],
      ["greatest common factor", "the greatest factor shared by the amounts", "GCF(24,36)=12"],
      ["least common multiple", "the first positive multiple shared by repeating sequences", "LCM(4,6)=12"],
    ),
    model: {
      label: "SAME NUMBERS · DIFFERENT QUESTION",
      prompt: "What do 24 and 36 tell us in a packing story and in a repeating-event story?",
      steps: [
        "Packing: list common factors of 24 and 36: 1, 2, 3, 4, 6, 12.",
        "Choose 12 because the story asks for the greatest number of identical packs; each gets 2 and 3.",
        "Repeating: list multiples of 24 and 36 until both lists reach 72.",
        "Choose 72 because the story asks when the two cycles first meet again.",
      ],
      conclusion: "GCF divides fixed supplies into greatest identical groups. LCM finds the first shared point in repeating sequences.",
    },
    partnerCards: [
      { title: "RESCUE PACKS", body: "Make the greatest number of identical kits from 18 blue and 30 gold badges with none left. State kits and contents.", answer: "GCF(18,30)=6, so 6 kits with 3 blue and 5 gold badges each." },
      { title: "SIGNAL MEETING", body: "One signal flashes every 9 seconds and another every 12 seconds. When do they first meet again?", answer: "LCM(9,12)=36 seconds." },
      { title: "CHOOSE THE TOOL", body: "A teacher has 28 pencils and 42 erasers for the greatest possible identical prize bags. Factor or multiple reasoning?", answer: "Factor reasoning; GCF(28,42)=14 bags, each with 2 pencils and 3 erasers." },
      { title: "REPAIR THE CLAIM", body: "A student says LCM(4,6)=24 because 24 is in both lists. What did the student miss?", answer: "24 is common but not least; 12 is the first positive common multiple." },
    ],
    check: [
      { prompt: "Find the GCF of 20 and 32 and explain what it means for identical packs.", answer: "GCF=4; four greatest identical packs, with 5 of the first item and 8 of the second." },
      { prompt: "Find the LCM of 5 and 8.", answer: "40." },
      { prompt: "Write one clue that tells you a story needs GCF rather than LCM.", answer: "It splits fixed amounts into the greatest number of identical whole groups with no leftovers." },
    ],
    readinessQuestions: [
      { prompt: "Which number is a factor of both 24 and 36?", choices: ["5", "6", "8"], answer: 1, feedback: "Both 24 and 36 divide exactly by 6." },
      { prompt: "Which list shows multiples of 4?", choices: ["1, 2, 4", "4, 8, 12", "4, 6, 8"], answer: 1, feedback: "Multiples of 4 are reached by counting 4, 8, 12, and onward." },
    ],
    likelyMisconceptions: ["Calling factors and multiples the same thing", "Choosing any common value instead of the greatest or least one requested", "Using GCF for a repeating meeting story", "Assuming prime factorization is required"],
    supportRoute: "Keep quantities within known facts. Build every candidate grouping with counters and every repeating event on one labelled strip; use a multiplication chart without turning support into a speed test.",
    extensionRoute: "Design two stories using the same pair of numbers—one requiring GCF and one requiring LCM—and peer-test whether the clues are unambiguous.",
    spaces: "Keep the packing mat and timeline in class; teacher observation is sufficient evidence.",
  },
  {
    id: "pattern-relations-pack",
    anchorIds: ["pattern-forecast"],
    title: "Show one pattern five ways",
    shortTitle: "Increasing and decreasing relations workshop",
    timing: "January · before Pattern Forest",
    blocks: "3 × 45–55 min",
    role: "BC CORE",
    readinessLevel: "full",
    mathUpTopics: ["Patterns"],
    prerequisite: "Continue a numeric or visual pattern and plot ordered pairs in the first quadrant.",
    learningGoal: "Connect an increasing or decreasing pattern across a model, table, graph, words, and an expression, then decide when the rule fits the context.",
    whyBefore: "Pattern Forest interactively develops increasing rules. This full workshop adds an equally visible decreasing route and connects both directions to tables, graphs, expressions, forecasts, and context limits.",
    background: [
      "A relation connects an input, such as stage number n, with one output value. Each table row and graph point must describe the same stage.",
      "A constant change means the same amount is added or removed each stage. Increasing and decreasing patterns can both have a constant change.",
      "For a Stage 1 value of 7 that grows by 4, 4n + 3 works because 4(1)+3=7. Testing n=1 catches many rules with the right change but wrong start.",
      "For a Stage 1 value of 42 that loses 5, 42 − 5(n−1) keeps Stage 1 at 42. A symbolic rule may continue below zero even when a physical story must stop.",
    ],
    teacherMoves: [
      "Build Stages 1–4 of 7, 11, 15, 19 with counters; colour the four new pieces and the three fixed pieces differently.",
      "Record the same stages in a table and plot (1,7), (2,11), (3,15), and (4,19) with equal axis intervals.",
      "Write the rule first in words, then as 4n+3, and test n=1 and n=10.",
      "Build the decreasing route 42, 37, 32, 27 and connect it to 42−5(n−1).",
      "Ask when the decreasing physical context must stop even though an expression can keep producing values.",
    ],
    studentMoves: [
      "Build or draw four stages and mark what changes and what stays fixed.",
      "Complete a value table and verify that every row matches the model.",
      "Plot the ordered pairs with stage on the horizontal axis and value on the vertical axis.",
      "Write the rule in words and symbols; test Stage 1 before making a far forecast.",
      "Compare one increasing and one decreasing route, including the stage where a physical interpretation no longer makes sense.",
    ],
    supplied: ["Increasing and decreasing stage cards", "Model-table-graph-expression organizer", "Pre-labelled and blank axes", "Rule-test strip", "Context-limit card", "Guided practice and teacher answers"],
    gather: ["Counters or tiles", "Grid paper", "Pencils and two colours", "Ruler"],
    vocabulary: words(
      ["relation", "a connection between an input and an output", "Stage 3 connects to 15 lights"],
      ["constant change", "the same amount added or removed each step", "The pattern changes by −5 each stage"],
      ["expression", "numbers, operations, and variables that describe a value", "4n+3"],
      ["variable", "a letter standing for a number that can change", "n stands for stage number"],
      ["coordinate", "an ordered pair locating one input and output on a graph", "(3,15) means Stage 3 has value 15"],
    ),
    model: {
      label: "GROWING + SHRINKING · SAME REPRESENTATION ROUTE",
      prompt: "How can one rule make 7, 11, 15, 19 while another makes 42, 37, 32, 27?",
      steps: [
        "Growing route: table the pairs (1,7), (2,11), (3,15), (4,19); each output rises by 4.",
        "Write 4n+3 and test Stage 1: 4(1)+3=7; Stage 10 is 43.",
        "Decreasing route: table (1,42), (2,37), (3,32), (4,27); each output falls by 5.",
        "Write 42−5(n−1); Stage 9 is 2 and Stage 10 is −3, so a story counting physical objects must stop after Stage 9.",
      ],
      conclusion: "Model, table, graph, words, and expression must agree. The expression can also reveal when a real context reaches its limit.",
    },
    partnerCards: [
      { title: "INCREASING ROUTE", body: "Stage 1 has 6 tiles and each new stage adds 3. List Stages 1–5, write a rule, and find Stage 10.", answer: "6,9,12,15,18; rule 3n+3; Stage 10=33." },
      { title: "DECREASING ROUTE", body: "Stage 1 has 50 tickets and each stage uses 6. List Stages 1–5 and write a rule using n−1.", answer: "50,44,38,32,26; rule 50−6(n−1)." },
      { title: "GRAPH CHECK", body: "A table shows (1,12), (2,9), (3,6), (4,3). Which axis holds stage, and what direction should the points move?", answer: "Stage is horizontal; the points move down from left to right with constant change −3." },
      { title: "CONTEXT LIMIT", body: "For 25−4(n−1), find the last stage with a non-negative whole number of objects.", answer: "Stage 7 gives 1; Stage 8 gives −3, so Stage 7 is the last physical stage." },
    ],
    check: [
      { prompt: "For 5, 9, 13, 17, write a rule with Stage 1 equal to 5 and find Stage 20.", answer: "4n+1; Stage 20=81." },
      { prompt: "For 36, 31, 26, 21, write a decreasing rule and find Stage 7.", answer: "36−5(n−1); Stage 7=6." },
      { prompt: "Explain one way a graph can reveal whether a table and rule disagree.", answer: "The plotted points will not follow the expected constant rise/fall or one point will not match the rule's output." },
    ],
    readinessQuestions: [
      { prompt: "The values are 8, 11, 14, 17. What is the constant change?", choices: ["+3", "+8", "−3"], answer: 0, feedback: "Each output is three more than the one before it." },
      { prompt: "Which rule gives 7 at Stage 1 and then adds 4 each stage?", choices: ["4n+3", "7n+4", "4n+7"], answer: 0, feedback: "Test n=1: 4+3=7." },
    ],
    likelyMisconceptions: ["Using the Stage 1 value as the coefficient", "Putting value on the horizontal axis without defining it", "Writing a decreasing rule that already subtracts once at Stage 1", "Treating a negative symbolic output as a possible count of physical objects"],
    supportRoute: "Use counters and a pre-labelled two-column table. Colour the fixed part and repeated change separately; plot only four points before writing the rule in words.",
    extensionRoute: "Compare two rules with the same constant change but different starting values, then design a context where the graphs meet or where one must stop.",
    spaces: "A model-table-graph-rule page may serve as selected evidence; it is not a default upload.",
  },
  {
    id: "one-step-equations-pack",
    anchorIds: ["equation-balance"],
    title: "Keep both sides true",
    shortTitle: "One-step equation workshop",
    timing: "Late January–early February",
    blocks: "2 × 45–55 min + retrieval",
    role: "BC CORE",
    readinessLevel: "full",
    mathUpTopics: ["Algebra"],
    prerequisite: "Use fact families and explain that the equals sign means both expressions have the same value.",
    learningGoal: "Model and solve one-step whole-number equations by keeping both sides equal, then substitute to check the solution.",
    whyBefore: "The Equation Balance Room is an application and feedback lab. This pack supplies the physical model, inverse-operation explanation, guided cases, and independent check needed to teach without a video.",
    background: [
      "An equals sign means the value on the left is the same as the value on the right. It does not mean ‘the answer comes next.’",
      "A variable is a symbol for an unknown value. Solving means finding the value that makes the original equation true.",
      "An inverse operation undoes an operation. Subtraction undoes addition; division undoes multiplication.",
      "Whatever change preserves equality must be applied to both sides. After solving, substitute the value into the original equation to check.",
    ],
    teacherMoves: [
      "Build x+4=11 with one covered cup and counters on a balance mat. Remove four counters from both sides.",
      "Record the physical move symbolically as x+4−4=11−4, then simplify to x=7.",
      "Model 4x=52 as four equal covered groups sharing 52 counters; divide both sides by four.",
      "Contrast x÷6=9 and 72−x=29 so students choose the inverse from the actual structure rather than a memorized switch rule.",
      "Substitute every solution into the unchanged original equation and reject any value that makes the sides unequal.",
    ],
    studentMoves: [
      "Build or draw both sides of the equation and mark the unknown.",
      "Name the operation attached to the unknown and choose an inverse move.",
      "Apply an equality-preserving move to both sides and isolate the unknown.",
      "Substitute the value into the original equation and calculate both sides.",
      "Write a one-step mystery for a partner and revise it if more than one reading is possible.",
    ],
    supplied: ["Balance mats", "Cup and counter cards", "Inverse-operation reference", "Four guided equation cards", "Error-repair cards", "Independent check with teacher answers"],
    gather: ["Counters", "Cups or folded paper covers", "Plain paper", "Optional balance scale"],
    vocabulary: words(
      ["equation", "a statement that two expressions have equal value", "x+4=11"],
      ["variable", "a letter or symbol standing for an unknown or changing number", "x is the hidden number"],
      ["inverse operation", "an operation that undoes another operation", "Subtract 4 to undo adding 4"],
      ["solution", "a value that makes the original equation true", "7 is the solution to x+4=11"],
      ["substitute", "replace a variable with a value to test it", "7+4=11 verifies x=7"],
    ),
    model: {
      label: "BUILD · UNDO BOTH SIDES · CHECK",
      prompt: "A covered cup plus 4 counters balances 11 counters. What is in the cup?",
      steps: [
        "Represent the balance as x+4=11.",
        "Remove 4 from both sides: x+4−4=11−4.",
        "Simplify to x=7.",
        "Substitute into the original equation: 7+4=11, so both sides are equal.",
      ],
      conclusion: "The solution is not a guessed answer. It is the value that survives an equality-preserving move and makes the original equation true.",
    },
    partnerCards: [
      { title: "ADDITION MYSTERY", body: "Solve x+17=45. Show the same change on both sides and substitute to check.", answer: "x=28; 28+17=45." },
      { title: "MULTIPLICATION MYSTERY", body: "Solve 4x=52 with four equal groups and check.", answer: "x=13; 4×13=52." },
      { title: "DIVISION MYSTERY", body: "Solve x÷6=9. Name the inverse move and check.", answer: "x=54; 54÷6=9." },
      { title: "SUBTRACTION TRAP", body: "Solve 72−x=29 without reversing the original subtraction. Check by substitution.", answer: "x=43; 72−43=29." },
    ],
    check: [
      { prompt: "Solve y+26=70 and check.", answer: "y=44; 44+26=70." },
      { prompt: "Solve 8m=96 and check.", answer: "m=12; 8×12=96." },
      { prompt: "A student solves p÷5=7 as p=2. Diagnose and repair the move.", answer: "The student subtracted instead of undoing division. Multiply both sides by 5: p=35; 35÷5=7." },
    ],
    readinessQuestions: [
      { prompt: "What does the equals sign mean in 8+5=10+3?", choices: ["The answer comes next", "Both sides have the same value", "Add every number"], answer: 1, feedback: "Both expressions have value 13." },
      { prompt: "Which operation undoes multiplication by 6?", choices: ["Add 6", "Subtract 6", "Divide by 6"], answer: 2, feedback: "Division by the same non-zero number undoes multiplication." },
    ],
    likelyMisconceptions: ["Reading equals as ‘write the answer’", "Changing only one side", "Using a memorized opposite operation without reading the equation", "Checking a rearranged equation instead of the original"],
    supportRoute: "Use one physical cup and counters. Keep each written line beside the matching physical move, and limit early equations to facts students can verify without extra computation load.",
    extensionRoute: "Create and diagnose a false solution line, or compare two different one-step equations that share the same solution.",
    spaces: "Keep the balance proof and substitution check in the Math folder; no default post.",
  },
  {
    id: "first-quadrant-transformations-pack",
    anchorIds: ["transformation-cipher"],
    title: "Move the shape without changing the shape",
    shortTitle: "First-quadrant transformation workshop",
    timing: "May · before Transformation Cipher",
    blocks: "2–3 × 45–55 min",
    role: "BC CORE",
    readinessLevel: "full",
    mathUpTopics: ["Location and Movement"],
    prerequisite: "Plot and read positive whole-number ordered pairs in the first quadrant, always moving across for x and then up for y.",
    learningGoal: "Apply and describe a combination of translations, reflections, and rotations in the first quadrant while preserving size and shape.",
    whyBefore: "The Cipher asks students to combine moves. This core pack explicitly teaches each move, coordinate recording, overlay checking, and sequencing before the optional negative-coordinate extension.",
    background: [
      "A translation slides every point the same distance and direction. The image keeps its size, shape, and orientation.",
      "A reflection flips an image across a named mirror line. Each point and its image stay the same perpendicular distance from that line.",
      "A rotation turns an image around a named centre by a stated angle and direction. Tracing paper makes the preserved size and turn visible.",
      "A combination applies moves in order. The output of Move 1 becomes the input for Move 2, so changing the order can change the final image.",
    ],
    teacherMoves: [
      "Plot a five-point creature in the first quadrant and rehearse x first, then y.",
      "Translate every vertex 3 right and 1 up; record each primed coordinate and verify the same move occurred.",
      "Reflect the translated image across x=6 using equal perpendicular distances; record double-prime coordinates.",
      "Demonstrate a quarter-turn with tracing paper around a marked centre, naming clockwise or counterclockwise.",
      "Compare two move orders and use an overlay or side-length check to distinguish a valid transformation from distortion.",
    ],
    studentMoves: [
      "Plot and connect the starting coordinates in the first quadrant.",
      "Apply one translation to every point and label the image with prime marks.",
      "Apply a reflection or rotation to the new image and label double-prime points.",
      "Use tracing paper, equal distances, or matching side lengths to verify size and shape stayed fixed.",
      "Write a two-move cipher, trade it, and revise any instruction a partner could not reproduce.",
    ],
    supplied: ["First-quadrant grids", "Starting creature card", "Translation/reflection/rotation reference", "Tracing-overlay directions", "Two-move cipher record", "Guided cards and teacher answers"],
    gather: ["Grid paper", "Tracing paper or transparent sleeve", "Pencils", "Ruler", "Optional coordinate pegboard"],
    vocabulary: words(
      ["translation", "a slide that moves every point the same distance and direction", "Move every point 3 right and 1 up"],
      ["reflection", "a flip across a named mirror line", "Reflect across x=6"],
      ["rotation", "a turn around a named centre", "Turn 90° counterclockwise around (4,4)"],
      ["image", "the new figure after a transformation", "A′B′C′ is the image after Move 1"],
      ["combination", "two or more transformations applied in a stated order", "Translate, then reflect"],
    ),
    model: {
      label: "MOVE 1 → MOVE 2 · RECORD EVERY POINT",
      prompt: "What happens to A(2,2), B(5,2), C(5,4), D(3,6), E(2,4) after a translation and reflection?",
      steps: [
        "Translate 3 right and 1 up: A′(5,3), B′(8,3), C′(8,5), D′(6,7), E′(5,5).",
        "Draw the vertical mirror line x=6.",
        "Reflect each primed point across x=6: A″(7,3), B″(4,3), C″(4,5), D″(6,7), E″(7,5).",
        "Overlay or compare side lengths to verify the final image has the same size and shape as the start.",
      ],
      conclusion: "Every point follows both moves in order. Coordinate labels and an overlay make the combination reproducible and prove the figure was not distorted.",
    },
    partnerCards: [
      { title: "TRANSLATE", body: "Move P(2,3), Q(4,3), R(3,5) two right and three up.", answer: "P′(4,6), Q′(6,6), R′(5,8)." },
      { title: "REFLECT", body: "Reflect A(3,2) across the vertical line x=5. Keep the same y-coordinate.", answer: "A′(7,2), two units on the other side of x=5." },
      { title: "QUARTER-TURN", body: "Rotate P(5,4) and Q(4,6) 90° counterclockwise around (4,4).", answer: "P′(4,5) and Q′(2,4)." },
      { title: "ORDER TEST", body: "Explain why ‘reflect, then translate’ may not land in the same place as ‘translate, then reflect.’", answer: "Move 2 acts on the result of Move 1; changing the intermediate image can change every final coordinate." },
    ],
    check: [
      { prompt: "Translate (1,4) four right and two up.", answer: "(5,6)." },
      { prompt: "A point is 3 units left of x=7 at (4,5). Where is its reflection across x=7?", answer: "(10,5), three units right of the mirror line." },
      { prompt: "Name two pieces of evidence that a transformation preserved the figure.", answer: "Examples: an overlay matches; corresponding side lengths and angles remain equal; every point followed the same defined move." },
    ],
    readinessQuestions: [
      { prompt: "How do you plot (3,5) in the first quadrant?", choices: ["3 right, then 5 up", "5 right, then 3 up", "3 left, then 5 down"], answer: 0, feedback: "Read x first, then y." },
      { prompt: "Which move is a reflection?", choices: ["Slide 4 right", "Flip across x=6", "Turn 90° around a point"], answer: 1, feedback: "A reflection flips across a named mirror line." },
    ],
    likelyMisconceptions: ["Moving only one vertex", "Swapping x and y without a defined rule", "Measuring reflection distance diagonally instead of perpendicular to the mirror line", "Applying both moves to the original instead of using the first image"],
    supportRoute: "Use a three-point figure, colour-coded x-then-y arrows, and tracing paper. Complete one move and check every point before beginning the second.",
    extensionRoute: "Compare two move orders or open the separately labelled negative-coordinate bridge only after the first-quadrant combination is independently secure.",
    spaces: "Keep the decoded cipher in class; assess the first-quadrant combination before any optional four-quadrant work.",
  },
];
