export type NewsroomRoutineId = "watch" | "notice" | "question" | "discuss" | "investigate" | "imagine";

export const newsroomProgram = {
  id: "grade-6-newsroom",
  contentVersion: "source-lab-newsroom-2026-08-20-v3",
  shared: {
    eyebrow: "SOURCE LAB & NEWSROOM · CURRENT + HISTORICAL",
    title: "Source Lab & Newsroom",
    bigQuestion: "What does this source show—and what would we need to check before believing more?",
    summary: "Begin with one real photograph, map, graph, quotation, headline, short text, or video. Students examine it together before they receive an explanation, make a claim, or decide what to investigate next.",
    cadence: "Use a Quick Look for an 8–12 minute source conversation or a Deep Dive when the source deserves comparison, research, or a longer response.",
    sourcePromise: "Every source is visible, named, dated when possible, and linked to its publisher or archive. Current sources receive a review date; historical sources keep their archive credit and context.",
    routes: [
      { id: "quick-look", label: "QUICK LOOK", minutes: "8–12 min", path: "Look → Notice → Claim → Next", use: "One source, one careful claim, one uncertainty. End with discussion or save one question." },
      { id: "deep-dive", label: "DEEP DIVE", minutes: "25–45 min", path: "Look → Notice → Claim → Compare → Check → Next", use: "Open the source record, compare another source or perspective, and create a response only when the question earns more time." },
    ],
    routine: [
      { id: "watch", label: "LOOK", title: "Meet the source", prompt: "Study it quietly once. What is literally here before anyone explains it?" },
      { id: "notice", label: "NOTICE", title: "Collect clues", prompt: "Point to exact words, dates, numbers, labels, objects, sounds, or visible details." },
      { id: "question", label: "CLAIM", title: "Make a careful first idea", prompt: "What might the source show or suggest? What question or uncertainty must stay attached?" },
      { id: "discuss", label: "COMPARE", title: "Test the idea with other people", prompt: "In a pair or team, compare interpretations. Which clues support each idea, and where are we relying on assumptions?" },
      { id: "investigate", label: "CHECK", title: "Open the source record", prompt: "Who made it, when, for what purpose, and what changes after reading its caption, context, data notes, or another source?" },
      { id: "imagine", label: "NEXT", title: "Choose how this source ends", prompt: "Revise the claim, stop after a useful discussion, save a strong question, or continue into research, writing, data, art, design, or action." },
    ] satisfies readonly { id: NewsroomRoutineId; label: string; title: string; prompt: string }[],
    endings: [
      { id: "discuss-only", label: "DISCUSS & STOP", title: "A useful conversation can be enough", detail: "Name one careful conclusion and one uncertainty. Nothing needs to be posted." },
      { id: "save-seed", label: "SAVE A SEED", title: "Carry one question forward", detail: "Write a promising question in an inquiry notebook, team passport, or the class question wall." },
      { id: "teacher-follow-up", label: "FOLLOW IT", title: "Continue when the question earns more time", detail: "The teacher may choose a source set, field observation, interview, data task, story, model, or design challenge." },
    ],
  },
  student: {
    title: "Start with the source—not the answer.",
    summary: "Your job is to collect clues, make a possible claim, hear another interpretation, and revise when the caption, context, or another source changes the evidence.",
    firstMove: "Look quietly. Point to one exact detail and say, “I notice ___.” Do not explain it yet.",
    inquiryRoutes: [
      { title: "Talk it through", detail: "The class makes sense of the story and stops. Good thinking does not need to become an assignment." },
      { title: "Keep the question", detail: "Write one inquiry seed you genuinely want to revisit. Include why it matters and what kind of evidence could help." },
      { title: "Build, teach, or act", detail: "When a question connects to our Big Ideas, the class may investigate, make something, teach an audience, or propose a careful solution." },
    ],
    finish: "I can say what the source supports, what remains uncertain, and the next question I would ask.",
    absentOrStuck: "Ask a partner for the source, the class question, and one detail they can point to. Add your own question before asking for the class conclusion.",
    spacesNote: "Most Source Lab work stays in discussion, notebooks, and class work. Only selected evidence or reflection belongs in SpacesEDU.",
  },
  family: {
    title: "What families should know about Source Lab & Newsroom",
    summary: "Students regularly examine a real current or historical source and practise separating observation, inference, evidence, context, and uncertainty. Some sources lead only to a short conversation; others connect to a larger inquiry or project.",
    quickReference: [
      { label: "What students do", detail: "Study one visible, teacher-reviewed source, identify exact clues, compare interpretations, open its context, and decide whether a question deserves more investigation." },
      { label: "How collaboration works", detail: "Pairs or small groups are common because explaining, questioning, and revising with other people strengthens the thinking. Individual reflection is used when each student's own learning matters." },
      { label: "Visual clue challenges", detail: "The teacher leads one whole-class visual challenge while teams record three precise details, a place or time range, one uncertainty, and a revision after the reveal. Students do not need an account and do not post a public response." },
      { label: "How it is assessed", detail: "The teacher looks for careful use of evidence, useful questions, listening, revision, and honest uncertainty. A student's political opinion is not graded." },
      { label: "What comes home", detail: "You may see a discussion question, inquiry seed, or selected learning artifact. Most stories remain short classroom conversations and do not become portfolio posts." },
    ],
    conversationPrompts: [
      "What detail changed or complicated your first idea?",
      "Whose experience or perspective was missing from the source?",
      "What would you need to check before sharing that claim?",
    ],
    spacesNote: "SpacesEDU remains the secure home for selected evidence and reflection; the public site does not collect student responses.",
  },
  teacher: {
    groupingDefault: "Begin in pairs or table teams when comparison, questioning, or perspective-taking improves the thinking. Use individual work when the evidence must show each student's own interpretation or reflection.",
    selectionRule: "Choose one source-rich current or historical source with a real connection to the curriculum, students' place, or a question worth discussing. Prefer depth over a headline roundup.",
    publicationRule: "Only a deliberately promoted, recently checked feature is shared to the public Student/Family site. Class responses, votes, drafts, and private inquiry questions never leave the Teacher Hub.",
    offlineFallback: "Project or print the checked source card, read a short attributed excerpt aloud, and run the same moves through talk, the board, and paper.",
    sourceDoors: [
      { label: "CBC Kids News", url: "https://www.cbc.ca/kidsnews/", use: "Preview one possible Canadian or world story; choose a single image, text, graph, or clip for the class." },
      { label: "Surrey Archives photographs", url: "https://www.surrey.ca/arts-culture/surrey-archives/archives-collection/photographs", use: "Choose a credited local historical photograph and keep its archive record attached." },
      { label: "Surrey then-and-now tools", url: "https://www.surrey.ca/arts-culture/heritage/online-heritage-tools", use: "Use a historic image, time-lapse, or 1949/1966 map to compare place across time." },
      { label: "Surrey Schools", url: "https://www.surreyschools.ca/", use: "Check school and district information at its official source before presenting it as current." },
      { label: "Statistics Canada", url: "https://www.statcan.gc.ca/en/start", use: "Use dated official data when a story needs scale, trend, or comparison." },
    ],
    clueGamePreflight: [
      "Preview the exact round before class, including the first image, controls, reveal, and next-screen behaviour.",
      "Use one teacher-controlled screen only. Students do not create accounts, enter personal names or join codes, or open Community rounds.",
      "If an ad, login wall, unsafe round, or district filter interrupts the route, stop immediately and use the local Surrey Archives fallback.",
    ],
    clueGames: [
      {
        id: "geoguessr",
        title: "GeoGuessr · Where clues",
        projectorTitle: "Where in the world?",
        url: "https://www.geoguessr.com/free",
        minutes: "10–15 min",
        setup: "Preview one exact free round, open it only on the teacher computer, and control every click and reveal.",
        teamTask: "Study the teacher-selected scene. Record three precise visual clues, a location range, one alternative, and how confident your team is.",
        clues: ["Signs or language", "Land, weather, and plants", "Roads, buildings, and transportation"],
        roles: "Teams of 3–4: Detail Hunter · Mapper · Skeptic · Reporter",
        reveal: "After the reveal: Which clue was strongest? Which inference was only possible? What did the image not tell us about people who live there?",
      },
      {
        id: "timeguessr",
        title: "TimeGuessr · Where + when clues",
        projectorTitle: "Where and when?",
        url: "https://timeguessr.com/game-settings",
        minutes: "12–18 min",
        setup: "Preview one exact round from Game Settings, use no timer at first, avoid Community, and control every click and reveal from the teacher computer.",
        teamTask: "Study the teacher-selected photograph. Record three precise visual clues, a place and decade range, one alternative, and one uncertainty.",
        clues: ["Transportation and technology", "Clothing, signs, and objects", "Buildings, materials, and photo quality"],
        roles: "Teams of 3–4: Detail Hunter · Time Detective · Skeptic · Reporter",
        reveal: "After the reveal: Which clue narrowed the decade? Which clue tempted a stereotype? What context would an archive caption add?",
      },
    ],
    localClueFallback: {
      title: "Surrey Archives fallback · Fleetwood Elementary",
      projectorTitle: "Mystery Surrey school",
      url: "https://www.surrey.ca/news-events/news/take-groovy-look-surrey-70s",
      credit: "Surrey Archives · City of Surrey Collection · SACR2002.001.231",
      setup: "Open the official City of Surrey page and project its fourth archival image. Cover the caption until teams have recorded three clues and a decade range.",
      teamTask: "Study the archival school photograph. Record three precise visual clues, a decade range, one alternative, and one detail you still cannot explain.",
      clues: ["Transportation and street features", "Building materials and school design", "Clothing, objects, and image quality"],
      roles: "Teams of 3–4: Detail Hunter · Time Detective · Skeptic · Reporter",
      reveal: "Reveal the official credit and the article's 1970s context. Do not present the article context as an exact photograph date. Ask: What changed around Surrey schools, and what evidence would we need before claiming why?",
    },
  },
} as const;
