"use client";

import "./opening-week.css";

export function OpeningWeekCockpit({ onNavigate }: { onNavigate: (page: string) => void }) {
  return <section className="opening-week" aria-labelledby="opening-week-title">
    <header><p>START HERE · OPENING WEEK</p><h1 id="opening-week-title">Open. Project. Teach.</h1><span>One teacher computer and projector. Students use paper, pencils and conversation.</span></header>
    <div className="opening-week-routes">
      <article><div><small>1 · WELCOME · 5–10 MIN</small><h2>Settle in and notice.</h2><p>Project the simple welcome. Students choose a place, take out a pencil and notice something in the room. Invite one observation; passing is fine. Nothing to collect.</p></div><nav aria-label="Welcome actions"><a href="?view=Opening+Welcome&mode=student">Project simple welcome</a><button onClick={() => onNavigate("Morning Screen")}>Prepare the daily screen</button></nav></article>
      <article><div><small>2 · ROTATIONS · 45 / 60 / 75 MIN</small><h2>One Discovery page today.</h2><p>Choose one organizer after you know the group and time. Give each student that page and a pencil. They write, draw or skip private questions, then decorate to show their ideas.</p></div><nav aria-label="Discovery actions"><button onClick={() => onNavigate("First Week Mission")}>Choose page and lesson</button><a href="?view=First+Week+Mission&mode=student">Project Discovery directions</a><a href="/printables/Grade_6_Discovery_Booklet.pdf" target="_blank" rel="noreferrer">Open Discovery booklet · 5 pages</a></nav></article>
      <article><div><small>3 · AFTER CLASSES FORM · 45–55 MIN BLOCKS</small><h2>Begin with 0.008.</h2><p>Show how endpoints and equal jumps locate a number. Students predict, compare scales, practise with a partner and explain on paper. Keep maths work in class; no post.</p></div><nav aria-label="Opening maths actions"><a href="?subject=Mathematics&experience=magnitude-gallery&mode=teacher">Open first maths lesson</a><a href="?subject=Mathematics&experience=magnitude-gallery&mode=student">Project first maths lesson</a><a href="/printables/magnitude-number-lines-and-periods.pdf" target="_blank" rel="noreferrer">Open maths sheet · 2 pages</a></nav></article>
    </div>
    <div className="opening-week-notes">
      <details><summary>Hand-in, extra time and colouring</summary><p><b>Hand in:</b> Leave the front name line blank. Name, date and group go on the back. Add PAUSED for a check-in; collect face-down in the group folder. Originals stay private with teachers. Do not post them to SpacesEDU.</p><p><b>Extra 5–15 minutes:</b> Colour or shade today's Discovery organizer, add a pattern or clarify one safe idea. Blank/private parts stay blank; no need to finish all five pages. The illustrated booklet is the available colouring option. The separate colouring pack is not yet released.</p><p><b>Plain-paper backup · 15–20 minutes:</b> Draw an ordinary classroom object and label five details. Imagine one change that would help someone use it. Draw and explain the change to a partner. Collect the labelled design or keep it in the student's folder.</p></details>
      <details><summary>First maths blocks and next options</summary><ol><li><b>Block 1:</b> Teach 0.008 on 0–0.01, then wider scales. Use the first five worked steps and the blank lines. Finish with an interval explanation.</li><li><b>Block 2:</b> Model the distinct billions comparison. Try partner cards, then the independent check. Keep answers with the teacher.</li><li><b>Block 3:</b> Use Scale City: predict, reveal, keep the number fixed and change the scale. Pairs explain one changed position on paper.</li><li><b>Block 4:</b> Create and repair a two-scale comparison. Finish with labelled endpoints, equal jumps and a sentence explaining why the value did not change.</li></ol><p>Use later blocks for targeted practice or reteaching based on the check. Rotations may continue; these are teaching blocks, not fixed dates.</p><p><a href="?subject=Mathematics&experience=strategy-league&mode=teacher">Next: multiplication and division strategies</a> · <a href="?subject=Mathematics&experience=pack-and-sync&mode=teacher">Later: factors and multiples</a></p></details>
      <details><summary>If technology fails</summary><p>Open or print the booklet and maths PDF before class. Read the chosen directions aloud; use the board for a model and paper for responses. The plain-paper design task above needs no downloads. No core activity requires a student account, video, AI or Wi-Fi.</p><button onClick={() => onNavigate("TTOC Day Plan")}>Open the printable day-plan builder</button></details>
    </div>
    <footer><a href="https://dlwyatt-eng.github.io/learn/" target="_blank" rel="noreferrer">Student &amp; Family Hub ↗</a><a href="https://dlwyatt-eng.github.io/equity-hub/" target="_blank" rel="noreferrer">Standalone Equity Hub ↗</a><span>Current teaching release: GitHub Pages. Older ChatGPT Site copies are not this release.</span></footer>
  </section>;
}

export function OpeningWelcome() {
  return <section className="opening-welcome" aria-labelledby="opening-welcome-title"><p>WELCOME TO GRADE 6</p><h1 id="opening-welcome-title">Come in. Get comfortable.</h1><ol><li>Choose an available seat.</li><li>Have a pencil ready. We will give you a page.</li><li>Notice one interesting detail in the room.</li></ol><aside>When we share, you may speak, point or pass. You never have to tell a private story.</aside><p>Today: a welcome, one Discovery page and time to make it your own.</p></section>;
}
