import type { ProficiencyModelSet } from "./proficiency-models";

/** Career models value observable evidence and privacy-safe next steps. */
export const careerProficiencyModelSets = [
  {
    id: "career-learning-story",
    title: "Strength in Action + Next Step",
    subtitle: "Use a class action, its effect, and one small plan for growth",
    activityIds: ["learning-user-manual", "strengths-action-quest"],
    spacesEvidenceIds: ["spaces-sept-learning-story"],
    sourceCapsule: { label: "Fictional practice evidence · paper bridge", text: "During a paper-bridge challenge, Kai noticed the bridge leaning, asked the group to compare two base shapes, and helped test both. The second base held six more blocks." },
    prompt: "What action shows a strength? Explain what happened, name a helpful condition or next role, and plan one small step you can check.",
    criteria: ["Exact class moment", "Observable action", "Effect or result", "Support and responsibility", "Small checkable next step"],
    copyGuard: "Kai and the bridge are fictional. Students may use a different class example or the fictional route. Never assess private disclosure, labels, confidence, or length.",
    teacherUse: ["Compare action words before response length.", "Ask what a person could see or hear when a response uses only praise.", "Accept writing, audio, drawing, scribing, or a private conference."],
    models: [
      { level: "Emerging", growthLabel: "A strength and hope are named", sample: "I am good at teamwork. My goal is to help more.", whatWorks: ["Names a possible strength", "Shows interest in contributing"], nextImprovement: "Add one class moment, the action you took, and what happened because of it.", teacherUseNote: "Keep the idea and prompt for one observable moment." },
      { level: "Developing", growthLabel: "One action makes the strength visible", sample: "When our bridge leaned, I asked the group to test a wider base. This shows problem solving. Next time I will share another idea.", whatWorks: ["Names an exact moment", "Connects an action to a strength", "Includes a next intention"], nextImprovement: "Explain the effect and make the next step easy to notice or check.", teacherUseNote: "Ask what changed for the bridge or group and when the next step will happen." },
      { level: "Proficient", growthLabel: "Evidence leads to a checkable plan", sample: "When the bridge leaned, I asked the group to compare two bases and helped test both. The wider base held six more blocks, so the action shows testing and including ideas. In the next team task, I will try the checker role and record one test result.", whatWorks: ["Links action to a result", "Names a practical support or role", "Sets a specific next action"], nextImprovement: "After the next task, compare what happened and revise the plan if it did not help.", teacherUseNote: "This meets the target without more personal information or length." },
      { level: "Extending", growthLabel: "The learner tests and revises the idea", sample: "The bridge example shows I used testing and inclusion in that task; it does not prove I use them in every group. I will try the checker role in science, record results, and review the plan after two work periods.", whatWorks: ["Keeps the strength claim in context", "Plans evidence that could challenge the idea", "Includes a review point"], nextImprovement: "Compare the action in a different task and explain what transfers.", teacherUseNote: "Extending means testing a plan, not advanced words or more disclosure." },
    ],
  },
  {
    id: "digital-trust-decision",
    title: "Digital Profile Evidence + Repair",
    subtitle: "Separate what is visible from what is guessed, then choose a repair",
    activityIds: ["digital-identity-forensics"],
    spacesEvidenceIds: [],
    sourceCapsule: { label: "Fictional profile · Riley Creates", text: "The public profile shows a strong model with no image credit, a photo with a school sign, an old unkind joke, a kind reply, and an event post with a time and place." },
    prompt: "What does the profile show, what might an audience infer, and which repair best protects privacy, credit, safety, or trust?",
    criteria: ["Visible evidence", "Inference kept separate", "Audience and consequence", "Justified repair", "Limit or uncertainty"],
    copyGuard: "This person and profile are fictional. Never ask students to search, show, or explain a real account, username, image, location, or private experience.",
    teacherUse: ["Colour-code evidence, inference, audience, consequence, and repair.", "Do not teach that one post proves character or deletion removes every copy.", "Assess decision reasoning, not social-media use."],
    models: [
      { level: "Emerging", growthLabel: "A concern is noticed", sample: "The profile is unsafe, so Riley should delete everything.", whatWorks: ["Notices a possible risk", "Suggests an action"], nextImprovement: "Point to one visible clue, name who could see it, and choose a repair for that concern.", teacherUseNote: "Ask which post concerns the student before discussing the repair." },
      { level: "Developing", growthLabel: "Evidence supports one repair", sample: "The photo shows a school sign, so a stranger might guess where Riley goes. Riley should crop the sign or limit the audience.", whatWorks: ["Uses one visible clue", "Keeps inference uncertain", "Suggests a relevant repair"], nextImprovement: "Explain what the repair protects, what it cannot undo, and consider another audience.", teacherUseNote: "Highlight ‘might,’ then ask what remains uncertain." },
      { level: "Proficient", growthLabel: "Audience, consequence, and repair connect", sample: "The photo includes a school sign and the event post gives a time and place. A stranger could combine those clues, although the profile does not prove Riley will be there. Riley should crop the sign, remove public event details, add image credit, and rewrite the old joke. These repairs reduce risk but cannot guarantee that no copy exists.", whatWorks: ["Connects clues without overclaiming", "Chooses repairs for privacy, credit, and tone", "Names a repair limit"], nextImprovement: "Turn the reasoning into three short decision rules and test them on a new post.", teacherUseNote: "This meets the target without a personal example." },
      { level: "Extending", growthLabel: "The rules transfer to a new case", sample: "My rules are: check what clues combine, who needs access, and permission and credit before posting. For a team photo, I would remove location clues, ask everyone shown, credit borrowed work, and use the smallest useful audience. The goal is not zero sharing; it is a choice affected people can understand and change.", whatWorks: ["Transfers the lesson into rules", "Balances benefits and risks", "Includes consent, credit, and audience control"], nextImprovement: "Consider what someone can do when another person or platform refuses a repair.", teacherUseNote: "The extension is balanced transfer and accountability, not a longer danger list." },
    ],
  },
  {
    id: "team-leadership-project-plan",
    title: "Team Leadership + Project Rescue",
    subtitle: "Show how one action helped work, fairness, safety, or trust",
    activityIds: ["leadership-relay", "project-rescue-studio"],
    spacesEvidenceIds: ["spaces-feb-inquiry"],
    sourceCapsule: { label: "Fictional practice plan · pollinator display", text: "A Friday plan says only ‘research, build, present.’ One person has seven of ten jobs, painting begins before measuring, materials are unchecked, and there is no safety review or midpoint test." },
    prompt: "Which team action or plan change helped? Name the original problem, action, effect, and one check, repair, or next move.",
    criteria: ["Specific problem", "Observable action", "Effect on work or people", "Fairness, safety, or checkpoint", "Repair and next move"],
    copyGuard: "The team is fictional. Assess planning and leadership evidence, not popularity, speed, confidence, personality, or identical roles.",
    teacherUse: ["Point to before-and-after plan evidence.", "Value quiet checking, organizing, connecting, repairing, and including.", "Assess the shared artifact and individual evidence separately."],
    models: [
      { level: "Emerging", growthLabel: "A role or change is named", sample: "I was the leader and told everyone what to do. We made a better plan.", whatWorks: ["Names team participation", "Recognizes that the plan needed change"], nextImprovement: "Name the exact problem, action, and effect on the work or group.", teacherUseNote: "Move from title to action: what could someone see or hear?" },
      { level: "Developing", growthLabel: "One action responds to a problem", sample: "The jobs were unfair, so I moved three cards from one person and asked which jobs people could do. Everyone had a job after that.", whatWorks: ["Identifies a workload problem", "Describes an action", "Names an effect"], nextImprovement: "Explain why the plan is fair and add a check for order, materials, safety, or progress.", teacherUseNote: "Fair need not mean identical; ask how work matches needs and access." },
      { level: "Proficient", growthLabel: "Action, effect, and checkpoint align", sample: "Our plan started painting before pieces were measured. I put measuring and cutting first, then the group shared roles by task and access needs. We added a Wednesday fit-check, materials check, and safe-tool check. The new order prevented repainting and exposed a missing label early.", whatWorks: ["Explains a task-order change", "Includes fair roles and checks", "Links action to team effect"], nextImprovement: "Test the plan against one realistic surprise and decide what must stay fixed.", teacherUseNote: "A labelled task board plus a short conference can show the same proficiency." },
      { level: "Extending", growthLabel: "The team tests a trade-off and adapts", sample: "Rain closed the outdoor area, so we kept the goal but moved to a smaller indoor display. We chose three strong examples instead of rushing six, then tested access and source labels. We made fewer pieces, but visitors could use and understand them without coaching.", whatWorks: ["Keeps the goal while changing the route", "Explains a fair trade-off", "Tests different leadership actions"], nextImprovement: "Set one success check and explain how the team will respond if evidence conflicts.", teacherUseNote: "Extending is adaptive judgment, not more tasks or control." },
    ],
  },
  {
    id: "career-network-next-step",
    title: "Career Network + Next Experience",
    subtitle: "Trace connected roles and choose one small way to learn more",
    activityIds: ["career-constellation"],
    spacesEvidenceIds: ["spaces-june-final"],
    sourceCapsule: { label: "Fictional project · garden open house", text: "The event depends on gardeners, a custodian, access tester, interpreter, water technician, student guides, designer, volunteer coordinator, care helpers, and waste collection." },
    prompt: "How do roles, skills, tools, service, and pathways connect? Name one assumption the evidence changed and one low-risk experience to try next.",
    criteria: ["Varied connected roles", "Labelled links", "More than one pathway", "Assumption revised", "Realistic next experience"],
    copyGuard: "The project and profiles are fictional. Do not assess career certainty, salary goals, prestige, family access, ambition, or personal disclosure.",
    teacherUse: ["Look for labelled connections, not the longest job list.", "Value paid, unpaid, care, volunteer, creative, technical, and community contributions.", "Students may plan for a fictional learner."],
    models: [
      { level: "Emerging", growthLabel: "Some roles are visible", sample: "A garden needs a gardener, teacher, and students. I might want to work with plants.", whatWorks: ["Names several roles", "Makes a starting connection"], nextImprovement: "Add what each role contributes, one hidden role, and one link.", teacherUseNote: "Keep interest optional; ask who helps before, during, and after." },
      { level: "Developing", growthLabel: "Roles begin to form a network", sample: "The gardener grows plants, the water technician keeps the system working, and student guides explain it. They use observation and communication. A volunteer could learn by helping at one event.", whatWorks: ["Explains contributions", "Finds a shared skill", "Names one pathway"], nextImprovement: "Add care, access, maintenance, or language work and show a dependency.", teacherUseNote: "Label arrows with verbs such as supplies, checks, explains, or repairs." },
      { level: "Proficient", growthLabel: "Connections and pathways are clear", sample: "The open house is a network. The gardener depends on the water technician; guides use the gardener's information; the interpreter and access tester help more visitors. People enter through community knowledge, volunteering, school, mentorship, or training. I had assumed the gardener did most work, but maintenance, access, communication, and care are essential too.", whatWorks: ["Shows visible and hidden work", "Includes several pathways", "Revises an assumption"], nextImprovement: "Add one way technology or community change could reshape several roles.", teacherUseNote: "The evidence may be a labelled map rather than a paragraph." },
      { level: "Extending", growthLabel: "The network changes under a new condition", sample: "If the garden adds automatic watering, the technician's work shifts toward sensors, data, and repair. Gardeners still use plant knowledge, and access testers check the controls. The change may save time but costs money and adds dependence on equipment. I would map one real school system and ask two workers how their roles connect.", whatWorks: ["Explains how one change affects roles", "Names a benefit, cost, and dependency", "Plans a low-risk investigation"], nextImprovement: "Compare how the change may affect workers or communities differently.", teacherUseNote: "Extending is systems thinking, not predicting a career." },
    ],
  },
] as const satisfies readonly ProficiencyModelSet[];
