import type { ExperienceKit, ExperienceMedia, ProgramArc, ProgramExperience, StudentStep, WordHelp } from "./program-types";
import { bloxelsStoryGame } from "./cross-curricular-program";
import { spacesPolicyForActivity } from "./classroom-program";

const stepTitles = ["Look", "Choose", "Try it", "Show why", "Make it better", "Share it"];

// This is a final cleanup for internal/admin phrases only. Academic words such
// as inference, variable, criteria, prototype, and representation stay intact
// and are taught in context through word help. Student copy must be authored,
// not generated by swapping isolated words.
const plainLanguageReplacements: [RegExp, string][] = [
  [/\bcold[- ]test\b/gi, "ask classmates who have not seen it to try it"],
  [/\bcurated\b/gi, "teacher-chosen"],
  [/\bannotated\b/gi, "clearly labelled"],
  [/\baudit\b/gi, "check carefully"],
  [/\bfirst[- ]pass experiences\b/gi, "class activities"],
  [/\bfirst[- ]pass experience\b/gi, "class activity"],
  [/\bregistered portfolio (?:post|evidence)s?\b/gi, "work your teacher asks you to save"],
  [/\bmedia capture\b/gi, "an optional teacher-managed class photo, audio clip, or video"],
];

const exactStudentSteps: Record<string, string[]> = {
  "learning-user-manual": [
    "Think of one recent class moment that went well enough to study.",
    "Circle one helpful action you took in that moment.",
    "Match that action to one strength card.",
    "Choose one learning condition that helps you use that strength.",
    "Pick one responsibility you can take when the work feels hard.",
    "Write one small goal with a first step, check date, and help source.",
  ],
  "ordinary-object-story": [
    "Choose one object in the picture. Write or say five details you can truly see.",
    "Invent a beginning, a surprising turn, and an ending. You may keep the story completely made up.",
    "Tell your story in 60–90 seconds while your partner listens for the three parts.",
    "Use your partner's question to make one part clearer, then tell or write it again.",
  ],
  "edit-room": [
    "Study the full scene before looking at any crop or caption. List facts you can actually see.",
    "Compare two versions. Point out what was cropped, reordered, captioned, or emphasized.",
    "Make a fair four-frame version for a chosen audience. Keep the important context.",
    "Name two editing choices and one detail you refused to hide.",
  ],
  "place-soundwalk": [
    "Move to the listening spot your teacher chose.",
    "Listen quietly for twenty seconds.",
    "Write one exact sound word for each sound you notice.",
    "Mark each sound as near, middle, or far.",
    "Sort each note as an observation or a guess.",
    "Revise one line so a reader can hear the place more clearly.",
  ],
  "bloxels-story-blueprint": bloxelsStoryGame.elaMoves,
  "bloxels-game-studio": bloxelsStoryGame.adstMoves,
  "packet-rescue": [
    "Study the network diagram. Point to the student device, two routers, the server, two possible routes, and the six numbered packets.",
    "At a table, send the six-piece cat picture from the server to the device. Put the pieces in order and check that 1 through 6 arrived.",
    "Take a role in the human network. Run one slow practice round with both routes open while an observer checks each job.",
    "Close one route and run the message again. Routers must choose the open route without changing or rebuilding the packets.",
    "Remove packet 4. The receiving device identifies the missing number, requests packet 4 again, and reassembles the picture.",
    "Draw the simplified system and explain the request, server, packets, routers, routes, check, and repair. Name one way the model is simpler than a real network.",
  ],
  "magnitude-gallery": [
    "Place each number near a useful benchmark before you calculate anything.",
    "Zoom between the four number lines. Say what each scale can and cannot show.",
    "Put six numbers in order and defend the two placements most likely to fool someone.",
    "Create one exact visual comparison that makes a surprising size difference clear.",
  ],
  "zoo-design-studio": [
    "Finish the polygon, perimeter/formula, and area workshops your teacher opens. Keep the check beside your design page.",
    "Read the fictional Zoo brief. Choose six habitat cards and sketch more than one possible arrangement before committing to a grid plan.",
    "Draw the exact plan. Mark dimensions, perpendicular heights, the 2 m accessible path, entry, quiet area, and every required connection.",
    "Show the perimeter and area calculation named on each habitat card. Label centimetres on the paper model and metres in the fictional zoo.",
    "Trade plans. Check one calculation, one shape rule, and one design limit. Return the plan with one specific question or correction.",
    "Revise one part because of the check. Be ready to show the original, evidence, and changed design.",
  ],
  "graph-story-lab": [
    "Act out how one amount changes over time, then describe the pattern you made.",
    "Compare the two graphs. They use the same data, so explain why they feel different.",
    "Create a line graph with a title, labelled axes, equal intervals, and an honest scale.",
    "Write one claim the graph supports and one question the graph cannot answer.",
  ],
  "four-arts-languages": [
    "Complete the visual-art study: notice one move in the named work, then use line, shape, colour or value, texture, space, contrast, and emphasis to guide attention in your own full thumbnail.",
    "Complete the music study: listen for beat, rhythm, silence, pitch, timbre, dynamics, texture, and form, then draw and perform a repeatable 20-second graphic score.",
    "Complete the drama study: plan a before and after tableau using focus, level, distance, gesture, character, place, and tension.",
    "Complete the dance study: make and notate an eight-count phrase using body, space, time, dynamics, relationship, repetition, and contrast.",
    "Combine two completed studies into a 45–60 second work or small display. Ask what the audience noticed first, revise one artistic choice, and explain why.",
  ],
  "map-what-maps-miss": [
    "Record the artist, work title, date, place or Nation when the exact source names it, material when stated, context, one observed move, and one question; write ‘not stated’ instead of guessing.",
    "Complete the technique study: try line, shape, texture, value, colour, balance, variety, unity, emphasis, and negative space; distinguish a source-supported symbol from a viewer's possible interpretation.",
    "Gather direct place observations or use the supplied evidence pack. Keep source evidence, direct observation, artistic interpretation, and unknown in separate parts of the organizer.",
    "Make the complete layered artwork and four-part evidence legend. Add one original symbol or visual metaphor from your own observation, label it as student interpretation, and do not copy the mentor artist's cultural imagery or style.",
    "Collect one specific viewer response, revise one composition or symbolism choice, and complete the creator/source note with one limitation and next improvement.",
  ],
  "same-facts-frame": [
    "Listen to the named work twice. Record musical evidence first, then describe its possible effect without inventing a story the sound cannot prove.",
    "Try steady beat and metre, rhythm and silence, timbre and dynamics, and texture and form with voice, body percussion, objects, instruments, or the silent visual route.",
    "Draw a complete 30–45 second graphic score with a key, timeline, repeat or contrast, dynamic marks, intentional silence, and a clear ending.",
    "Trade scores. Let a new group perform what it understands without coaching; record where the notation works and where performers pause or disagree.",
    "Revise the score, perform the changed version, and complete the composer statement with one musical choice and one next improvement.",
  ],
  "rights-in-thirty": [
    "Watch the exact mentor segment and notice how focus, level, distance, gesture, rhythm, tension, and relationship change between two moments.",
    "Read one supplied fictional access case. Name the barrier and possible repair without assigning anyone a lived identity or reenacting harm. Compare tableau sequence, narrated scene, and readers' theatre as three dramatic forms.",
    "Rehearse one safe moment in two forms, choose and name the form that best serves your intention, then build and draw the before and after moments using character, place, level, focus, distance, gesture, tension, and mood.",
    "Notate a safe transition using pathway, direction, speed, weight, repetition, contrast, relationship, and optional sound or silence.",
    "Perform or present the whole storyboard. Record what the audience understood, revise one Arts choice, and try the changed moment again.",
  ],
  "audience-remix": [
    "Study the supplied curator model. Name how entry point, sequence, spacing, contrast, pacing, sound, labels, or ending guide attention.",
    "Choose the supplied mini-artifact or a current work. State one intended audience response and make a complete first arrangement.",
    "Let a new audience member begin without coaching. Record the first notice, pause, question, route, and misunderstanding without names or ratings.",
    "Change one high-leverage artistic choice, test the changed part again, and compare the two audience records.",
    "Complete the before-and-after curator note: intention, technique, evidence, revision, remaining limitation, and next improvement.",
  ],
  "cosmic-scale-gallery": [
    "Encounter the named works and complete the context card: creator, title, date or place, material or performers, one observed move, one supported interpretation, and one question.",
    "Complete all four technique trials: kinetic form, light and shadow or colour, soundscape and graphic score, and movement or spatial score.",
    "Choose an intention and medium. Complete the full plan with elements, material or process, audience action, safety and access, source credit, one deliberate limitation, and one manageable creative risk to test.",
    "Build or rehearse the smallest complete work. Curate its entry point, sequence, label or score, and ending before adding detail.",
    "Run a no-coaching audience encounter, revise one artistic and one access or presentation choice, then share the work with an individual reflection on the creative risk, limitation, and next improvement.",
  ],
  "search-under-hood": [
    "Study the sample results on the shared screen. Find the ad label, source, date, headline, and short preview.",
    "Turn a vague search into a focused question with precise keywords.",
    "Choose the result most likely to answer the question. Explain why first does not always mean best.",
    "Follow one claim to its original source. Note aloud, on the board, or on paper who made it, when, why, and what it cannot prove.",
  ],
  "everyone-in-game": [
    "Learn the simple no-elimination game and practise moving, passing, and using space safely.",
    "Use the tally to notice who gets choices, touches, space, and quick ways back into play.",
    "Change one rule, team size, space, piece of equipment, or role. Then play again.",
    "Use the tally to decide whether your change helped more people join in.",
  ],
  "career-constellation": [
    "Choose one familiar service or project. Map every job or helping role you can see.",
    "Use the profiles on the shared screen to add work that usually stays hidden.",
    "Connect each role to skills, tools, technology, mentors, and more than one way to enter the work.",
    "Choose one small experience you could try next and name the first realistic step.",
  ],
  "each-one-teach-one": [
    "Choose one safe, focused question you want to understand well enough to teach. Name the learner you are designing for without using a real person's private information.",
    "Use at least two teacher-approved sources. Record who made each source, its title or organization, date when available, where to find it, and one limit or uncertainty.",
    "Write the learning intention, three signs that the experience works, and limits for time, tools, safety, access, privacy, and sharing.",
    "Draw the whole learner journey on paper: invitation, first action, information, meaningful choice or interaction, feedback, understanding check, and ending.",
    "Build the smallest complete version as a physical station, paper branching experience, Bloxels route, Minecraft model, or teacher-approved private app or website prototype.",
    "Watch a new learner try it without coaching. Record only actions and points of confusion—no names, accounts, photos, or personal comments.",
    "Change one content feature and one access, navigation, or feedback feature because of the test. Ask someone to try the changed part again.",
    "Teach, run a no-name understanding check, credit sources and tools, and explain your contribution, evidence, limitation, revision, and next improvement in your own words.",
  ],
};

function makePlain(step: string) {
  return plainLanguageReplacements.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), step)
    .replace(/\s+/g, " ")
    .trim();
}

const studentTitleOverrides: Record<string, string> = {
  "pattern-forecast": "Find the rule. Reveal the path.",
  "hook-cold-audience": "Try your opening on a new audience",
  "source-mosaic": "Can we cool the courtyard?",
  "geometry-field-lab": "Angle Expedition",
  "live-anthology": "Choose, improve, and share one strong piece",
  "magnitude-gallery": "How big is this number?",
  "zoo-design-studio": "Design a zoo with exact area and perimeter",
  "probability-game-audit": "Is this chance game fair?",
  "space-under-constraints": "Design within space, cost, and material limits",
  "cold-test-prototype": "Can someone use it without our help?",
  "bloxels-story-blueprint": "Write the story before building the game",
  "bloxels-game-studio": "Build a story someone can play",
  "career-constellation": "The people and skills behind one project",
  "packet-rescue": "How does a message travel through a network?",
  "project-rescue-studio": "Turn deadline chaos into a plan that works",
  "search-under-hood": "Why did this search result show up first?",
  "learning-user-manual": "Build your learning settings for right now",
  "digital-identity-forensics": "What story does this profile tell?",
  "everyone-in-game": "Remix the game so everyone has a real role",
  "effort-meter-trail": "Find the pace that works for you today",
  "each-one-teach-one": "Each One, Teach One",
};

export function plainForStudents(text: string) {
  return makePlain(text);
}

export function studentTitleFor(experience: ProgramExperience) {
  return studentTitleOverrides[experience.id] ?? makePlain(experience.title);
}

export function studentStepsFor(experience: ProgramExperience): StudentStep[] {
  const actions = exactStudentSteps[experience.id] ?? experience.steps.map(makePlain);
  return actions.map((action, index) => ({
    title: stepTitles[index] ?? `Step ${index + 1}`,
    action,
    show: index === actions.length - 1
      ? `Show your finished work: ${makePlain(experience.product)}.`
      : "Point to what you noticed, chose, tested, or changed.",
  }));
}

const vocabulary: Record<string, WordHelp> = {
  "active listening": { term: "active listening", meaning: "showing that you are following a speaker's ideas", example: "Ask a useful question about a detail you heard." },
  audience: { term: "audience", meaning: "the people a message or creation is made for", example: "A Grade 2 class needs different explanations than a science expert." },
  benchmark: { term: "benchmark", meaning: "a familiar value used for comparison", example: "One half is a useful benchmark for comparing fractions." },
  caption: { term: "caption", meaning: "words placed with an image to guide its meaning", example: "The same photo can feel different under a new caption." },
  accessibility: { term: "accessibility", meaning: "design choices that help more people understand and use something", example: "Clear contrast and a second route can make a game easier to follow." },
  cause: { term: "cause", meaning: "something that helps make an event happen", example: "A cause is not always the same as a coincidence." },
  collaboration: { term: "collaboration", meaning: "working with others toward a shared goal", example: "The team changes roles so every person can contribute." },
  composition: { term: "composition", meaning: "the way parts are arranged in an artwork", example: "Placing one object in the centre gives it emphasis." },
  consent: { term: "consent", meaning: "a clear and freely given agreement that can be changed", example: "A person can say no or change their mind." },
  constraint: { term: "constraint", meaning: "a limit or rule a design must work within", example: "The game must be finished in one short level and use school-approved sharing." },
  context: { term: "context", meaning: "information around an event or text that helps it make sense", example: "The wide image shows context that a tight crop hides." },
  contrast: { term: "contrast", meaning: "a strong difference used to make something stand out", example: "A bright shape against a dark background creates contrast." },
  creative_credit: { term: "creative credit", meaning: "naming the creator or source of ideas, art, sound, or media you use", example: "Original work and approved assets are labelled in the creator note." },
  conflict: { term: "conflict or problem", meaning: "the challenge that drives a story", example: "A bridge is broken, so the character must find another route." },
  crop: { term: "crop", meaning: "to remove the outer parts of an image", example: "A crop can hide what happened just outside the frame." },
  data: { term: "data", meaning: "information collected to answer a question", example: "Thirty trial results are data; one guess is not." },
  debug: { term: "debug", meaning: "find and fix a problem in instructions or code", example: "We debugged the steps after the character got stuck." },
  dialogue: { term: "dialogue", meaning: "words spoken by a character", example: "A guide says, ‘The glowing stones mark the safe path.’" },
  evidence: { term: "evidence", meaning: "information that supports or challenges an idea", example: "Quote a line, point to a measurement, or name what you observed." },
  exertion: { term: "exertion", meaning: "how hard your body is working", example: "You can use a personal 1–5 effort check without comparing bodies." },
  factor: { term: "factor", meaning: "a whole number that divides another number with no remainder", example: "3 and 4 are factors of 12." },
  fair_play: { term: "fair play", meaning: "safe, honest play that includes and respects others", example: "A fair rule gives everyone a useful way back into the game." },
  feedback: { term: "feedback", meaning: "specific information used to improve work", example: "The tester showed exactly where the directions became unclear." },
  game_mechanic: { term: "game mechanic", meaning: "an action or rule that shapes how a game works", example: "Collecting three keys is the mechanic that opens the final door." },
  genre: { term: "genre", meaning: "a category of text with shared features", example: "Mystery, fantasy, biography, and news report are genres." },
  goal: { term: "goal", meaning: "a result you plan to work toward", example: "A useful goal includes a first step and a check date." },
  imagery: { term: "imagery", meaning: "language that helps an audience picture, hear, or feel something", example: "The rain tapped the railing like quick fingers." },
  inference: { term: "inference", meaning: "an idea worked out from evidence and reasoning", example: "An empty wet umbrella suggests rain, but does not prove who used it." },
  interval: { term: "interval", meaning: "the equal amount between marks on a scale", example: "The graph's vertical intervals increase by 10 each time." },
  leadership: { term: "leadership", meaning: "actions that help a group move forward safely and fairly", example: "Making space for a quiet idea can be leadership." },
  limit: { term: "limit", meaning: "something evidence, a model, or a design cannot do or show", example: "A map shows routes but not every person's experience." },
  locomotor: { term: "locomotor movement", meaning: "movement that travels from one place to another", example: "Running, hopping, and rolling are locomotor movements." },
  manipulative: { term: "manipulative skill", meaning: "controlling an object with hands, feet, or equipment", example: "Throwing, catching, kicking, and striking are manipulative skills." },
  metaphor: { term: "metaphor", meaning: "a comparison that says one thing is another to create meaning", example: "Calling the heart a pump helps in some ways but has limits." },
  milestone: { term: "milestone", meaning: "an important checkpoint in a longer project", example: "Finish the test version before the feedback milestone." },
  model: { term: "model", meaning: "a useful representation of an object, idea, or system", example: "A diagram can show a system but may leave out scale." },
  network: { term: "network", meaning: "two or more connected devices that can exchange information", example: "A classroom laptop can connect through a school network to request a webpage." },
  device_client: { term: "device or client", meaning: "the phone, tablet, or computer that asks a server for information", example: "The student device requests the six-piece picture and checks that every piece arrives." },
  server: { term: "server", meaning: "a computer that stores or provides information when another device requests it", example: "The server provides the picture after the student device asks for it." },
  packet: { term: "packet", meaning: "one small piece of a larger message sent through a network", example: "Packet 4 is one numbered piece of the six-piece picture." },
  route: { term: "route", meaning: "a path information can take from one network device to another", example: "When Route A closes, the packets use the open Route B." },
  reassemble: { term: "reassemble", meaning: "put separate pieces back together in the correct order", example: "The receiving device reassembles packets 1 through 6 to show the complete picture." },
  request: { term: "request", meaning: "a message asking another device or server to provide something", example: "The device requests the picture, then requests packet 4 again when it is missing." },
  multiple: { term: "multiple", meaning: "a number made by multiplying a whole number", example: "12, 18, and 24 are multiples of 6." },
  narrator: { term: "narrator", meaning: "the voice that tells a story", example: "A first-person narrator uses I and may not know everything." },
  original_source: { term: "original source", meaning: "the earliest available place where information or evidence was published", example: "Follow a cropped repost back to the full report or update." },
  paraphrase: { term: "paraphrase", meaning: "put a source idea into your own words without changing its meaning", example: "Name the source even when you paraphrase." },
  perspective: { term: "perspective", meaning: "a point of view shaped by position, knowledge, values, and experience", example: "Two witnesses may notice different parts of the same event." },
  player_character: { term: "player character", meaning: "the character a player controls", example: "The player character must reach the observatory before the last signal fades." },
  playtest: { term: "playtest", meaning: "watching someone try a game so the designer can learn what to improve", example: "The playtest showed that players missed the first clue." },
  plot: { term: "plot", meaning: "the connected events that make up a story", example: "The plot moves from a goal, through a problem and turn, to an ending." },
  place_value: { term: "place value", meaning: "the value a digit has because of its position", example: "The 5 in 0.05 means five hundredths." },
  probability: { term: "probability", meaning: "how likely an outcome is", example: "A fair six-sided die has a 1 in 6 probability of rolling a 4." },
  prototype: { term: "test version", meaning: "an early version made so people can try it and help improve it", example: "Paper buttons can test an app idea before coding." },
  ratio: { term: "ratio", meaning: "a comparison between two quantities", example: "A 2:3 ratio means two parts of one amount for every three of another." },
  reliable: { term: "reliable source", meaning: "a source that is consistently careful, accurate, and open about its evidence", example: "Check the creator, date, purpose, evidence, and other sources." },
  revise: { term: "revise", meaning: "change ideas, structure, or design to make work stronger", example: "Revision is more than fixing spelling." },
  rhythm: { term: "rhythm", meaning: "a pattern of sounds, silences, or movements over time", example: "Clap-clap-pause can become a repeating rhythm." },
  router: { term: "router", meaning: "a device that directs information packets between networks", example: "A router chooses where a packet should travel next." },
  scale: { term: "scale", meaning: "the values or size relationship used in a graph, map, or model", example: "Changing a graph's scale can change its first impression." },
  sequence: { term: "sequence", meaning: "the order in which parts happen or appear", example: "Changing the sequence of clips can suggest a different cause." },
  setting: { term: "setting", meaning: "where and when a story happens", example: "The game begins in a flooded forest at dawn." },
  source: { term: "source", meaning: "where information, evidence, or a creative work comes from", example: "Record the creator, title, organization, and date when possible." },
  story_block: { term: "story block", meaning: "a short piece of story information placed where the player needs it", example: "A warning appears before the player chooses a tunnel." },
  strength: { term: "strength", meaning: "an ability or helpful action supported by evidence", example: "I organized the materials and helped the group restart." },
  strategy: { term: "strategy", meaning: "a planned way to reach a goal or solve a problem", example: "Moving into open space is a game strategy." },
  success_rules: { term: "success rules", meaning: "clear statements describing what a working design must do", example: "A new player can begin, follow the story, and reach the ending without hints." },
  symbol: { term: "symbol", meaning: "an image, sound, object, or action used to represent an idea", example: "A broken chain can symbolize freedom." },
  system: { term: "system", meaning: "connected parts that work together", example: "A network includes devices, routers, messages, and rules." },
  tableau: { term: "tableau", meaning: "a still image made with bodies or figures", example: "Hold one frozen pose to show the moment power changes." },
  theoretical: { term: "theoretical probability", meaning: "the probability predicted from all equally likely outcomes", example: "There are two even numbers on a four-part equal spinner, so the probability is 2/4." },
  trend: { term: "trend", meaning: "a general direction or pattern in data", example: "The values generally rise, even though one point drops." },
  turning_point: { term: "turning point", meaning: "a moment when the problem, plan, or understanding changes", example: "The map is wrong, and the player must follow the river instead." },
  variable: { term: "variable", meaning: "a symbol for a number that can change or is not yet known", example: "In 3n + 1, n is the variable." },
  well_being: { term: "well-being", meaning: "physical, emotional, mental, and social health together", example: "Sleep, belonging, movement, safety, and support can affect well-being." },
};

const arcWords: Record<string, string[]> = {
  "ela-belonging": ["active listening", "narrator", "source", "context", "revise"],
  "ela-media": ["perspective", "crop", "context", "caption"],
  "ela-reading-power": ["inference", "evidence", "plot", "conflict", "turning_point", "dialogue", "story_block"],
  "ela-research": ["source", "reliable", "paraphrase", "audience"],
  "ela-language-lab": ["metaphor", "imagery", "limit"],
  "ela-worldbuilding": ["genre", "narrator", "revise", "audience"],
  "math-number": ["place_value", "benchmark", "factor", "multiple"],
  "math-fractions": ["ratio", "benchmark", "place_value"],
  "math-patterns": ["variable", "strategy", "model"],
  "math-data": ["data", "scale", "interval", "trend", "probability"],
  "math-geometry": ["scale", "model", "revise"],
  "math-design": ["model", "ratio", "limit", "revise"],
  "arts-place": ["composition", "rhythm", "tableau", "symbol"],
  "arts-power": ["symbol", "metaphor", "contrast", "perspective"],
  "arts-audience": ["audience", "composition", "feedback", "revise"],
  "arts-systems": ["rhythm", "model", "scale", "limit"],
  "adst-systems": ["network", "device_client", "server", "packet", "router", "route", "reassemble", "request"],
  "adst-access": ["prototype", "feedback", "limit", "revise"],
  "adst-game": ["player_character", "game_mechanic", "success_rules", "constraint", "playtest", "debug", "accessibility", "creative_credit", "revise"],
  "adst-prototype": ["prototype", "feedback", "model", "revise"],
  "adst-code": ["debug", "sequence", "system", "model"],
  "phe-belonging": ["locomotor", "manipulative", "fair_play", "strategy"],
  "phe-strategy": ["strategy", "rhythm", "exertion", "fair_play"],
  "phe-health": ["reliable", "consent", "well_being", "source"],
  "phe-life": ["exertion", "goal", "strategy", "well_being"],
  "career-learning": ["strength", "goal", "evidence"],
  "career-trust": ["leadership", "collaboration", "audience", "evidence"],
  "career-project": ["milestone", "collaboration", "feedback", "revise"],
  "career-futures": ["strength", "milestone", "collaboration", "goal"],
};

export function wordHelpFor(arcId: string): WordHelp[] {
  return (arcWords[arcId] ?? []).map(key => vocabulary[key]).filter(Boolean);
}

export const experienceKits: Record<string, ExperienceKit> = {
  "learning-user-manual": {
    setupMinutes: 4,
    provided: ["Projectable fictional learner case", "Printable strength-action cards", "Learning-conditions menu", "One-page private learning-manual sheet", "Goal-path strip", "Completed mini model"],
    gather: ["Pencils", "Scrap paper or notebooks", "Coloured pencils optional"],
    shortRoute: "Build Noor's completed mini model on the projector one box at a time. Students circle one strength with evidence, choose one condition, and finish one support-and-responsibility pair on paper.",
    cards: [
      { title: "MINI MODEL · NOOR'S CLASS MOMENT", body: "During a paper-bridge task, Noor saw the bridge bend, moved one strip, and tested it again. Later, Noor asked to see one writing direction at a time. These are class actions, not personality labels." },
      { title: "1 · FIND THE ACTION", body: "Finish this sentence: I __ when __. Model: I tested a new strip when the paper bridge bent." },
      { title: "2 · NAME THE STRENGTH", body: "Match the action to one strength: notice · organize · explain · include · persist · create · test · ask for help. Model: Noor's action shows testing and persisting." },
      { title: "3 · CHOOSE A CONDITION", body: "Circle one: one direction at a time · a worked example · quiet thinking time · talk before writing · a movement break · materials within reach. Model: Noor chooses one direction at a time." },
      { title: "4 · BALANCE HELP AND RESPONSIBILITY", body: "Useful help: show one direction at a time. My responsibility: point to my current step and ask one clear question if I am stuck." },
      { title: "5 · MAKE A SMALL GOAL", body: "By September 30, Noor will begin the first step within two minutes in three class tasks. First step: underline the action word. Check: each Friday. Help source: teacher or partner." },
      { title: "QUIET AND PRIVATE ROUTE", body: "Point, circle, draw, or write. You do not have to read your sheet aloud. Use the fictional Noor model if you do not want to use a personal example. No device or public sharing is needed." },
    ],
  },
  "place-soundwalk": {
    setupMinutes: 5,
    provided: ["Projectable three-layer sound map", "Printable near-middle-far listening rings", "Observation-or-guess sorting cards", "Place-postcard frame", "Completed library-doorway mini model"],
    gather: ["Pencils", "Clipboards or firm books", "Scrap paper", "Two classroom objects for an optional soundscape"],
    shortRoute: "Listen at one teacher-chosen station for twenty seconds, mark three sounds on paper, sort observation from guess, and revise one exact place sentence. Use the indoor desk route whenever outside is unavailable.",
    cards: [
      { title: "1 · LISTEN", body: "Stay at the teacher-chosen spot. Listen quietly for twenty seconds. Make one small mark each time you notice a new sound." },
      { title: "2 · MAP THE LAYERS", body: "Write each sound in one ring: NEAR · MIDDLE · FAR. Add a sound word such as tik-tik, rrr-stop, shhhh, scrape, hum, or rustle." },
      { title: "3 · SORT WHAT YOU KNOW", body: "Observation: ‘A wheel rumbled and stopped.’ Guess: ‘Someone was in a hurry.’ Mark a guess with ? until more evidence appears." },
      { title: "MINI MODEL · LIBRARY DOORWAY", body: "NEAR: pencil, tik-tik, two taps. MIDDLE: cart wheel, rrr-stop, moving left. FAR: rain, shhhh, steady behind the window." },
      { title: "4 · BUILD ONE PLACE LINE", body: "Model: ‘Behind two bright pencil taps, a cart wheel rumbles left while rain brushes the far window with a steady shhhh.’" },
      { title: "5 · REVISE", body: "Ask: Which detail helps you hear the place? Replace one vague word with an exact sound, direction, distance, or pattern." },
      { title: "INDOOR OR QUIET ROUTE", body: "Listen from a desk, hallway doorway, or closed window. Write a sound postcard instead of performing. No recording, headphones, tablets, or student devices are needed." },
    ],
  },
  "packet-rescue": {
    setupMinutes: 7,
    provided: ["Three-view visual sequence: tabletop model, exact network diagram, and human network", "Six-piece cat-picture packet set", "Device, router, server, packet, and observer role cards", "Route A and Route B signs", "Route-closed and missing-packet cards", "Observer log and troubleshooting map"],
    gather: ["Masking tape or two lengths of rope", "Six envelopes or paper clips", "Pencils", "Optional clipboards"],
    shortRoute: "Teach the words with the diagram, complete the tabletop picture once, then run one working human-network round and one missing-packet repair.",
    cards: [
      { title: "STUDENT DEVICE / CLIENT", body: "Say: ‘I request the cat picture.’ Receive the numbered packets. Put them in order, check 1–6, and request any missing number again." },
      { title: "SERVER", body: "Keep the complete six-piece picture. When the request arrives, give packets 1–6 to the first router one at a time. Resend only a specifically requested missing packet." },
      { title: "ROUTER A", body: "Receive one packet at a time. Read its destination label, choose an open route, and pass it on. Do not open, change, or rebuild the picture." },
      { title: "ROUTER B", body: "Receive one packet at a time. Read its destination label, choose an open route, and pass it on. If one route closes, use the other open route." },
      { title: "PACKETS 1–6", body: "Carry only your numbered piece. Follow the route chosen by the router. Packets may arrive in a different order." },
      { title: "OBSERVER", body: "Check: request reached server · packets stayed numbered · routers chose routes · device checked 1–6 · missing packet was requested again · message was reassembled." },
      { title: "ROUND 1 · BOTH ROUTES OPEN", body: "Run slowly. Pause after each handoff so the class can name the device, router, server, packet, and route." },
      { title: "ROUND 2 · ROUTE A CLOSED", body: "Place the ROUTE CLOSED card on Route A. Routers redirect packets along Route B. Discuss what changed and what stayed the same." },
      { title: "ROUND 3 · PACKET 4 MISSING", body: "Hold packet 4 at the observer station. The device checks the numbers, requests 4 again, and reassembles only after it arrives." },
      { title: "TROUBLESHOOTING MAP", body: "Problem noticed → evidence → possible location → one change → test again → result. End by naming one limit of the role-play model." },
    ],
  },
  "ordinary-object-story": {
    setupMinutes: 3,
    provided: ["Seven projectable object-image sets", "Six-move story builder", "Three-beat listener map", "Fictional, observation-only, and optional-connection routes"],
    gather: ["Notebook or scrap paper", "Pencil", "Optional single teacher-managed recorder for a class capture"],
    shortRoute: "Partners choose one object, name five visible clues, tell a 45-second three-beat story, ask one exact question, and retell it more clearly.",
    cards: [
      { title: "VISIBLE CLUES", body: "Choose one object from Sets A–G. Partners take turns pointing to five details and saying ‘I can see…’ before anyone invents." },
      { title: "BEGINNING · PERSON + PLACE + WANT", body: "Who notices the object? Where are they? What do they want in this exact moment? Use one visible clue." },
      { title: "TURN · CHANGE + CHOICE", body: "Use a second visible clue to create a surprise, problem, discovery, or choice that changes what happens next." },
      { title: "ENDING · CAUSE + CHANGE", body: "Show what is different because of the turn. Connect the ending back to the object instead of simply stopping." },
      { title: "LISTENER TEST", body: "Listener: name the beginning, turn, and ending you heard. Then ask one exact question about the place where you got lost." },
      { title: "RETELL", body: "Storyteller: add the detail that answers the listener's question. Tell it again without adding unrelated length." },
    ],
  },
  "semiahmoo-story-source-lab": {
    setupMinutes: 8,
    provided: ["Projectable attribution card", "Heard · interpreted · wondered note frame", "Permission and sharing-boundary card", "Original fictional oral-text backup"],
    gather: ["Teacher-controlled computer and projector for the district source", "Paper or notebooks", "Pencils"],
    shortRoute: "No Wi-Fi or TTOC: read the supplied fictional account aloud twice. Students complete the same source card and sort heard, interpreted, and wondered. This rehearses the listening skill only; reschedule the Semiahmoo source and do not count the rehearsal as First Peoples oral-tradition evidence.",
    cards: [
      { title: "SOURCE CARD · BEFORE LISTENING", body: "Record: exact title · speaker · community or context exactly as the source names it · host/source route · format · date accessed. Do not add a Nation, teaching, or ownership claim the source does not state." },
      { title: "LISTEN 1 · NO STORY NOTES", body: "Listen for the whole source. After it ends, record one learning and one question. A blank is safer than a guess." },
      { title: "LISTEN 2 · SORT THE RESPONSE", body: "HEARD: the source supports it. INTERPRETED: my thinking about it. WONDERED: a question I still have." },
      { title: "PERMISSION CHECK", body: "Access to listen is not automatic permission to copy, download, transcribe, retell, reenact, remix, or repost. Follow current guidance and acknowledge the source and any owner the source identifies." },
      { title: "NO-WIFI FICTIONAL REHEARSAL · TEACHER READS", body: "After lunch, Mina notices a paper envelope beneath the covered bench. The front says ‘Room 12,’ but no name. She brings it unopened to the office. The secretary calls Room 12, and a student retrieves a set of handmade game cards before dismissal. Attribute this as a teacher-read fictional Classroom OS practice text." },
    ],
  },
  "edit-room": {
    setupMinutes: 3,
    provided: ["Full-context event image", "Crop and caption prompts", "Four-frame storyboard directions", "Creator-note questions"],
    gather: ["Paper or board space", "Pencil or marker", "Optional teacher-managed slide or recording tool"],
    shortRoute: "Compare the full scene with one misleading crop, discuss context, then make one fair caption.",
    cards: [
      { title: "FACT", body: "What can everyone verify in the full image?" },
      { title: "CROP", body: "What disappears when only the spilled supplies are shown?" },
      { title: "CAPTION", body: "Write one dramatic caption and one fair caption. Which words push a conclusion?" },
      { title: "SEQUENCE", body: "Choose four moments: before, spill, response, cleanup. Do not rearrange cause and effect." },
      { title: "CREATOR NOTE", body: "I kept __ because __. My audience needs this context: __." },
    ],
  },
  "bloxels-story-blueprint": {
    setupMinutes: 5,
    provided: ["Original projectable pixel-world image", "Story blueprint", "Paper level map", "Story-block planner", "Partner story-test prompts"],
    gather: ["Pencils", "Plain or grid paper", "Optional school-approved speech-to-text or audio tool"],
    shortRoute: "Plan one beginning, one turning point, and one ending. Place all three on one paper route and revise the part a partner cannot follow.",
    cards: bloxelsStoryGame.printables.slice(0, 2).map(sheet => ({ title: sheet.title.toUpperCase(), body: sheet.prompts.join(" · ") })),
  },
  "bloxels-game-studio": {
    setupMinutes: 10,
    provided: bloxelsStoryGame.provided,
    gather: bloxelsStoryGame.gather,
    shortRoute: bloxelsStoryGame.shortRoute,
    cards: bloxelsStoryGame.printables.map(sheet => ({ title: sheet.title.toUpperCase(), body: sheet.prompts.join(" · ") })),
  },
  "each-one-teach-one": {
    setupMinutes: 8,
    provided: ["Five-route choice board", "Source and claim check", "Complete paper learner-flow map", "No-name learner-test record", "Before/after revision note", "Four-question understanding-check planner", "SpacesEDU reflection frame"],
    gather: ["Plain paper or index cards", "Pencils, markers, sticky notes, scissors, and tape", "Two teacher-approved source routes per topic", "Optional school-managed Bloxels, Minecraft, visual-coding, or private prototype access"],
    shortRoute: "Use four blocks and the paper branching route: choose and verify one idea; draw a complete teaching path; let a new learner try it; revise one content and one access feature; teach it with a no-name paper or whole-class check. Keep the same source, test, revision, and reflection evidence.",
    cards: [
      { title: "PROJECT BRIEF", body: "Help a Grade 6 learner understand one worthwhile idea in 5–10 minutes. The learner must know what to notice, do, check, and take away without the designer whispering directions." },
      { title: "ROUTE 1 · PHYSICAL / NO TECH", body: "Use objects, cards, a mini-demo, model, board game, sort, foldable, or station. Keep the learner action, feedback, understanding check, test, and revision." },
      { title: "ROUTE 2 · PAPER BRANCHING STORY", body: "Use numbered or linked cards. Include at least one meaningful choice, feedback for both routes, a return path when useful, and a clear ending." },
      { title: "ROUTE 3 · BLOXELS", body: "Build one short teaching route with original or approved assets, visible feedback, private class sharing, and a complete paper route first." },
      { title: "ROUTE 4 · MINECRAFT", body: "Build a purposeful model, demonstration, or knowledge world. Every structure must teach; include signs, narration, or a live guide plus an equivalent paper plan." },
      { title: "ROUTE 5 · APP / WEBSITE PROTOTYPE", body: "Wireframe every screen on paper first. Use only a teacher-approved school route with private sharing. No public publishing, comments, analytics, personal accounts, or student information." },
      { title: "SOURCE CHECK", body: "For each key claim: creator or organization · title · date when available · link or route · what it supports · what it cannot prove. Compare at least two teacher-approved sources." },
      { title: "AI TRAFFIC LIGHT", body: "GREEN: ask for questions, alternatives, debugging ideas, or wording to compare. YELLOW: verify every claim and protect authorship. RED: no confidential information, copied final answers, fake citations, impersonation, or raw AI output in SpacesEDU." },
      { title: "NO-NAME LEARNER TEST", body: "Watch without coaching. Record: first action · where the learner paused · what they understood · what feedback they noticed · one barrier. Record actions, not names, photos, accounts, or personal comments." },
      { title: "UNDERSTANDING CHECK", body: "Plan four quick questions: identify the key idea · explain why or how · apply it to a new case · name one source, limit, or uncertainty. Use mini-whiteboards, corners, cards, talk, paper, or a teacher-run Kahoot." },
      { title: "REVISION + REFLECTION", body: "I wanted learners to understand __. The test showed __. I changed __ because __. My contribution was __. One source or limit was __. My next improvement would be __." },
    ],
  },
  "magnitude-gallery": {
    setupMinutes: 4,
    provided: ["Interactive number-line lab", "Mixed-up number cards", "Accurate zoom scales", "Immediate placement checks"],
    gather: ["Board or scrap paper", "Pencils or markers"],
    shortRoute: "Repair the decimal trio, place the billion cards on one accurate scale, and explain one surprising position.",
    cards: [
      { title: "NUMBER CARDS A", body: "0.004 · 0.04 · 0.4 · 4 · 40 · 400" },
      { title: "NUMBER CARDS B", body: "4,000 · 40,000 · 4,000,000 · 4,000,000,000" },
      { title: "BENCHMARKS", body: "0 · 0.5 · 1 · 10 · 100 · 1,000 · 1 million · 1 billion" },
      { title: "DEFEND", body: "I placed __ between __ and __ because the digit __ has a value of __." },
    ],
  },
  "zoo-design-studio": {
    setupMinutes: 8,
    provided: ["30 m × 24 m fictional site brief", "Six core habitat cards plus two choice cards", "Path and access rules", "Calculation record", "Peer-check card", "Revision prompt"],
    gather: ["1 cm grid paper", "Rulers", "Pencils and coloured pencils", "Calculator after a method is shown", "Scissors optional"],
    shortRoute: "Use four core habitats on a 24 m × 18 m site. Require one rectangle, one right triangle, one parallelogram, the 2 m path, and one checked revision.",
    cards: [
      { title: "FICTIONAL SITE BRIEF", body: "The site is 30 m by 24 m. On 1 cm grid paper, 1 square represents 1 m. Keep a continuous 2 m-wide route from the entry to every habitat. Add one 4 m × 4 m quiet area. Habitats may share a fence but may not overlap the path." },
      { title: "HABITAT A · FOREST RED PANDA", body: "Rectangle: 8 m × 6 m. Show area and perimeter. One 6 m side must face the main path." },
      { title: "HABITAT B · RESCUE CRANE", body: "Right triangle: legs 6 m and 8 m; third side 10 m. Show area and perimeter. Mark the right angle and perpendicular height." },
      { title: "HABITAT C · RIVER OTTER", body: "Parallelogram: base 9 m, perpendicular height 4 m, slanted side 5 m. Show area and perimeter. Do not use the slanted side as height." },
      { title: "HABITAT D · DESERT TORTOISE", body: "Isosceles trapezoid: parallel bases 10 m and 16 m, height 4 m, legs 5 m each. Show area and perimeter. Mark the two parallel sides." },
      { title: "HABITAT E · POLLINATOR GARDEN", body: "Square: side 7 m. Show area and perimeter. Connect it to the quiet area without blocking the main path." },
      { title: "HABITAT F · FROG WETLAND", body: "L-shape made by removing a 4 m × 3 m corner from a 10 m × 8 m rectangle. Show remaining area and complex perimeter. Label the missing side lengths." },
      { title: "CHOICE G · NOCTURNAL HOUSE", body: "Rectangle with area 48 m² and one side 6 m. Find the missing side and perimeter before placing it." },
      { title: "CHOICE H · AVIARY", body: "Right triangle with area 30 m² and base 12 m. Find the perpendicular height. The three sides are 5 m, 12 m, and 13 m." },
      { title: "CALCULATION RECORD", body: "Shape · dimensions shown · formula built from the model · substitution · answer with units · reasonableness check. Circle every perpendicular height." },
      { title: "PARTNER CHECK", body: "Check one area · one perimeter · one shape property · the 2 m route · one shared fence · one place where the plan could be clearer. Ask before changing another team's work." },
      { title: "REVISION NOTE", body: "My first plan showed __. The check found __. I changed __ because the Mathematics showed __." },
      { title: "CORE ANSWERS", body: "A: A48 m², P28 m · B: A24 m², P24 m · C: A36 m², P28 m · D: A52 m², P36 m · E: A49 m², P28 m · F: A68 m², P36 m · G: missing side 8 m, P28 m · H: height 5 m, P30 m." },
    ],
  },
  "graph-story-lab": {
    setupMinutes: 3,
    provided: ["Same-data/different-scale graph pair", "Two data sets", "Graph checklist", "Claim-and-limit prompts"],
    gather: ["Grid paper", "Pencil and ruler", "Optional floor tape"],
    shortRoute: "Compare the two supplied graphs, build one honest graph, and state one claim plus one limit.",
    cards: [
      { title: "DATA SET A · WATER", body: "Day 1–6 (L): 48, 50, 49, 52, 53, 54" },
      { title: "DATA SET B · SHADE", body: "Hour 9–14 (°C): 17, 19, 22, 24, 23, 21" },
      { title: "GRAPH CHECK", body: "Title · both axes labelled · equal intervals · useful scale · points connected in time order" },
      { title: "CLAIM", body: "The graph supports __ because __." },
      { title: "LIMIT", body: "The graph cannot show __ because __." },
    ],
  },
  "four-arts-languages": {
    setupMinutes: 8,
    provided: ["Complete four-part Arts Foundations folio", "Visual, music, drama, and dance technique cards", "Mentor encounter/source card", "Graphic notation key", "Audience-response and revision card", "Projectable courtyard practice scene"],
    gather: ["Paper and drawing tools", "Safe classroom sound objects or instruments", "Clear floor, seated, hand-only, or tabletop movement space", "Optional teacher-controlled audio"],
    shortRoute: "Use one 75-minute sampler only when the full five-studio sequence is impossible: complete a visual study and graphic score, make one tableau or movement notation, combine two forms, collect one response, and revise. Return to the missing studies later so the folio is complete.",
    cards: [
      { title: "MENTOR ENCOUNTER", body: "Creator/performers · title · date/place · form · one precise move I noticed · what that move does · one question. Look or listen twice before making." },
      { title: "1 · COMPLETE VISUAL STUDY", body: "Fill the full thumbnail. Label at least four choices from line · shape · colour/value · texture · space · balance · contrast · emphasis. Circle what the audience should notice first." },
      { title: "2 · COMPLETE GRAPHIC SCORE", body: "Draw a 20-second timeline and key. Include beat or pulse · rhythm · at least one silence · timbre · dynamic change · repeat or contrast · clear ending. Voice, body, objects, instruments, and a silent visual route are valid." },
      { title: "3 · COMPLETE TABLEAU STORYBOARD", body: "Draw BEFORE and AFTER. Label focus · level · distance · gesture · character/place · tension or mood. Add arrows or words for what changes; nobody must perform." },
      { title: "4 · COMPLETE MOVEMENT SCORE", body: "Notate eight counts. Include body or prop · pathway/direction · speed/time · weight/dynamics · relationship · repeat or contrast. Standing, seated, hand-only, or tabletop routes count equally." },
      { title: "5 · TWO-FORM REMIX", body: "Forms chosen: __ + __. Intended first notice: __. Entry cue: __. 45–60 second sequence: beginning __ / change __ / ending __." },
      { title: "AUDIENCE + REVISION", body: "Audience: I noticed __ first because __. Maker: I wanted __. I changed __ after the response because __. It now __. Next I would __." },
      { title: "STUDIO SAFETY", body: "Use the class volume ceiling and freeze signal. Keep pathways clear. Do not swing objects, touch another person, require disclosure, or copy a mentor's distinctive work." },
    ],
  },
  "map-what-maps-miss": {
    setupMinutes: 8,
    provided: ["Exact artist/context card", "Credited mentor still or teacher-read source capsule", "Direct-observation or fictional place-evidence sheet", "Visual technique and symbol/metaphor cards", "Four-part evidence legend", "Creator/source and response note"],
    gather: ["Large paper", "Pencils and erasers", "Colour, charcoal, collage, or texture tools as available", "Optional clipboard for observation"],
    shortRoute: "Use the credited mentor still and supplied fictional courtyard evidence. Complete the technique strip, an original symbol or metaphor, the layered composition, all four evidence-legend sections, one viewer response, and one revision without web access or field travel.",
    cards: [
      { title: "ARTIST + CONTEXT", body: "Artist(s) · work title · date · place/Nation only as the exact source names it · materials when stated (write ‘not stated’ when they are not) · public context · one observed choice · one supported interpretation · one question. Never merge title or date details from different sources." },
      { title: "SUPPLIED PLACE EVIDENCE", body: "Fictional practice site: a rain channel curves from roof to garden; three sturgeon-shaped bicycle racks repeat near the path; rough cedar-coloured panels contrast with blue-grey pavement; a quiet bench faces the wetland; wheel and bird sounds cross the space. This card is Classroom OS fiction, not local cultural evidence." },
      { title: "TECHNIQUE STRIP", body: "Try one small example of each: line/path · geometric and organic shape · texture mark · three values · colour relationship · positive/negative space · balance · variety and unity · emphasis." },
      { title: "SYMBOL + METAPHOR · YOUR IDEA", body: "A symbol is one sign, object, colour, or mark used to carry an idea. A visual metaphor shows one idea through another relationship. Create your own from direct observation—not from a mentor's cultural imagery. Mark it STUDENT INTERPRETATION and explain: ‘I used __ to suggest __ because __.’" },
      { title: "COMPOSITION PLAN", body: "Intention: __. First notice: __. Visual path: __. Foreground/middle/background: __. Repeated pattern: __. Contrast: __. Original symbol/metaphor: __. Empty space: __. Material/process: __." },
      { title: "FOUR-PART LEGEND · COMPLETE ALL", body: "SOURCE CONTEXT = exact attributed fact · DIRECT OBSERVATION = what I noticed · ARTISTIC INTERPRETATION = my chosen meaning · UNKNOWN = what this work cannot claim. Use a different symbol or border for each." },
      { title: "SOURCE CARE", body: "Do not copy a cultural style, symbol, story, or protocol. Do not harvest, taste, record people, or turn one work into a claim about a whole Nation or community." },
      { title: "VIEWER RESPONSE", body: "I noticed __ first. My eye followed __. The visual choice that helped was __. I was unsure about __. This describes the work; it does not rate the artist." },
      { title: "CREATOR NOTE + REVISION", body: "My intention was __. I used __ to __. My source/observation was __. The response showed __. I changed __ because __. One limit or next improvement is __." },
    ],
  },
  "same-facts-frame": {
    setupMinutes: 6,
    provided: ["Music encounter card", "Four technique mini-labs", "Graphic-notation key", "Complete score template", "Performer test and composer revision card"],
    gather: ["Large paper and markers", "Voices, body percussion, safe objects, or classroom instruments", "Timer", "Optional teacher-controlled recording"],
    shortRoute: "Teacher performs the supplied four-layer model. Students complete a 20-second score with key, silence, dynamics, form, and ending; a new pair performs it; composers revise one unclear symbol.",
    cards: [
      { title: "LISTENING EVIDENCE", body: "Creator/performers · title · exact segment · steady beat? · rhythm/silence · pitch direction · timbre · dynamics · texture · form · one precise sound moment · possible effect. Evidence before story." },
      { title: "MINI-LAB 1 · BEAT, METRE, RHYTHM", body: "Keep 8 steady beats. Group them 4 + 4. Place a different rhythm over the beat. Try the same rhythm without a steady beat and compare." },
      { title: "MINI-LAB 2 · SILENCE + DYNAMICS", body: "Perform four sounds, two beats of silence, then four sounds that grow from soft to medium. Silence is an intentional event, not empty time." },
      { title: "MINI-LAB 3 · TIMBRE + TEXTURE", body: "Perform one pattern with voice, hands, and one object. Then layer two patterns. Describe how the tone colour and number of layers change the effect." },
      { title: "MINI-LAB 4 · FORM", body: "Build A–A–B–A or A–B–A. Make B different through rhythm, pitch, timbre, dynamics, texture, or silence—not simply louder." },
      { title: "GRAPHIC NOTATION KEY", body: "● short sound · ━ held sound · / rising pitch · \\ falling pitch · > grow louder · < grow softer · □ silence · × repeat · brackets = play together. Add your own symbols and define them." },
      { title: "COMPLETE SCORE", body: "Title/intention · performers/materials · 0–45 second timeline · symbol key · pulse/metre if used · rhythm · silence · dynamic change · timbre/layers · repeat/contrast · clear ending · accessibility route." },
      { title: "PERFORMER TEST", body: "Without composer coaching: Where did we start? Which symbols matched? Where did we pause, disagree, or lose time? What did we think the ending was? Record actions, not ratings." },
      { title: "COMPOSER REVISION", body: "I intended __. Performers understood __. They paused at __ because __. I changed the symbol/sequence __. The second performance __. Next I would __." },
      { title: "VOLUME + OBJECT SAFETY", body: "Agree on a volume ceiling, stop signal, and safe object list. No throwing, striking furniture, surprise noise, or sound beside another person's ear. A quiet or visual rhythm route is always available." },
    ],
  },
  "rights-in-thirty": {
    setupMinutes: 8,
    provided: ["Four low-risk fictional case cards", "Dramatic-form, drama, and dance technique cards", "Before–transition–after score", "Six-frame storyboard", "Audience evidence and revision card"],
    gather: ["Open, seated, hand-only, or tabletop performance space", "Paper and markers", "Optional safe sound objects", "Optional neutral props such as a sign or ribbon"],
    shortRoute: "Choose one supplied case and one taught form—tableau sequence, narrated scene, or readers' theatre. Complete all six storyboard frames and technique labels, read or show it to an audience, record what was understood, and revise one frame. Performance is optional.",
    cards: [
      { title: "CASE A · YOUTH MEETING", body: "The fictional meeting notice is tiny print and the room has a stairs-only entrance. Repair possibilities include large clear information, more than one format, and a step-free route." },
      { title: "CASE B · LIBRARY WORKSHOP", body: "The fictional workshop registration works only through a smartphone app and closes after ten minutes. Repair possibilities include in-person/paper registration, more time, and a help route." },
      { title: "CASE C · COMMUNITY GAME", body: "The fictional game directions are spoken once while equipment blocks the view. Repair possibilities include visual and demonstrated instructions, clear space, slower rehearsal, and useful non-running roles." },
      { title: "CASE D · GARDEN CONSULTATION", body: "The fictional consultation happens only at 2:30 p.m. on one weekday and accepts only long written comments. Repair possibilities include varied times and short spoken, drawn, translated, or written response routes." },
      { title: "DRAMATIC FORMS · COMPARE + CHOOSE", body: "TABLEAU SEQUENCE: meaning through connected frozen images. NARRATED SCENE: a narrator links brief safe actions or images. READERS' THEATRE: voices interpret a written script while movement stays minimal. Rehearse one moment in two forms, compare the audience effect, then choose and name the form used." },
      { title: "DRAMA TECHNIQUE", body: "Character · place · situation · focus · level · distance · gesture · tension · mood · contrast. Show the system barrier, not a stereotype of a person." },
      { title: "DANCE / TRANSITION TECHNIQUE", body: "Body/prop · pathway · direction · level · speed/time · weight/dynamics · relationship · repetition · contrast · transition. Standing, seated, hand-only, and tabletop options are equal." },
      { title: "COMPLETE SIX-FRAME SCORE", body: "1 place/context · 2 before focus · 3 barrier becomes clear · 4 transition begins · 5 repair changes the relationship · 6 after image and ending. Label technique, optional sound/silence, and safe pathways in every frame." },
      { title: "AUDIENCE EVIDENCE", body: "What place did you see? What barrier? What changed? Which Arts choice showed the repair? Where were you uncertain? Describe what was understood; do not rate acting ability." },
      { title: "REVISION + REFLECTION", body: "Our intention was __. The audience understood __ and missed __. We changed focus/space/gesture/timing/sound __ because __. My contribution was __. Next we would __." },
      { title: "SAFETY + REPRESENTATION", body: "No personal disclosure, identity assignment, restraint, isolation, falling, threatening gesture, surprise touch, trauma reenactment, or imitation of a lived disability. Use the supplied system-level cases only." },
    ],
  },
  "audience-remix": {
    setupMinutes: 5,
    provided: ["Common fictional mini-artifact", "Crowded and revised curator models", "Intention and first-arrangement plan", "No-name audience observation sheet", "Before/after curator statement"],
    gather: ["Paper, sticky notes, tape, and markers", "Table or wall area", "Optional safe sound or movement element", "Optional current student artwork"],
    shortRoute: "Use the common mini-artifact, make two paper arrangements, ask a new viewer to begin without coaching, revise the strongest barrier, and complete the before/after note.",
    cards: [
      { title: "COMMON MINI-ARTIFACT · NIGHT GARDEN", body: "Three small artworks: moth at a lamp · rain on leaves · snail trail. Three captions: ‘Follow the light’ · ‘Listen between drops’ · ‘A silver route appears.’ One 8-beat sound pattern: tap–tap–silence–brush / tap–silence–brush–hold. Classroom OS fiction." },
      { title: "MODEL A · CROWDED", body: "All images, captions, and sound directions begin at once; labels use the same size; entry and ending are unmarked. Audience problem: no clear first action or path." },
      { title: "MODEL B · CURATED", body: "One moth image opens the route; spacing and arrows lead to rain, then snail; the sound cue begins at station 2; the ending asks viewers to trace one pattern. Audience effect: a legible sequence with one intentional pause." },
      { title: "INTENTION + FIRST ARRANGEMENT", body: "Audience: __. I want them to notice/feel/think/do __. First action: __. Sequence: __. Emphasis: __. Pacing/silence: __. Label or score: __. Ending: __. Access route: __." },
      { title: "NO-NAME AUDIENCE RECORD", body: "First notice · first action · route taken · pause point · question asked · part skipped · idea they understood · barrier. Record actions and words only—no names, photos, ratings, or popularity votes." },
      { title: "CHOOSE THE REVISION", body: "Change one high-leverage Arts feature: entry point · scale/contrast · spacing · sequence · sound/silence · pacing · focus · label/score · ending · access route. Predict the effect before testing again." },
      { title: "CURATOR STATEMENT", body: "My intention was __. I used __ to __. The first test showed __. I changed __ because __. The second test showed __. One limit remains __. My next improvement is __." },
    ],
  },
  "cosmic-scale-gallery": {
    setupMinutes: 10,
    provided: ["Mentor context/technique card", "Four complete technique trials", "Intention and medium plan", "Safety/access checklist", "Curation and audience-test record", "Individual reflection"],
    gather: ["Paper, card, reused materials, tape, clips, string, and scissors", "Translucent paper and teacher-approved safe lights", "Sound objects or instruments", "Open, seated, or tabletop movement space"],
    shortRoute: "Use table-top routes for all four trials, choose one, make a small complete work with label/score and ending, run a no-coaching encounter, and revise one artistic and one access choice.",
    cards: [
      { title: "MENTOR CONTEXT + TECHNIQUE", body: "Creator/performers · title · date/place · material/form · context · one exact movement, sound, light, spatial, or material choice · effect supported by evidence · one question. Do not copy the work." },
      { title: "TRIAL 1 · KINETIC FORM", body: "Build a balanced or suspended paper form that changes with a gentle teacher-made air current or hand movement. Sketch rest and motion. Label pivot, balance, pathway, pattern, and one safety limit." },
      { title: "TRIAL 2 · LIGHT / SHADOW / COLOUR", body: "Layer opaque, translucent, and cut paper with one steady safe light. Record three arrangements. Choose how value, colour, overlap, positive/negative space, and distance change the image." },
      { title: "TRIAL 3 · SOUNDSCAPE / SCORE", body: "Compose 20 seconds with a key, intentional silence, timbre contrast, dynamics, layers, repetition, and ending. A silent visual score is an equal route." },
      { title: "TRIAL 4 · MOVEMENT / SPATIAL SCORE", body: "Notate eight counts or eight changes using pathway, direction, level, speed/time, weight/dynamics, relationship, repetition, contrast, and freeze. Standing, seated, hand-only, prop, or tabletop routes are equal." },
      { title: "FULL WORK PLAN", body: "Intention · audience · chosen form · taught elements · material/process · beginning/change/ending · audience action · source/credit · access route · safety · deliberate limitation · one manageable creative risk to test · cleanup." },
      { title: "CURATE THE ENCOUNTER", body: "Entry point · what the audience does first · spacing and route · label/score/caption · sound and light boundary · quiet alternative · ending · reset between groups." },
      { title: "AUDIENCE TEST + REVISION", body: "Record first notice, action, pause, interpretation, barrier, and question. Revise one artistic choice and one access/presentation choice. Test the changed part again." },
      { title: "INDIVIDUAL REFLECTION", body: "My intention was __. My contribution was __. My manageable creative risk was __; it taught me __. The technique that mattered was __ because __. The audience evidence showed __. I revised __. A source/context or deliberate limit was __. Next I would __." },
      { title: "SAFETY", body: "No lasers, strobe effects, hot bulbs, dangling lines in routes, blocked exits, dark-room travel, surprise sound, swinging objects, climbing, or unapproved cutting tools. Use stable tabletop versions whenever needed." },
    ],
  },
  "search-under-hood": {
    setupMinutes: 2,
    provided: ["Fictional search-results screen", "Three query challenges", "Source-trail prompts", "Result-quality checklist"],
    gather: ["Scrap paper or mini-whiteboards"],
    shortRoute: "Compare three results, improve one query, and explain why the first result is not automatically best.",
    cards: [
      { title: "VAGUE QUERY", body: "parks good or bad" },
      { title: "FOCUSED QUERY", body: "Fleetwood public park shade access plan site:surrey.ca" },
      { title: "RESULT CHECK", body: "Ad? · creator? · date? · source type? · evidence? · purpose?" },
      { title: "SOURCE TRAIL", body: "Repost → article → report or original data. Stop and record what changes at each step." },
    ],
  },
  "everyone-in-game": {
    setupMinutes: 5,
    provided: ["Exact no-elimination base game", "Observer tally", "Three tested rule remixes", "Access and safety choices"],
    gather: ["6–10 soft balls or beanbags", "8 cones", "Pinnies optional"],
    shortRoute: "Play 4 minutes, change one rule, replay 4 minutes, and compare participation evidence.",
    cards: [
      { title: "BASE GAME", body: "Teams score by completing five passes to five different teammates. No running with the ball. If it drops or leaves the area, the other team starts. Nobody is eliminated." },
      { title: "REMIX A", body: "A point counts only after every teammate has had a useful role in the play." },
      { title: "REMIX B", body: "Add safe end zones and a neutral connector who can help either team." },
      { title: "REMIX C", body: "Use two smaller games, a larger ball, walking pace, or a seated passing route." },
      { title: "OBSERVER TALLY", body: "Touches · choices · open-space moves · long waits · quick re-entry. Count team patterns, not named students." },
    ],
  },
  "career-constellation": {
    setupMinutes: 4,
    provided: ["Six ready-to-use fictional profile cards", "Role-category cards", "Skill and pathway prompts", "Constellation canvas directions"],
    gather: ["Large paper or board space", "Markers"],
    shortRoute: "Map one familiar project, add six hidden roles, connect three shared skills, and choose one next experience.",
    cards: [
      { title: "VISIBLE ROLES", body: "Who plans, builds, teaches, performs, repairs, serves, or leads?" },
      { title: "HIDDEN ROLES", body: "Who schedules, cleans, translates, checks safety, manages data, transports, cares, or maintains systems?" },
      { title: "PROFILE 1 · PARK TECHNICIAN", body: "Checks play equipment, repairs surfaces, records hazards, and works with planners. Skills: observe, measure, repair, communicate." },
      { title: "PROFILE 2 · COMMUNITY INTERPRETER", body: "Helps people understand one another across languages and settings. Skills: listen, explain, protect meaning, build trust." },
      { title: "PROFILE 3 · ACCESSIBILITY TESTER", body: "Tries routes, signs, websites, or tools and reports barriers. Skills: notice, test, document, recommend changes." },
      { title: "PROFILE 4 · WATER OPERATOR", body: "Monitors treatment equipment, reads data, collects samples, and follows safety rules. Skills: measure, troubleshoot, record, respond." },
      { title: "PROFILE 5 · DIGITAL STORY PRODUCER", body: "Plans a message, records image and sound, edits for an audience, and credits sources. Skills: create, organize, revise, collaborate." },
      { title: "PROFILE 6 · EVENT CARE LEAD", body: "Plans food, quiet space, cleanup, volunteer roles, and help routes. Skills: include, schedule, adapt, care, solve problems." },
      { title: "SKILLS", body: "Communicate · organize · create · measure · troubleshoot · include · research · adapt" },
      { title: "PATHWAYS", body: "School learning · family/community knowledge · mentorship · volunteering · training · practice · work experience" },
      { title: "NEXT EXPERIENCE", body: "One small thing I could try is __. My first step is __. A person or place that could help is __." },
    ],
  },
};

export const experienceMedia: Record<string, ExperienceMedia[]> = {
  "packet-rescue": [
    { type: "image", label: "View 1 · Break one message into six packets", source: "Generated fictional tabletop model", localSrc: "/images/visual-review/packet-rescue-tabletop-v2.webp", purpose: "Make splitting, numbering, and rebuilding visible before introducing network labels.", studentTask: "Find the complete picture, six numbered pieces, sender, and receiver. Predict what the receiver must check.", fallback: "Cut any simple picture into six pieces and number them 1–6." },
    { type: "image", label: "View 3 · Become the network", source: "Generated fictional classroom role-play", localSrc: "/images/visual-review/packet-rescue-human-network-v1.webp", purpose: "Preview the physical roles and two-route challenge before students move.", studentTask: "Point to the sender, routers, packets, two routes, receiver, and observer. Predict what happens if one route closes.", fallback: "Place role cards and two tape routes on the floor before students enter them." },
    { type: "article", label: "What is a packet?", source: "Cloudflare Learning Center", url: "https://www.cloudflare.com/learning/network-layer/what-is-a-packet/", purpose: "Give the teacher an accurate optional explanation of packets, routing, and reassembly after the supplied concrete model.", studentTask: "With your teacher, compare the article's index-card example with our six-piece picture model. Name one match and one simplification.", fallback: "Use the supplied network diagram, six-piece picture, and role cards; the activity does not depend on the link." },
  ],
  "ordinary-object-story": [
    { type: "image", label: "Set A · Key, ticket, spoon, lace, wheel, and photograph", source: "Generated classroom observation scene", localSrc: "/images/ordinary-object-storytelling-still-life.png", purpose: "Offer six low-risk objects with visible clues for noticing and invention.", studentTask: "Choose one object with a partner and point to five visible details before inventing.", fallback: "Use any six ordinary classroom objects placed on one table." },
    { type: "image", label: "Set B · The scratched blue arcade token", source: "Generated fictional object study", localSrc: "/images/object-story-arcade-token-v1.webp", purpose: "Match the model story exactly so students can trace how the silver star, number 8, and scratch become story clues.", studentTask: "Find the star, number, scratch, colour, and worn edge. Decide which clue could create the turning point.", fallback: "Sketch a blue token with a silver star, number 8, one deep scratch, and a worn edge." },
    { type: "image", label: "Set C · Mitten, transit slip, striped stone, bell, pencil, and seed packet", source: "Generated fictional object study", localSrc: "/images/object-story-table-set-c-v1.webp", purpose: "Give pairs a second collection with different textures, marks, and possible uses.", studentTask: "Choose one object and separate five visible clues from three possible story ideas.", fallback: "Draw six simple object silhouettes and add one visible mark to each." },
    { type: "image", label: "Set D · Map, wooden animal, button, ribbon, flashlight, and stamped envelope", source: "Generated fictional object study", localSrc: "/images/object-story-table-set-d-v1.webp", purpose: "Support a second oral round so partners can swap roles with fresh evidence.", studentTask: "Use a different object for the second telling. Build a new beginning, turn, and ending from its clues.", fallback: "Swap in six different safe classroom or household objects." },
    { type: "image", label: "Set E · Discovery drawer", source: "Generated fictional object study", localSrc: "/images/visual-review/object-gallery-discovery-drawer-v1.webp", purpose: "Offer a dense drawer of small clues for careful observation and different story choices.", studentTask: "Choose two objects that might belong in the same story. Point to the visible clue that could connect them.", fallback: "Place six safe objects in a shallow box or desk drawer." },
    { type: "image", label: "Set F · Lost-and-found shelf", source: "Generated fictional object study", localSrc: "/images/visual-review/object-gallery-lost-found-v1.webp", purpose: "Invite stories about ownership, misunderstanding, return, and belonging without requiring personal disclosure.", studentTask: "Choose one object. Invent who notices it, what changes, and how the object matters again at the ending.", fallback: "Arrange clean classroom lost-and-found items on one shelf." },
    { type: "image", label: "Set G · Repair workbench", source: "Generated fictional object study", localSrc: "/images/visual-review/object-gallery-workbench-v1.webp", purpose: "Add making and repair as possible story actions rather than relying only on mysterious keepsakes.", studentTask: "Choose one worn or repairable object. Use a visible mark to create the story's turning point.", fallback: "Sketch a workbench with a broken toy, loose wheel, thread, tape, and small tools." },
  ],
  "three-voices": [{ type: "image", label: "One shared moment, three sightlines", source: "Generated fictional evidence scene", localSrc: "/images/three-voices-shared-moment-v1.webp", purpose: "Give every viewpoint the same fictional scene so students can separate visible facts, reasonable inferences, and unknowns before retelling it.", studentTask: "Study all three sightlines. Name one visible fact, one possible inference, and one detail that remains unknown before choosing a narrator.", fallback: "Use the supplied shared-event description and three sightline cards." }],
  "edit-room": [{ type: "image", label: "The full courtyard before the crop", source: "Generated fictional school event", localSrc: "/images/edit-room-courtyard-context-v2.webp", purpose: "Give every crop the same rich source image so students can see exactly what framing keeps and removes.", studentTask: "Point to visible facts in the wide view, then compare them with the left and centre crops in the on-screen Edit Room.", fallback: "Use the supplied written scene and four-frame sequence cards." }],
  "bloxels-story-blueprint": [
    { type: "image", label: "A world with possible story beats", source: "Original generated pixel-art planning scene", localSrc: "/images/bloxels-story-world-v1.png", purpose: "Give the class a shared, copyright-safe world for noticing how setting, route, problem, turn, and ending might connect.", studentTask: "Point to a possible beginning, problem, turning point, and ending before inventing your own story.", fallback: "Use the supplied six-part paper level map." },
    { type: "article", label: "Storytelling in Games", source: "Bloxels", url: "https://www.bloxels.com/education/storytelling-in-games-part-one", purpose: "Use a teacher-selected section to discuss how a player experiences story through actions and choices.", studentTask: "Name one way a game story differs from a story that is only read or watched.", fallback: "Compare the projectable image with the paper story-route prompts." },
  ],
  "bloxels-game-studio": [
    { type: "image", label: "Plan a playable route", source: "Original generated pixel-art planning scene", localSrc: "/images/bloxels-story-world-v1.png", purpose: "Make the relationship among setting, route, story information, challenge, and destination visible before students build.", studentTask: "Trace one possible route and explain where the player needs story information.", fallback: "Use the supplied paper level-map template." },
    { type: "website", label: "Bloxels Education", source: "Bloxels", url: "https://www.bloxels.com/education", purpose: "Confirm current EDU features, private class sharing, and educator resources.", studentTask: "Open only with your teacher; use the approved class route.", fallback: "Complete the equivalent paper interactive-story project." },
    { type: "interactive", label: "Bloxels web app", source: "Bloxels", url: "https://play.bloxels.com/", purpose: "Use the school-managed web route after the story and paper plan are ready.", studentTask: "Build the smallest complete version before adding decoration.", fallback: "Use pixel-grid paper and route cards with the same playtest and revision requirements." },
  ],
  "place-soundwalk": [{ type: "activity", label: "Make a 20-second sound map", source: "Student-created local observation", purpose: "Treat listening as a way of gathering precise place evidence.", studentTask: "Recreate three sound layers with voices, body percussion, or classroom objects and name where each came from.", fallback: "Write sound words and mark their distance on paper." }],
  "four-arts-languages": [
    { type: "website", label: "SKWA WACH :: STURGEON", source: "Roxanne Charles and Easton Arnouse · Semiahmoo First Nation · installed 2025 · City of Surrey Public Art", url: "https://www.surrey.ca/arts-culture/public-art/permanent-public-art-collection/skwa-wach-sturgeon", purpose: "Begin visual-art study with an exact local contemporary public artwork, artist context, place, and ecosystem relationship.", studentTask: "Record artist, title, context, one exact visual choice, and one question. If a requested detail such as material is absent, write ‘not stated.’ Respond through your own technique study; do not copy the work or a cultural style.", fallback: "Project the live official page when available or read the supplied text-only credited artist/context capsule, then lead the same slow-look prompts. Do not copy or rehost an image without permission." },
    { type: "video", label: "Great Canadian Orchestra Field Trip", source: "National Arts Centre · Arts Alive", url: "https://nac-cna.ca/en/orchestrafieldtrip", duration: "Teacher registers in advance and records one chosen episode + 3–5 minute segment", purpose: "Use one exact registered performance to hear a change in timbre, dynamics, texture, rhythm, or form. The official on-demand series is free but currently asks schools to register.", studentTask: "Listen once for the whole effect, then again for one named musical change. Mark the exact moment.", fallback: "Use the supplied listening card while the teacher performs or describes a four-layer Classroom OS sound model with voice, body percussion, and objects." },
    { type: "video", label: "Foundational Elements of Dance: Aspects of Space", source: "Allison Carrier · National Arts Centre", url: "https://nac-cna.ca/en/video/map-foundational-elements-of-dance-2-space", duration: "13:09 · teacher previews and selects one short comparison", purpose: "Model pathways, direction, level, size, and relationship with an exact artist-led source before students compose.", studentTask: "Freeze two moments and record how the use of space changes. The standing, seated, hand-only, or prop adaptation is a Classroom OS route.", fallback: "Teacher demonstrates the supplied eight-count phrase standing, seated, hand-only, or with a paper prop; students compare two changes using the same notice card." },
    { type: "video", label: "Theatre Works: Kevin Loring", source: "Kevin Loring · Nlaka'pamux (Lytton First Nation) · National Arts Centre", url: "https://nac-cna.ca/en/video/theatre-works-kevin-loring", duration: "2:55 · captions available", purpose: "Show how an artistic director helps shape story, relationships, purpose, and audience experience—not only dialogue.", studentTask: "Record the artist and role, then name one decision a director can guide in focus, place, tension, mood, relationship, light, sound, or transition.", fallback: "Read the credited Kevin Loring role/context capsule and use the supplied six-frame tableau model before students compose." },
    { type: "image", label: "After-rain courtyard practice scene", source: "Original generated Classroom OS observation scene", localSrc: "/images/four-arts-rain-courtyard-v1.webp", purpose: "Provide one copyright-safe shared scene for the two-form remix after all four foundation studies are complete.", studentTask: "Choose one visible detail and use two completed Arts studies to guide the audience toward it.", fallback: "Arrange six ordinary classroom objects after an imaginary gust of wind and make a direct-observation thumbnail." },
  ],
  "map-what-maps-miss": [
    { type: "website", label: "SKWA WACH :: STURGEON", source: "Roxanne Charles and Easton Arnouse · Semiahmoo First Nation · installed 2025 · City of Surrey Public Art", url: "https://www.surrey.ca/arts-culture/public-art/permanent-public-art-collection/skwa-wach-sturgeon", purpose: "Study an exact contemporary local public artwork in relation to place, family collaboration, and the river ecosystem.", studentTask: "Complete the artist/context card and slow look; record only details the exact page supplies, write ‘not stated’ for missing details such as material, and do not copy or generalize cultural imagery.", fallback: "Project the live official page when available or use the teacher-read text-only official-source capsule with the complete slow-look and context card. Do not copy or rehost an image without permission." },
    { type: "map", label: "First Peoples' Map of B.C.", source: "First Peoples' Cultural Council", url: "https://maps.fpcc.ca/", purpose: "Keep living languages, communities, and place specificity visible while distinguishing a contextual map from an artwork.", studentTask: "Notice what the map names that a standard street map may not, then keep that contextual evidence separate from artistic interpretation.", fallback: "Use the supplied attributed map/context card; return to the live map with the teacher when available." },
    { type: "article", label: "Sharing Perspectives · exact teacher-selected artist page", source: "Surrey Art Gallery · Grades 4–12 teacher guide", url: "https://www.surrey.ca/files/Teachers%20Guide_4-12_Indigenous%20Contemporary%20Art%20Workshop_Surrey%20Art%20Gallerly_online.pdf", purpose: "Use one exact page to supply credited artist context, observation routines, differentiation, and material processes from a local gallery source. Keep the title/date shown on that exact source; do not merge conflicting metadata from another page.", studentTask: "Work only with the assigned artist and page. Record artist, work, context, an observed technique, and a question before making your own response.", fallback: "Teacher reads a text-only credited context capsule; students complete the same technique study without copying or reproducing the work." },
  ],
  "same-facts-frame": [
    { type: "video", label: "Rhythms of Resilience · Music Alive Song Activity", source: "Sherryl Sewepagaham · Cree-Dene songwriter and educator · National Arts Centre", url: "https://nac-cna.ca/en/artsalive/resource/all-my-relations-rhythmic-fun-with-music-alive/module/36164", duration: "Teacher previews the Grade 4–6 module and selects one short activity/performance segment", purpose: "Meet rhythm, voice, relationship, and artist context through an exact artist-led Canadian music module.", studentTask: "Credit the artist and source. Listen for one exact use of beat, rhythm, silence, timbre, dynamics, texture, form, or interaction and mark the moment.", fallback: "Teacher reads the credited artist/context capsule and performs the supplied four-layer Classroom OS rhythm model; students use the same listening-evidence card." },
    { type: "video", label: "Autorickshaw · Raga, Tala, and Solkattu module", source: "Autorickshaw · resource by Suba Sankaran · National Arts Centre Arts Alive", url: "https://nac-cna.ca/en/artsalive/resource/autorickshaw/module/39055", duration: "Teacher previews the exact concert/resource module and records one chosen segment", purpose: "Encounter raga, tala, and solkattu through an artist-led resource and widen the class listening beyond one musical tradition.", studentTask: "Credit the artists and source. Notice one exact melodic or rhythmic move the resource names; compare elements without ranking cultures or copying a tradition out of context.", fallback: "Teacher reads the credited source capsule and uses the supplied rhythm/notation mini-labs; reschedule the artist encounter rather than presenting the fallback as Carnatic music instruction." },
    { type: "video", label: "Great Canadian Orchestra Field Trip", source: "National Arts Centre · Arts Alive", url: "https://nac-cna.ca/en/orchestrafieldtrip", duration: "Optional registered 3–5 minute segment", purpose: "Compare how a different ensemble organizes timbre, dynamics, texture, rhythm, and form. The official on-demand series is free but currently asks schools to register.", studentTask: "Compare one musical element across the two sources; do not rank cultures, performers, or genres.", fallback: "Compare two teacher-performed versions of the supplied score using different sound sources." },
  ],
  "rights-in-thirty": [
    { type: "video", label: "The power of storytelling in theatre: The Artistic Director's role", source: "Kevin Loring · Nlaka'pamux (Lytton First Nation) · National Arts Centre", url: "https://nac-cna.ca/en/video/theatre-works-kevin-loring", duration: "2:55 · captions available", purpose: "Meet one Canadian theatre artist and notice how an artistic director shapes purpose, story, relationships, and audience experience.", studentTask: "Record the artist, role, and source. Name one artistic decision the role guides, then connect it to a focus, place, tension, mood, or relationship choice in your fictional scene.", fallback: "Read the credited Kevin Loring role/context capsule, then use the supplied before–transition–after model and teacher narration." },
    { type: "video", label: "Foundational Elements of Dance: Types of Motion", source: "Allison Carrier · National Arts Centre", url: "https://nac-cna.ca/en/video/map-foundational-elements-of-dance-4-motion", duration: "9:45 · teacher previews and selects two comparison moments", purpose: "Give students an exact artist-led motion example they can pause before notating a safe transition.", studentTask: "Freeze two moments. Record what changed in motion, shape, space, time, pathway, level, direction, weight, or relationship. Adaptation routes are supplied by Classroom OS.", fallback: "Teacher demonstrates the supplied transition twice—standing, seated, hand-only, or tabletop—and students complete the same comparison." },
  ],
  "audience-remix": [
    { type: "website", label: "A Slow Look at Petroushka · Elementary", source: "National Gallery of Canada · Paraskeva Clark, Petroushka (1937)", url: "https://www.gallery.ca/learn/for-schools/resources-for-teachers", purpose: "Use the named Elementary slow-look routine only to gather precise noticing evidence before the Classroom OS models teach curation.", studentTask: "Follow the teacher-opened Petroushka slow look and record what you notice first plus the exact visual evidence. Then use the original Night Garden models—not the Gallery source—to study entry, spacing, sequence, and audience path.", fallback: "Use the supplied Night Garden mini-artifact and crowded/revised curator models for both the looking warm-up and full curation lesson." },
  ],
  "cosmic-scale-gallery": [
    { type: "website", label: "Machine for Singing · official context", source: "Ian Johnston · Machine for Singing (2007–09) · Surrey Art Gallery exhibition, 2010", url: "https://www.surrey.ca/arts-culture/surrey-art-gallery/exhibitions/ian-johnston-machine-singing", purpose: "Establish exact artist, dates, place, material, visitor activation, and environmental/consumption context before viewing the companion video.", studentTask: "Record Ian Johnston, title, work dates, 2010 Surrey exhibition context, materials, visitor action, and one supported question about objects or consumption.", fallback: "Teacher reads the text-only credited context capsule; do not copy or rehost the page image." },
    { type: "video", label: "Machine for Singing · artist video", source: "Ian Johnston · Surrey Art Gallery official video", url: "https://www.youtube.com/watch?v=EQY6ciBfPZY", duration: "Teacher previews and records one exact short segment", purpose: "Study a local bridge among sculpture, sound, participation, material, space, and audience action.", studentTask: "Record one exact relationship among object, sound, space, and audience, then connect it to the official context page. Do not download or repost the video.", fallback: "Use the text-only official context capsule plus the supplied paper kinetic-form and graphic-score trials; do not copy the artwork." },
    { type: "video", label: "Foundational Elements of Dance: Understanding Time", source: "Allison Carrier · National Arts Centre", url: "https://nac-cna.ca/en/video/map-foundational-elements-of-dance-3-time", duration: "8:02 · teacher previews and selects two comparison moments", purpose: "Support the movement/spatial-score trial with an exact artist-led time example.", studentTask: "Trace one change in time, body, space, dynamics, or relationship and translate the element—not the choreography—into your own eight-count score. Adaptation routes are supplied by Classroom OS.", fallback: "Teacher demonstrates the supplied movement-score card standing, seated, hand-only, or with a paper prop." },
    { type: "article", label: "Circulation · official public-art handout", source: "Pierre Sasseville and Jean-François Cooke · Grandview Heights Aquatic Centre · City of Surrey Public Art", url: "https://www.surrey.ca/sites/default/files/media/documents/Circulation.pdf", purpose: "Connect public sculpture, humour, creatures, nature, material, and local context through an official credited source; note that the City listing gives 2015 while the handout says installed 2016.", studentTask: "Record the artists and location, distinguish work year from installation year when the source does, and note one material or compositional choice plus its possible effect.", fallback: "Teacher reads the text-only credited source capsule; students complete the same context/technique record without reproducing the handout image." },
  ],
  "edit-room-source": [{ type: "website", label: "Canadian youth news source collection", source: "CBC Kids News", url: "https://www.cbc.ca/kidsnews/", purpose: "Choose one exact article or video, then study how it combines image, order, caption, voice, and context.", studentTask: "Name one editing choice that helps the audience understand.", fallback: "Use the generated scene and supplied storyboard only." }],
  "graph-story-lab": [{ type: "interactive", label: "Exact graphing and virtual tools", source: "Mathigon Polypad", url: "https://mathigon.org/polypad", purpose: "Offer a teacher-controlled shared-screen route for graphing and scale comparison.", studentTask: "Direct the teacher as the class rebuilds one data set and tests a second useful scale on the projector.", fallback: "Use grid paper and the supplied graph checklist." }],
  "search-under-hood": [{ type: "article", label: "How search and digital media shape choices", source: "MediaSmarts", url: "https://mediasmarts.ca/teacher-resources/digital-media-literacy-framework/digital-media-literacy-framework-grades-4-6", purpose: "Ground the search audit in Canadian digital-literacy guidance.", studentTask: "Use the teacher-selected excerpt on the shared screen to add one result-check question aloud, on the board, or on paper.", fallback: "Use the fully fictional search-results screen and checklist." }],
  "everyone-in-game": [
    { type: "image", label: "Who can enter, contribute, adjust, and rejoin?", source: "Generated fictional game scene", localSrc: "/images/everyone-in-game-field-v1.webp", purpose: "Give the whole class one rich scene for noticing movement choices, space, roles, re-entry, and barriers before changing a rule.", studentTask: "Point to two different ways a student contributes, then name one rule or space change that could open the play further.", fallback: "Use the exact top-down court diagram and act out one freeze-frame with volunteers." },
    { type: "website", label: "Canadian physical-education teaching tools", source: "PHE Canada", url: "https://phecanada.ca/teaching-tools", purpose: "Give the teacher optional movement and inclusion extensions.", studentTask: "Your teacher may select one safe movement cue or game variation.", fallback: "Use the supplied base game and three remixes." },
  ],
  "career-constellation": [{ type: "website", label: "Explore varied B.C. work and pathways", source: "WorkBC", url: "https://www.workbc.ca/plan-career/explore-careers", purpose: "Replace stereotypes with real, varied profiles and more than one pathway.", studentTask: "Study one teacher-projected profile and add a hidden role, skill, or pathway to the class constellation.", fallback: "Use the supplied role, skill, and pathway cards." }],
};

export function mediaFor(experienceId: string): ExperienceMedia[] {
  if (experienceId === "edit-room") return [...experienceMedia[experienceId], ...experienceMedia["edit-room-source"]];
  return experienceMedia[experienceId] ?? [];
}

export function spacesBookendsFor(arc: ProgramArc, experiences: ProgramExperience[]) {
  if (arc.id === "adst-game") return {
    entry: {
      title: "Optional entry snapshot",
      prompt: "What makes a game easy to understand and a story worth following? Keep this local or add it to the beginning of the same Bloxels post.",
      choices: ["Annotated image or sketch", "20–30 second audio", "Quick game/story T-chart"],
    },
    exit: {
      title: "Required combined project evidence",
      prompt: "Use one Bloxels post: show the game, one story change, one game or access change, the playtest evidence, and your individual contribution.",
      choices: ["Teacher-recorded class showcase clip", "Teacher-added game link", "Photo of the equivalent paper game", "Audio, written, or video reflection"],
    },
  };
  const finalExperience = experiences.findLast(item => arc.experienceIds.includes(item.id) && (spacesPolicyForActivity(item.id)?.decision ?? item.spacesUse) !== "none")
    ?? experiences.findLast(item => arc.experienceIds.includes(item.id));
  const finalPolicy = finalExperience ? spacesPolicyForActivity(finalExperience.id) : null;
  const exitPrompt = finalExperience
    ? finalPolicy?.decision === "required"
      ? `${finalPolicy.teacherPrompt} Explain what changed in your thinking and point to the evidence.`
      : finalPolicy?.decision === "reuse"
        ? `${finalPolicy.teacherPrompt} Choose the part of “${finalExperience.title}” that best supports that shared artifact.`
        : `Choose useful evidence from “${finalExperience.title}.” Explain what changed in your thinking and point to the evidence.`
    : "Choose one piece that shows how your thinking changed.";
  return {
    entry: {
      title: "Optional entry snapshot",
      prompt: `Before this arc, respond to: ${arc.question}`,
      choices: ["20–30 second audio", "One image or first model with a caption", "Two or three sentences", "A quick diagram plus one wonder"],
    },
    exit: {
      title: "Possible end-of-arc evidence",
      prompt: exitPrompt,
      choices: ["Photo of a model or creation", "Short video demonstration", "Audio explanation", "Written or visual reflection"],
    },
  };
}
