/** Original review notes; source-file permissions are unchanged. Reviewed 13 September 2026. */
export const savedResourceIndex = [
  {
    "id": "1-lRxGkZYNJavqSVJ-03uXCr9JMErDFBC",
    "title": "Friends: Being Different",
    "originalTitle": "FriendsBeingDifferentGrade6-1.pdf",
    "url": "https://drive.google.com/file/d/1-lRxGkZYNJavqSVJ-03uXCr9JMErDFBC/view?usp=drivesdk",
    "category": "Language Arts",
    "fit": "Adapt",
    "use": "Short reading, vocabulary and comparison work. Use as supported reading or a belonging discussion.",
    "note": "The passage mentions MSN; update that reference. Let students discuss fictional preferences instead of disclosing personal differences.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1O90g2CO2vrF-Lg5RJqAq-QWHR4OUQ579",
    "title": "Independent Study / Genius Hour",
    "originalTitle": "IndependentStudyGeniusHourPassionProjects-1.pdf",
    "url": "https://drive.google.com/file/d/1O90g2CO2vrF-Lg5RJqAq-QWHR4OUQ579/view?usp=drivesdk",
    "category": "Inquiry",
    "fit": "Use selectively",
    "use": "A useful passion-and-problem brainstorming framework; it explicitly leaves the final project open.",
    "note": "Add a manageable question, two classroom sources, a short conference and one finished product. The packet alone is not a complete independent unit.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1PPRVDqb4B2t7vXxS01hbjAB9F460L6Mc",
    "title": "Classroom and outdoor scavenger hunts",
    "originalTitle": "ScavengerHuntsaroundtheschoolandinnatureprintableClassroomOutdoor-2.pdf",
    "url": "https://drive.google.com/file/d/1PPRVDqb4B2t7vXxS01hbjAB9F460L6Mc/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Use selectively",
    "use": "Choose a named hunt: contents list math p. 12, classroom p. 15, nature p. 19 and imagination p. 20.",
    "note": "Select for available materials and access. Internet, kitchen and winter hunts have different requirements; do not present every hunt as a ready classroom activity.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1BwoYJnNp7Zh5Pp2uJxyyj5Zydq1vD4_E",
    "title": "Inquiry and Research: student-choice unit",
    "originalTitle": "InquiryandResearchAStudentChoiceGuidedUnitProjectBasedLearning-1.pdf",
    "url": "https://drive.google.com/file/d/1BwoYJnNp7Zh5Pp2uJxyyj5Zydq1vD4_E/view?usp=drivesdk",
    "category": "Inquiry",
    "fit": "Use selectively",
    "use": "Use question generation, first-search notes, sorting and reflection as a flexible research sequence.",
    "note": "Model a focused question and source note first. Provide printed sources; choose a few useful organizers rather than assigning the full packet.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1G95L0TsVij042NWi98J3FFfSdhNdJdY6",
    "title": "Brain breaks and review games",
    "originalTitle": "BRAINBREAKSANDREVIEWGAMESEnergizeLearningEngageStudentsAnySubject-1.pdf",
    "url": "https://drive.google.com/file/d/1G95L0TsVij042NWi98J3FFfSdhNdJdY6/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Use selectively",
    "use": "A large collection of greetings, movement and review structures. Keep a small rotation within reach for transitions.",
    "note": "Choose the actual card and prepare its materials. Offer seated or non-performing roles; a review game still needs the teacher’s subject questions.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1mvUZDM3cjihKJPD8BDsTq9njOejyX81P",
    "title": "African and Asian elephants: compare and contrast",
    "originalTitle": "CompareandContrastWritingAfricanandAsianElephants-1.pdf",
    "url": "https://drive.google.com/file/d/1mvUZDM3cjihKJPD8BDsTq9njOejyX81P/view?usp=drivesdk",
    "category": "Language Arts",
    "fit": "Use selectively",
    "use": "A substantial reading-to-writing sequence with a source passage, organizers and comprehension work.",
    "note": "Select one shared reading and a comparison paragraph. Model a text-supported similarity and difference; verify factual claims before presenting them as current science.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1_hefXdJnOjD6g6fVgBoq1dMCSQ6CbhTt",
    "title": "Design your own amusement park map",
    "originalTitle": "MapSkillsMappingDesignYourOwnAmusementPark-1.pdf",
    "url": "https://drive.google.com/file/d/1_hefXdJnOjD6g6fVgBoq1dMCSQ6CbhTt/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Use selectively",
    "use": "An authentic map-design context that can support a geometry application or Social Studies map conventions.",
    "note": "Assess a key, orientation and clear placement. Add explicit dimensions or coordinate constraints for a math lesson; artistic polish alone is not mathematical evidence.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1LOwGOPqRnIA4XHhkFENaUHsAd-H1hkuD",
    "title": "Probability math stations",
    "originalTitle": "ProbabilityMathStationsMathCenters-1.pdf",
    "url": "https://drive.google.com/file/d/1LOwGOPqRnIA4XHhkFENaUHsAd-H1hkuD/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Adapt",
    "use": "Begin with stations A, B, C or E: ordinary die, replacement colour draw, coin or letter draw. Compare predictions with pooled trials.",
    "note": "The cuboctahedron has differently shaped faces: equal likelihood is not established by counting faces. The rubric has overlapping score ranges and inconsistent station counts. Use revised criteria and discuss sample variation.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1ST2ROLbxc0zB8S5OQzXgVbZQZ6rDR-Qo",
    "title": "BC Core Competencies: activities and self-assessment K–7",
    "originalTitle": "BCCoreCompetenciesActivitiesSelfAssessmentK7-1.pdf",
    "url": "https://drive.google.com/file/d/1ST2ROLbxc0zB8S5OQzXgVbZQZ6rDR-Qo/view?usp=drivesdk",
    "category": "Assessment",
    "fit": "Preview needed",
    "use": "The contents provide a large bank of reflection activities across grades. Select an intermediate prompt tied to work students have actually done.",
    "note": "This very large illustrated file was screened through extracted text and contents, not visually reviewed page by page. Avoid duplicating paper reflection and SpacesEDU uploads.",
    "review": "Limited extraction; original-page review needed"
  },
  {
    "id": "1Zez1_R4YWNerHIpIduo5AWfB5dz58Hzo",
    "title": "Spring Break Bingo Challenge",
    "originalTitle": "SpringBreakMixedReviewBingoChallenge-1.pdf",
    "url": "https://drive.google.com/file/d/1Zez1_R4YWNerHIpIduo5AWfB5dz58Hzo/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Adapt",
    "use": "Some choices can become optional classroom or holiday enrichment.",
    "note": "Remove prize points, required family signatures and assumptions about devices, food, family access or physical ability. Several math choices are outside the immediate Grade 6 goal; select deliberately.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1ovIR1OJxEl8JGqyD6l_T4B1lod2gOs-u",
    "title": "Patterns in Graphing: differentiated worksheets",
    "originalTitle": "CoordinateGraphingPatternsWorksheets5thGradeMathStandards-1.pdf",
    "url": "https://drive.google.com/file/d/1ovIR1OJxEl8JGqyD6l_T4B1lod2gOs-u/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Use selectively",
    "use": "Contents identify multiple-choice practice on pp. 7–8, open response on pp. 9–10 and keys on pp. 16–20.",
    "note": "A/B and C/D repeat the same questions with different response formats. Choose one version. US Grade 5 labels do not establish BC alignment.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1FycjXnjFU-CHWF5Egnr9H2nEOa8ZrFDe",
    "title": "Rolling with Patterns: dice centres",
    "originalTitle": "NumberPatternsandPatterningMathCentersandWorksheets-1.pdf",
    "url": "https://drive.google.com/file/d/1FycjXnjFU-CHWF5Egnr9H2nEOa8ZrFDe/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Use selectively",
    "use": "Use a station after modelling its rule. Includes addition, subtraction, multiplication, charts, calendars and input/output practice.",
    "note": "Distinguish constant additive change from multiplicative growth. Ask for an explanation or table, not only completed number sequences.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1EAk7OS4fLKoumvHXGcYOwbj-6lr7LqKo",
    "title": "Grade 6 Patterning Activity Packet",
    "originalTitle": "Grade6PatterningActivityPacket-1.pdf",
    "url": "https://drive.google.com/file/d/1EAk7OS4fLKoumvHXGcYOwbj-6lr7LqKo/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Use selectively",
    "use": "A useful teaching sequence: contents show pre-assessment pp. 6–7, lessons pp. 13–35, partner work pp. 46–49 and keys pp. 52–69.",
    "note": "Ontario 2015 alignment needs selection for BC. Start with the diagnostic, then choose a lesson about rules, tables or graphs; do not assign all 70 pages.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1ZjTSQS0lvyK0F_RjfcV3mOkZxNXvZwiH",
    "title": "Poetry forms, templates and choice projects",
    "originalTitle": "PoetryUnit33PagesofPoemTemplatesSpringPoetryWritingMonthofApril-2.pdf",
    "url": "https://drive.google.com/file/d/1ZjTSQS0lvyK0F_RjfcV3mOkZxNXvZwiH/view?usp=drivesdk",
    "category": "Language Arts",
    "fit": "Use selectively",
    "use": "Includes explanations, examples, guided practice and independent poem forms. Choose a form and read its model before writing.",
    "note": "Select a small sequence with student choice and revision. A completed template is a draft, not the whole writing process; the bundle includes more than the title’s 33 pages.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1FD-YqVjcH9hLALXB4xHeY__tVMlcaVz_",
    "title": "Factors and multiples: guided doodle notes",
    "originalTitle": "FactorsMultiplesVisualInteractiveGuidedMathDoodleNoteswithLCMGCF-1.pdf",
    "url": "https://drive.google.com/file/d/1FD-YqVjcH9hLALXB4xHeY__tVMlcaVz_/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Use selectively",
    "use": "Use as guided vocabulary, factor/multiple comparison and GCF/LCM practice.",
    "note": "Show a factor-pair example before filling notes. Connect GCF to equal packs and LCM to repeating events. Graphic layouts were not visually verified in this review.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1z6XF4p5FhRtW6q82c5RIa1QJXK52hJYR",
    "title": "Van Gogh: sunflowers and Starry Night art",
    "originalTitle": "VanGoghArtProjectSpringSunflowersStarryNightPaintingCollage-1.pdf",
    "url": "https://drive.google.com/file/d/1z6XF4p5FhRtW6q82c5RIa1QJXK52hJYR/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Use selectively",
    "use": "Use the artist images and drawing process as a starting point for choices about line, colour and composition.",
    "note": "Preview the actual reference image and art-history wording. Assess deliberate choices and revision rather than resemblance to the sample.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1-px6goAtmcMhdKcXfz0-RMUmUdci2q-D",
    "title": "Parts of speech: differentiated colouring",
    "originalTitle": "PARTSOFSPEECHELAColoringPagesALLYEARBacktoSchoolActivityMorningWork-1.pdf",
    "url": "https://drive.google.com/file/d/1-px6goAtmcMhdKcXfz0-RMUmUdci2q-D/view?usp=drivesdk",
    "category": "Language Arts",
    "fit": "Use selectively",
    "use": "A large differentiated bank. Contents separate starter/basic, beginner, intermediate and advanced sheets with answer sections.",
    "note": "Select a page from observed grammar needs and check its key. Ask students to justify words in context; colouring accuracy alone is weak evidence of grammar understanding.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1Nv7unvkiQogzX6cfAydY8QmzL0injXPh",
    "title": "Save the Sea Turtles: Earth Day art",
    "originalTitle": "EarthDayColoringPagesSavetheSeaTurtlesEarthDayArtActivityFunCraft-1.pdf",
    "url": "https://drive.google.com/file/d/1Nv7unvkiQogzX6cfAydY8QmzL0injXPh/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Use selectively",
    "use": "Includes turtle templates, mark-making, pattern and display ideas. Use as an art activity with an optional environmental reading.",
    "note": "It does not supply a complete scientific investigation. Choose materials and template complexity; support cutting or offer a flat drawing version.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1GhUsgT9sTL4V5jX7TBI2YgZePQbU4OUa",
    "title": "Poppy lantern craft",
    "originalTitle": "PoppyCraftRemembranceDayVeteransDayAnzacDayPeace-1.pdf",
    "url": "https://drive.google.com/file/d/1GhUsgT9sTL4V5jX7TBI2YgZePQbU4OUa/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Use selectively",
    "use": "Mix-and-match lantern, trim and writing pieces allow a manageable seasonal making task.",
    "note": "Select and print the pieces before class. Connect to an appropriate remembrance source and explain the symbols; making a lantern is not itself historical inquiry.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1PJBv633Qxza216YyPeLvB6ARWiXnc9Tc",
    "title": "Lunar New Year 2026 activities",
    "originalTitle": "ChineseNewYear2026LunarNewYear-1.pdf",
    "url": "https://drive.google.com/file/d/1PJBv633Qxza216YyPeLvB6ARWiXnc9Tc/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Adapt",
    "use": "A seasonal art and information resource that needs deliberate selection for the community and year.",
    "note": "Check the printed year before reusing in 2027. Use specific cultural attribution and avoid presenting different Lunar New Year traditions as interchangeable.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1ExwwlwJ5ei2Jr8N3aVaSke9J1Dr1kX6R",
    "title": "Dragon Eye drawing lesson",
    "originalTitle": "DragonEyeArtLessonNoPrepDrawingProjectStepbyStepArtActivity-1.pdf",
    "url": "https://drive.google.com/file/d/1ExwwlwJ5ei2Jr8N3aVaSke9J1Dr1kX6R/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Use selectively",
    "use": "Observation and drawing steps precede examples. Use line weight, texture and colour gradients as visible success criteria.",
    "note": "Let students vary the design. Plan the drawing media and a short reflection on one intentional choice.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1RkP42lS8HdJ-uij4F5a7cwd-c1Qf37_k",
    "title": "Moose Hide Campaign: Moose is Medicine",
    "originalTitle": "TheMooseHideCampaignasmedicineanIndigenousinnovationforALL-1.pdf",
    "url": "https://drive.google.com/file/d/1RkP42lS8HdJ-uij4F5a7cwd-c1Qf37_k/view?usp=drivesdk",
    "category": "Social Studies",
    "fit": "Use selectively",
    "use": "Keep the Campaign’s own voice and named cultural context when discussing the pin, gifts and peaceful action.",
    "note": "Preview the linked video and use the campaign meaning of medicine. Offer fictional or general responses instead of requiring disclosures about violence or family experiences.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1PbMnWXnHLE1Kypf-zpuQsaYkWuW8DcEk",
    "title": "Moose Hide Campaign: Indigenous innovation",
    "originalTitle": "TheMooseHideCampaignIndigenousinnovationforALLCanadians-1.pdf",
    "url": "https://drive.google.com/file/d/1PbMnWXnHLE1Kypf-zpuQsaYkWuW8DcEk/view?usp=drivesdk",
    "category": "Social Studies",
    "fit": "Use selectively",
    "use": "Use the middle-years questions with the Campaign introduction and an explicit purpose for listening.",
    "note": "Preserve Nation-specific attribution. Choose one question and an action students can explain; students can pass on personal family or healing questions.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1TjhF13UTg1Y0o9up0roq7WmtmzvX8S9H",
    "title": "What is Two Spirit?",
    "originalTitle": "WhatisTwoSpiritUnderstandingGenderandGenderDiverseCultures-1.pdf",
    "url": "https://drive.google.com/file/d/1TjhF13UTg1Y0o9up0roq7WmtmzvX8S9H/view?usp=drivesdk",
    "category": "Social Studies",
    "fit": "Use selectively",
    "use": "Use the source’s Indigenous framing and its distinction between gender identity and sex assigned at birth.",
    "note": "Preview the videos and map. Keep participation non-disclosing; omit the contest/email submission direction unless deliberately arranged by the teacher.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1zkD6sZn93-Ppjq5scZYqNGGGLyU3ci-Q",
    "title": "Charades action phrases",
    "originalTitle": "Listofphrasesforcharades-1.pdf",
    "url": "https://drive.google.com/file/d/1zkD6sZn93-Ppjq5scZYqNGGGLyU3ci-Q/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Preview needed",
    "use": "A quick movement or vocabulary game bank, with some readable action phrases.",
    "note": "Much of the extracted text is font-encoded and unreadable. Inspect the original cards before choosing them; offer a drawing, clue-giving or seated role.",
    "review": "Limited extraction; original-page review needed"
  },
  {
    "id": "1oN1LouDpRP50BEuBCyyR6bqi3uaYnQed",
    "title": "Find Someone Who",
    "originalTitle": "FindSomeoneWho-1.pdf",
    "url": "https://drive.google.com/file/d/1oN1LouDpRP50BEuBCyyR6bqi3uaYnQed/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Adapt",
    "use": "Use the structure for a low-pressure getting-to-know-you conversation.",
    "note": "Several prompts depend on travel, appearance, medical history or family structure. Replace them with classroom interests and choices; allow passing and use Canadian wording.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1n38-cMRwUdrxh-vIqngYYhHOXo2_n-iR",
    "title": "Order of operations: colour by number",
    "originalTitle": "OrderofOperationsMathWorksheetsColorbyNumberActivityDigitalResources-1.pdf",
    "url": "https://drive.google.com/file/d/1n38-cMRwUdrxh-vIqngYYhHOXo2_n-iR/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Adapt",
    "use": "Can provide practice after an explicit operation-order lesson.",
    "note": "The expressions include exponents. Choose non-exponent questions for core BC Grade 6 and inspect the original superscripts. Math Antics pages 1–3 offer a clearer default selection.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1Ua9zsu0GTmyHhjlHEEXfTypm4y5DMBn-",
    "title": "Emoji transformations",
    "originalTitle": "TransformationsontheCoordinatePlaneGeometryPracticeWorksheetActivity-1.pdf",
    "url": "https://drive.google.com/file/d/1Ua9zsu0GTmyHhjlHEEXfTypm4y5DMBn-/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Use selectively",
    "use": "An engaging extension bank with translations, reflections, rotations, dilations and combinations; contents list keys on pp. 16–20.",
    "note": "Four quadrants, diagonal reflections and dilations are harder than the core first-quadrant task. Select a page after checking its actual coordinates and moves.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1SE-raftXT65pVsdvEAWPr3JbmG3CWwV8",
    "title": "Million Dollar Challenge: financial literacy",
    "originalTitle": "TheMillionDollarChallengeFinancialLiteracyProjectmathdollardeals26-1.pdf",
    "url": "https://drive.google.com/file/d/1SE-raftXT65pVsdvEAWPr3JbmG3CWwV8/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Adapt",
    "use": "A longer budget project with a checklist, ledger and spending decisions. Contents place the ledger on p. 24 and cheque on p. 25.",
    "note": "Replace the inheritance/bereavement premise if unsuitable. Prepare fictional Canadian prices offline; cheque-writing and unrestricted website shopping are not needed for the core simple-budget goal.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1ONNQa_GTTGQAhEKS8x16sboNmWxDqvLC",
    "title": "Robot art: roll and draw",
    "originalTitle": "RobotArtLessonSubPlansEarlyFinishersNoPrepSubstituteArtLesson-2.pdf",
    "url": "https://drive.google.com/file/d/1ONNQa_GTTGQAhEKS8x16sboNmWxDqvLC/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Use selectively",
    "use": "A supplied dice-grid drawing task with examples, writing and reflection options.",
    "note": "Prepare one die per group and the grid. Let students change details deliberately; use drawing paper and pencils for the simplest TTOC route.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1c3Ws3Jrh9ChiJCmKwGoniZ3SHQEHwjzP",
    "title": "Any-fiction reading organizer",
    "originalTitle": "ReadingComprehensionGraphicOrganizerFitsANYFictionBookFree-1.pdf",
    "url": "https://drive.google.com/file/d/1c3Ws3Jrh9ChiJCmKwGoniZ3SHQEHwjzP/view?usp=drivesdk",
    "category": "Language Arts",
    "fit": "Use selectively",
    "use": "A flexible organizer for characters, setting, vocabulary, connections and response to a shared or independent text.",
    "note": "Name the book and reading section first. Choose a few fields and model a page-supported response instead of requiring every field after every reading.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1RYSxJUzP6_ZFXZsWVKVAh502SNDYK-Ix",
    "title": "Middle-school informational-text sub plans",
    "originalTitle": "MiddleSchoolEmergencySubPlansInformationalTextsandNoPrepActivities-1.pdf",
    "url": "https://drive.google.com/file/d/1RYSxJUzP6_ZFXZsWVKVAh502SNDYK-Ix/view?usp=drivesdk",
    "category": "Language Arts",
    "fit": "Adapt",
    "use": "Includes levelled readings and accompanying tasks, including Franklin, Groundhog Day, inaugurations and service dogs.",
    "note": "Much is US-specific and one text concerns the 2017 inauguration. Treat dated passages as historical texts, check claims, and select a text suitable for the class rather than using the bundle indiscriminately.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "11NnN_eja55jYPUokkFXcAG4X3Mi1pBGk",
    "title": "Castles art: roll and draw",
    "originalTitle": "CastlesArtLessonNoPrepArtSubPlansEarlyFinishersArtWorksheets-2.pdf",
    "url": "https://drive.google.com/file/d/11NnN_eja55jYPUokkFXcAG4X3Mi1pBGk/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Use selectively",
    "use": "A supplied drawing guide, dice game and optional story/poem activities.",
    "note": "Choose one art goal and one follow-up. Historical claims need a source; a fantasy castle drawing is a creative task, not automatically a medieval-history lesson.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1WUqLcF7nz2bnpdTFPBOzLIWWbzPshukw",
    "title": "Middle-school emergency math: equations",
    "originalTitle": "MiddleSchoolMathEmergencySubPlansNoPrepWorksheets6th7th8thGrade-1.pdf",
    "url": "https://drive.google.com/file/d/1WUqLcF7nz2bnpdTFPBOzLIWWbzPshukw/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Adapt",
    "use": "The actual task bank centres on equations rather than general Grade 6 review.",
    "note": "Select one-step equations with whole-number coefficients and solutions. Harder levels include negative or fractional answers. Replace punitive compliance language and inspect image-based questions before assigning.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1sWhY1KBu9ab5ZTxcWFdYan2e5px2QN3v",
    "title": "Miró art and writing",
    "originalTitle": "ArtSubPlansMiroNoPrepArtActivitywithArtHistoryWritingPrompts-2.pdf",
    "url": "https://drive.google.com/file/d/1sWhY1KBu9ab5ZTxcWFdYan2e5px2QN3v/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Use selectively",
    "use": "Includes an artist introduction, hand-drawn prompts and a creative drawing route.",
    "note": "Preview the reference artwork and artist context; let students make and explain their own choices rather than treating a copied style as the only successful outcome.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1TCGV6f8o13QOGwd8NlssoiL74SAWXm8j",
    "title": "World-language substitute choice board",
    "originalTitle": "SubPlansChoiceBoard-1.docx",
    "url": "https://docs.google.com/document/d/1TCGV6f8o13QOGwd8NlssoiL74SAWXm8j/edit?usp=drivesdk&ouid=108022318824044956714&rtpof=true&sd=true",
    "category": "Language Arts",
    "fit": "Adapt",
    "use": "The actual document is a German-course choice board spanning introductory through AP levels.",
    "note": "It is not a ready Grade 6 general substitute plan. Reuse only the choice-board structure after replacing the tasks, language expectations, materials and finish criteria.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "17p1xFV_DfE6votjFWZ9jZHyCjEIVLb0e",
    "title": "Grammar and spelling memes slideshow",
    "originalTitle": "FixtheGrammarandSpellingUsingMemesGrades46-1.pptx",
    "url": "https://docs.google.com/presentation/d/17p1xFV_DfE6votjFWZ9jZHyCjEIVLb0e/edit?usp=drivesdk&ouid=108022318824044956714&rtpof=true&sd=true",
    "category": "Language Arts",
    "fit": "Preview needed",
    "use": "Potential editing discussion resource.",
    "note": "Only a very small amount of text was extractable. Images, wording, answers and age suitability remain unverified; do not mark the deck ready on its filename alone.",
    "review": "Limited extraction; original-page review needed"
  },
  {
    "id": "1zM0TLbwTOgHMOw-yw3PZ14sYTQ_6LRss",
    "title": "Halloween colouring",
    "originalTitle": "HalloweenColoringPagesColoringSheetsOctoberActivitiesColoringWorksheets-1.pdf",
    "url": "https://drive.google.com/file/d/1zM0TLbwTOgHMOw-yw3PZ14sYTQ_6LRss/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Use selectively",
    "use": "Optional seasonal colouring or quiet-choice material.",
    "note": "Select an appropriate page and provide a non-seasonal option. It is not a complete visual-arts lesson without a specific art-making purpose.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1qfVRYYmehpmpm2COppnlN4nq5XURscWe",
    "title": "Two-day division substitute plans",
    "originalTitle": "EmergencySubstitutePlans5thGradeMathSubPlansDivision-1.pdf",
    "url": "https://drive.google.com/file/d/1qfVRYYmehpmpm2COppnlN4nq5XURscWe/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Use selectively",
    "use": "A comparatively complete paper route: teacher script, multi-digit division practice, word problems, maze, choice board and keys. Sets A and B are listed as pp. 3–12 and 13–22.",
    "note": "Use after the division method has been taught. Select one day, set the number of choice-board tasks and supply the key separately.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1GdVU5lQoM0jM92bH9G45jGLlX97uUScj",
    "title": "Science roots and creature project",
    "originalTitle": "EmergencyScienceSubPlanActivityorProjectBacktoSchoolScience-2.pdf",
    "url": "https://drive.google.com/file/d/1GdVU5lQoM0jM92bH9G45jGLlX97uUScj/view?usp=drivesdk",
    "category": "Science",
    "fit": "Use selectively",
    "use": "A vocabulary/word-building task with a supplied root bank and invented-creature product.",
    "note": "Model decoding a scientific term and constructing a name. Label invented organisms as fictional; this is vocabulary practice rather than evidence of a full biology investigation.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "16K7XUzE6zd0uBLW4R_CvEw6g4tQRYDJH",
    "title": "Unscramble a masterpiece",
    "originalTitle": "UnscrambletheMasterpieceArtHistoryProjectorEmergencySubPlanActivity-1.pdf",
    "url": "https://drive.google.com/file/d/16K7XUzE6zd0uBLW4R_CvEw6g4tQRYDJH/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Use selectively",
    "use": "A cut-and-reassemble/drawing activity that can develop close observation and spatial reasoning.",
    "note": "Prepare the chosen image and accessible cutting route. Add one observation about composition; completion alone does not show art-historical understanding.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1QpCnYXYAkGSUSN0X95M8-GammZkSvoRl",
    "title": "Five-day Social Studies substitute pack",
    "originalTitle": "EMERGENCYSUBPLANSforSocialStudies5th6th7thGrade-1.pdf",
    "url": "https://drive.google.com/file/d/1QpCnYXYAkGSUSN0X95M8-GammZkSvoRl/view?usp=drivesdk",
    "category": "Social Studies",
    "fit": "Use selectively",
    "use": "A linked sequence of reading, annotation, writing, timeline/map work and optional extras with teacher preparation pages.",
    "note": "Read and select the actual passage before placing it in a BC unit. Prepare copies and classroom-specific directions; generic grade-band labels do not establish curriculum coverage.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1a2p0Odgps2cHAR15kCqLApY95JV9Nzuh",
    "title": "Grammar worksheet bank",
    "originalTitle": "GrammarWorksheetPack-2.pdf",
    "url": "https://drive.google.com/file/d/1a2p0Odgps2cHAR15kCqLApY95JV9Nzuh/view?usp=drivesdk",
    "category": "Language Arts",
    "fit": "Use selectively",
    "use": "Hint boxes and stepped practice support targeted vocabulary and grammar instruction.",
    "note": "Choose one demonstrated need, model an example and apply the skill to students’ own writing. Avoid turning the whole bank into compulsory seatwork.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1-cT7t1BZXSR3dsoB6gBRAFuN7HF0kVDi",
    "title": "Water-bottle flip STEM challenge",
    "originalTitle": "WaterBottleFlipSTEMChallengeSTEMActivity-2.pdf",
    "url": "https://drive.google.com/file/d/1-cT7t1BZXSR3dsoB6gBRAFuN7HF0kVDi/view?usp=drivesdk",
    "category": "Science",
    "fit": "Adapt",
    "use": "An experiment context for repeated trials, recording results and comparing conditions.",
    "note": "Vary one condition at a time and keep trial counts consistent. Manage spills and offer a partner-operated role. A successful flip alone is not evidence of a fair test.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "19PJF42GK7RJpAwPl-0qOgBWOM8R8mNPN",
    "title": "Planet research collaboration posters",
    "originalTitle": "PlanetsResearchPostersCollaborativeSolarSystemScienceColoringActivity-1.pdf",
    "url": "https://drive.google.com/file/d/19PJF42GK7RJpAwPl-0qOgBWOM8R8mNPN/view?usp=drivesdk",
    "category": "Science",
    "fit": "Use selectively",
    "use": "A collaborative research-and-display format with prompts for planets.",
    "note": "Supply reliable print or digital sources and require a source note. Preview all nine poster subjects and distinguish classifications appropriately; decoration is not the research evidence.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1iZ5QSQQbCBfPY2xwdMeYxmqW0vzVWDKF",
    "title": "Literary devices in sentences: Grades 4–6",
    "originalTitle": "LiteraryDevicesWorksheetsandTypesofSentencesNOPREPGrade46-2.pdf",
    "url": "https://drive.google.com/file/d/1iZ5QSQQbCBfPY2xwdMeYxmqW0vzVWDKF/view?usp=drivesdk",
    "category": "Language Arts",
    "fit": "Use selectively",
    "use": "A substantial bank for spotting and composing examples of literary devices.",
    "note": "Teach one device with a shared sentence, then ask students to explain its effect and use it in their own writing. Choose pages instead of assigning the entire bank.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1dqsj8QMXBUVXXfeVOYKBroi6v4CsOjIg",
    "title": "The Reflection in Me slideshow",
    "originalTitle": "TheReflectioninMe-1.pptx",
    "url": "https://docs.google.com/presentation/d/1dqsj8QMXBUVXXfeVOYKBroi6v4CsOjIg/edit?usp=drivesdk&ouid=108022318824044956714&rtpof=true&sd=true",
    "category": "Classroom routines",
    "fit": "Use selectively",
    "use": "Before/during/after viewing prompts lead toward an “I am” response.",
    "note": "Preview the video and slides. Offer strengths, interests or fictional-character responses rather than requiring appearance or self-image disclosure.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "11G4mYMRRXaWTew3m2Y4qQ2LP5kiNWnkq",
    "title": "Neurodiversity-affirming colouring",
    "originalTitle": "NeurodiversityAffirmingAutismAcceptanceandAwareness44COLORINGPAGES-1.pdf",
    "url": "https://drive.google.com/file/d/11G4mYMRRXaWTew3m2Y4qQ2LP5kiNWnkq/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Use selectively",
    "use": "Positive messages and varied colouring choices can support a welcoming quiet-choice space.",
    "note": "Do not infer or ask students to disclose diagnoses. Let students choose the message and mode; colouring does not substitute for teaching inclusive classroom practices.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1uOCxzWbYBCIcd8NpeQs9FHI3GbNEO0mr",
    "title": "Winter break reading challenge",
    "originalTitle": "WinterBreakMarshmallowReadingChallenge-1.pdf",
    "url": "https://drive.google.com/file/d/1uOCxzWbYBCIcd8NpeQs9FHI3GbNEO0mr/view?usp=drivesdk",
    "category": "Language Arts",
    "fit": "Adapt",
    "use": "A marshmallow-themed reading activity with winter/Christmas choices.",
    "note": "Use a neutral option and accessible books. Make family participation optional; do not grade home resources, signatures or holiday practices.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1L2gHP2CDvR9CGmETktKF_-xWwrXGLKM1",
    "title": "3D shape Bump games",
    "originalTitle": "3DShapesWorksheetGamesFacesEdgesVerticesNetsAttributesGeometryActivity-1.pdf",
    "url": "https://drive.google.com/file/d/1L2gHP2CDvR9CGmETktKF_-xWwrXGLKM1/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Use selectively",
    "use": "Ten games review solids, faces, edges, vertices, nets and attributes, with an answer key.",
    "note": "Read the specific game’s rules: materials differ between games. These review shape knowledge; they do not teach or assess volume calculations by themselves.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1vWQ9bY51Pl7dP_ufHuMaQD92XX16Q79Q",
    "title": "Earth Day recycling activity",
    "originalTitle": "FREEEarthDayActivity-1.pdf",
    "url": "https://drive.google.com/file/d/1vWQ9bY51Pl7dP_ufHuMaQD92XX16Q79Q/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Preview needed",
    "use": "Only a brief recycling caption was extractable.",
    "note": "The page images and task structure remain unverified. Inspect the original before deciding whether it suits Grade 6 or needs a richer sorting/explanation task.",
    "review": "Limited extraction; original-page review needed"
  },
  {
    "id": "1ImyPZ8WFcgCozsI_Zt2aU-iyKJqWH0UF",
    "title": "Back-to-school activity bundle",
    "originalTitle": "BacktoSchoolActivitiesFirstWeekofSchoolBeginningoftheYearBUNDLE-1.pdf",
    "url": "https://drive.google.com/file/d/1ImyPZ8WFcgCozsI_Zt2aU-iyKJqWH0UF/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Use selectively",
    "use": "Includes introductory printables, digital options and a math survey. Use a small selection to learn about students.",
    "note": "Choose a purpose for each activity and avoid collecting the same personal information repeatedly. Provide a paper option and a right to pass.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1pUBjm0qM3BXYvLzLEBdcscyLgP7Xl1eb",
    "title": "Pop-art pet colouring",
    "originalTitle": "PopArtPetColoringPagesSheetsAnimalArtProjectDogCatHamster-1.pdf",
    "url": "https://drive.google.com/file/d/1pUBjm0qM3BXYvLzLEBdcscyLgP7Xl1eb/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Preview needed",
    "use": "The filename suggests an optional animal-art colouring bank.",
    "note": "No readable text was returned. Page designs, directions and print quality have not been inspected; no readiness claim is made.",
    "review": "Limited extraction; original-page review needed"
  },
  {
    "id": "13Xw68Xx4G7hDdti3PAYIzRGnyOXBvbW_",
    "title": "K-pop-inspired colouring",
    "originalTitle": "KpopDemonHuntersColoringBookAnimeInspiredPrintableColoringSheets-1.pdf",
    "url": "https://drive.google.com/file/d/13Xw68Xx4G7hDdti3PAYIzRGnyOXBvbW_/view?usp=drivesdk",
    "category": "Arts",
    "fit": "Preview needed",
    "use": "A possible interest-based quiet-choice resource.",
    "note": "The extraction contains mainly character labels. Inspect the artwork and student suitability; the title alone is not enough to plan a lesson.",
    "review": "Limited extraction; original-page review needed"
  },
  {
    "id": "11IqC5kreT35UPR_azDlr75qNRRTZkLNK",
    "title": "Equivalent ratios: maze, riddle and colouring",
    "originalTitle": "EQUIVALENTRATIOSANDRATIOTABLEMazeRiddleColoringPagePrintorDigital-2.pdf",
    "url": "https://drive.google.com/file/d/11IqC5kreT35UPR_azDlr75qNRRTZkLNK/view?usp=drivesdk",
    "category": "Mathematics",
    "fit": "Use selectively",
    "use": "Use the maze or ratio-table riddle after modelling equal batches; have students explain one multiplier.",
    "note": "Student and answer versions are interleaved. Print only selected student pages. The riddle adds English-language demand separate from ratio understanding.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1knMCOYQ7fJTz3ifGrqbBbGM-jePRVFSX",
    "title": "Brain teasers: rebus word puzzles",
    "originalTitle": "BrainTeasersandLogicPuzzlesforEarlyFinishers-1.pdf",
    "url": "https://drive.google.com/file/d/1knMCOYQ7fJTz3ifGrqbBbGM-jePRVFSX/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Use selectively",
    "use": "The actual pages are rebus-style word puzzles with answers, useful for optional language play.",
    "note": "Do not label them a mathematics lesson or a general measure of reasoning ability. Model how visual word placement creates a clue and accept alternative plausible readings.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1pTwTBYQluCR5IM2ltfJA0XlX-VXkPcc9",
    "title": "New Year resolutions and goals",
    "originalTitle": "FREENewYears2026WritingResolutionsandGoalsDigitalPrint-2.pdf",
    "url": "https://drive.google.com/file/d/1pTwTBYQluCR5IM2ltfJA0XlX-VXkPcc9/view?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Adapt",
    "use": "Goal prompts can support a short reflection and one concrete next step.",
    "note": "Check the visible year before reuse; the supplied digital activity says it is not editable. Use a year-neutral paper response if necessary and keep personal goals optional.",
    "review": "Extracted content reviewed; page layout not fully verified"
  },
  {
    "id": "1q_sl2Pw8Xf9uMGiHGZBH1f2XwO3kppdFKkt47zWOBY0",
    "title": "Puzzles and riddles slideshow",
    "originalTitle": "Puzzles & Riddles for High Schoolers & Middles",
    "url": "https://docs.google.com/presentation/d/1q_sl2Pw8Xf9uMGiHGZBH1f2XwO3kppdFKkt47zWOBY0/edit?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Preview needed",
    "use": "The slideshow may offer extension choices, but no meaningful slide text was returned.",
    "note": "Inspect the images, solutions, reading demand and grade suitability before assigning. It is indexed for access, not verified as a complete lesson.",
    "review": "Limited extraction; original-page review needed"
  },
  {
    "id": "1Ib8M0GMSl3ESv_yNXsuxwYJFCrjO6wI-4PbT-cSGf88",
    "title": "End-of-year bundle: teacher guide",
    "originalTitle": "The End Of The Year Activities Bundle Teacher Guide",
    "url": "https://docs.google.com/document/d/1Ib8M0GMSl3ESv_yNXsuxwYJFCrjO6wI-4PbT-cSGf88/edit?usp=drivesdk",
    "category": "Classroom routines",
    "fit": "Use selectively",
    "use": "The guide points to five separate activities: memories, teacher feedback, class-survival advice, goal bookmarks and thank-you notes.",
    "note": "The guide is not the activity set itself. Open and prepare the linked copies before class; their full content was not included in this guide review.",
    "review": "Extracted content reviewed; page layout not fully verified"
  }
];
