export type SocialResource = {
  label: string;
  type: "Interactive map" | "Website" | "Article" | "Data profile";
  url: string;
  source: string;
  purpose: string;
  gradeFit: "Core Grade 6" | "Supported stretch" | "Teacher preview";
};

export type SocialScene = {
  label: string;
  title: string;
  prompt: string;
  time: string;
  learningMode: string;
  studentTask: string;
};

export type SocialLesson = {
  id: string;
  unitId: "place-evidence-perspective" | "power-rights-government" | "global-systems" | "solutionary-inquiry";
  title: string;
  question: string;
  duration: string;
  kind: string;
  learning: string;
  success: string[];
  vocabulary: string[];
  scenes: SocialScene[];
  resources: SocialResource[];
  materials: string[];
  beforeClass: string[];
  teacherMoves: string[];
  lookFors: string[];
  misconceptions: string[];
  lowerPrep: string;
  evidenceLevel: "Practice" | "Checkpoint" | "Portfolio Highlight";
  evidenceSubjects: string[];
  spacesUse: "none" | "optional" | "required";
  spacesPrompt: string;
};

export const socialUnits = [
  {
    id: "place-evidence-perspective",
    number: "01",
    title: "Place, Evidence & Perspective",
    subtitle: "How sources shape what becomes visible",
    question: "How does the source—and the person who made it—shape what we understand about a place?",
    color: "#4f75a6",
    soft: "#e4ecf6",
    weeks: "4–5 weeks",
    status: "Classroom audit in progress",
    content: ["evidence", "perspective", "maps and media", "local change"],
  },
  {
    id: "power-rights-government",
    number: "02",
    title: "Power, Rights & Government",
    subtitle: "Who decides—and whose rights are protected?",
    question: "How do different systems make decisions, distribute power, and protect rights?",
    color: "#7459a6",
    soft: "#eee8f7",
    weeks: "4–5 weeks",
    status: "Experience build ready · adjust during the year",
    content: ["systems of government", "human rights", "civic participation", "ethical judgment"],
  },
  {
    id: "global-systems",
    number: "03",
    title: "Global Systems & Inequality",
    subtitle: "Connections, consequences, and cooperation",
    question: "Why do global problems persist, and what can cooperation change?",
    color: "#a87837",
    soft: "#f6ead7",
    weeks: "4–5 weeks",
    status: "Four experience drafts ready · adjust during the year",
    content: ["migration and urbanization", "poverty and inequality", "trade and resource decisions", "conflict and international cooperation"],
  },
  {
    id: "solutionary-inquiry",
    number: "04",
    title: "Solutionary Inquiry",
    subtitle: "Understand systems before proposing change",
    question: "How can we investigate a complex issue and teach a responsible response without oversimplifying it?",
    color: "#347d72",
    soft: "#deeeea",
    weeks: "5–6 weeks",
    status: "Four inquiry studios ready · adjust during the year",
    content: ["systems and significance", "change and continuity", "existing responses", "expert-team teaching"],
  },
] as const;

export const socialLessons: SocialLesson[] = [
  {
    id: "maps-make-arguments",
    unitId: "place-evidence-perspective",
    title: "Three maps of Fleetwood",
    question: "Why do three maps of the same place show us different things?",
    duration: "2 × 55–65 min",
    kind: "Whole-class map inquiry",
    learning: "We are learning that mapmakers choose what to show because each map has a different job.",
    success: [
      "I can point to something a map actually shows.",
      "I can explain the job each map was made to do.",
      "I can use more than one map and name something the maps still cannot tell us.",
    ],
    vocabulary: ["source", "evidence", "inference", "perspective", "territory", "unceded"],
    scenes: [
      { label: "Meet", title: "Three maps. One place. Different choices.", prompt: "The teacher opens each real map on the projector. Students point out one visible detail and decide what kind of information the mapmaker chose to make easy to see.", time: "15–20 min", learningMode: "One projector · class noticing · oral, board, or paper response", studentTask: "One visible detail and one question from each map" },
      { label: "Purpose", title: "What job is each map doing?", prompt: "Compare the creator, labels, legend, and information on each projected map. Explain what the map helps someone do and what it cannot answer alone.", time: "20–25 min", learningMode: "Whole-class source comparison · turn-and-talk · shared board", studentTask: "A three-map purpose comparison said aloud, recorded on the board, or sketched on paper" },
      { label: "Compare", title: "What can we understand when we use all three?", prompt: "Bring one detail from each source into the on-screen comparison. Build a careful statement about Fleetwood, then name a voice or kind of knowledge the maps still do not contain.", time: "25–30 min", learningMode: "Projector evidence conference · class synthesis", studentTask: "One shared claim supported by more than one map and one honest limit" },
      { label: "Explain", title: "Teach the mapmaker’s choices", prompt: "Choose a Fleetwood question. Use the projected sources and the on-screen frame to explain what each map adds, what it leaves out, and why using several perspectives matters.", time: "25–35 min", learningMode: "Whole-class model · oral explanation · board or paper option", studentTask: "A short spoken, board, or paper explanation using all three maps" },
    ],
    resources: [
      { label: "Surrey COSMOS", type: "Interactive map", url: "https://cosmos.surrey.ca/external/cosmosmobile/new/", source: "City of Surrey", purpose: "Examine current roads, facilities, parks, parcels, and other official geographic layers around Walnut Road and Fleetwood.", gradeFit: "Core Grade 6" },
      { label: "First Peoples’ Map of B.C.", type: "Interactive map", url: "https://maps.fpcc.ca/", source: "First Peoples’ Cultural Council", purpose: "Explore language regions, communities, place names, and the source information provided by the map.", gradeFit: "Core Grade 6" },
      { label: "Maps of local territories and language groups", type: "Website", url: "https://surreyschoolsone.ca/indigenous/resource-post/?permalink=maps-that-show-local-language-groups-and-territories", source: "Surrey Schools Indigenous Learning · intermediate", purpose: "Use the district-curated local map set to compare purposes and limitations. Link to the source page rather than merging the maps into one fixed boundary image.", gradeFit: "Core Grade 6" },
      { label: "Katzie, Kwantlen, and Semiahmoo source collection", type: "Website", url: "https://surreyschoolsone.ca/indigenous/resources/local-nations/", source: "Surrey Schools Indigenous Learning", purpose: "Move from a broad map to the specific Nation websites selected by district Indigenous Helping Teachers before making a local claim.", gradeFit: "Core Grade 6" },
      { label: "Fleetwood Plan", type: "Website", url: "https://fleetwoodplan.surrey.ca/", source: "City of Surrey", purpose: "Identify what the planning map emphasizes as Fleetwood prepares for growth and rapid transit.", gradeFit: "Core Grade 6" },
      { label: "Surrey–Langley SkyTrain: current work", type: "Website", url: "https://surreylangleyskytrain.gov.bc.ca/current-work/", source: "Province of British Columbia · official project site", purpose: "Compare what students can see being built now with what is planned for later. Construction is underway; passenger service on the extension is not running yet.", gradeFit: "Core Grade 6" },
      { label: "Surrey Schools territorial acknowledgment guidance", type: "Article", url: "https://www.surreyschools.ca/queenelizabethcontinuingeducation/territorial-acknowledgment-plaques-being-installed-at-every-school-in-the-surrey-school-district.128934", source: "Surrey Schools", purpose: "Confirm the district’s wording and the named Katzie, Kwantlen, and Semiahmoo First Nations; do not turn the acknowledgment into a generic claim.", gradeFit: "Teacher preview" },
    ],
    materials: ["One projector", "Teacher computer with the three real map sources open", "Class whiteboard and markers", "Optional plain paper and pencils"],
    beforeClass: ["Open the exact three map sources in teacher tabs and choose useful Fleetwood/Surrey views.", "Test that each map loads on the projector; the on-screen lesson remains the no-link backup.", "Review the district territorial-acknowledgment protocol and pronounce Nation names carefully.", "Do not ask students to enter addresses, personal locations, or use individual devices."],
    teacherMoves: ["Keep the maps on one shared projector and pause for students to point, talk, or sketch.", "Require a visible detail before an explanation.", "Ask who made the map and what the map helps people do.", "Treat omissions as choices and limits—not automatic proof of bad intent.", "Attribute Indigenous place knowledge to the specific source and Nations named; remind students that language regions are not property boundaries."],
    lookFors: ["Students point to a visible map feature before explaining.", "Students describe a different purpose for each map.", "Students compare rather than rank one map as the only truth.", "The shared conclusion uses more than one source and names a missing voice or kind of knowledge."],
    misconceptions: ["Maps are photographs of reality.", "A map is biased only when it contains false information.", "Political boundaries are the only meaningful way to represent land.", "A land acknowledgment is complete learning rather than a relationship and responsibility."],
    lowerPrep: "Use the built-in three-map comparison and open real sources only when helpful. Students answer aloud, contribute to the board, or make a quick paper sketch; no screenshots, printing, or student devices are required.",
    evidenceLevel: "Practice",
    evidenceSubjects: ["Social Studies", "English Language Arts", "Arts Education"],
    spacesUse: "none",
    spacesPrompt: "No post required. Save the purposeful map only if it shows especially useful thinking for a later case file.",
  },
  {
    id: "trace-the-claim",
    unitId: "place-evidence-perspective",
    title: "Trace the claim",
    question: "What should we do before we believe, share, or act on an online claim?",
    duration: "1 × 55–65 min",
    kind: "Media evidence lab",
    learning: "We are learning to leave a post, locate the original source, verify the source, and compare independent coverage.",
    success: ["I can trace a claim toward its original source.", "I can find the truth and explain which evidence makes it believable.", "I can label a conclusion supported, contradicted, or still uncertain."],
    vocabulary: ["claim", "original source", "corroborate", "context", "reliable", "uncertain"],
    scenes: [
      { label: "Diagnose", title: "Pause before you share", prompt: "Examine a fictional field-trip post. Identify language that pushes a fast reaction, distance from the original source, and missing proof before deciding whether the claim is true.", time: "10–12 min", learningMode: "Visual diagnosis · clue reveal · respectful discussion", studentTask: "Three reasons to pause and a first source to check" },
      { label: "Play", title: "Quick practice: Two Lies and a Truth", prompt: "This short game is one part of Trace the Claim. Study three sources as a class. Show A, B, or C for the statement that matches each source, then point to the exact word or number that proves it.", time: "12–15 min", learningMode: "Whole-class projector game · A/B/C vote · spoken evidence defence", studentTask: "Three spoken truth choices with evidence; no written product" },
      { label: "Trace", title: "Find where the rumour began", prompt: "Start with a cropped group-chat post. Follow its clues back to the full school update, class calendar, and new permission form.", time: "25–30 min", learningMode: "Source trail · collaborative evidence table", studentTask: "A four-stop trail showing where one postponed trip became ‘all year’" },
    ],
    resources: [
      { label: "Break the Fake", type: "Website", url: "https://mediasmarts.ca/break-fake", source: "MediaSmarts", purpose: "Learn and apply four practical verification moves before sharing or acting on a claim.", gradeFit: "Core Grade 6" },
      { label: "Digital Media Literacy Framework: Grades 4–6", type: "Article", url: "https://mediasmarts.ca/teacher-resources/digital-media-literacy-framework/digital-media-literacy-framework-grades-4-6", source: "MediaSmarts", purpose: "Teacher check for Grade 6 fit and follow-up creation tasks.", gradeFit: "Teacher preview" },
    ],
    materials: ["One projected screen", "Source-trail recording sheet for the longer investigation", "Highlighters", "Notebook or usual writing space"],
    beforeClass: ["Two Lies and a Truth has not replaced Trace the Claim. It is the quick practice round inside the larger lesson: pause at a suspicious post, practise matching claims to evidence, then trace the rumour back to its source.", "Preview the three whole-class rounds and the fixed field-trip source trail; the game needs no copies or student devices.", "Check the optional MediaSmarts link and save a screenshot or short summary as an offline fallback.", "Do not use student social-media accounts or ask students to search distressing current events."],
    teacherMoves: ["Ask students to withhold judgment while they gather context.", "Hear two or three reasons before revealing each truth; ask students to complete ‘I think ___ is true because the source shows ___.’", "Model opening new tabs and reading laterally.", "Praise careful uncertainty, not just confident debunking.", "Separate a statement that sounds believable from one that the evidence actually supports."],
    lookFors: ["Students choose the one statement the displayed source supports.", "Students point to exact words or numbers before explaining.", "Students can explain why each tempting lie goes beyond the source.", "The original source and dates are identified in the field-trip trail."],
    misconceptions: ["A professional-looking page is reliable.", "A .org or large follower count proves credibility.", "One source agreeing is corroboration.", "If a claim cannot be confirmed quickly, it must be false."],
    lowerPrep: "Play only the three Two Lies and a Truth rounds. Students show A/B/C, defend the truth with one source detail, and hear the reveal. No handout, score, cutting, writing, or individual devices are required.",
    evidenceLevel: "Practice",
    evidenceSubjects: ["Social Studies", "English Language Arts", "ADST"],
    spacesUse: "none",
    spacesPrompt: "No SpacesEDU post. Use students’ spoken reasons and the short source trail as formative evidence.",
  },
  {
    id: "perspective-without-guessing",
    unitId: "place-evidence-perspective",
    title: "Perspective without guessing",
    question: "How can we understand what may matter to someone without pretending we know their thoughts?",
    duration: "2 × 55–65 min",
    kind: "Stakeholder case",
    learning: "We are learning to start with what a source actually tells us, make a careful possible explanation, and keep unknowns open as questions.",
    success: ["I can separate a fact from a careful possible explanation and a guess.", "I can point to the detail that supports what I say may matter.", "I can notice who may be helped, who may have a new problem, and who has not been heard."],
    vocabulary: ["stakeholder", "perspective", "interest", "value", "constraint", "trade-off"],
    scenes: [
      { label: "Commit", title: "Notice before choosing", prompt: "Study a clearly labelled generated school-street scene. Separate visible detail from inference, then respond privately to a fictional Fleetwood street redesign before seeing stakeholder evidence.", time: "20–25 min", learningMode: "Visual observation · scenario · private response", studentTask: "Visible observations, an initial decision and reason, and evidence still needed" },
      { label: "Build", title: "Evidence before empathy claims", prompt: "Use four stakeholder cards. Highlight stated facts, infer possible priorities, and mark what cannot be known from the evidence.", time: "35–40 min", learningMode: "Case cards · evidence coding · perspective map", studentTask: "Four evidence-based perspective profiles" },
      { label: "Test", title: "What happens when the conditions change?", prompt: "Add a new constraint—cost, accessibility, safety, housing, green space, or business access. Revise the options and identify who benefits, who carries costs, and who is missing.", time: "35–45 min", learningMode: "Decision simulation · trade-off matrix", studentTask: "A revised option with impact analysis" },
      { label: "Listen", title: "Hear another group and make the plan better", prompt: "Point to a fact, repeat another group’s concern in your own words, ask if you understood, and then change one part of your plan—or explain why you kept it.", time: "30–35 min", learningMode: "Council circle · listening notes · plan improvement", studentTask: "What the group heard, what it changed or kept, and one question that is still open" },
    ],
    resources: [
      { label: "Fleetwood community profile", type: "Data profile", url: "https://www.surrey.ca/sites/default/files/media/documents/Neighbourhood-Profile-Fleetwood.pdf", source: "City of Surrey · 2021 Census profile", purpose: "Use dated local demographic evidence carefully; name the year and avoid turning group data into assumptions about individuals.", gradeFit: "Supported stretch" },
      { label: "Fleetwood planning for the future", type: "Website", url: "https://www.surrey.ca/about-surrey/our-communities/fleetwood", source: "City of Surrey", purpose: "Identify public planning priorities and questions connected to local growth and transit.", gradeFit: "Core Grade 6" },
      { label: "Surrey–Langley SkyTrain project", type: "Website", url: "https://surreylangleyskytrain.gov.bc.ca/", source: "Province of British Columbia · official project site", purpose: "Use a visible Fleetwood change carefully: guideway and station construction are happening now, while passenger service is a future plan. The official site currently anticipates service in late 2029; check for updates before teaching.", gradeFit: "Core Grade 6" },
    ],
    materials: ["Projected generated school-street practice scene", "Fictional stakeholder cards", "Evidence/inference highlighters", "Trade-off matrix", "Council-circle role cards", "Reflection slips"],
    beforeClass: ["Keep the generated street image labelled as a fictional practice scene, not a photograph of Walnut Road or evidence about the real school.", "Keep stakeholder profiles fictional but grounded in public local evidence.", "Include renter, homeowner, youth, disabled transit user, small-business, environmental, and Nation/community-government perspectives across the set.", "Avoid assigning identities to students or asking them to represent a group they belong to.", "Preteach that a stakeholder group contains many perspectives."],
    teacherMoves: ["Begin with what is visibly present in the practice image; move every interpretation into inference or question.", "Require a quotation, data point, or role fact before accepting an inference.", "Ask what cannot be known.", "Add missing voices and constraints gradually.", "Assess reasoning and listening—not agreement with the teacher’s preferred option."],
    lookFors: ["Evidence and inference are visibly separated.", "Students avoid claiming an entire group thinks one thing.", "Recommendations name benefits, costs, and uncertainty.", "Students accurately paraphrase a view they do not share."],
    misconceptions: ["Perspective means opinion without evidence.", "People with the same identity share one viewpoint.", "Considering all perspectives requires treating every claim as equally supported.", "A compromise is automatically fair."],
    lowerPrep: "Use two stakeholder cards and one changing constraint as a whole-class fishbowl. Students complete an individual evidence–inference–unknown response.",
    evidenceLevel: "Practice",
    evidenceSubjects: ["Social Studies", "English Language Arts", "Career Education"],
    spacesUse: "none",
    spacesPrompt: "No post required. Keep the perspective map for the final case file.",
  },
  {
    id: "fleetwood-case-file",
    unitId: "place-evidence-perspective",
    title: "Fleetwood evidence & perspective case file",
    question: "How should Fleetwood respond to growth while caring for people, place, and future needs?",
    duration: "2–3 × 55–65 min",
    kind: "Performance task",
    learning: "We are combining maps, public information, stakeholder evidence, and careful reasoning to make a defensible local recommendation.",
    success: ["I can answer a focused question with evidence from meaningfully different sources.", "I can represent perspectives without stereotyping.", "I can explain trade-offs, limits, and what evidence is still missing."],
    vocabulary: ["corroborate", "significance", "cause", "consequence", "ethical judgment", "recommendation"],
    scenes: [
      { label: "Focus", title: "Choose a question small enough to investigate", prompt: "Narrow the broad issue to one decision about mobility, housing, green space, community services, safety, or belonging. Define the place, people, and decision.", time: "30–35 min", learningMode: "Question clinic · teacher conference", studentTask: "One focused inquiry question and working plan" },
      { label: "Research", title: "Build a case—not a link pile", prompt: "Collect evidence from at least three meaningfully different sources. Record creator, date, purpose, useful evidence, and limitation as you work.", time: "55–65 min", learningMode: "Paired research · source conferences", studentTask: "A research trail and annotated evidence set" },
      { label: "Reason", title: "Make the trade-offs visible", prompt: "Compare options across affected people, short- and long-term effects, intended and unintended consequences, feasibility, and missing evidence.", time: "40–50 min", learningMode: "Impact matrix · ethical reasoning · peer challenge", studentTask: "A transparent decision matrix and draft recommendation" },
      { label: "Communicate", title: "Create a case file another person can check", prompt: "Build a short paper, audio, video, slide, poster, or interactive explanation. Cite evidence on the product and include one serious limitation.", time: "55–65 min", learningMode: "Choice product · feedback · revision", studentTask: "A revised case file and two-minute explanation" },
      { label: "Reflect", title: "Show your individual thinking", prompt: "Explain which source changed or complicated your thinking, what you contributed, and what evidence would make the recommendation stronger.", time: "20–25 min", learningMode: "Individual writing or recording · SpacesEDU", studentTask: "An individual portfolio reflection" },
    ],
    resources: [
      { label: "Fleetwood Plan", type: "Website", url: "https://fleetwoodplan.surrey.ca/", source: "City of Surrey", purpose: "Use the plan, engagement information, and mapping tool as one public-government source—not the only perspective.", gradeFit: "Core Grade 6" },
      { label: "Fleetwood community profile", type: "Data profile", url: "https://www.surrey.ca/sites/default/files/media/documents/Neighbourhood-Profile-Fleetwood.pdf", source: "City of Surrey · 2021 Census profile", purpose: "Use local demographic evidence with the year and source clearly named.", gradeFit: "Supported stretch" },
      { label: "First Peoples’ Map of B.C.", type: "Interactive map", url: "https://maps.fpcc.ca/", source: "First Peoples’ Cultural Council", purpose: "Keep Indigenous languages, communities, and place knowledge visible while recognizing that one map cannot substitute for relationship or Nation-specific learning.", gradeFit: "Core Grade 6" },
      { label: "Surrey–Langley SkyTrain: current work", type: "Website", url: "https://surreylangleyskytrain.gov.bc.ca/current-work/", source: "Province of British Columbia · official project site", purpose: "Investigate a major local change. Separate present-day construction evidence from claims about future passenger service and neighbourhood effects.", gradeFit: "Core Grade 6" },
    ],
    materials: ["Case-file planning sheet", "Source cards", "Impact matrix", "Citation guide", "Choice-product materials", "Peer-audit checklist", "SpacesEDU reflection prompt"],
    beforeClass: ["Approve questions before research so each is focused, safe, and supported by available sources.", "Prepare a small source bank; do not leave Grade 6 students to search the open web without guidance.", "Confirm which products and individual reflection will be assessed.", "Decide which paper, audio, video, model, or interactive routes are available and what evidence must be visible outside the final product."],
    teacherMoves: ["Conference on evidence quality before product design.", "Ask who is affected, who is missing, and who has decision-making authority.", "Require one limitation and one unanswered question.", "Assess Social Studies, ELA, and Arts/ADST evidence separately."],
    lookFors: ["The question is focused and researchable.", "At least three different sources do different work.", "The recommendation follows from the evidence and acknowledges trade-offs.", "Each student’s reflection reveals individual understanding and contribution."],
    misconceptions: ["More links automatically mean stronger research.", "A polished digital or physical product proves the Social Studies thinking.", "The most popular option is the most ethical.", "A recommendation must solve the whole issue."],
    lowerPrep: "Use one common class question and a teacher-curated six-source set. Students may produce a two-page case file or three-minute audio explanation instead of a large project.",
    evidenceLevel: "Portfolio Highlight",
    evidenceSubjects: ["Social Studies", "English Language Arts", "Arts Education or ADST"],
    spacesUse: "required",
    spacesPrompt: "Post the final case file or link, then individually explain: Which source changed or complicated my thinking? What did I contribute? What remains uncertain?",
  },
  {
    id: "power-in-the-room",
    unitId: "power-rights-government",
    title: "Power is already in the room",
    question: "Who gets to decide, who can shape the choice, and how could the rules become fairer?",
    duration: "2 × 55–65 min",
    kind: "Power simulation",
    learning: "We are learning that power can come from making the final choice, holding resources, knowing important information, or being taken seriously.",
    success: ["I can show who made the final choice, held the tokens, knew important information, and lived with the result.", "I can use one moment from the game to explain what felt fair or unfair.", "I can change one rule and explain whose power changed."],
    vocabulary: ["power", "authority", "legitimacy", "accountability", "influence", "stakeholder"],
    scenes: [
      { label: "Play", title: "Build the room with unequal roles", prompt: "In groups of four, follow one private role card and use ten counters to build a community room. The screen gives every step and a six-minute timer. Do not reveal the role cards until the first plan is finished.", time: "20–25 min", learningMode: "Projector-guided simulation · paper plan · private roles", studentTask: "One room plan and notes about who could decide, move resources, share information, and be heard" },
      { label: "Name", title: "Who decides, influences, benefits, and carries the cost?", prompt: "Reconstruct the simulation. Sort each role by formal authority, informal influence, access to information, resources, and exposure to consequences.", time: "30–35 min", learningMode: "Power mapping · evidence talk", studentTask: "An annotated power map" },
      { label: "Judge", title: "Does the process earn people’s trust?", prompt: "Check six things: Who had a voice? Could people see what happened? Were reasons given? Were rights protected? Could someone challenge the decision? Who had to answer for mistakes? Use examples to decide what was fair and what was missing. This is a legitimacy check.", time: "35–40 min", learningMode: "Fairness check · structured disagreement", studentTask: "An evidence-backed fairness check" },
      { label: "Redesign", title: "Change the process, then test it again", prompt: "Alter one rule, role, information flow, or appeal pathway. Run a second round and compare whose power and outcomes changed.", time: "35–45 min", learningMode: "Civic design · replay · comparison", studentTask: "A before-and-after process redesign" },
    ],
    resources: [
      { label: "Levels and branches of government", type: "Website", url: "https://learn.parl.ca/understanding-comprendre/en/canada-system-of-government/levels-of-government/", source: "Parliament of Canada", purpose: "Connect the classroom power map to formal responsibilities in Canada without treating government as the only source of power.", gradeFit: "Core Grade 6" },
      { label: "How Parliament works", type: "Website", url: "https://learn.parl.ca/understanding-comprendre/en/canada-system-of-government/", source: "Parliament of Canada", purpose: "Teacher-selected background on representation, institutions, and accountability.", gradeFit: "Teacher preview" },
    ],
    materials: ["Printable four-role card set from the lesson screen", "10 counters, blocks, or paper squares per group", "One sheet of paper per group", "Pencil or marker", "Optional fifth-student observer card"],
    beforeClass: ["Open Part 1 in Plan view and print one role-card set per group. Cut the four playing cards; use the optional observer card for groups of five.", "Put ten counters, blocks, or paper squares and one planning page at each group.", "Keep the simulation fictional and low stakes; never assign disadvantage by student identity.", "Tell students the room design is not being graded. The purpose is to notice how rules distribute power.", "Allow students to observe instead of role-play, and debrief before judging fairness."],
    teacherMoves: ["Ask what specific rule or resource created the power difference.", "Separate having power from using it ethically.", "Invite students to challenge the criteria and justify additions.", "Make room for withdrawal, private reflection, and multiple participation modes."],
    lookFors: ["Students name mechanisms of power rather than only powerful people.", "Claims about fairness use agreed criteria and evidence.", "Redesigns change a process, not merely promise nicer behaviour.", "Students notice who lacks voice or appeal."],
    misconceptions: ["Power only means being the official leader.", "A vote automatically makes every decision fair.", "Authority and legitimacy are the same thing.", "People without formal authority have no power."],
    lowerPrep: "Read a fictional decision scenario instead of running the simulation. Map the roles together, then have pairs audit and redesign the process.",
    evidenceLevel: "Practice",
    evidenceSubjects: ["Social Studies", "English Language Arts", "Career Education"],
    spacesUse: "none",
    spacesPrompt: "No post required. Keep the before-and-after power map as possible evidence for the unit civic case.",
  },
  {
    id: "compare-government-systems",
    unitId: "power-rights-government",
    title: "Same crisis, different systems",
    question: "How can the structure of a government change who decides, how quickly it acts, and how people can respond?",
    duration: "2 × 55–65 min",
    kind: "Government systems lab",
    learning: "We are learning to compare systems through decision rules, distribution of power, accountability, rights protections, and civic participation—not through simple country labels.",
    success: ["I can compare systems using the same criteria.", "I can explain a trade-off without ranking one system by speed alone.", "I can distinguish a system model from the complex reality of a country."],
    vocabulary: ["democracy", "authoritarian", "constitutional", "federal", "unitary", "representation"],
    scenes: [
      { label: "Launch", title: "A decision cannot wait", prompt: "A fictional community faces a water emergency. Identify essential needs, make a first prediction, and decide which criteria matter before comparing systems.", time: "15–20 min", learningMode: "Visual scenario · prediction · criteria reveal", studentTask: "A first response and one uncertainty" },
      { label: "Relay", title: "Follow the decision path", prompt: "Run the same water emergency through three simplified decision models: one leader acts, representatives decide, and a community vote. Rotate roles and trace warning, decision, action, and review.", time: "35–40 min", learningMode: "Tabletop decision relay · role rotation · cross-teach", studentTask: "One team decision path and oral cross-teach" },
      { label: "Compare", title: "Fast for whom? Accountable to whom?", prompt: "Place each model on a class wall for speed, public voice, clear reasons, rights checks, and ways to correct mistakes. Support every placement with a model feature.", time: "30–35 min", learningMode: "Movement scoreboard · evidence conference", studentTask: "A class comparison wall and one defended trade-off" },
      { label: "Layer", title: "Canada is a layered system", prompt: "Build Canada as a combination of representative parliamentary democracy, constitutional monarchy, federalism, and Charter/court/public checks. Revise claims that put real countries into one simple box.", time: "30–35 min", learningMode: "System stack · official game · misconception repair", studentTask: "A labelled Canada system stack and one revised comparison" },
    ],
    resources: [
      { label: "Canada’s system of government", type: "Website", url: "https://learn.parl.ca/understanding-comprendre/en/canada-system-of-government/", source: "Parliament of Canada", purpose: "Use Canada as one evidence-rich case for representation, constitutional monarchy, federalism, and responsible government.", gradeFit: "Core Grade 6" },
      { label: "Levels of Government game", type: "Website", url: "https://learn.parl.ca/en/games/game4/index.html", source: "Parliament of Canada", purpose: "Use the official drag-and-drop game to check which level of government is responsible for familiar services and decisions.", gradeFit: "Core Grade 6" },
      { label: "Democracy education resources", type: "Website", url: "https://education.elections.ca/", source: "Elections Canada", purpose: "Select non-partisan classroom material about elections, participation, and democratic decision-making.", gradeFit: "Teacher preview" },
    ],
    materials: ["Fictional emergency brief", "Four system-card sets", "Decision-path arrows", "Comparison matrix", "Teacher-curated country snapshots"],
    beforeClass: ["Teach system features without assigning students to defend real authoritarian abuses.", "Use fictional models first, then carefully sourced real examples.", "Avoid democracy-versus-dictatorship worksheets that erase hybrid systems and lived complexity.", "Check current institutional facts before using any country example."],
    teacherMoves: ["Require the same criteria across every comparison.", "Ask who can challenge a decision and what happens next.", "Interrupt country stereotypes and overgeneralizations.", "Treat speed, stability, participation, and rights as possible trade-offs—not a single score."],
    lookFors: ["Students trace actual decision pathways.", "Comparisons name structures and mechanisms.", "Students qualify claims about real countries.", "Students distinguish government level, branch, and system."],
    misconceptions: ["All democracies work the same way.", "Elections alone guarantee democracy and rights.", "Authoritarian systems are always faster at every stage.", "A constitutional monarchy gives the monarch everyday governing power."],
    lowerPrep: "Model two fictional systems as a class, then use a common comparison matrix and one carefully selected Canada snapshot.",
    evidenceLevel: "Practice",
    evidenceSubjects: ["Social Studies", "English Language Arts"],
    spacesUse: "none",
    spacesPrompt: "No SpacesEDU post. Photograph a strong team decision path only if it will help with the final civic challenge.",
  },
  {
    id: "rights-in-tension",
    unitId: "power-rights-government",
    title: "Who gets the park after dark?",
    question: "How can a city make a fair decision when one shared place affects people in different ways?",
    duration: "2 × 55–65 min",
    kind: "Public decision lab",
    learning: "We are learning that a fair public decision listens to people affected, uses evidence, explains what each option may change, and can be revised if it is not working.",
    success: ["I can explain how one rule affects several groups.", "I can separate what we know, need to ask, and need to hear.", "I can recommend a plan using a fact and a real check-back."],
    vocabulary: ["public space", "power", "evidence", "fair process", "review"],
    scenes: [
      { label: "Notice", title: "Who lives with the decision?", prompt: "Meet the fictional Juniper Park night-court decision. Predict and reveal how four groups could be affected before deciding what you think.", time: "20–25 min", learningMode: "Whole-class prediction · impact reveal · talk", studentTask: "A whole-class impact picture" },
      { label: "Listen", title: "Hear the park. Build the evidence wall.", prompt: "Read four community voices, paraphrase each fairly, then sort six clues into what we know, need to ask, or need to hear.", time: "30–35 min", learningMode: "Reader voices · class evidence wall · paper notes", studentTask: "A class wall of facts, questions, and voices" },
      { label: "Improve", title: "Choose a starting plan. Make it stronger.", prompt: "Compare three realistic city responses. Choose one the class can both defend and question, then add one fairness improvement.", time: "30–35 min", learningMode: "Option comparison · class choice · rule redesign", studentTask: "A testable first plan and one improvement" },
      { label: "Recommend", title: "Build a 30-second council recommendation.", prompt: "Choose a supporting fact and a check-back plan. Build the class recommendation, then improve one sentence on paper.", time: "30–35 min", learningMode: "Shared oral recommendation · paper revision", studentTask: "A short recommendation with evidence and a way to revise the rule" },
    ],
    resources: [
      { label: "Universal Declaration of Human Rights", type: "Website", url: "https://www.un.org/en/about-us/universal-declaration-of-human-rights", source: "United Nations", purpose: "Use selected articles as a global rights source and compare their language with student interpretations.", gradeFit: "Supported stretch" },
      { label: "Guide to the Canadian Charter", type: "Website", url: "https://www.canada.ca/en/canadian-heritage/services/how-rights-protected/guide-canadian-charter-rights-freedoms.html", source: "Government of Canada", purpose: "Provide accessible explanations of Charter freedoms, equality, democratic rights, and reasonable limits.", gradeFit: "Core Grade 6" },
      { label: "BC Human Rights Code and education", type: "Website", url: "https://bchumanrights.ca/human-rights/human-rights-in-bc/", source: "BC’s Office of the Human Rights Commissioner", purpose: "Connect broad rights language to protections and responsibilities in British Columbia.", gradeFit: "Teacher preview" },
    ],
    materials: ["One shared projector", "Scrap paper or sticky notes", "Pencils and colours", "Optional printed voice and evidence cards"],
    beforeClass: ["Open the Juniper Park case and test the four scenes.", "Decide whether students will answer by talk, hand signals, sticky notes, or paper cards.", "Keep the case fictional and do not ask students to disclose personal conflict or discrimination."],
    teacherMoves: ["Keep returning to the people who live with the decision—not only the loudest argument.", "Ask students to separate a stated fact from a question or a voice the city still needs.", "Treat every city option as a starting plan that can be questioned and improved.", "End with a review plan so students see that public rules can change when evidence shows they should."],
    lookFors: ["Students can explain how the same rule affects more than one group.", "Students paraphrase a different view fairly before responding.", "Recommendations use at least one case fact.", "The class includes a clear way to check what happened and revise the rule."],
    misconceptions: ["Fair means everybody gets exactly what they first wanted.", "The group with the most votes is the only group that matters.", "One complaint or one popular post proves what the city should do.", "Once government makes a rule, the rule cannot be questioned or changed."],
    lowerPrep: "Project all four scenes and build one recommendation orally as a class. Students improve one sentence on paper at the end; no printed package or individual device is required.",
    evidenceLevel: "Checkpoint",
    evidenceSubjects: ["Social Studies", "English Language Arts", "Career Education"],
    spacesUse: "none",
    spacesPrompt: "No separate SpacesEDU post. Keep the class recommendation as practice for the later civic decision brief.",
  },
  {
    id: "civic-decision-brief",
    unitId: "power-rights-government",
    title: "Civic decision brief",
    question: "How should a government respond to a public issue while sharing power, protecting rights, and remaining accountable?",
    duration: "3 × 55–65 min + optional ELA/Arts studio",
    kind: "Performance task",
    learning: "We are combining power analysis, government structure, rights evidence, perspectives, and consequences to make a defensible civic recommendation.",
    success: ["I can identify the responsible level or institution and its limits.", "I can use credible sources to analyze power, rights, perspectives, and consequences.", "I can recommend an accountable response with safeguards, review, and a serious limitation."],
    vocabulary: ["jurisdiction", "public policy", "representation", "safeguard", "remedy", "civic participation"],
    scenes: [
      { label: "Choose", title: "Make the public question specific", prompt: "Choose a teacher-approved fictional or low-risk public issue. Name the decision, responsible level of government, affected people, rights questions, and evidence needed.", time: "30–35 min", learningMode: "Issue clinic · jurisdiction check", studentTask: "A focused civic question and research plan" },
      { label: "Investigate", title: "Build the power-and-rights file", prompt: "Use at least three meaningfully different sources. Map formal authority, influence, affected perspectives, rights claims, and missing voices.", time: "55–65 min", learningMode: "Curated research · source conference", studentTask: "An annotated evidence and power map" },
      { label: "Deliberate", title: "Test more than one response", prompt: "Compare options for effectiveness, rights impacts, fairness, feasibility, intended and unintended consequences, safeguards, review, and appeal.", time: "45–50 min", learningMode: "Deliberative forum · option matrix", studentTask: "A transparent options analysis" },
      { label: "Recommend", title: "Make accountability part of the plan", prompt: "Create a council brief, short speech, podcast, poster, slide deck, video, or model. State what should happen, why, who is responsible, how rights are protected, and how the decision can be reviewed.", time: "55–65 min", learningMode: "Choice product · peer hearing · revision", studentTask: "A revised civic decision brief" },
      { label: "Reflect", title: "Show the thinking that belongs to you", prompt: "Individually explain which evidence or counterargument changed your thinking, what you contributed, and how a person could participate responsibly after the decision.", time: "20–25 min", learningMode: "Individual reflection · SpacesEDU", studentTask: "A personal evidence-and-participation reflection" },
    ],
    resources: [
      { label: "Levels of government", type: "Website", url: "https://learn.parl.ca/understanding-comprendre/en/canada-system-of-government/levels-of-government/", source: "Parliament of Canada", purpose: "Identify which level is responsible before recommending action.", gradeFit: "Core Grade 6" },
      { label: "Elections and Democracy", type: "Website", url: "https://electionsanddemocracy.ca/", source: "Elections Canada", purpose: "Explore non-partisan participation, elections, and ways citizens influence democratic life.", gradeFit: "Core Grade 6" },
      { label: "Surrey City Council", type: "Website", url: "https://www.surrey.ca/city-government/city-council", source: "City of Surrey", purpose: "Use a local public institution to examine roles, meetings, decisions, and participation pathways.", gradeFit: "Core Grade 6" },
    ],
    materials: ["Teacher-approved issue menu", "Jurisdiction guide", "Source-record sheet", "Power-and-rights map", "Options matrix", "Choice-product materials", "SpacesEDU prompt"],
    beforeClass: ["Offer several low-risk issues with sufficient credible sources and a fictional alternative.", "Confirm the responsible jurisdiction and current facts for every option.", "Avoid grading students on agreement with a political position.", "Decide which shared artifact and individual evidence will be assessed in each subject."],
    teacherMoves: ["Conference on jurisdiction and source quality before product design.", "Ask where power sits, how it is checked, and who can appeal.", "Require one serious counterargument and one safeguard.", "Assess Social Studies reasoning, ELA communication, and other subject evidence separately."],
    lookFors: ["The recommendation addresses an institution that can actually act.", "Rights claims are specific and sourced.", "Options include consequences, safeguards, review, and participation.", "Individual reflections reveal thinking beyond the shared product."],
    misconceptions: ["The federal government controls every public issue.", "The loudest or most popular view is automatically most democratic.", "A petition by itself guarantees change.", "Protecting rights removes the need to consider consequences or accountability."],
    lowerPrep: "Use one shared fictional issue and a six-source class set. Students create a two-page brief or three-minute recorded recommendation with an individual reflection.",
    evidenceLevel: "Portfolio Highlight",
    evidenceSubjects: ["Social Studies", "English Language Arts", "Career Education"],
    spacesUse: "required",
    spacesPrompt: "Post the final civic brief or link, then individually explain: What evidence or counterargument changed my thinking? What did I contribute? How could someone participate responsibly next?",
  },
  {
    id: "city-moves",
    unitId: "global-systems",
    title: "City Moves: four stories, one changing city",
    question: "Why do people move, and how can movement change both people and places?",
    duration: "2 × 55–65 min",
    kind: "Story-map challenge",
    learning: "We are learning to distinguish kinds and reasons for movement, trace interacting causes and consequences, and show change and continuity without reducing people to statistics.",
    success: ["I can distinguish movement within a country from movement across borders.", "I can connect several reasons for moving without assuming every story is the same.", "I can use a timeline and map to explain what changed, what continued, and what a city may need."],
    vocabulary: ["migration", "urbanization", "internal migration", "international migration", "refugee", "continuity"],
    scenes: [
      { label: "Meet", title: "Four stories, four different routes", prompt: "Read four teacher-curated, age-appropriate movement stories. Place route strings on a floor map, then distinguish internal and international movement and voluntary and forced movement without ranking the stories.", time: "25–30 min", learningMode: "Story cards · floor map · evidence sort", studentTask: "A mapped route and evidence-based movement labels" },
      { label: "Connect", title: "One move can have many reasons", prompt: "Build a reason web around each story using only stated evidence: work, study, family, safety, housing, environment, services, or another documented reason. Keep unknowns visible.", time: "30–35 min", learningMode: "Reason-web challenge · source checking", studentTask: "A multi-cause web with one honest unknown" },
      { label: "Change", title: "A changing city feels the movement", prompt: "Add housing, transit, school, health, work, language, and gathering-place consequence cards to the city board. Trace a short-term and long-term effect, including one possible unintended result.", time: "35–40 min", learningMode: "City-service board · consequence dominoes", studentTask: "A cause-and-consequence route through the city" },
      { label: "Time", title: "What changed—and what continued?", prompt: "Create a before–during–after timeline for one story and its city. Defend why the change matters, show one important continuity, and name evidence still needed.", time: "30–35 min", learningMode: "Timeline studio · significance defence", studentTask: "A change-and-continuity timeline with a significance claim" },
    ],
    resources: [
      { label: "Teaching materials ages 9–12", type: "Website", url: "https://www.unhcr.org/what-we-do/build-better-futures/education/teaching-about-refugees/teaching-materials-ages-9-12", source: "UNHCR", purpose: "Select age-appropriate definitions and real stories while protecting student privacy and distinguishing refugee experiences from migration generally.", gradeFit: "Teacher preview" },
      { label: "World Urbanization Prospects 2025", type: "Data profile", url: "https://www.un.org/development/desa/pd/world-urbanization-prospects-2025", source: "United Nations Population Division", purpose: "Use current global evidence about changes in cities, towns, and rural populations; attach the year and definition to every number.", gradeFit: "Supported stretch" },
    ],
    materials: ["Large world or regional floor map", "Four teacher-curated movement story cards", "Route string", "Reason and city-service cards", "Timeline strips"],
    beforeClass: ["Choose stories from trusted sources that preserve agency and do not centre graphic trauma.", "Never ask students to disclose why their own family moved.", "Prepare an alternate way to participate without reading a refugee story aloud.", "Check every route, date, and definition before teaching."],
    teacherMoves: ["Use person-first, specific language and distinguish migrant, refugee, asylum seeker, and internally displaced person carefully.", "Ask which detail supports every cause or label.", "Refuse single-cause stories and deficit descriptions of newcomers.", "Keep both change and continuity visible."],
    lookFors: ["Students use the story evidence instead of stereotypes.", "Cause webs include interacting reasons and unknowns.", "Consequences include people and city systems.", "Significance claims explain why a change matters and to whom."],
    misconceptions: ["Everyone who crosses a border is a refugee.", "People move for only one reason.", "Migration only changes the destination.", "Growing cities automatically improve or worsen life for everyone."],
    lowerPrep: "Project one UNHCR story and one simplified city map. Build a whole-class route, reason web, and before–during–after timeline before students defend one consequence orally.",
    evidenceLevel: "Practice",
    evidenceSubjects: ["Social Studies", "English Language Arts"],
    spacesUse: "none",
    spacesPrompt: "No SpacesEDU post. Keep the timeline or one strong cause web as a possible inquiry reference.",
  },
  {
    id: "data-skyline",
    unitId: "global-systems",
    title: "The Data Skyline: inequality is not one number",
    question: "What can averages reveal—and what can they hide about poverty and inequality?",
    duration: "2 × 55–65 min",
    kind: "Physical data lab",
    learning: "We are learning to read poverty and inequality data in context, compare dimensions and groups within places, and avoid turning country averages into judgments about people.",
    success: ["I can build and read a physical data display accurately.", "I can explain what an average shows and what it may hide.", "I can compare class, gender, wealth, and urban–rural patterns without ranking people or countries."],
    vocabulary: ["poverty", "inequality", "average", "indicator", "multidimensional", "disaggregate"],
    scenes: [
      { label: "Build", title: "Raise a data skyline", prompt: "Use teacher-prepared tiles from a dated official dataset to build a physical skyline. Match each height to its indicator, unit, place, year, and source before making any claim.", time: "30–35 min", learningMode: "Data tiles · physical visualization · accuracy check", studentTask: "One labelled data skyline" },
      { label: "Match", title: "Solve the mystery profile", prompt: "Match evidence cards to anonymized profiles. Explain which clues fit, which do not, and why one number cannot describe a whole place or person.", time: "25–30 min", learningMode: "Mystery match · evidence defence", studentTask: "A defended match and one rejected assumption" },
      { label: "Open", title: "Look inside the average", prompt: "Replace one overall bar with data split by wealth, gender, or urban–rural location. Mark a gap, ask what may help explain it, and avoid claiming cause from a pattern alone.", time: "35–40 min", learningMode: "Within-place comparison · data annotation", studentTask: "An annotated comparison showing what the average hid" },
      { label: "Qualify", title: "Write the caption the data deserves", prompt: "Create a two-sentence evidence caption: one precise supported claim and one limitation or missing dimension. Audit another team for labels, context, and respectful language.", time: "25–30 min", learningMode: "Caption studio · peer data audit", studentTask: "A sourced claim with a visible limit" },
    ],
    resources: [
      { label: "Poverty and Inequality Platform", type: "Data profile", url: "https://pip.worldbank.org/", source: "World Bank", purpose: "Prepare a small, dated dataset and definitions; do not send students into an unguided country-ranking task.", gradeFit: "Teacher preview" },
      { label: "Multidimensional Poverty Measure", type: "Article", url: "https://www.worldbank.org/en/topic/poverty/brief/multidimensional-poverty-measure", source: "World Bank", purpose: "Show why income alone cannot capture every dimension of poverty and why indicators must be interpreted together.", gradeFit: "Supported stretch" },
      { label: "UNICEF Data", type: "Data profile", url: "https://data.unicef.org/", source: "UNICEF", purpose: "Select child-centred education, health, water, or gender data that can be disaggregated and discussed without deficit framing.", gradeFit: "Teacher preview" },
    ],
    materials: ["Pre-cut skyline tiles or linking cubes", "Teacher-prepared data cards", "Large axis labels", "Mystery profiles", "Caption cards"],
    beforeClass: ["Use a tiny curated dataset with visible year, unit, definition, and source.", "Choose within-country comparisons so national averages are not treated as portraits of everyone.", "Avoid poverty simulations, country competitions, and images that strip people of dignity.", "Check whether missing data means zero, unavailable, or not comparable."],
    teacherMoves: ["Ask what the indicator actually measures before discussing why a gap exists.", "Interrupt causal claims that the data cannot support.", "Use people and communities as agents, not problems to solve.", "Invite multiple explanations and evidence still needed."],
    lookFors: ["Every bar has a unit, year, place, and source.", "Students distinguish pattern from cause.", "Captions expose at least one hidden average or limitation.", "Comparisons remain precise and respectful."],
    misconceptions: ["An average describes every person in a place.", "A lower number proves people made worse choices.", "Income is the only dimension of poverty.", "Missing data means nothing happened."],
    lowerPrep: "Build one class skyline from six teacher-prepared cards, then reveal two within-place splits and co-write one accurate caption plus limitation.",
    evidenceLevel: "Practice",
    evidenceSubjects: ["Social Studies", "Mathematics"],
    spacesUse: "none",
    spacesPrompt: "No SpacesEDU post. Photograph a class display only if it will support a team’s later inquiry.",
  },
  {
    id: "supply-chain-shockwave",
    unitId: "global-systems",
    title: "Who Made My Stuff? Supply-Chain Shockwave",
    question: "How do trade, resource decisions, work, and self-interest connect people—and create conflict?",
    duration: "2 × 55–65 min",
    kind: "Trade-web simulation",
    learning: "We are learning to trace economic interdependence, explain how self-interest and policy shape resource decisions, and evaluate effects on workers, communities, Indigenous Peoples, and environments.",
    success: ["I can trace a familiar product through several connected places and decisions.", "I can explain how a disruption affects more than one part of a system.", "I can compare benefits, costs, rights, and trade-offs before redesigning one link."],
    vocabulary: ["interdependence", "supply chain", "trade", "economic policy", "resource management", "self-interest"],
    scenes: [
      { label: "Trace", title: "Build the hidden web", prompt: "Use component, material, transport, work, and sales cards to build the route of a familiar product. Connect each step with string and mark who makes a decision there.", time: "30–35 min", learningMode: "Product cards · string web · decision mapping", studentTask: "A labelled supply-chain web" },
      { label: "Ripple", title: "Send a shockwave through it", prompt: "Draw a disruption card—shipping delay, crop loss, price change, labour-rights concern, policy change, or conflict. Trace at least three effects and identify who can adapt and who carries risk.", time: "30–35 min", learningMode: "System shock · consequence relay", studentTask: "A three-step ripple map with winners, costs, and uncertainty" },
      { label: "Examine", title: "Resource decisions are also rights decisions", prompt: "Study one named, dated Canadian resource case using a source from the affected Indigenous Nation or representative organization and a public decision source. Identify claimed benefits, specific effects, authority, consent or consultation questions, and missing evidence.", time: "35–45 min", learningMode: "Paired-source case · ethical audit", studentTask: "A specific resource-decision case card with attributed perspectives" },
      { label: "Redesign", title: "Improve one link—admit the trade-off", prompt: "Change one sourcing, policy, labour, transport, repair, reuse, or accountability rule. Run the shock again and explain who benefits, what new cost appears, and what would need monitoring.", time: "30–35 min", learningMode: "Resilience redesign · replay · pitch", studentTask: "One redesigned link and an honest trade-off" },
    ],
    resources: [
      { label: "Global Value Chains Dashboard", type: "Data profile", url: "https://stats.wto.org/dashboard/gvc_en.html", source: "World Trade Organization", purpose: "Use selected sector visuals to show that product value and production cross many borders; adapt the complexity for Grade 6.", gradeFit: "Teacher preview" },
      { label: "Canada’s State of Trade 2024: Supply chains", type: "Article", url: "https://www.international.gc.ca/transparency-transparence/state-trade-commerce-international/2024.aspx?lang=eng", source: "Global Affairs Canada", purpose: "Provide a Canadian evidence source about supply-chain connections, risks, and resilience.", gradeFit: "Teacher preview" },
      { label: "What is child labour?", type: "Article", url: "https://www.ilo.org/topics/child-labour/what-child-labour", source: "International Labour Organization", purpose: "Clarify labour-rights terms without asking students to impersonate exploited workers or assume all work by children is the same.", gradeFit: "Teacher preview" },
      { label: "First Nations Energy and Mining Council", type: "Website", url: "https://fnemc.ca/", source: "First Nations Energy and Mining Council", purpose: "Begin with an Indigenous-led source when preparing a specific B.C. resource-management case; never treat one organization as speaking for every Nation.", gradeFit: "Teacher preview" },
    ],
    materials: ["Product and component cards", "String", "Decision tokens", "Shockwave cards", "Teacher-curated Indigenous resource case pair", "Redesign cards"],
    beforeClass: ["Choose a familiar product with a traceable but simplified route and label every simplification.", "Prepare one specific resource case with a source from the named Nation or representative organization and one government or regulator source.", "Do not assign students exploited-worker roles or simulate unsafe working conditions.", "Avoid implying that one country, culture, or industry is uniformly abusive."],
    teacherMoves: ["Ask whose self-interest shapes each decision and when interests conflict.", "Separate documented effects from assumptions.", "Treat Indigenous Peoples as rights holders and decision-makers, not one stakeholder card.", "Require every redesign to reveal a new cost, limit, or monitoring need."],
    lookFors: ["Students trace material, labour, policy, and transport links.", "Shockwaves include intended and unintended consequences.", "The resource case names the Nation, sources, date, and limits.", "Redesigns improve a mechanism rather than promise better behaviour."],
    misconceptions: ["One country makes an entire product.", "Trade benefits or harms everyone equally.", "A cheaper product has no hidden costs.", "Consulting an Indigenous community is automatically the same as consent."],
    lowerPrep: "Build one T-shirt or backpack chain on the board, draw one shock card, then audit one teacher-curated resource case and redesign a single link as a class.",
    evidenceLevel: "Practice",
    evidenceSubjects: ["Social Studies", "ADST", "English Language Arts"],
    spacesUse: "none",
    spacesPrompt: "No SpacesEDU post. Carry one systems insight or unresolved resource question into the team inquiry.",
  },
  {
    id: "cooperation-control-room",
    unitId: "global-systems",
    title: "No One Solves It Alone: Cooperation Control Room",
    question: "Why do international problems and conflicts require cooperation—and why is cooperation still difficult?",
    duration: "2 × 55–65 min",
    kind: "Cooperation control room",
    learning: "We are learning to compare the roles and limits of governments, Indigenous organizations, NGOs, and international bodies while building an evidence-based response to a cross-border problem.",
    success: ["I can explain what different organizations can contribute and what limits them.", "I can use more than one source to compare coverage of the same event or conflict.", "I can build a cooperative plan with shared responsibilities, trade-offs, and a way to review it."],
    vocabulary: ["international cooperation", "conflict", "non-governmental organization", "Indigenous organization", "mandate", "agreement"],
    scenes: [
      { label: "Brief", title: "Same event, different coverage", prompt: "Compare two current, teacher-curated reports about the same safe regional or international issue. Mark shared facts, different emphasis, source purpose, and important missing context before entering the fictional control room.", time: "20–25 min", learningMode: "Authentic media comparison · lateral reading", studentTask: "A same-facts/different-frame source card" },
      { label: "Assign", title: "Every group has capacity—and limits", prompt: "Study the clearly labelled fictional river-basin challenge. Teams receive different mandates, knowledge, resources, and limits as a community or Indigenous organization, local or national government, NGO, or UN agency. No team can meet every success criterion alone.", time: "25–30 min", learningMode: "Fictional visual brief · capacity cards · planning", studentTask: "A capacity-and-limit board" },
      { label: "Negotiate", title: "Build an agreement that can survive pressure", prompt: "Share evidence and resources to address water, food, health, rights, and conflict pressures. Add one constraint card, revise responsibilities, and record where interests still clash.", time: "35–40 min", learningMode: "Control-room negotiation · constraint reveal", studentTask: "A shared agreement map with unresolved tension" },
      { label: "Audit", title: "Cooperation is not automatic success", prompt: "Compare two response plans for evidence, representation, fairness, feasibility, accountability, and unintended effects. Add one cooperation patch and a review signal that would show whether it works.", time: "30–35 min", learningMode: "Plan audit · cooperation patch · debrief", studentTask: "A revised cooperation plan and one measurable review signal" },
    ],
    resources: [
      { label: "Sustainable Development Goals", type: "Website", url: "https://sdgs.un.org/goals", source: "United Nations", purpose: "Select a small set of connected goals and targets; use them as criteria, not as proof that a plan will work.", gradeFit: "Supported stretch" },
      { label: "United Nations News", type: "Website", url: "https://news.un.org/en/", source: "United Nations", purpose: "Pair one dated report with independent coverage of the same event so students can compare facts, emphasis, purpose, and omissions.", gradeFit: "Teacher preview" },
      { label: "ICRC mandate and mission", type: "Website", url: "https://www.icrc.org/en/our-mandate-and-mission", source: "International Committee of the Red Cross", purpose: "Clarify one humanitarian organization’s specific mandate and limits in conflict; do not present NGOs as rescuers with unlimited authority.", gradeFit: "Teacher preview" },
    ],
    materials: ["Fictional river-basin image", "Organization mandate cards", "Evidence and resource tokens", "Constraint cards", "Agreement map", "Two current source excerpts"],
    beforeClass: ["Choose a current issue safe enough for the class and save two dated excerpts before teaching.", "Keep the simulation fictional; do not ask students to reenact war, displacement, or affected identities.", "Name specific organizations and mandates rather than using a generic helper role.", "Make an observer or evidence-analyst role available."],
    teacherMoves: ["Ask what each source emphasizes and why.", "Distinguish coordination from agreement and agreement from success.", "Avoid portraying communities, NGOs, the UN, or wealthy states as automatic rescuers.", "Require shared authority, accountability, and review."],
    lookFors: ["Students compare authentic coverage before making a claim.", "Plans depend on several actors for specific reasons.", "Conflicts of interest and limits remain visible.", "The review signal could reveal success or harm."],
    misconceptions: ["The United Nations is a world government.", "NGOs can act anywhere without permission or limits.", "Cooperation means everyone agrees.", "Signing an agreement proves the problem is solved."],
    lowerPrep: "Compare two short reports as a class, then give four table groups one shared fictional challenge and distinct capacity cards. Build one agreement and pressure-test it together.",
    evidenceLevel: "Checkpoint",
    evidenceSubjects: ["Social Studies", "English Language Arts", "Career Education"],
    spacesUse: "none",
    spacesPrompt: "No default post. Carry one team systems map and a 60-second individual explanation forward locally as a draft to revise in Unit 4.",
  },
  {
    id: "pull-the-system-thread",
    unitId: "solutionary-inquiry",
    title: "Pull the System Thread",
    question: "What keeps this issue going, and where might change travel through the system?",
    duration: "2 × 55–65 min",
    kind: "Systems-web studio",
    learning: "We are learning to separate symptoms, contributing causes, root conditions, power, and decision points, then predict intended and unintended effects of change.",
    success: ["I can build a connected system map from evidence.", "I can explain why the issue is significant and to whom.", "I can change one condition, trace several effects, and state an honest limit."],
    vocabulary: ["system", "symptom", "root cause", "leverage point", "significance", "unintended consequence"],
    scenes: [
      { label: "Reopen", title: "Return to the question—not the old answer", prompt: "Reopen one saved inquiry seed and source trail. Restate the issue, who is affected, why it matters, and what your team no longer assumes.", time: "25–30 min", learningMode: "Inquiry reset · significance conference", studentTask: "A focused question and defended significance statement" },
      { label: "Web", title: "Map what happened and what keeps it going", prompt: "Build a floor or wall web from symptoms to contributing causes, root conditions, power or decision points, and affected people. Attach evidence tags instead of relying on memory.", time: "40–45 min", learningMode: "Yarn systems web · evidence tagging", studentTask: "A sourced systems map" },
      { label: "Tug", title: "Change one condition and trace the effects", prompt: "Draw a change card and alter one policy, resource, information flow, incentive, relationship, or decision point. Trace three effects, including one unintended result or new tension.", time: "30–35 min", learningMode: "Leverage test · consequence tracing", studentTask: "A three-effect change path" },
      { label: "Focus", title: "Choose a leverage question, not a magic fix", prompt: "Select one place where further investigation could matter. Write a leverage question, evidence still needed, people who should shape the decision, and one limit to your current model.", time: "25–30 min", learningMode: "Question clinic · model revision", studentTask: "A revised system map and leverage question" },
    ],
    resources: [],
    materials: ["Saved inquiry seeds and source trails", "Yarn or movable arrows", "Symptom/cause/power cards", "Evidence tags", "Change cards"],
    beforeClass: ["Approve one manageable team question and assemble saved evidence before the web begins.", "Prepare examples that distinguish a symptom from a cause and a cause from a moral judgment.", "Offer a tabletop version for students who prefer not to work on the floor."],
    teacherMoves: ["Ask what evidence supports every connection.", "Keep significance, power, and affected perspectives in the web.", "Challenge single root-cause claims in complex systems.", "Reward revision when the model cannot support a confident answer."],
    lookFors: ["Connections are evidence tagged.", "Students distinguish symptom, cause, condition, and decision point.", "Significance is defended rather than announced.", "Change paths include limits or unintended effects."],
    misconceptions: ["A complex issue has one root cause.", "The most visible symptom is the cause.", "A leverage point guarantees a solution.", "A complicated-looking web is automatically accurate."],
    lowerPrep: "Build one shared web from a common case, then have each team annotate where its own inquiry may connect and write one leverage question.",
    evidenceLevel: "Practice",
    evidenceSubjects: ["Social Studies", "English Language Arts"],
    spacesUse: "none",
    spacesPrompt: "No SpacesEDU post. This is a working map that should change as the team learns more.",
  },
  {
    id: "responses-under-pressure",
    unitId: "solutionary-inquiry",
    title: "Responses Under Pressure",
    question: "What can existing responses teach us—even when none is a perfect solution?",
    duration: "2 × 55–65 min",
    kind: "Response lab",
    learning: "We are learning to compare real responses across scales, weigh evidence and impacts, and borrow ideas carefully instead of crowning a perfect solution.",
    success: ["I can compare relief, prevention, and system change without assuming one label makes a response better.", "I can test who benefits, who carries costs, and what evidence exists.", "I can keep, adapt, or question one feature and explain why."],
    vocabulary: ["response", "prevention", "scale", "feasibility", "design principle", "unintended consequence"],
    scenes: [
      { label: "Discover", title: "Three real responses, three different scales", prompt: "Visit three teacher-curated stations connected to your inquiry. Identify the actor, goal, action, evidence of effect, scale, and stated limit at each.", time: "35–40 min", learningMode: "Source stations · response discovery", studentTask: "Three concise response records" },
      { label: "Sort", title: "Relief, prevention, or system change?", prompt: "Place each response on the floor spectrum. More than one label may apply. Defend placements with a feature of the response, then revise when another team offers stronger evidence.", time: "25–30 min", learningMode: "Movement spectrum · evidence challenge", studentTask: "A defended and revised response sort" },
      { label: "Pressure-test", title: "Add a constraint", prompt: "Test each response for evidence, reach, fairness, cost, feasibility, rights, and unintended effects. Draw one constraint card and show what changes.", time: "35–40 min", learningMode: "Constraint cards · consequence audit", studentTask: "A pressure-tested comparison with one serious limit" },
      { label: "Borrow", title: "Keep, adapt, or question", prompt: "Choose one feature to keep, adapt, or question. Turn the reasoning into an evidence-backed design principle for your teaching experience or action pathway.", time: "25–30 min", learningMode: "Design-principle studio · peer challenge", studentTask: "One carefully borrowed feature and design principle" },
    ],
    resources: [],
    materials: ["Three real response source stations per topic cluster", "Relief–prevention–system change floor line", "Pressure-test cards", "Constraint cards"],
    beforeClass: ["Cluster teams with related topics so three high-quality response stations can serve several groups.", "Include responses from different scales and actors, with evidence and criticism or limits.", "Do not require every team to find a separate set of sources during class."],
    teacherMoves: ["Ask what evidence shows a response did what it claims.", "Separate reach from effectiveness and popularity from fairness.", "Require attention to who benefits and who carries costs.", "Do not let a polished campaign stand in for an evaluated response."],
    lookFors: ["Students compare responses with common criteria.", "Sorts allow overlap and revision.", "Constraints change the judgment.", "Design principles are evidence based and qualified."],
    misconceptions: ["A large response is always more effective.", "Relief is inferior to prevention.", "A good intention proves positive impact.", "Finding a limitation means rejecting the entire response."],
    lowerPrep: "Use three shared whole-class response cards, run one floor sort, then pressure-test the same response with two different constraints.",
    evidenceLevel: "Practice",
    evidenceSubjects: ["Social Studies", "English Language Arts", "ADST"],
    spacesUse: "none",
    spacesPrompt: "No SpacesEDU post. Add the strongest comparison and design principle to the team’s working evidence passport.",
  },
  {
    id: "make-it-teachable",
    unitId: "solutionary-inquiry",
    title: "Make It Teachable Studio",
    question: "How can we turn deep research into an experience that helps classmates think?",
    duration: "4–5 × 55–65 min",
    kind: "Prototype studio",
    learning: "We are learning to choose a form that serves the learning, prototype before polishing, and pass an accuracy and evidence gate before production.",
    success: ["I can choose a format that fits what the audience must understand and do.", "I can build the same strong learning spine in any format.", "I can use feedback to revise accuracy and experience design—not just appearance."],
    vocabulary: ["prototype", "audience", "learning spine", "citation", "accuracy", "uncertainty"],
    scenes: [
      { label: "Match", title: "Match the form to the learning", prompt: "Choose what classmates must understand, feel ready to question, and do. Test whether a simulation, interactive digital story, podcast, mini-documentary, exhibit, model, live workshop, or another approved form genuinely serves that learning.", time: "35–40 min", learningMode: "Format audition · audience test", studentTask: "A justified format choice and learning sequence" },
      { label: "Prototype", title: "Make it on paper first", prompt: "Storyboard the opening, three essential understandings, evidence moments, perspective or power decision, audience action, and closing uncertainty before using production tools.", time: "55–65 min", learningMode: "Paper prototype · walkthrough", studentTask: "A complete low-fidelity teaching experience" },
      { label: "Verify", title: "Pass the accuracy gate", prompt: "Conference on claims, citations, source diversity, timeline, causes and consequences, significance, existing responses, affected perspectives, and limits. Correct weak claims before polish.", time: "40–50 min", learningMode: "Accuracy conference · evidence passport", studentTask: "An approved content-and-evidence passport" },
      { label: "Build", title: "Create the minimum viable experience", prompt: "Build only what classmates need to learn, think, decide, create, or respond. Make accessibility, roles, timing, citations, and a realistic action pathway visible.", time: "2 × 55–65 min", learningMode: "Choice production · teacher conferences", studentTask: "A testable teaching experience; production polish is not assessed" },
    ],
    resources: [],
    materials: ["Format audition cards", "Storyboard paper", "Evidence passport", "Prototype materials or approved digital tools", "Accessibility and timing checklist"],
    beforeClass: ["Approve topic scope, sources, and minimum viable format before devices or building materials open.", "Schedule short accuracy conferences and a realistic production deadline.", "Provide low-tech and non-performance options with equal status.", "Keep the evidence passport outside the final product so polish cannot hide weak understanding."],
    teacherMoves: ["Ask what classmates will do with the idea, not just what they will watch.", "Check accuracy before aesthetics.", "Protect affected people from reenactment, stereotyping, or trauma-as-entertainment.", "Assess subject understanding separately from technical polish."],
    lookFors: ["The form serves a clear learning goal.", "Every experience shares the full content spine.", "Claims are cited and limits visible.", "Classmates must think, decide, create, or respond."],
    misconceptions: ["A more complex build demonstrates deeper learning.", "Video, podcast, model, or digital polish is the Social Studies assessment.", "A list of facts is a teaching experience.", "Citations can be added after production."],
    lowerPrep: "Offer three forms—tabletop experience, paper exhibit, or short live workshop—and use one shared storyboard and evidence-passport template.",
    evidenceLevel: "Checkpoint",
    evidenceSubjects: ["Social Studies", "English Language Arts", "ADST", "Arts Education"],
    spacesUse: "none",
    spacesPrompt: "No SpacesEDU post yet. The prototype and evidence passport stay local until after audience testing and revision.",
  },
  {
    id: "expert-exchange",
    unitId: "solutionary-inquiry",
    title: "Audience Test Lab + Expert Exchange",
    question: "What did our audience actually learn, and how should that evidence change our teaching?",
    duration: "3–4 × 55–65 min",
    kind: "Expert teaching exchange",
    learning: "We are learning to test a teaching experience with a real audience, use feedback as evidence, revise content and design, and explain our own contribution and growth.",
    success: ["I can collect feedback that shows learning, confusion, and evidence needs.", "I can revise one content claim and one experience feature for clear reasons.", "I can teach accurately, answer questions, and reflect on my individual learning."],
    vocabulary: ["feedback", "teach-back", "revision", "contribution", "action pathway", "accountability"],
    scenes: [
      { label: "Test", title: "Run a cold test", prompt: "Another team completes your experience without a preview. Observe where they act, pause, misunderstand, ask for proof, or teach the idea back successfully; do not coach them through weak directions.", time: "55–65 min", learningMode: "Cold audience test · observation", studentTask: "Audience evidence: I learned / I got stuck / I need proof for" },
      { label: "Teach back", title: "Can the audience explain the heart of it?", prompt: "Testers teach back the main idea, significance, evidence, and one limit. Creators compare that explanation with the intended learning spine.", time: "30–35 min", learningMode: "Audience teach-back · gap analysis", studentTask: "A learning-gap map" },
      { label: "Revise", title: "Change one idea and one experience feature", prompt: "Correct or qualify one content claim and improve one direction, interaction, accessibility feature, or evidence moment. Record the audience signal behind each change.", time: "40–50 min", learningMode: "Evidence-led revision · final check", studentTask: "A before-and-after revision record" },
      { label: "Exchange", title: "Teach, respond, and reflect", prompt: "Run the final expert exchange, answer audience questions, and post the shared artifact or link once. Each student adds a brief audio, video, or text reflection showing understanding, contribution, revision, and a realistic action pathway with limits.", time: "2 × 55–65 min", learningMode: "Rotating teach-back · SpacesEDU reflection", studentTask: "One shared teaching product plus one individual SpacesEDU reflection" },
    ],
    resources: [],
    materials: ["Completed minimum viable experiences", "Three-signal feedback cards", "Observation notes", "Revision record", "SpacesEDU posting prompt"],
    beforeClass: ["Create a testing rotation with enough time for quiet reset and revision.", "Check privacy, permissions, accessibility, links, and media before posting.", "Decide what counts as the shared team artifact and how each student can reflect by audio, video, or text.", "Do not assess production polish as Social Studies understanding."],
    teacherMoves: ["Watch what the audience can explain, not how impressed they appear.", "Ask which audience signal caused each revision.", "Keep questions about uncertainty and contested evidence open.", "Assess individual understanding and contribution separately from the team artifact."],
    lookFors: ["Feedback describes learning rather than taste.", "Revisions include content and experience design.", "Teach-backs address significance, systems, evidence, perspectives, responses, and limits.", "Individual reflections show specific thinking beyond the group product."],
    misconceptions: ["Applause proves the audience learned.", "Revision means making it prettier.", "The strongest speaker did the most learning.", "Posting the group artifact is enough individual assessment."],
    lowerPrep: "Run paired team tests, require the same three feedback signals and two revisions, then hold shorter rotating teach-backs with one shared link and individual reflection.",
    evidenceLevel: "Portfolio Highlight",
    evidenceSubjects: ["Social Studies", "English Language Arts", "ADST", "Career Education"],
    spacesUse: "required",
    spacesPrompt: "Post the team artifact or link once. Individually explain: What do I now understand? What evidence changed or complicated our thinking? What did I contribute? What audience evidence caused a revision? What realistic action or participation pathway exists, and what are its limits?",
  },
];

export const unit1SocialLessons = socialLessons.filter((lesson) => lesson.unitId === "place-evidence-perspective");
export const unit2SocialLessons = socialLessons.filter((lesson) => lesson.unitId === "power-rights-government");
export const unit3SocialLessons = socialLessons.filter((lesson) => lesson.unitId === "global-systems");
export const unit4SocialLessons = socialLessons.filter((lesson) => lesson.unitId === "solutionary-inquiry");

export const socialInquiryProject = {
  title: "Social Studies Solutionary Inquiry",
  question: "How can understanding a complex issue help us teach others about responsible paths toward change?",
  teamSize: "3–4 students",
  promise: "Each group becomes the class expert on one topic, investigates it across the Social Studies units, and teaches the class near the end of the term.",
  topicFamilies: [
    { title: "Power, government & human rights", examples: "democratic participation, discrimination, freedom and responsibility, access to justice" },
    { title: "Indigenous rights, land & reconciliation", examples: "local Nations, land and governance, residential-school legacies, language and cultural resurgence" },
    { title: "Migration, identity & belonging", examples: "reasons people move, refugee experiences, multiculturalism, inclusion and barriers" },
    { title: "Global inequality & interdependence", examples: "poverty, labour and trade, access to education or health, international cooperation" },
    { title: "Environment, community & sustainable futures", examples: "climate justice, water, food systems, urban growth, local-to-global responsibility" },
  ],
  checkpoints: [
    { when: "October · Unit 1 · Notice", action: "Save two inquiry seeds from maps, media claims, local change, or a perspective that deserves deeper study.", evidence: "Two possible topics + why each matters" },
    { when: "Nov. 16–27 · Unit 2 · Choose", action: "Form a team, compare seeds, choose a teacher-approved topic, and write one complex inquiry question.", evidence: "Team agreement + focused question + roles" },
    { when: "Nov. 23–Dec. 4 · Unit 2 · Map", action: "Identify decision-makers, forms of power, rights, affected groups, missing voices, and the government or institution involved.", evidence: "Power–rights–perspective map" },
    { when: "Dec. 7–Jan. 22 · Unit 3 · Investigate", action: "Build a source trail, short change-and-continuity timeline, defended significance claim, and systems/root-cause map; compare current responses across scales.", evidence: "Annotated sources + timeline + working systems map" },
    { when: "Jan. 18–Feb. 11 · Unit 4 · Create", action: "Compare real responses, choose a realistic action pathway, and design an accurate experience that helps classmates think—not just hear a report.", evidence: "Response comparison + paper prototype + evidence passport" },
    { when: "Feb. 16–26 · Unit 4 · Teach", action: "Cold-test the experience, revise one claim and one design feature, teach the class, and post the shared artifact plus an individual reflection to SpacesEDU.", evidence: "Audience evidence + revised product + individual reflection" },
  ],
  productChoices: ["Interactive lesson or simulation", "Interactive digital story or guided experience", "Mini-documentary or podcast", "Exhibit, model, or gallery walk", "Case-file workshop or structured discussion", "Another teacher-approved format"],
  requirements: [
    "A focused question with no one-step answer",
    "A defended explanation of why the issue or development is significant—and to whom",
    "A short timeline showing one important change and one important continuity",
    "Several credible and meaningfully different sources",
    "Evidence about causes, systems, power, rights, and affected perspectives",
    "First Peoples’ knowledge or perspectives only when relevant, specific, attributed, and respectfully sourced",
    "An honest comparison of existing responses, limitations, and possible unintended consequences",
    "A realistic participation or action pathway naming an actor, next steps, possible effects, limits, and review",
    "A learning experience that asks classmates to think, decide, create, or respond",
    "Visible citations and a clear statement of what remains uncertain",
    "A shared product plus individual evidence of thinking and contribution",
  ],
  reflection: [
    "What did I understand differently by the end?",
    "Which evidence or perspective changed or complicated our thinking?",
    "What did I contribute to the team and the teaching experience?",
    "What remains uncertain or contested?",
    "What is one responsible action or participation pathway, who could take the next step, and what are its limits?",
  ],
};

export const socialPacing = [
  ["Sept. 8–18 · Launch + live local case", "Belonging, source care, local decisions, and representation", "Establish discussion and attribution routines; use maps, Power in the Room, and Who Decides What? to distinguish school, district, municipal, provincial, and federal responsibilities. Open the official candidate list only after Sept. 11."],
  ["Sept. 21–Oct. 2 · Unit 1 + selected Unit 2", "Perspectives, city trade-offs, trustees, and candidate evidence", "Use authentic Surrey questions to practise evidence-based perspective taking. Bring forward the strongest power, jurisdiction, and rights activities without duplicating them."],
  ["Oct. 5–16 · Claims, comparison, and participation", "Verify promises and prepare the existing civic hearing/mock vote", "Trace checkable candidate claims to original sources, compare responsibilities and trade-offs, and use a private class ballot only after students can explain the offices and evidence."],
  ["Oct. 19–23 · Election reflection", "Results, limits, and what happens next", "Use the Newsroom for a short source-based reflection: compare results and student priorities, then ask what winners can actually do and how people can continue to influence decisions."],
  ["Nov. 2–6 · Unit 1 synthesis", "Fleetwood case file", "Combine sources, consequences, stakeholder perspectives, and ethical judgment in the first substantial case file."],
  ["Nov. 9–Dec. 10 · Unit 2", "Power, rights, and government + inquiry launch", "Compare decision-making systems and human-rights protections; teams choose a topic and build a power–rights–perspective map, culminating in the Human Rights Day gallery."],
  ["Dec. 11–Jan. 22 · Unit 3", "Global systems + inquiry investigation", "Investigate migration, inequality, interdependence, and cooperation while teams build source trails and root-cause maps; pause cleanly for winter break."],
  ["Jan. 25–Feb. 26 · Unit 4", "Solutionary expert inquiry", "Teams compare responses, create an interactive learning experience, teach the class, revise, and reflect individually in SpacesEDU."],
  ["Feb. 25–26 · Bridge", "Social Studies reflection into Science inquiry", "Use the completed inquiry to name transferable habits: fair evidence, model limits, careful claims, teamwork, feedback, and accountable teaching."],
] as const;
