import type { StudentLessonContract } from "./student-lesson-contract";

/** Reviewed, privacy-safe projector contracts for Career Education. */
export const careerStudentLessonContracts = {
  "strengths-action-quest": {
    id: "strengths-action-quest",
    reviewState: "reviewed",
    challenge: "How can actions show different strengths when a challenge changes?",
    why: "We are learning to notice what people do, explain how it helps, and choose one strength to practise next.",
    firstAction: "Study the sample action note. Find the action, the moment it happened, and the result.",
    materials: ["Challenge cards", "Simple building and sorting materials", "Role cards", "Strength-in-action stems", "Private evidence note"],
    choices: [{
      prompt: "Choose a comfortable first role. You will rotate later.",
      options: [
        { label: "Build or test", detail: "Handle materials, try an idea, or check whether it works." },
        { label: "Explain or listen", detail: "Clarify the task, ask a question, or restate an idea." },
        { label: "Organize or check", detail: "Track the steps, time, materials, or signs of success." },
        { label: "Observe or support", detail: "Notice useful actions, help someone rejoin, or record evidence." },
      ],
    }],
    steps: [
      { title: "See the evidence", action: "Use the sample pattern: action + moment + result. Replace praise words such as ‘smart’ with something a person could see or hear.", finishCheck: "You can point to the action, moment, and result in the sample.", minutes: "8–10 min" },
      { title: "Try the circuit", action: "Complete two short challenges. Rotate jobs so building, explaining, organizing, checking, and including can all become visible.", finishCheck: "Your group completed both challenges, and nobody was ranked by speed, volume, or winning.", minutes: "30–35 min" },
      { title: "Notice + explain", action: "Record one useful action without using a private detail or fixed label. Use: ‘I saw __ when __. It helped because __.’", finishCheck: "The note names an observable action and its effect on the task or group.", minutes: "12–15 min" },
      { title: "Switch + practise", action: "Choose a different role or strength for one more challenge. Ask for an access route if a movement, speaking, reading, or materials job is not a good fit.", finishCheck: "You tried one different action and recorded what happened.", minutes: "25–30 min" },
      { title: "Choose a next move", action: "Choose one useful action for the next class team task. Name the task, action, and evidence you will notice.", finishCheck: "The next move is small, specific, and possible in an upcoming lesson.", minutes: "8–10 min" },
    ],
    finishEvidence: ["Two completed team challenges", "One action + moment + result note", "Respectful evidence without fixed labels", "One different role attempted", "One specific next-team action"],
    saveAction: { kind: "add-to-existing-post", message: "Keep the full record in class. If asked, add only one example you choose to the existing September Learning Story. Do not make a separate post." },
    readiness: "quick",
  },
  "digital-identity-forensics": {
    id: "digital-identity-forensics",
    reviewState: "reviewed",
    challenge: "What might different people think after seeing the same digital profile?",
    why: "We are learning to separate visible facts from guesses, consider different audiences, and repair choices that could affect privacy, safety, credit, or trust.",
    firstAction: "Study the fictional profile. Record only details you can see or read. Do not search for a real person or account.",
    materials: ["Fictional profile", "Evidence-or-inference cards", "Audience cards", "Risk-and-repair prompts", "Board or plain paper"],
    choices: [{
      prompt: "How will you investigate the fictional profile?",
      options: [
        { label: "Mark a copy", detail: "Circle visible facts and question guesses." },
        { label: "Sort cards", detail: "Move details into evidence, inference, audience, and repair groups." },
        { label: "Talk + scribe", detail: "Explain while a partner or adult records key words." },
        { label: "Class board", detail: "Point, vote, or contribute to one shared map." },
      ],
    }],
    steps: [
      { title: "Record visible facts", action: "List what the fictional profile shows, including words, images, settings, dates, replies, and credits.", finishCheck: "Every item can be pointed to on the fictional profile.", minutes: "8–10 min" },
      { title: "Separate guesses", action: "Sort each statement as evidence or inference. Mark any guess that the profile cannot prove.", finishCheck: "Your group can explain the difference between what is shown and what someone might infer.", minutes: "12–15 min" },
      { title: "Check audiences + risks", action: "Consider several audiences. For at least three, flag one privacy, permanence, credit, tone, relationship, or safety concern.", finishCheck: "Each concern names the audience, visible clue, and possible result without claiming certainty.", minutes: "15–18 min" },
      { title: "Repair the profile", action: "Choose useful repairs such as cropping a location clue, changing the audience, adding credit, rewriting a comment, asking permission, apologizing, or removing a post. Explain each repair's limit.", finishCheck: "The repaired version protects trust while keeping suitable work or expression visible.", minutes: "20–25 min" },
      { title: "Write decision rules", action: "Write three rules for future digital choices. Test each rule against one new fictional post.", finishCheck: "Each rule helps someone pause, check an audience or consequence, and choose an action.", minutes: "12–15 min" },
    ],
    finishEvidence: ["A visible-fact list", "An evidence-versus-inference sort", "Three audience checks", "A justified repair map", "Three tested digital-choice rules"],
    saveAction: { kind: "keep-in-class", message: "Keep this fictional investigation in class. No upload, real-account search, username, screenshot, or personal disclosure is needed." },
    readiness: "teach",
  },
  "leadership-relay": {
    id: "leadership-relay",
    reviewState: "reviewed",
    challenge: "Which leadership action would help the team move forward right now?",
    why: "Leadership is not the same as being the boss. We are learning actions that help a group understand, organize, check, connect, include, or repair its work.",
    firstAction: "Read the five role cards. Underline the one action each role should make visible during today's team task.",
    materials: ["Current inquiry or project", "Leadership role cards", "Team agreement", "Midpoint evidence slip", "Pencil or shared board"],
    choices: [{
      prompt: "Choose one role to practise:",
      options: [
        { label: "Facilitator", detail: "Clarify the goal and invite a voice that has not been heard." },
        { label: "Organizer", detail: "Name the next task, time, or material without controlling everyone." },
        { label: "Checker", detail: "Compare the work with evidence and suggest a repair." },
        { label: "Connector", detail: "Link two ideas, sources, or parts of the project." },
        { label: "Access encourager", detail: "Help someone enter or re-enter the work with a useful route." },
      ],
    }],
    steps: [
      { title: "Learn the role", action: "Read your role's useful action and warning. Say or point to what it could look like in today's task.", finishCheck: "You know one action to try and one bossy, vague, or unhelpful action to avoid.", minutes: "3–5 min" },
      { title: "Choose + plan", action: "Choose a role that is possible today. Tell the team the one action you will try.", finishCheck: "Every person has an accessible role and no one was assigned by personality.", minutes: "2–3 min" },
      { title: "Work + notice", action: "Complete the real class task. Use your leadership action and notice one action that helps the work or trust move forward.", finishCheck: "The group has task evidence, not only a discussion about roles.", minutes: "15–25 min" },
      { title: "Pause + rotate", action: "Record: ‘The action was __. It helped by __.’ Repair a problem if needed, then rotate roles.", finishCheck: "The evidence names an action and effect without ranking or labelling a person.", minutes: "4–5 min" },
      { title: "Revise the agreement", action: "Finish the host task, then change one team agreement using evidence. Name one action to carry into the next task.", finishCheck: "The revision says what the team will do, when, and how the group will know it helped.", minutes: "8–10 min" },
    ],
    finishEvidence: ["One leadership role attempted", "One action + effect note", "Evidence from the host task", "One problem repaired", "One team-agreement revision"],
    saveAction: { kind: "add-to-existing-post", message: "Keep role slips in class. When relevant, add one action-and-effect sentence to the existing February reflection only." },
    readiness: "quick",
  },
  "project-rescue-studio": {
    id: "project-rescue-studio",
    reviewState: "reviewed",
    challenge: "Which changes can turn a stressful project into a plan the team can actually use?",
    why: "We are learning to set a clear finish line, put tasks in order, share work fairly, check safety and materials, and prepare for change.",
    firstAction: "Study the fictional plan. Mark the unclear goal, missing job, unfair workload, missing material, unsafe step, and missing review time.",
    materials: ["Flawed fictional plan", "Task and role cards", "Timeline or task-board frame", "Safety-and-material check", "Surprise cards", "Teacher answer notes"],
    choices: [{
      prompt: "How will your team rebuild the plan?",
      options: [
        { label: "Card sort", detail: "Move task and role cards into a workable order." },
        { label: "Draw a timeline", detail: "Use boxes and arrows to show order and checkpoints." },
        { label: "Shared class board", detail: "Point, suggest, or scribe while the class repairs one plan." },
      ],
    }],
    steps: [
      { title: "Find the trouble", action: "Locate all six flaws. Explain how each could affect time, safety, fairness, materials, or the result.", finishCheck: "Your team found the unclear goal, missing task, unfair workload, missing material, unsafe step, and missing review time.", minutes: "10–12 min" },
      { title: "Set the finish + order", action: "Write a clear finish line. Put task cards in order and draw an arrow wherever one job must happen before another.", finishCheck: "Someone outside the group can tell what finished means and which jobs depend on others.", minutes: "18–22 min" },
      { title: "Share + check", action: "Assign flexible roles by task need, not personality. Add a materials check, safety check, and midpoint test.", finishCheck: "The work is possible, safer, and fairer; fair does not have to mean identical.", minutes: "15–18 min" },
      { title: "Test a surprise", action: "Draw one surprise card. Keep the learning goal, change the route, and build a backup plan.", finishCheck: "The backup responds to the problem and still reaches the learning goal.", minutes: "18–22 min" },
      { title: "Cold-check + revise", action: "Give the repaired plan to another group without explaining it. Use their question or failed step to make one visible revision.", finishCheck: "The final plan includes an evidence-based change and one remaining risk or next check.", minutes: "12–15 min" },
    ],
    finishEvidence: ["All six flaws identified", "A clear finish line", "Ordered tasks with arrows", "Fair roles plus materials, safety, and midpoint checks", "A tested backup plan and peer-evidence revision"],
    saveAction: { kind: "add-to-existing-post", message: "Keep the fictional map in class. If these planning moves improve the February inquiry, add one before-and-after example there only." },
    readiness: "teach",
  },
  "career-constellation": {
    id: "career-constellation",
    reviewState: "reviewed",
    challenge: "How many connected people, skills, tools, and pathways sit behind one familiar project?",
    why: "Useful work is a network, not one hero job or one straight pathway. Paid work, care, service, creative work, technical work, and volunteering can all matter.",
    firstAction: "Choose one familiar project or service. Place it in the centre and add every role your group can already see.",
    materials: ["Fictional pathway profiles", "Optional WorkBC profiles", "Role and skill cards", "Large paper or board", "Constellation canvas", "Next-experience card"],
    choices: [{
      prompt: "Choose a safe way to build the constellation:",
      options: [
        { label: "Large group map", detail: "Add roles and labelled links to shared paper." },
        { label: "Card network", detail: "Arrange role, skill, tool, and pathway cards, then sketch the map." },
        { label: "Class board", detail: "Point, suggest, sort, or scribe while the class builds one network." },
        { label: "Private next step", detail: "Use a fictional learner or keep your own possibility private." },
      ],
    }],
    steps: [
      { title: "Map visible roles", action: "Add the people who plan, build, teach, perform, repair, serve, care, or lead. Label what each contributes.", finishCheck: "The map has at least four visible roles and each has a job in the project.", minutes: "15–18 min" },
      { title: "Study pathways", action: "Investigate at least three provided profiles. Record one contribution, two skills, one tool, and one possible learning route for each.", finishCheck: "Every note comes from a supplied profile or source.", minutes: "25–30 min" },
      { title: "Add hidden work", action: "Add care, volunteer, technical, creative, language, access, cleaning, safety, transport, data, or maintenance roles that were missing.", finishCheck: "The map now has at least eight varied roles and does not rank them by pay or prestige.", minutes: "25–30 min" },
      { title: "Connect the network", action: "Draw at least four labelled links showing a shared skill, tool, service, influence, or job that must happen first. Add two different ways a person could learn or enter the work.", finishCheck: "Another group can follow the links and see more than one pathway.", minutes: "20–25 min" },
      { title: "Choose one experience", action: "Correct one assumption the evidence challenged. Then choose one small experience a fictional learner—or you, if you choose—could try next. Add a first step and help source.", finishCheck: "The next experience is low-risk, possible, and based on the constellation.", minutes: "15–20 min" },
    ],
    finishEvidence: ["At least eight varied roles", "Three sourced profile notes", "Four labelled links", "Two pathways", "One revised assumption and next-experience plan"],
    saveAction: { kind: "add-to-existing-post", message: "Keep the full map in class. If asked, add only a chosen insight to the existing June Core Competency and Leadership reflection." },
    readiness: "teach",
  },
} as const satisfies Record<string, StudentLessonContract>;
