import type { StudentLessonContract } from "./student-lesson-contract";

/** Reviewed, privacy-safe projector contracts for every PHE experience. */
export const pheStudentLessonContracts = {
  "everyone-in-game": {
    id: "everyone-in-game",
    reviewState: "reviewed",
    challenge: "Which one change helps more players enter, contribute, and rejoin the game?",
    why: "A rule can be the same for everyone and still leave some players waiting. A no-name tally and player feedback help us test a change.",
    firstAction: "Learn Gate Pass, practise the freeze signal, and make one safe pass before the first round begins.",
    materials: ["8 cones for four gates", "One soft ball per game", "No-name participation tally", "Pencil", "Optional pinnies"],
    choices: [{
      prompt: "Choose a route that works toward the same goal:",
      options: [
        { label: "Active play", detail: "Move into space, pass, receive, and rejoin at a pace that is safe for you." },
        { label: "Lower intensity", detail: "Use a smaller area, walking or wheeling pace, rolling passes, or a planned rest and return." },
        { label: "Observer-designer", detail: "Keep the tally without names. Notice who gets a chance to join in, make choices, or rejoin, and suggest one rule change. Rotate when ready." },
      ],
    }],
    steps: [
      { title: "Learn Gate Pass", action: "In teams of four or five, pass a soft ball through any cone gate to a teammate to score. Hold it for no more than three counts and do not run with it. Defenders intercept passes only—no contact, grabbing, body blocking, or elimination.", finishCheck: "Everyone can show the freeze signal, three-count rule, and one safe pass or roll.", minutes: "8 min" },
      { title: "Play + notice", action: "Play one four-minute round. One rotating observer marks no names—only how many players received a pass, made a choice, mostly waited, or found a quick way back into play.", finishCheck: "The tally describes the round without ranking, naming, or blaming a player.", minutes: "10 min" },
      { title: "Change + replay", action: "Change one rule, space, team-size, equipment, or role. Predict how it may improve access, then replay for four minutes with the same safe-play rules.", finishCheck: "The group changed one feature and gathered a second no-name tally for a fair comparison.", minutes: "10 min" },
      { title: "Decide from evidence", action: "Compare both rounds. Look at the tally and find one pattern in what players said. Name one thing the evidence cannot show. Use all three to decide whether to keep, revise, or reject the change.", finishCheck: "The decision checks participation, choice, safety, and enjoyment—not touches alone.", minutes: "9 min" },
    ],
    finishEvidence: ["Safe participation in an active or observer-designer role", "Two no-name round tallies", "One tested change", "A keep, revise, or reject decision with evidence", "One limit or next test"],
    saveAction: { kind: "keep-in-class", message: "Keep the team tally and decision in class. Do not post names, body information, rankings, photos, or video to SpacesEDU." },
    readiness: "teach",
  },
  "strategy-remix-league": {
    id: "strategy-remix-league",
    reviewState: "reviewed",
    challenge: "How can one team plan create a better next play?",
    why: "Players can freeze, notice open space, support, and timing, choose one change, then replay to see whether it helped.",
    firstAction: "Learn End-Zone Pass and practise the freeze signal before anyone defends.",
    materials: ["One soft ball per game", "Cones for sidelines and two end zones", "Optional pinnies", "Strategy freeze card", "No-name replay note"],
    choices: [{
      prompt: "Choose a meaningful way to read and change the game:",
      options: [
        { label: "Player", detail: "Pass, move into safe space, support a teammate, and help test the plan." },
        { label: "Boundary player", detail: "Play from a marked side lane with walking, wheeling, rolling, or shorter-pass options." },
        { label: "Strategy observer", detail: "Track open space, support, or timing and report at the freeze. Rotate when ready." },
      ],
    }],
    steps: [
      { title: "Learn the game", action: "Play three-against-three or four-against-four. Score when a teammate receives the ball in the end zone. Pivot but do not run with the ball; pass within three counts. Defend by intercepting only—no contact, grabbing, body blocking, or knocking the ball from hands.", finishCheck: "Every group can show a safe restart, legal score, and the freeze signal.", minutes: "8 min" },
      { title: "Play + freeze", action: "Play for four minutes. On the freeze signal, stop safely and point to one open space, support option, timing problem, or safer choice. Describe positions, not player blame.", finishCheck: "The team names one visible pattern and one piece of evidence for it.", minutes: "8 min" },
      { title: "Plan + replay", action: "Choose one plan: move wide after passing, make a support triangle, wait for a passing lane, or use a safer shorter pass. Assign rotating jobs and replay.", finishCheck: "The team tests one named plan, and every member has a useful role.", minutes: "10 min" },
      { title: "Compare the plays", action: "Use one exact moment from before and after the plan. Explain what changed, what did not, and what the team should try next.", finishCheck: "The explanation links a team choice to play evidence without judging athletic ability.", minutes: "8 min" },
    ],
    finishEvidence: ["Safe use of one game skill or strategy role", "One tactical cue noticed", "One team plan tested", "A before-and-after comparison", "One realistic next adjustment"],
    saveAction: { kind: "keep-in-class", message: "Keep the no-name strategy note in class. No game video, player ranking, or body information is needed in SpacesEDU." },
    readiness: "teach",
  },
  "rhythm-movement-lab": {
    id: "rhythm-movement-lab",
    reviewState: "reviewed",
    challenge: "How can four safe movements make a clear eight-count pattern?",
    why: "A steady count, controlled movement, clear pathway, and planned transition help another person follow the pattern.",
    firstAction: "Copy the class four-move, eight-count example once while seated or standing in your own marked space.",
    materials: ["Four movement cards per group", "Eight-count strip", "Floor or table-space marker", "Pencil", "Optional music with a steady beat"],
    choices: [{
      prompt: "Choose a route that keeps the movement goal the same:",
      options: [
        { label: "Standing", detail: "Use controlled steps, levels, balances, and pathways. Jumps and spins are not required." },
        { label: "Seated or hands", detail: "Use hands, arms, levels, directions, balances, and pauses on the same counts." },
        { label: "Card director", detail: "Arrange and point through the score, keep the count, and coach one transition." },
      ],
    }],
    steps: [
      { title: "Copy the pattern", action: "Follow the class model: reach on counts 1–2, step or tap on 3–4, balance or hold on 5–6, and change direction on 7–8. Repeat once in silence.", finishCheck: "You can follow all eight counts safely using a standing, seated, hand, or director route.", minutes: "7 min" },
      { title: "Build your score", action: "Choose four safe movement cards. Put one movement on each pair of counts and mark one transition that connects two movements smoothly.", finishCheck: "The score shows counts 1–8, four movements, and one clear transition.", minutes: "10 min" },
      { title: "Rehearse + repair", action: "Rehearse with music, spoken counts, visual cards, or silence. A partner notices timing, control, spacing, and the transition. Change one unsafe or unclear part.", finishCheck: "The revised pattern stays in the safe space and can be followed twice without a missing count.", minutes: "12 min" },
      { title: "Share + explain", action: "Show the pattern live, seated, with hands, or by directing cards. Explain how one movement choice made the pattern clearer.", finishCheck: "The explanation names one exact choice and its effect; public performance is optional.", minutes: "8 min" },
    ],
    finishEvidence: ["A complete four-move, eight-count score", "Safe control and spacing", "One partner observation", "One useful revision", "One intentional choice explained"],
    saveAction: { kind: "keep-in-class", message: "Keep the score in class. Recording or posting your body or performance is never required." },
    readiness: "teach",
  },
  "trusted-health-studio": {
    id: "trusted-health-studio",
    reviewState: "reviewed",
    challenge: "How can we check whether a health message is trustworthy enough to use?",
    why: "Confidence, popularity, and polished design are not evidence. We can check who made a message, what proof it gives, why it was made, and where to get safe help.",
    firstAction: "Study the fictional NeonFocus ad. Circle who made it and underline what it wants the audience to think or do.",
    materials: ["Fictional NeonFocus ad", "Health Message Check card", "Provided health-source capsule", "Pencil or sticky notes", "Private question route"],
    choices: [{
      prompt: "Choose a private or shared way to show the same thinking:",
      options: [
        { label: "Mark the message", detail: "Circle the source, underline the claim, box evidence, and question missing information." },
        { label: "Sort cards", detail: "Place source, claim, evidence, purpose, missing information, and next-step cards." },
        { label: "Explain privately", detail: "Point, speak, or write privately. You never need to share a health experience." },
      ],
    }],
    steps: [
      { title: "Name source + purpose", action: "Identify who made the fictional message, who may benefit, its audience, and what it wants people to think, feel, buy, or do.", finishCheck: "You can point to message details that support your source and purpose ideas.", minutes: "8 min" },
      { title: "Check claim + evidence", action: "Separate the main claim from its evidence. Mark missing details such as a named expert, study, date, ingredients, limits, or a source that can be checked.", finishCheck: "The claim and evidence are separate, and one important missing detail is named.", minutes: "10 min" },
      { title: "Compare a trusted source", action: "Read the provided information from the school district or province. Record what it supports, what it does not prove, and whether it answers the ad's exact claim.", finishCheck: "Your comparison says only what the source can support and keeps one uncertainty visible.", minutes: "10 min" },
      { title: "Repair the response", action: "Write or say a safer response: what we know, what we do not know, what not to share or do, and which trusted adult or qualified professional could help next.", finishCheck: "The response protects private information and names an appropriate help route.", minutes: "10 min" },
    ],
    finishEvidence: ["The message creator and purpose", "The exact claim and evidence", "One missing detail or limit", "A trusted-source comparison", "A privacy-safe help route"],
    saveAction: { kind: "keep-in-class", message: "Keep this fictional check in class. Do not post personal health, body, medication, relationship, or diagnosis information to SpacesEDU." },
    readiness: "teach",
  },
  "safety-help-circuit": {
    id: "safety-help-circuit",
    reviewState: "reviewed",
    challenge: "What is the safest next step when a fictional situation feels wrong or risky?",
    why: "You do not need a perfect speech. Move toward safety, tell the right help, and keep asking until a responsible adult acts.",
    firstAction: "Read the shared fictional case and point to the safest immediate action before discussing reasons.",
    materials: ["Four low-detail fictional case cards", "Pause–Protect–Get Help path", "Urgent or non-urgent cards", "School help map", "Private response card"],
    choices: [{
      prompt: "Choose a safe response route:",
      options: [
        { label: "Point + place", detail: "Place action and help cards on the path without speaking to the class." },
        { label: "Partner reason", detail: "Compare two safe options using only the fictional case details." },
        { label: "Private route", detail: "Use a different low-detail case or respond privately. You may pass on any case." },
      ],
    }],
    steps: [
      { title: "Check urgency", action: "Sort the case as immediate danger, needs adult help soon, or needs support and follow-up. If there may be immediate danger, get an adult now and use the school's emergency route; do not investigate alone.", finishCheck: "The response puts immediate safety before explanation, evidence collection, or confrontation.", minutes: "8 min" },
      { title: "Pause + protect", action: "For one low-detail case, choose a safe pause, exit, distance, block, or stay-with-others action.", finishCheck: "The action reduces risk without blaming the person needing help or asking a child to handle harm alone.", minutes: "10 min" },
      { title: "Get the right help", action: "Use the school help map to name a trusted adult or service, what the student could say, and what private information should not be shared with peers or unknown accounts.", finishCheck: "The help route fits the case, and an adult is responsible for the next protection step.", minutes: "10 min" },
      { title: "Plan follow-up", action: "Decide what the fictional person should do if the first adult is unavailable, does not understand, or does not act. Improve one response that ends too early.", finishCheck: "The plan includes another safe adult or service and avoids a new risk.", minutes: "8 min" },
    ],
    finishEvidence: ["An urgency decision", "One immediate protection action", "An appropriate adult or service", "Privacy-safe words for asking for help", "A follow-up route"],
    saveAction: { kind: "keep-in-class", message: "Keep fictional case responses in class. Personal disclosures go privately to a trusted adult and are never a SpacesEDU task." },
    readiness: "teach",
  },
  "effort-meter-trail": {
    id: "effort-meter-trail",
    reviewState: "reviewed",
    challenge: "How can you change an activity so it fits your body today?",
    why: "A private effort check helps you choose a safe pace, rest, route, or movement. The goal is a useful adjustment—not comparison.",
    firstAction: "Join the short warm-up, learn the private 1–5 effort scale and talk test, and practise the stop-and-tell signal.",
    materials: ["Private 1–5 effort card", "Six station cards", "Cones or floor markers", "Soft balls and targets", "Stable support option", "Pencil"],
    choices: [{
      prompt: "Choose three stations and a route at each:",
      options: [
        { label: "Travel", detail: "Walk, wheel, or use a short loop at a self-chosen pace." },
        { label: "Step or tap", detail: "Step, seated-step, tap, or hand-tap a steady pattern." },
        { label: "Balance", detail: "Use standing, seated, hand, wall, or chair-supported control." },
        { label: "Target or recovery", detail: "Roll, toss, direct, slow down, rest, or take a water break." },
      ],
    }],
    steps: [
      { title: "Learn the private check", action: "Use the 1–5 scale and talk test during a gentle warm-up. Keep the number private. Stop and tell an adult about pain, dizziness, unusual breathing trouble, or another concern.", finishCheck: "You can choose an effort number privately and name one safe way to lower, raise, pause, or stop.", minutes: "7 min" },
      { title: "Try three stations", action: "Complete three 60-second stations with transition and rest time. Choose a standing, seated, walking, wheeling, rolling, directing, or quiet route that keeps the purpose.", finishCheck: "You tried three routes safely without recording anyone else's effort or body data.", minutes: "12 min" },
      { title: "Adjust + retest", action: "Change one feature—pace, rest, range, route, resistance, time, or movement type—then repeat and privately check what changed.", finishCheck: "You can name the adjustment, the cue you noticed, and whether to keep, change, rest, or stop.", minutes: "10 min" },
      { title: "Make one FITT plan", action: "Change one part of a familiar activity: frequency means how often, intensity means how hard, time means how long, and type means which activity. Explain why it fits today's purpose.", finishCheck: "The plan changes one FITT part, includes a safe check-in, and can be revised on another day.", minutes: "8 min" },
    ],
    finishEvidence: ["A private effort and talk-test check", "Three safely chosen routes", "One tested adjustment", "One realistic FITT change", "A stop, rest, or help plan"],
    saveAction: { kind: "keep-in-class", message: "Keep the plan private or share it only in a teacher conference. Do not post body, fitness, diagnosis, or health data." },
    readiness: "teach",
  },
} as const satisfies Record<string, StudentLessonContract>;
