import type { StudentLessonContract } from "./student-lesson-contract";

/** Reviewed projector contracts for the ELA lessons not defined in the core file. */
export const elaStudentLessonContracts = {
  "semiahmoo-story-source-lab": {
    id: "semiahmoo-story-source-lab",
    reviewState: "reviewed",
    challenge: "How do careful listeners keep a speaker, story, and source together?",
    why: "We are learning to name where a story comes from, say only what the source supports, and follow its sharing rules.",
    firstAction: "Read the source card. Record the exact title, speaker, Semiahmoo context, source route, and format—nothing from memory.",
    materials: ["Surrey Schools source page", "Storytelling protocol", "Source-card frame or plain paper", "Pencil", "Fictional listening backup"],
    choices: [{ prompt: "How will you show your listening?", options: [
      { label: "Write", detail: "Use short notes on the source card." },
      { label: "Draw + label", detail: "Use a simple visual with exact source labels." },
      { label: "Speak", detail: "Give your response while a partner or adult records key words." },
    ] }],
    steps: [
      { title: "Name the source", action: "Copy the exact title, speaker, Semiahmoo context, source route, and format from the district page.", finishCheck: "Every source detail can be checked on the page.", minutes: "5–8 min" },
      { title: "Check the boundary", action: "Read the storytelling protocol. Name what listening access allows and what still needs permission.", finishCheck: "You can explain why opening a story is not permission to copy, retell, remix, or repost it.", minutes: "6–8 min" },
      { title: "Listen first", action: "Listen without story notes. When the listening ends, record one learning and one honest question.", finishCheck: "You left a gap instead of guessing about anything the source did not explain.", minutes: "15–25 min" },
      { title: "Listen for support", action: "Listen again to the selected part. Add one supported idea and label your own thinking as an interpretation or question.", finishCheck: "A partner can tell which idea came from the source and which thought is yours.", minutes: "12–15 min" },
      { title: "Check + close", action: "Complete the whole source card. Ask a partner to check its source details, supported learning, and sharing boundary.", finishCheck: "The card is accurate, complete, and does not reproduce or retell the story.", minutes: "8–10 min" },
    ],
    finishEvidence: ["Exact source details", "One source-supported learning", "One labelled interpretation or question", "One accurate sharing boundary", "A completed partner check"],
    saveAction: { kind: "keep-in-class", message: "Keep the source card in class. Do not upload or reproduce story content." },
    readiness: "teach",
  },
  "three-voices": {
    id: "three-voices",
    reviewState: "reviewed",
    challenge: "How can three people describe the same moment honestly—and differently?",
    why: "Viewpoint changes what a narrator notices, but every version still needs evidence from the shared scene.",
    firstAction: "Study the full fictional scene. List three things anyone could point to, then mark one detail that is unknown.",
    materials: ["Shared fictional scene", "Three narrator cards", "Three-column evidence grid", "Paper or approved recording tool", "Pencil and colours"],
    choices: [{ prompt: "How will you create the three voices?", options: [
      { label: "Short prose", detail: "Write one paragraph for each narrator." },
      { label: "Comic", detail: "Use panels, captions, and speech or thought bubbles." },
      { label: "Monologues", detail: "Write or record three short spoken versions." },
    ] }],
    steps: [
      { title: "Find shared facts", action: "Sort scene details into visible facts, possible ideas, and unknowns.", finishCheck: "Every fact can be pointed to; every guess is labelled as possible.", minutes: "10–12 min" },
      { title: "Meet the narrators", action: "Read all three narrator cards. Mark each person's location, goal, and information.", finishCheck: "You can explain one thing each narrator can and cannot know.", minutes: "12–15 min" },
      { title: "Create three versions", action: "Retell the same moment three ways. Keep shared facts steady while changing what each narrator notices and how they sound.", finishCheck: "A reader can identify all three viewpoints without stereotypes or guesses presented as facts.", minutes: "30–35 min" },
      { title: "Label choices", action: "On each version, label one detail included and one detail that narrator left out.", finishCheck: "Each label explains how viewpoint shaped the telling.", minutes: "15–20 min" },
      { title: "Compare + revise", action: "Trade with a partner. Revise one line, panel, or spoken part where evidence or viewpoint was unclear.", finishCheck: "The revision makes one narrator clearer without changing the shared event.", minutes: "12–15 min" },
    ],
    finishEvidence: ["A fact / possible / unknown sort", "Three complete narrator versions", "One choice and omission labelled in each", "One evidence-based revision"],
    saveAction: { kind: "keep-in-class", message: "Keep the complete triptych in your ELA folder. No separate SpacesEDU post is needed." },
    readiness: "teach",
  },
  "edit-room": {
    id: "edit-room",
    reviewState: "reviewed",
    challenge: "How can an edit change what an audience thinks without changing every fact?",
    why: "Crops, captions, order, and sound can guide an audience. We are learning to keep needed context visible.",
    firstAction: "Study the full fictional event before seeing an edit. List four facts that are clearly visible in the wide view.",
    materials: ["Projected fictional courtyard image", "Shared Edit Room screen or printed image", "Paper frame or two L-shaped strips", "Three-frame order strip", "Pencil"],
    choices: [{ prompt: "Choose a way to take part in the same class edit:", options: [
      { label: "Tap + explain", detail: "Choose on the shared screen and explain the visible clue." },
      { label: "Point + speak", detail: "Point from your seat or tell a partner what to select." },
      { label: "Paper frame", detail: "Use a paper frame on a printed or sketched scene and order three frame cards." },
    ] }],
    steps: [
      { title: "See the whole event", action: "Study the wide view and source facts. Record what is visible, unknown, and important to keep in context.", finishCheck: "Your notes separate facts from guesses.", minutes: "10–12 min" },
      { title: "Test two crops", action: "Compare the model crop and helping crop with the wide view. Decide what each makes easiest to believe and what disappears outside it.", finishCheck: "You can explain how both crops are true pieces but neither is the whole event.", minutes: "8–10 min" },
      { title: "Check the caption", action: "Choose the caption that stays closest to visible evidence. Reject words that invent motive or push a feeling the image cannot prove.", finishCheck: "The chosen caption names only what the class can point to.", minutes: "7–9 min" },
      { title: "Build the complete edit", action: "Choose exactly three frames in order. Include the wide view so the audience can return to the full event.", finishCheck: "The three-frame edit is complete, ordered, and passes the context check.", minutes: "10–12 min" },
      { title: "Protect context", action: "Choose one detail the edit must not hide, then read the class editor's note and name one possible improvement.", finishCheck: "The final note explains a protected detail and one honest next revision.", minutes: "7–9 min" },
    ],
    finishEvidence: ["Four visible details found", "Both crop effects explained", "An evidence-safe caption", "A complete three-frame edit with the wide view", "One protected context detail and next improvement"],
    saveAction: { kind: "keep-in-class", message: "Keep the complete three-frame order and editor's note in class. Do not create a separate SpacesEDU post." },
    readiness: "teach",
  },
  "character-council": {
    id: "character-council",
    reviewState: "reviewed",
    challenge: "What should this character do next—and what does the text support?",
    why: "We are learning to use exact text details, listen to a different idea, and change our recommendation when evidence calls for it.",
    firstAction: "Read or listen to the turning point. Record two exact details that show the character's problem, choices, or limits.",
    materials: ["Choice text or excerpt", "Audio or graphic-text route", "Evidence placemat", "Council role cards", "Pencil"],
    choices: [{ prompt: "How will you take part?", options: [
      { label: "Speak", detail: "Give part of the recommendation or counterargument." },
      { label: "Point + pass", detail: "Point to evidence while a partner reads the group's words." },
      { label: "Write", detail: "Prepare the evidence or response card." },
    ] }],
    steps: [
      { title: "Collect evidence", action: "Read or listen and place two exact details on the evidence placemat.", finishCheck: "Both details come from the text and connect to the character's situation.", minutes: "7–9 min" },
      { title: "Test two choices", action: "Name two possible next moves and predict one likely result of each.", finishCheck: "Both predictions fit what the text has shown so far.", minutes: "7–9 min" },
      { title: "Hold the council", action: "Use the roles to give a 90-second recommendation supported by at least one text detail.", finishCheck: "The group states a choice, evidence, and reason.", minutes: "10–12 min" },
      { title: "Hear a challenge", action: "Listen to one counterargument. Point to the text detail that makes it worth considering.", finishCheck: "You can restate the other idea fairly before responding.", minutes: "6–8 min" },
      { title: "Revise or defend", action: "Change the recommendation, or keep it and explain why the evidence still supports it.", finishCheck: "Your final response names the evidence that affected your thinking.", minutes: "4–6 min" },
    ],
    finishEvidence: ["Two exact text details", "Two possible choices and results", "A 90-second recommendation", "One fair counterargument", "A revise-or-defend note"],
    saveAction: { kind: "keep-in-class", message: "Keep the placemat in class. Discussion notes and the reading conference are the evidence; no upload is needed." },
    readiness: "quick",
  },
  "turning-point-remix": {
    id: "turning-point-remix",
    reviewState: "reviewed",
    challenge: "Can you retell an important scene in a new way and keep what makes it matter?",
    why: "Viewpoint and form can change a scene while its key facts, conflict, and meaning stay recognizable.",
    firstAction: "Choose one important scene. Fill the three must-stay boxes: key fact, main conflict, and idea or feeling that matters.",
    materials: ["Approved source text", "Must-stay frame", "Format templates", "Credit box", "Paper or approved media tool"],
    choices: [{ prompt: "Which new form will you use?", options: [
      { label: "Monologue or letter" }, { label: "Comic or visual sequence" }, { label: "Script or audio scene" },
    ] }],
    steps: [
      { title: "Find what matters", action: "Reread or relisten. Record the key fact, conflict, and meaning that must stay true.", finishCheck: "All three choices can be supported by the source text.", minutes: "10–15 min" },
      { title: "Choose a new angle", action: "Choose a narrator, audience, and form. Plan what the new form can reveal.", finishCheck: "The plan explains why this angle fits the scene.", minutes: "10–15 min" },
      { title: "Create the remix", action: "Complete the new version. Credit the original work without copying a long passage.", finishCheck: "A reader can recognize the turning point and all three must-stay ideas.", minutes: "40–55 min" },
      { title: "Run a recognition test", action: "Ask a partner to identify the turning point, conflict, and important meaning without coaching.", finishCheck: "The tester names what stayed clear and one confusing place.", minutes: "12–15 min" },
      { title: "Revise + explain", action: "Fix one unclear part. Add a creator note naming two changes and one meaning you protected.", finishCheck: "The note uses evidence from the original and partner test.", minutes: "15–20 min" },
    ],
    finishEvidence: ["A complete must-stay frame", "A finished transformed text", "Visible source credit", "A recognition test", "A revision and creator note"],
    saveAction: { kind: "add-to-existing-post", message: "Add this only to an existing class-reading or case-file post if asked. Do not create a duplicate ELA post." },
    readiness: "quick",
  },
  "bloxels-story-blueprint": {
    id: "bloxels-story-blueprint",
    reviewState: "reviewed",
    challenge: "How can a player understand the story while playing?",
    why: "We are learning to place clear story information where a player needs it, then revise when a new player gets lost.",
    firstAction: "Study the short game-story example. Name the character, goal, setting, problem, turning point, and ending.",
    materials: ["Pixel-world example", "Complete story blueprint", "Paper level map", "Story-block planner", "Silent playtest sheet", "Pencil and colours"],
    choices: [{ prompt: "Which complete route will you build?", options: [
      { label: "Bloxels", detail: "Build with school-managed access and approved assets." },
      { label: "Paper game", detail: "Make a playable grid or card route with the same story and test." },
    ] }],
    steps: [
      { title: "Notice story parts", action: "Study the example and label its character, goal, setting, problem, turn, and ending.", finishCheck: "You can point to where a player learns each part.", minutes: "15–20 min" },
      { title: "Complete the blueprint", action: "Plan an original story. Fill every section before decorating: character, goal, setting, world rule, problem, turning point, and ending.", finishCheck: "The goal and event order make sense from beginning to end.", minutes: "25–35 min" },
      { title: "Map story to action", action: "Complete the whole paper route map. Place short story blocks beside actions or choices where players need them.", finishCheck: "Each story block appears before—not after—the information is needed.", minutes: "30–40 min" },
      { title: "Run a silent test", action: "A partner follows the paper or digital route without hints while you record pauses, missed clues, and confusion.", finishCheck: "The sheet records what the player did, not only whether they liked it.", minutes: "25–30 min" },
      { title: "Revise + explain", action: "Change one story block, sequence, or clue. Finish and decorate the complete organizer, then explain the change.", finishCheck: "Before-and-after evidence shows how the revision improved the story.", minutes: "25–35 min" },
    ],
    finishEvidence: ["A fully completed and decorated story blueprint", "A complete paper level map", "Beginning, turn, and ending story blocks", "A silent playtest record", "One visible ELA revision"],
    saveAction: { kind: "add-to-existing-post", message: "Add this evidence to the single Bloxels Story-Game post with the ADST work. Do not create a second ELA upload." },
    readiness: "teach",
  },
  "hook-cold-audience": {
    id: "hook-cold-audience",
    reviewState: "reviewed",
    challenge: "What makes an audience pay attention and helps them learn?",
    why: "We are learning to choose an opening for a purpose, watch where a new audience gets stuck, and revise using evidence.",
    firstAction: "Write: ‘By the end, my audience should understand ___.’ Circle the one fact they need first.",
    materials: ["Current inquiry content", "Opening-format cards", "Audience signal cards", "Complete revision log", "Paper or approved presentation tool"],
    choices: [{ prompt: "Which opening will you test?", options: [
      { label: "Question" }, { label: "Tiny story" }, { label: "Strong image" }, { label: "Quick demonstration" },
    ] }],
    steps: [
      { title: "Set the goal", action: "Name what the audience should understand and the first fact they need.", finishCheck: "Your goal is about learning, not only being entertained.", minutes: "8–10 min" },
      { title: "Try four openings", action: "Sketch the same idea as a question, tiny story, strong image, and quick demonstration.", finishCheck: "All four openings are complete enough to compare.", minutes: "15–20 min" },
      { title: "Choose for a reason", action: "Choose the opening that best fits your purpose and audience. Explain why.", finishCheck: "Your reason connects the opening to what the audience needs to notice.", minutes: "10–12 min" },
      { title: "Test with a new audience", action: "Ask people who have not seen your project to try it without hints. Record what they understood, where they got stuck, and which claim they wanted proof for.", finishCheck: "The log records exact words or actions, not only ‘They liked it.’", minutes: "20–25 min" },
      { title: "Revise two things", action: "Change one part of what you teach and one part of how you present it. For each change, record what the audience said or did that led you to change it.", finishCheck: "The second version is clearer—not simply louder or more decorated.", minutes: "20–25 min" },
    ],
    finishEvidence: ["One audience learning goal", "Four opening sketches", "A chosen opening with a reason", "A complete test log", "Two changes, each explained with something the audience said or did"],
    saveAction: { kind: "add-to-existing-post", message: "Add the improved opening to the existing Social Studies expert artifact or reflection. Do not create a duplicate ELA post." },
    readiness: "quick",
  },
  "metaphor-with-limits": {
    id: "metaphor-with-limits",
    reviewState: "reviewed",
    challenge: "When does a comparison help—and where does it stop working?",
    why: "We are learning to use a comparison to explain a science idea without letting it replace the facts.",
    firstAction: "Read the science fact card. Underline the part you must keep accurate before choosing a comparison.",
    materials: ["Science diagram or fact card", "Metaphor cards", "Works Here / Breaks Here organizer", "Paper or model materials", "Pencil and colours"],
    choices: [{ prompt: "How will you explain it?", options: [
      { label: "Illustrated card" }, { label: "Comic" }, { label: "Small model" }, { label: "Spoken explanation" },
    ] }],
    steps: [
      { title: "Know the science", action: "Study the source diagram or fact card. State the accurate idea in plain words.", finishCheck: "Your statement agrees with the supplied source.", minutes: "8–12 min" },
      { title: "Test comparisons", action: "Try at least two comparisons. Name one part that matches and one that does not.", finishCheck: "You reject or repair any comparison that changes the core idea.", minutes: "12–15 min" },
      { title: "Create the explanation", action: "Complete one visual, comic, model, or spoken explanation using the strongest comparison.", finishCheck: "A classmate can identify the science idea and matching parts.", minutes: "20–30 min" },
      { title: "Label the limit", action: "Complete both organizer sections: Works Here and Breaks Here.", finishCheck: "The limit names a specific difference.", minutes: "10–12 min" },
      { title: "Test + revise", action: "Ask what the comparison taught and what it might wrongly suggest. Revise one label or explanation.", finishCheck: "The final version helps learning while keeping the warning visible.", minutes: "8–10 min" },
    ],
    finishEvidence: ["An accurate plain-language idea", "Two tested comparisons", "One complete explanation", "Works Here and Breaks Here labels", "One tested revision"],
    saveAction: { kind: "keep-in-class", message: "Keep the complete organizer as ELA and Science evidence. No upload is needed." },
    readiness: "teach",
  },
  "precision-poetry": {
    id: "precision-poetry",
    reviewState: "reviewed",
    challenge: "How can a poem be vivid and scientifically accurate?",
    why: "We are learning to choose exact words, images, sounds, and line breaks so a real observation becomes worth hearing twice.",
    firstAction: "Study the shared observation, object, or process. Collect five exact words for what you can see, hear, feel, or verify.",
    materials: ["Shared observation or source bank", "Short mentor texts or audio", "Complete word-cabinet organizer", "Notebook or paper", "Optional teacher-managed recorder"],
    choices: [{ prompt: "Which complete poem route will you use?", options: [
      { label: "Page poem", detail: "Write 12–20 lines." }, { label: "Visual poem" }, { label: "Choral piece" }, { label: "Sound poem" },
    ] }],
    steps: [
      { title: "Observe exactly", action: "Collect exact sensory words and accurate science terms from the source or observation.", finishCheck: "You can point to or verify every factual word.", minutes: "12–15 min" },
      { title: "Notice a mentor move", action: "Read or listen to a short mentor text. Name one move involving sound, image, repetition, or line breaks.", finishCheck: "You can describe the move without copying the wording.", minutes: "12–15 min" },
      { title: "Fill the word cabinet", action: "Complete every section: exact, sensory, technical, surprising, action, and sound words. Decorate after the language work is complete.", finishCheck: "The cabinet contains enough choices to build a whole poem.", minutes: "15–20 min" },
      { title: "Draft a complete poem", action: "Create the full poem. Use at least one accurate science term and two purposeful craft moves.", finishCheck: "The poem has a clear focus and no image that makes the science false.", minutes: "35–45 min" },
      { title: "Listen + revise", action: "Use a private, partner, choral, or performance route. Gather one response and revise sound, image, or structure.", finishCheck: "The before-and-after lines show one meaningful revision.", minutes: "20–25 min" },
    ],
    finishEvidence: ["Five verified observation words", "One mentor-text move", "A complete decorated word cabinet", "A complete poem", "One response and revision"],
    saveAction: { kind: "keep-in-class", message: "Keep the poem in your ELA folder. Add it to an existing post only if you choose it and new evidence is needed." },
    readiness: "quick",
  },
  "impossible-scene-repair": {
    id: "impossible-scene-repair",
    reviewState: "reviewed",
    challenge: "Can you repair an impossible scene—or invent a clear world rule that makes it work?",
    why: "We are learning to separate fact from invention and make a story world's rules clear enough to follow.",
    firstAction: "Study the full fictional storyboard. Mark one accurate detail, one impossible detail, and one you are unsure about.",
    materials: ["Projected storyboard", "Science fact cards", "Fact/invention organizer", "Storyboard or script frame", "Paper and pencil"],
    choices: [{ prompt: "How will your team repair it?", options: [
      { label: "Repair reality", detail: "Change the action so it follows the science evidence." },
      { label: "Create a world rule", detail: "Keep the unusual action but state a consistent fictional rule and effects." },
    ] }],
    steps: [
      { title: "Spot the breaks", action: "Sort scene details into accurate, uncertain, impossible, and intentionally invented.", finishCheck: "Each choice points to the storyboard or a fact card.", minutes: "12–15 min" },
      { title: "Choose a repair", action: "Repair reality or create a fictional rule. Write the rule in one clear sentence.", finishCheck: "The rule explains what changes and stays consistent.", minutes: "10–12 min" },
      { title: "Rebuild the scene", action: "Complete a revised storyboard, script, animation plan, or audio-drama plan from beginning to result.", finishCheck: "The sequence follows the rule and shows cause and effect.", minutes: "30–40 min" },
      { title: "Run a rule test", action: "Another group identifies the rule, one fact, and one invented part without coaching.", finishCheck: "The test shows where the rule or sequence is unclear.", minutes: "15–20 min" },
      { title: "Revise + credit", action: "Fix one unclear part. Add a note naming fact, invention, source, and one question.", finishCheck: "The note clearly separates known facts from invention.", minutes: "10–12 min" },
    ],
    finishEvidence: ["A complete fact/invention sort", "One repair or world rule", "A complete revised scene", "A no-coaching test", "A creator note"],
    saveAction: { kind: "keep-in-class", message: "Keep the repaired scene in class and use it to prepare for the Science showcase. Do not create another upload." },
    readiness: "teach",
  },
  "live-anthology": {
    id: "live-anthology",
    reviewState: "reviewed",
    challenge: "Which piece best shows how you grew—and what revision will make that growth clearer?",
    why: "We are learning to choose strong evidence, make one revision that matters, and explain growth with exact before-and-after details.",
    firstAction: "Gather three to five pieces from the year. For each, name the learning it shows—not how pretty, long, or finished it looks.",
    materials: ["Three to five pieces", "Complete selection grid", "Revision menu", "Curator-note frame", "Privacy-safe sharing choices"],
    choices: [{ prompt: "How will you share your chosen piece?", options: [
      { label: "Display" }, { label: "Perform", detail: "Use a private alternative when wanted." }, { label: "Record" }, { label: "Private conference" },
    ] }],
    steps: [
      { title: "Build a shortlist", action: "Complete the selection grid for three to five pieces. Match each piece to learning it shows.", finishCheck: "Every reason names a skill, choice, or change—not decoration or length.", minutes: "15–20 min" },
      { title: "Choose with evidence", action: "Choose one piece to revise and one earlier piece to compare. Mark exact evidence in both.", finishCheck: "You can explain why these pieces show growth.", minutes: "12–15 min" },
      { title: "Make one deep revision", action: "Choose one content, craft, or design revision and complete the whole new version before final decoration.", finishCheck: "Before and after show a change that improves meaning, clarity, or effect.", minutes: "45–90 min" },
      { title: "Prepare a safe share", action: "Publish, perform, record, display, or prepare a private conference. Check names, faces, voices, permissions, and source credit.", finishCheck: "The sharing route protects privacy and fits the work's purpose.", minutes: "25–35 min" },
      { title: "Explain the growth", action: "Write or record a curator note using the chosen and earlier piece as evidence. Name one next improvement.", finishCheck: "The note includes two exact examples, the revision's effect, and a next step.", minutes: "18–22 min" },
    ],
    finishEvidence: ["A complete selection grid", "One deeply revised piece", "Before-and-after evidence", "A privacy and credit check", "A curator note with a next step"],
    saveAction: { kind: "add-to-existing-post", message: "Add the chosen evidence and note to the existing June Core Competency reflection. Do not create a second anthology upload." },
    readiness: "quick",
  },
} as const satisfies Record<string, StudentLessonContract>;
