// Authored student-facing summaries. Full assessment criteria stay in each lesson contract.
export const STUDENT_FINISH_SUMMARIES: Record<string, string> = {
  "ordinary-object-story": "A spoken story and six-sentence draft that help a listener follow the beginning, turning point, and ending.",
  "magnitude-gallery": "Two number lines showing 0.008, with an explanation of how the scale changes its position.",
  "pattern-forecast": "A pattern card showing how your rule predicts Stage 10 without building every stage.",
  "source-mosaic": "A suggestion for a cooler, more welcoming outdoor area, using facts from more than one source.",
  "geometry-field-lab": "An angle you have measured and named, and a triangle you can prove matches the given rules.",
  "rights-in-tension": "A suggestion to city council explaining how a park rule could be fairer for the people who use it.",
  "place-soundwalk": "A short piece of writing, sound, or art that helps someone picture a place you observed.",
  "four-arts-languages": "Four Arts pages and a short work that combines two art forms to help an audience notice your idea.",
  "map-what-maps-miss": "An artwork with your own symbols and a key that helps viewers notice what you found in a place.",
  "same-facts-frame": "A music score with drawings and symbols that another group can follow without your help.",
  "rights-in-thirty": "A scene, storyboard, or movement pattern that shows an audience how a fictional situation changes.",
  "audience-remix": "An improved display or performance that helps an audience know where to start and what to follow.",
  "cosmic-scale-gallery": "An artwork or performance improved after watching how people find their way through it.",
  "learning-user-manual": "A private guide to what helps you learn, with examples you are comfortable using and one goal to work toward.",
  "packet-rescue": "A rebuilt picture and network drawing showing how pieces of a message arrive, even when something goes wrong.",
  "search-under-hood": "A better search and notes explaining why you chose a result and what its source can tell you.",
  "access-by-design": "A tested model that makes one task easier for the person described in your class brief.",
  "bloxels-game-studio": "A short digital or paper game that you have tested and improved to tell a story through play.",
  "cold-test-prototype": "A small model, paper activity, or demonstration that you have tested and improved so someone can use it without help.",
  "science-design-series": "An improved build and test results showing whether your change helped it solve the class challenge.",
  "cosmic-mission-control": "A card or computer tour with choices that help another student understand one idea about space.",
  "each-one-teach-one": "A short lesson you have tested and improved so another student can learn from it.",
  "space-motion-lab": "A day-and-night diagram and planet graphs or tables that help explain Earth's rotation and the lengths of days and years.",
  "strategy-league": "A multiplication or division solution showing how two methods connect and why the answer makes sense.",
  "pack-and-sync": "Identical supply kits and a timeline of shared flashes. Show your factor lists and multiples.",
  "scoreboard-rules": "A score card that shows another team how brackets and calculation order affect the answer.",
  "fraction-ratio-remix": "Models showing how to grow a ratio without changing its balance and rename a fraction without changing its amount.",
  "decimal-dispatch": "A corrected invoice with calculations showing how you spotted and fixed a decimal mistake.",
  "sale-lab": "An event shopping plan that uses sale prices to get what is needed without going over budget.",
  "equation-balance": "A model and solved equation showing how you found a missing number while keeping both sides equal.",
  "graph-story-lab": "A line graph and explanation showing what the numbers tell us and how the scale changes their appearance.",
  "probability-game-audit": "A changed chance game and a record of your trials explaining why results do not always match predictions.",
  "zoo-design-studio": "A zoo map with measurements and calculations showing how the habitats, fences, and paths fit the rules.",
  "transformation-cipher": "A grid drawing and code showing two moves in order, plus a partner's drawing to check.",
  "space-under-constraints": "A measured plan and small model showing how a learning space can fit the site, visitors, and budget.",
  "semiahmoo-story-source-lab": "A card explaining what you learned from a story, who shared it, and what you have permission to share.",
  "three-voices": "Three versions of one scene showing what each narrator notices differently while keeping the same facts.",
  "edit-room": "A three-picture edit and caption that guide the audience without hiding important parts of the event.",
  "character-council": "A suggestion for what a character should do next, explained using text details and a response to another idea.",
  "turning-point-remix": "A scene retold in a new form that keeps the original problem and important meaning clear.",
  "bloxels-story-blueprint": "A story plan and game map that put clues where players need them to follow the story.",
  "hook-cold-audience": "A tested opening that catches attention and helps the audience understand the idea you want to teach.",
  "metaphor-with-limits": "A science explanation using a comparison, with a warning about where the comparison stops working.",
  "precision-poetry": "A poem that uses carefully chosen words to bring a real observation to life without changing the science.",
  "impossible-scene-repair": "A repaired scene that follows real science or a clear made-up rule, with facts and inventions labelled.",
  "live-anthology": "An improved piece of your work and a short note explaining what it shows about your learning.",
  "strengths-action-quest": "A note showing how one action helped your team, and one action you want to practise next.",
  "digital-identity-forensics": "A plan for fixing a made-up online profile, explaining how changes protect privacy and affect what different people think.",
  "leadership-relay": "A note about an action that helped your team and a changed agreement to improve how you work together.",
  "project-rescue-studio": "A repaired project plan that helps a team share the work safely and keep going when a problem comes up.",
  "career-constellation": "A map of different jobs, the skills they use, and one skill you would like to try.",
  "everyone-in-game": "Two round tallies and a decision explaining whether changing the game helped more players take part safely.",
  "strategy-remix-league": "A team plan you have tried, with notes showing what changed in the game and what to try next.",
  "rhythm-movement-lab": "A safe four-move, eight-count pattern and a score that helps someone follow it smoothly.",
  "trusted-health-studio": "A check of a made-up health ad explaining what its evidence supports and where to find trusted help.",
  "safety-help-circuit": "A plan showing how someone in a made-up situation can move toward safety and keep asking for help.",
  "effort-meter-trail": "A private plan showing how you can change an activity to fit your body today."
};

export function studentFinishSummary(id: string, fallback: string): string {
  return STUDENT_FINISH_SUMMARIES[id] ?? fallback;
}
