export const surreyElectionSources = [
  { id: "surrey-election", title: "2026 Surrey Municipal Election", organization: "City of Surrey", url: "https://www.surrey.ca/city-government/2026-municipal-election", dated: "Updated for 2026", use: "Official dates, voting information, declared candidates after September 11, and results after election day." },
  { id: "surrey-candidates", title: "Candidates", organization: "City of Surrey", url: "https://www.surrey.ca/city-government/2026-municipal-election/candidates", dated: "Declared list after Sept. 11 · recheck after Sept. 18", use: "Use only after nominations close, then recheck after the withdrawal period. This is the class starting point for candidate names—not campaign social media or search results." },
  { id: "surrey-roles", title: "Mayor, council & trustee roles", organization: "City of Surrey", url: "https://www.surrey.ca/city-government/2026-municipal-election/candidates/elected-positions-roles-responsibilities", dated: "Checked Aug. 23, 2026", use: "Answer what each elected office can do, what it cannot do alone, and why council or the board must decide collectively." },
  { id: "bc-local-election", title: "2026 General Local Elections", organization: "Elections BC", url: "https://elections.bc.ca/local-elections/2026-general-local-elections/", dated: "Updated through the 2026 election", use: "Clarify what is elected locally and distinguish election rules from the City of Surrey's administration of voting." },
  { id: "surrey-board", title: "Board of Education overview", organization: "Surrey Schools", url: "https://www.surreyschools.ca/board-overview", dated: "Checked Aug. 22, 2026", use: "Begin the trustee investigation with the actual local board rather than a generic definition." },
  { id: "surrey-elections", title: "Elections", organization: "Surrey Schools", url: "https://www.surreyschools.ca/elections", dated: "Checked Aug. 22, 2026", use: "Official district doorway for school-trustee election information." },
  { id: "student-vote", title: "BC local elections Student Vote", organization: "CIVIX · Student Vote", url: "https://studentvote.ca/", dated: "October 17, 2026 program", use: "Register or confirm participation, use the official-candidate materials and election supplies, assign student election-worker roles, run a private ballot, and wait until polls close before opening results. Do not rebuild these tools in Classroom OS." },
  { id: "digital-democracy", title: "Digital Skills for Democracy", organization: "Elections Canada", url: "https://electionsanddemocracy.ca/digital-skills-democracy", dated: "Current civic-education resource", use: "Use the verification moves to check campaign claims without endorsing a candidate." },
  { id: "surrey-budget", title: "2026 City Budget", organization: "City of Surrey", url: "https://www.surrey.ca/city-government/city-budget", dated: "2026–2030 approved plan", use: "Use the visible service and capital figures for a real trade-off among public safety, roads and transportation, parks, recreation, neighbourhoods, and other city priorities." },
  { id: "surrey-school-capacity", title: "2027–28 five-year capital plan", organization: "Surrey Schools", url: "https://www.surreyschools.ca/board-approves-2027-28-five-year-capital-plan-requesting--5-5b-for-student-space-needs.205991", dated: "Published June 22, 2026", use: "Investigate school-space pressure, the board's priorities, Fleetwood growth, and which next steps require provincial funding." },
] as const;

export const surreyElectionCalendar = [
  { date: "SEPT. 1–11", label: "Nominations", action: "Study roles and local issues. Do not build a candidate comparison from provisional names." },
  { date: "SEPT. 11", label: "Declared candidates", action: "Open the official Surrey list and record the source date." },
  { date: "MID/LATE SEPT.", label: "Investigate", action: "Compare responsibilities, candidate evidence, local questions, promises, and missing perspectives." },
  { date: "EARLY OCT.", label: "Check and compare", action: "Verify claims, examine persuasion, and weigh trade-offs without ranking personalities." },
  { date: "BEFORE OCT. 17", label: "Class vote", action: "Use the existing mock-election routine after students can explain offices, evidence, and ballot choices." },
  { date: "AFTER OCT. 17", label: "Results and responsibility", action: "Compare results and questions, then investigate what elected officials can actually do next." },
] as const;
