export type VisualReviewCategory =
  | "Morning Screen"
  | "Technology & AI"
  | "Object Story"
  | "Lesson Visual"
  | "Public Site"
  | "Unit World";

export type VisualCandidate = {
  id: string;
  briefId: string;
  title: string;
  category: VisualReviewCategory;
  src: string;
  learningJob: string;
  proposedPlacements: string[];
  difference: string;
  alt: string;
  caption: string;
  publicSafe: boolean;
  reuseRule: string;
};

export const visualCandidates: readonly VisualCandidate[] = [
  {
    id: "M01",
    briefId: "morning-independent-bank",
    title: "After-rain arrival",
    category: "Morning Screen",
    src: "/images/visual-review/morning-arrival-after-rain-v1.webp",
    learningJob: "Invite students to notice several small human stories, separate observation from inference, and begin talking with a partner.",
    proposedPlacements: ["Teacher Hub · Morning Screen visual bank", "Optional first-week welcome prompt"],
    difference: "A wide social scene with many possible entry points; no single hidden answer.",
    alt: "Illustrated school arrival courtyard after rain with Grade 6 students, puddles, bicycles, books, and several small details to notice.",
    caption: "FICTIONAL OBSERVATION SCENE · What can you see? What might be happening? What remains unknown?",
    publicSafe: true,
    reuseRule: "Morning Screen and the matching welcome only.",
  },
  {
    id: "M02",
    briefId: "morning-independent-bank",
    title: "Mystery table",
    category: "Morning Screen",
    src: "/images/visual-review/morning-mystery-table-v1.webp",
    learningJob: "Support grouping, pattern finding, odd-one-out reasoning, descriptive language, and rapid oral storytelling.",
    proposedPlacements: ["Teacher Hub · Morning Screen visual bank", "Projector bellringer library"],
    difference: "A close, calm object study that works for ELA, Mathematics, or open-ended noticing.",
    alt: "Overhead still life of twelve worn everyday objects arranged on a classroom worktable.",
    caption: "VISUAL RIDDLE · Make two groups. Then find a completely different way to group them.",
    publicSafe: true,
    reuseRule: "Recurring morning routine only; not an Object Story lesson plate.",
  },
  {
    id: "M03",
    briefId: "morning-independent-bank",
    title: "Nature left clues",
    category: "Morning Screen",
    src: "/images/visual-review/morning-nature-clues-v1.webp",
    learningJob: "Prompt evidence-based inference from tracks, textures, changes, and uncertainty in a West Coast setting.",
    proposedPlacements: ["Teacher Hub · Morning Screen visual bank", "Science observation opener"],
    difference: "No people and no visible animal—the evidence must do the storytelling.",
    alt: "Rain-wet school-edge path with moss, cedar needles, footprints, a feather, a nibbled cone, and puddle rings.",
    caption: "EVIDENCE SCENE · What visited? Which clue is strongest? What else could explain it?",
    publicSafe: true,
    reuseRule: "Morning observation and the directly related Science opener only.",
  },
  {
    id: "T01",
    briefId: "technology-choice-scenes",
    title: "Choices across one classroom",
    category: "Technology & AI",
    src: "/images/visual-review/technology-choices-mural-v1.webp",
    learningJob: "Give the class several visible technology decisions to classify, defend, and revise together.",
    proposedPlacements: ["First Week Mission · Detect and Sort", "Technology Agreement projector challenge"],
    difference: "One panoramic mural holds several contrasting situations without turning them into tiny cards.",
    alt: "Wide illustrated Grade 6 classroom containing several different technology and collaboration situations.",
    caption: "FICTIONAL PRACTICE SCENE · Which choices help learning? Which need checking? Which should stop?",
    publicSafe: true,
    reuseRule: "Responsible Technology sequence only.",
  },
  {
    id: "T02",
    briefId: "technology-choice-scenes",
    title: "Decision cards on the table",
    category: "Technology & AI",
    src: "/images/visual-review/technology-scenario-table-v1.webp",
    learningJob: "Make the sorting routine concrete before students write their own technology agreement.",
    proposedPlacements: ["First Week Mission · Sort", "Printable scenario-card preview"],
    difference: "A tactile overhead composition emphasizes hands, evidence cards, and group decisions rather than devices.",
    alt: "Overhead view of a diverse group sorting illustrated classroom situation cards into three colour-and-symbol zones.",
    caption: "PAIR / GROUP DECISION · Place it. Give a reason. Move it when stronger evidence changes your mind.",
    publicSafe: true,
    reuseRule: "Projector and printable preview for the same activity.",
  },
  {
    id: "T03",
    briefId: "technology-choice-scenes",
    title: "Check the confident answer",
    category: "Technology & AI",
    src: "/images/visual-review/technology-check-the-answer-v1.webp",
    learningJob: "Show the moment when a team pauses, checks an AI response against another source, and keeps human responsibility visible.",
    proposedPlacements: ["First Week Mission · Challenge", "Public Learning · responsible use snapshot"],
    difference: "A focused team scene makes verification—not screen use—the visible action.",
    alt: "Grade 6 students around one shared screen comparing a confident digital answer with a book, notes, and a paper checklist.",
    caption: "FICTIONAL TEAM SCENE · A confident answer is a reason to check—not a reason to stop thinking.",
    publicSafe: true,
    reuseRule: "Technology Agreement and its matching public overview only.",
  },
  {
    id: "O01",
    briefId: "object-story-expansion",
    title: "The discovery drawer",
    category: "Object Story",
    src: "/images/visual-review/object-gallery-discovery-drawer-v1.webp",
    learningJob: "Offer a new set of richly worn objects with marks students can point to before inventing a story.",
    proposedPlacements: ["ELA · Story in an Object · image picker", "Partner storytelling round 3"],
    difference: "Contained drawer composition with strong texture and close visual evidence.",
    alt: "Open wooden discovery drawer containing varied worn everyday objects with scratches, folds, knots, and faded colour.",
    caption: "OBJECT PLATE E · Choose one object. Name five visible clues before you invent anything.",
    publicSafe: true,
    reuseRule: "Object Story lesson only.",
  },
  {
    id: "O02",
    briefId: "object-story-expansion",
    title: "Lost-and-found shelf",
    category: "Object Story",
    src: "/images/visual-review/object-gallery-lost-found-v1.webp",
    learningJob: "Create implied owners and possible journeys while keeping visible fact separate from imagined history.",
    proposedPlacements: ["ELA · Story in an Object · image picker", "Small-group oral storytelling"],
    difference: "A shelf scene encourages relationships among objects as well as single-object stories.",
    alt: "Fictional school lost-and-found shelf with a mitten, keyring, notebook, ribbon, bottle, toy wheel, and other worn objects.",
    caption: "OBJECT PLATE F · What is visible? What is possible? What would you need to know?",
    publicSafe: true,
    reuseRule: "Object Story lesson only.",
  },
  {
    id: "O03",
    briefId: "object-story-expansion",
    title: "Repair-bench stories",
    category: "Object Story",
    src: "/images/visual-review/object-gallery-workbench-v1.webp",
    learningJob: "Support stories about change, repair, care, and why an object might matter after it breaks.",
    proposedPlacements: ["ELA · Story in an Object · image picker", "ADST connection · repair and redesign"],
    difference: "Every object has a visible repair, missing part, or evidence of repeated use.",
    alt: "Warm workbench still life of repaired and worn everyday objects, thread, a small wheel, tape, a cracked handle, and simple tools.",
    caption: "OBJECT PLATE G · Which mark could become the turning point of a story?",
    publicSafe: true,
    reuseRule: "Object Story and its direct repair connection only.",
  },
  {
    id: "P01",
    briefId: "packet-rescue-visuals",
    title: "Packet Rescue tabletop model",
    category: "Lesson Visual",
    src: "/images/visual-review/packet-rescue-tabletop-v2.webp",
    learningJob: "Make device, server, routers, two routes, numbered picture pieces, and reassembly visible before the human drama.",
    proposedPlacements: ["ADST · Packet Rescue · background lesson", "Teacher preparation preview"],
    difference: "A concrete overhead model shows the entire simplified system at once.",
    alt: "Overhead tabletop network model with a server, six picture pieces, two routers and routes, a blocked upper route, an open lower route, a device, and a five-piece reassembly with one gap.",
    caption: "SIMPLIFIED MODEL · Ask → route → check → rebuild. Real networks are more complex.",
    publicSafe: true,
    reuseRule: "Packet Rescue only.",
  },
  {
    id: "P02",
    briefId: "packet-rescue-visuals",
    title: "Become the network",
    category: "Lesson Visual",
    src: "/images/visual-review/packet-rescue-human-network-v1.webp",
    learningJob: "Let students see the physical roles, route choices, missing packet, and observer position before acting them out.",
    proposedPlacements: ["ADST · Packet Rescue · drama launch", "Role-card reference"],
    difference: "A room-scale human model makes movement and role relationships easier to understand.",
    alt: "Illustrated classroom human-network drama with students at device, server, router, packet, and observer stations connected by two floor routes.",
    caption: "HUMAN MODEL · Who sends? Who routes? Who checks? What changes when one path closes?",
    publicSafe: true,
    reuseRule: "Packet Rescue only.",
  },
  {
    id: "PU01",
    briefId: "public-student-orientation",
    title: "Look · talk · make · move · read",
    category: "Public Site",
    src: "/images/visual-review/public-student-learning-mosaic-v1.webp",
    learningJob: "Show students and families that Grade 6 learning takes several equally valuable forms.",
    proposedPlacements: ["Public · Learning page · current approach", "Private Teacher Hub · philosophy quick view"],
    difference: "A coherent five-zone learning mosaic rather than another generic classroom photograph.",
    alt: "Five-part illustrated classroom mosaic showing students closely observing, discussing, making, moving, and reading.",
    caption: "LEARNING HAS MANY FORMS · Look closely. Talk it through. Make, move, read, test, and revise.",
    publicSafe: true,
    reuseRule: "Public Learning page and the exact matching teacher overview only.",
  },
  {
    id: "PU02",
    briefId: "public-student-orientation",
    title: "This week begins together",
    category: "Public Site",
    src: "/images/visual-review/public-week-collaboration-hero-v1.webp",
    learningJob: "Communicate the current week’s pair-and-group decision work before students read any details.",
    proposedPlacements: ["Public · This Week hero", "Public · Students first move"],
    difference: "The composition is designed for a website crop while retaining the actual collaborative action.",
    alt: "Editorial illustration of Grade 6 students working in pairs and small groups with paper decision cards and one shared projector.",
    caption: "THIS WEEK · Notice, discuss, check, and build a shared agreement.",
    publicSafe: true,
    reuseRule: "Current-week Home and Students pages for the same learning window.",
  },
  {
    id: "PF01",
    briefId: "public-family-orientation",
    title: "A learning story comes home",
    category: "Public Site",
    src: "/images/visual-review/public-family-artifact-conversation-v1.webp",
    learningJob: "Make family support feel concrete: look at the work, ask one useful question, and listen to the student explain.",
    proposedPlacements: ["Public · Families hero", "Public · SpacesEDU explanation"],
    difference: "The student artifact—not a device—is the centre of the family conversation.",
    alt: "Warm fictional family table scene with a Grade 6 student showing a handmade learning artifact while adults listen and ask questions.",
    caption: "FAMILY MOVE · Ask what changed, what was difficult, and what the student is proud of.",
    publicSafe: true,
    reuseRule: "Families page only.",
  },
  {
    id: "N01",
    briefId: "newsroom-orientation",
    title: "The source desk",
    category: "Public Site",
    src: "/images/visual-review/newsroom-source-desk-v1.webp",
    learningJob: "Orient students to the idea that a photograph, map, data display, excerpt, date, and creator each offer different evidence.",
    proposedPlacements: ["Private · Newsroom landing", "Public · Newsroom orientation"],
    difference: "A recurring navigation image—not a substitute for the authentic source in each story.",
    alt: "Overhead editorial source-analysis desk with an unlabeled map, photograph, chart, document excerpt, date card, pencil, and hand lens.",
    caption: "SOURCE DESK · The real story must still begin with a named, credited source.",
    publicSafe: true,
    reuseRule: "Newsroom orientation only; never presented as evidence.",
  },
  {
    id: "S01",
    briefId: "mixtures-visuals",
    title: "Separation station",
    category: "Lesson Visual",
    src: "/images/visual-review/mixtures-separation-station-v1.webp",
    learningJob: "Show the visible relationship between a mixture’s properties, a chosen tool, what passes or stays, and the remaining limitation.",
    proposedPlacements: ["Science · Mixtures · separation toolkit", "Printable method atlas cover"],
    difference: "A realistic bench scene gives each method physical scale before exact labels are added in HTML.",
    alt: "Clean classroom science bench with magnets, sieves, skimming tools, filter funnel, evaporation dish, and paper chromatography arranged around safe fictional samples.",
    caption: "METHOD ATLAS · Choose a tool because of a property—not because it is nearby.",
    publicSafe: true,
    reuseRule: "Mixtures sequence only.",
  },
  {
    id: "C01",
    briefId: "civic-power-visuals",
    title: "Who can move the decision?",
    category: "Lesson Visual",
    src: "/images/visual-review/civic-decision-room-v1.webp",
    learningJob: "Make access to information, speaking time, decision power, affected groups, and review safeguards visible before the simulation.",
    proposedPlacements: ["Social Studies · Power in the Room", "Social Studies · fair decision debrief"],
    difference: "A fictional hearing-room composition reveals unequal positions without assigning a moral answer.",
    alt: "Fictional classroom civic hearing with students in different roles around a decision table, observers, evidence folders, and an empty review chair.",
    caption: "FICTIONAL DECISION ROOM · Who can speak? Who is affected? Who decides? Who can ask for review?",
    publicSafe: true,
    reuseRule: "Power in the Room and its direct debrief only.",
  },
  {
    id: "W01",
    briefId: "distinct-unit-worlds",
    title: "Storywood Crossroads",
    category: "Unit World",
    src: "/images/visual-review/unit-world-storywood-crossroads-v1.webp",
    learningJob: "Give ELA reading and story design its own visual identity instead of borrowing the Mathematics Pattern Forest.",
    proposedPlacements: ["ELA · Storywood Crossroads unit hero", "Bloxels story-planning transition"],
    difference: "Branching narrative paths, character traces, and possible turning points distinguish it from a mathematical pattern landscape.",
    alt: "Cinematic story forest crossroads with several distinct paths, subtle traces of characters, a reader’s gate, and a distant worldbuilding clearing.",
    caption: "STORYWOOD CROSSROADS · Text evidence lights the path you can defend.",
    publicSafe: true,
    reuseRule: "ELA reading and the connected Bloxels story pathway only.",
  },
  {
    id: "W02",
    briefId: "distinct-unit-worlds",
    title: "The Listening Grove",
    category: "Unit World",
    src: "/images/visual-review/unit-world-listening-grove-v1.webp",
    learningJob: "Give the September stories, voice, and belonging unit a memorable but calm visual home.",
    proposedPlacements: ["ELA · Stories, Voice & Belonging unit hero", "September formed-class entry"],
    difference: "A welcoming circle, objects with stories, and many ways to participate replace a generic CSS landscape.",
    alt: "Warm fictional woodland-edge learning grove with a circle of seats, a story table, quiet path, making table, and listening spaces.",
    caption: "THE LISTENING GROVE · Every voice can enter in more than one way.",
    publicSafe: true,
    reuseRule: "ELA belonging unit only.",
  },
  {
    id: "W03",
    briefId: "distinct-unit-worlds",
    title: "The House of Many Windows",
    category: "Unit World",
    src: "/images/visual-review/unit-world-house-many-windows-v1.webp",
    learningJob: "Separate the ELA media-framing world from the Research Mosaic Library it currently shares.",
    proposedPlacements: ["ELA · Media, Framing & Responsibility unit hero", "Edit Room transition"],
    difference: "Windows, lenses, crop frames, listening rooms, and partial views make framing physically visible.",
    alt: "Imaginative old house interior with many windows, lenses, crop frames, listening alcoves, and doors revealing different parts of one courtyard event.",
    caption: "THE HOUSE OF MANY WINDOWS · Every frame reveals something and leaves something outside.",
    publicSafe: true,
    reuseRule: "ELA media-framing unit only.",
  },
] as const;

export type CodeVisualConcept = {
  id: string;
  title: string;
  placement: string;
  job: string;
  kind: "shape" | "roles" | "compass" | "story" | "source" | "student" | "family" | "year";
};

export const codeVisualConcepts: readonly CodeVisualConcept[] = [
  { id: "D01", title: "Shape of the Day", placement: "Morning Screen · Teacher Home", job: "Arrival, blocks, breaks, changes, and dismissal understood in five seconds.", kind: "shape" },
  { id: "D02", title: "Technology Decision Compass", placement: "First Week Mission · agreement poster", job: "Helps Learning · Check It · Stop + Ask becomes a reusable decision routine.", kind: "compass" },
  { id: "D03", title: "AI Team Roles", placement: "Projector · group role cards · printable", job: "Thinker, Prompter, Checker, and Connector/Recorder share one device meaningfully.", kind: "roles" },
  { id: "D04", title: "Object Clue → Story Arc", placement: "Object Story projector · printable", job: "Visible clue becomes beginning, turning point, meaning, and listener question.", kind: "story" },
  { id: "D05", title: "Authentic Source Stage", placement: "Private and public Newsroom", job: "Image or document, creator, date, caption, and first noticing question stay together.", kind: "source" },
  { id: "D06", title: "Student Action Path", placement: "Public Students · projector lessons", job: "Start, work together, check, finish, and post only when assigned.", kind: "student" },
  { id: "D07", title: "Family Four Answers", placement: "Public Families", job: "At school, students make, teacher notices, and ask at home—at one glance.", kind: "family" },
  { id: "D08", title: "Year Learning Path", placement: "Public Learning · private Year Plan", job: "Ten months become a visible seasonal path with connected inquiries and evidence windows.", kind: "year" },
] as const;

export const authenticSourceNeeds = [
  { title: "Fleetwood change over time", need: "Official Surrey–Langley SkyTrain maps, construction photographs, dates, and current status—not a generated transit map.", placement: "Newsroom · Social Studies · public current connection" },
  { title: "Nation-authored local sources", need: "Attributed, community-approved maps, photographs, art, place names, and teaching resources—not synthetic ‘Indigenous-style’ imagery.", placement: "Local source shelf · place inquiry · unit lessons" },
  { title: "Current and historical Newsroom evidence", need: "A credited photograph, map, chart, advertisement, artifact, excerpt, or document for every selected story.", placement: "Private and public Newsroom source stage" },
  { title: "Local weather and environment data", need: "Current official data and maps with dates, units, captions, and a text equivalent.", placement: "Morning Screen · Science · Mathematics graphing" },
] as const;

export const visualAuditFacts = [
  { value: "27", label: "existing private raster assets" },
  { value: "7", label: "distinct images serving 37 unit worlds" },
  { value: "5 / 5", label: "Morning visuals borrowed from lessons" },
  { value: "1", label: "active public image, repeated twice" },
  { value: "20", label: "new generated candidates in this review" },
  { value: "8", label: "live code-built visual concepts" },
] as const;
