'use client';
import {useState} from 'react';
import {werewolfLessons,werewolfRules,narratorScript,type WerewolfLesson} from './werewolf-lessons';
import './werewolf-studio.css';
const asset=(file:string)=>`./werewolf/${file}`;
export function WerewolfUnitLink(){return <section className="ww-unit-link"><h2>Werewolf · learn the game and tell the story</h2><p>Six lessons: rules, practice, story structure, voice, narrator rehearsal and a hosted game with individual retelling.</p><a href="?subject=English+Language+Arts&experience=werewolf-learn">Open Werewolf lessons →</a><p>Use 1–2 lessons a week over 3–6 weeks when the class is ready. Then revisit one skill during occasional ELA practice. In a busy week, choose a 10-minute partner rehearsal instead of a full game.</p></section>}
export function WerewolfRules(){return <section><h2>Classroom starter rules</h2><p>This version has three player roles. Learn it before adding other roles or house rules.</p>{werewolfRules.map((r,i)=><article key={r.title}><h3>{i+1}. {r.title}</h3><p>{r.text}</p></article>)}</section>}
export function WerewolfNarratorScript(){return <section><h2>Narrator script</h2><p>Use a calm, clear voice for instructions. Add one short story sentence between actions; never invent a clue about a player.</p>{narratorScript.map(s=><article key={s.title}><h3>{s.title}</h3><p>{s.text}</p></article>)}</section>}
export function WerewolfCuePlanner(){return <section className="ww-cue-planner"><h2>Storyteller cue planner</h2><p>Name: ____________________ Date: ____________</p>{['Setting: Where are we? Choose one sound or movement.','Change: What interrupts the ordinary moment?','Question: What will the listener want to know?','Three to five cue words: remember the story without reading sentences.','Voice choice: where will you pause, change pace or add emphasis?','Game narrator: opening → night directions → morning transition → actual ending.','Two possible endings: a team wins / time runs out with no winner.'].map(p=><div className="ww-write" key={p}><strong>{p}</strong><div aria-hidden="true">________________________________________________</div></div>)}<h2>Listen, retell and revise</h2>{['Story order: First… Then… Finally…','One clear moment I heard or noticed…','One question I asked my partner…','Feedback I received…','The part I changed and how it helped…'].map(p=><div className="ww-write" key={p}><strong>{p}</strong><div aria-hidden="true">________________________________________________</div></div>)}</section>}
export function WerewolfPrintPack(){const deck=['Werewolf','Werewolf','Seer',...Array(9).fill('Villager')];return <main className="ww-print-pack"><h1>Werewolf · classroom print pack</h1><p>Print only the pages you need. Rules and script are reusable. Cue sheets support each student’s speaking and listening.</p><WerewolfRules/><section className="ww-new-page"><WerewolfNarratorScript/><h3>Private narrator record</h3><p>Keep this off the projector. Do not show hidden roles during play.</p><p>Player number / role / active or tracker</p>{Array.from({length:12},(_,i)=><p key={i}>{i+1}. ________________________________</p>)}</section><section className="ww-new-page"><WerewolfCuePlanner/></section><section className="ww-new-page"><h2>Plain role cards · cut equal rectangles</h2><p>Choose 8–12 players plus a narrator. Use 2 wolves, 1 Seer and enough Villagers to give every player one card. For 9 players, use 6 Villagers. Remove unused cards before shuffling. Use opaque paper or identical sleeves so backs cannot reveal roles.</p><div className="ww-card-grid">{deck.map((role,i)=><article key={i}><h3>{role.toUpperCase()}</h3><p>{role==='Werewolf'?'At night, choose one active non-wolf player with your pack.':role==='Seer'?'At night, ask about one other active player. You are on the village team.':'Listen. Discuss. Vote. Find the werewolves.'}</p></article>)}</div></section><section className="ww-new-page"><h2>Storytelling models and practice tasks</h2>{werewolfLessons.map(l=><article key={l.id}><h3>{l.title}</h3><p>{l.product}</p>{l.steps.map(s=><div key={s.title}><h4>{s.title} · {s.minutes}</h4><p>{s.action}</p>{s.model&&<blockquote>{s.model}</blockquote>}<p><b>Check:</b> {s.check}</p></div>)}<p><b>Think and explain:</b> {l.question}</p></article>)}</section></main>}
export function WerewolfLessonStudio({lesson,projector=false}:{lesson:WerewolfLesson;projector?:boolean}){
 const [tab,setTab]=useState('lesson');const [step,setStep]=useState(0);const [answer,setAnswer]=useState(false);
 const active=lesson.steps[step];
 return <section className={`ww-studio ${projector?'ww-projector':''}`}>
  <header><p>LANGUAGE ARTS · ORAL STORYTELLING</p><h1>{lesson.title}</h1><p>{lesson.focus}</p></header>
  <div className="ww-toolbar">
   {!projector&&<a className="ww-primary" href={`?subject=English+Language+Arts&experience=${lesson.id}&mode=student`}>Open student screens</a>}
   <a href={asset('role-cards.png')} target="_blank" rel="noreferrer">Illustrated role cards</a><a href={asset('rules-poster.png')} target="_blank" rel="noreferrer">Rules poster</a><a href={asset('classroom-pack.pdf')} target="_blank" rel="noreferrer">Printable PDF & cue sheets</a><a href={asset('print.html')} target="_blank" rel="noreferrer">Read the complete pack</a>
  </div>
  {!projector&&<details className="ww-prep" open><summary>Prepare and assess this lesson</summary><p>{lesson.prep}</p><p><b>Finish with:</b> {lesson.product}</p><p>Observe story order, clear expression, listening and revision. Give a specific strength and one manageable next step. Game success and leadership chores do not determine the ELA assessment.</p></details>}
  <nav className="ww-tabs" aria-label="Werewolf materials">{[['lesson','Lesson steps'],['rules','Rules'],['script','Narrator script'],['cues','Cue planner'],['cards','Card gallery']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {tab==='lesson'&&<>
   <nav className="ww-steps" aria-label="Werewolf lesson steps">{lesson.steps.map((s,i)=><button key={s.title} aria-current={step===i?'step':undefined} onClick={()=>{setStep(i);setAnswer(false);}}>{i+1}. {s.title}</button>)}</nav>
   <article className="ww-active"><small>{active.minutes}</small><h2>{active.title}</h2><p>{active.action}</p>{active.model&&<blockquote><b>Model</b><p>{active.model}</p></blockquote>}<p className="ww-check"><b>Check:</b> {active.check}</p></article>
   <div className="ww-toolbar"><button disabled={step===0} onClick={()=>{setStep(step-1);setAnswer(false);}}>← Previous step</button><span>Step {step+1} of {lesson.steps.length}</span><button disabled={step===lesson.steps.length-1} onClick={()=>{setStep(step+1);setAnswer(false);}}>Next step →</button></div>
   {step===lesson.steps.length-1&&<section className="ww-exit"><h2>Think and explain</h2><p>{lesson.question}</p><button aria-expanded={answer} onClick={()=>setAnswer(!answer)}>{answer?'Hide explanation':'Reveal explanation after discussing'}</button>{answer&&<p>{lesson.answer}</p>}<p><b>Finish with:</b> {lesson.product}</p></section>}
  </>}
  {tab==='rules'&&<WerewolfRules/>}{tab==='script'&&<WerewolfNarratorScript/>}{tab==='cues'&&<WerewolfCuePlanner/>}
  {tab==='cards'&&<section><h2>Starter deck · nine players and a narrator</h2><p>Six villagers, two werewolves and one seer. Print on opaque paper or use identical sleeves. Cut cards to the same size. The print pack includes extra plain Villager cards for groups of 8–12 players, plus a narrator.</p><img className="ww-card-image" src={asset('role-cards.png')} alt="Nine illustrated role cards: six Villagers, two Werewolves and one Seer. Accessible card text is in the print pack."/><p><a href={asset('role-cards.png')} download>Download illustrated card sheet</a></p></section>}
  <details><summary>Choose another Werewolf lesson</summary><ol>{werewolfLessons.map(l=><li key={l.id}><a href={`?subject=English+Language+Arts&experience=${l.id}${projector?'&mode=student':''}`}>{l.title}</a></li>)}</ol></details>
  {!projector&&<details><summary>Sequence, sources and captain connection</summary><p>Teach these six lessons in order, at 1–2 per week over 3–6 weeks. Thereafter, choose a brief skill rehearsal or a familiar game within existing ELA time. Later focuses can include character voice, viewpoint and improvisation. Rotate narrator opportunities so all students can practise. Captains help prepare and host; Career reflections can draw on that experience separately.</p><p>This classroom variant simplifies familiar Werewolf mechanics: no Doctor, one simultaneous plurality vote, no removal on a tie, hidden departed roles, and a timed ending without an automatic winner. It is not a reproduction of a commercial rulebook or a One Night game.</p><p><a href="https://playwerewolf.co/pages/rules" target="_blank" rel="noreferrer">Stellar Factory: a published Werewolf version</a> · <a href="https://curriculum.gov.bc.ca/curriculum/english-language-arts/6/core" target="_blank" rel="noreferrer">BC Grade 6 ELA: oral language and storytelling</a>. Checked September 13, 2026. Illustrations and classroom text are original; images are AI-generated. The separate Semiahmoo source lesson remains attributed source learning.</p></details>}
 </section>
}
