import type { ProgramExperience } from './program-types';
import type { StudentLessonContract } from './student-lesson-contract';
export type WerewolfStep = {title:string; minutes:string; action:string; model?:string; check:string};
export type WerewolfLesson = {id:string; title:string; focus:string; product:string; prep:string; steps:WerewolfStep[]; question:string; answer:string};
export const werewolfRules = [
 {title:'Deal secret roles',text:'Starter circle: 9 players and 1 narrator. Deal 6 Villagers, 2 Werewolves and 1 Seer. The narrator gets no secret card and is neutral. Keep cards hidden until the game ends. Villagers and the Seer are on the village team; werewolves are on the wolf team.'},
 {title:'Night: werewolves, then seer',text:'Everyone closes their eyes. The narrator wakes the werewolves, who silently agree on one active non-wolf player by pointing. The narrator confirms the choice and asks them to sleep. The narrator wakes the Seer, who points to one other active player. Thumbs up means werewolf; thumbs down means not a werewolf. The Seer sleeps. Complete both actions before announcing the night result.'},
 {title:'Day: announce the result',text:'Everyone opens their eyes. The narrator names the player chosen by the werewolves. That player leaves active play, keeps their role hidden, and becomes a quiet story tracker. Track public events only; do not signal, advise or vote. The narrator checks whether a team has won.'},
 {title:'Discuss and vote',text:'Active players discuss for 3 minutes. Take turns, ask for reasons and allow a response. Players may bluff about their fictional role; claims are not automatically facts. On a count of three, every active player points to one other active player. The player with the most votes leaves active play. If the highest vote is tied, nobody leaves; do not hold another vote. Keep roles hidden.'},
 {title:'Check the ending',text:'After each removal, the narrator checks: no wolves left means the village wins. Wolves equal to or greater than all other active players combined means the wolves win. The Seer counts with the village. Otherwise start another night. At the agreed 15-minute practice limit, finish the current action, check for a winner, and stop with no winner if neither condition is met.'},
 {title:'Keep everyone involved',text:'If the Seer leaves active play, the narrator still calls the Seer step and waits the same amount of time; nobody responds. Story trackers stay silent until the game ends, then help retell the public events. Return and shuffle all cards for the next game. Change who narrates. Discuss game actions, never classmates’ personalities or friendships.'},
];
export const narratorScript = [
 {title:'Before starting',text:'Count the cards and players. Agree on the time limit. Privately note each player’s number and role by checking cards one at a time. Keep that list off the projector. Say: “Keep your role hidden. At night, respond only when your role is called.”'},
 {title:'Close the village',text:'“Night falls. Everyone, close your eyes. Werewolves, open your eyes. Silently agree on one active non-wolf player.” Confirm the choice with a nod. “Werewolves, close your eyes.”'},
 {title:'Ask the seer',text:'“Seer, open your eyes. Point to one other active player.” Give thumbs up for wolf or thumbs down for not wolf. “Seer, close your eyes.” Call this step even if the Seer is no longer active.'},
 {title:'Open the day',text:'“Morning comes. Everyone, open your eyes. Player __ has left the village and is now a story tracker.” Do not reveal that player’s role. Check your private list for a win before discussion.'},
 {title:'Host discussion',text:'“You have three minutes. What did you hear or notice during the game? Who has a different idea?” Invite a response before moving on. “We will vote together: three, two, one, point.” Count aloud without commenting on choices.'},
 {title:'Close or continue',text:'Announce the most-voted player, or say: “The highest vote is tied, so everyone stays.” Update your private list and check both win conditions. Start another night or announce the ending. When play ends, reveal roles and invite everyone to retell and reflect.'},
];
export const werewolfLessons:WerewolfLesson[] = [
 {id:'werewolf-learn',title:'Werewolf 1 · Learn the game',focus:'Explain the roles and follow night, day, discussion and voting.',product:'A spoken explanation of one role and the order of a complete round.',prep:'35 minutes. Print one starter deck on opaque paper, cut equal cards, and seat nine volunteers in a circle with the teacher narrating. Everyone else watches one public demonstration before roles rotate. Read Rules and Narrator script first. This is a classroom starter variant, not One Night Werewolf.',question:'Two wolves and two other active players remain. What happens? What if two players tie for the highest vote?',answer:'The wolves win: they equal the other active players. In a tied vote, nobody leaves active play; check the time limit, then continue to night if play continues.',steps:[
  {title:'Meet the roles',minutes:'7 min',action:'Open Rules and read the first two panels together. Find Villager, Werewolf and Seer on the card sheet. Explain each job to a partner. The narrator runs the game and does not play on either team.',model:'“I am a Villager. I sleep at night. During the day, I listen, discuss and vote. My team tries to find every werewolf.”',check:'Both partners can explain a role and say which team it belongs to.'},
  {title:'Watch an open demonstration',minutes:'10 min',action:'Use face-up cards for a teaching demonstration only. The teacher narrates one night and one day using the script. Pause after each action to name who acts next. Nobody has to guess hidden roles yet.',model:'Example only: players 1 and 2 are wolves, 3 is the Seer, and 4–9 are villagers. Wolves choose 9. Seer asks about 1 and receives thumbs up. At daybreak, 9 becomes a story tracker. The remaining players discuss and vote.',check:'You can explain why player 9 does not vote and why the Seer receives a private answer.'},
  {title:'Rehearse the order',minutes:'12 min',action:'Close or hide the script. With a partner, say the order from dealing cards to checking a winner. Swap speakers. Reopen Rules to repair any missed step. Try a tied-vote example together.',check:'Your explanation includes night actions, day result, discussion, simultaneous vote and a winner check.'},
  {title:'Explain before playing',minutes:'6 min',action:'Each person explains one role and the next action after a tied vote. Answer the check question below before revealing the explanation.',check:'You can follow the rules without relying on a captain to decide what happens.'},
 ]},
 {id:'werewolf-practise',title:'Werewolf 2 · Practise playing and listening',focus:'Follow a hidden-role game and separate a claim from a known event.',product:'A short public-event retelling and one question that helped discussion.',prep:'40 minutes. Use one teacher-led circle first, or supervised circles once narrators can run the script accurately. Groups of 8–12 players use 2 wolves, 1 Seer and the rest villagers, plus a narrator. Add plain Villager cards from the print pack if needed. A group of 10 people uses the nine-card illustrated deck. Re-deal between games, not between nights.',question:'“Player 4 says they are the Seer.” Is that proof? How could you ask for useful information?',answer:'It is a claim, not proof: roles are hidden and players can bluff. Ask what information they are willing to share, compare public statements and keep uncertainty in your explanation.',steps:[
  {title:'Practise useful discussion',minutes:'6 min',action:'Read the example. With a partner, replace a comment about someone’s personality with a question about this game. Agree that quietness, eye contact and friendships do not prove a role.',model:'Instead of “You always lie,” try “Earlier you suggested player 2. What made you change your vote to player 5?” A reply can be “I changed my mind because __. I am still unsure about __.”',check:'Your question names a game statement or action and gives someone room to reply.'},
  {title:'Play a short game',minutes:'15 min',action:'Deal hidden roles. Use Rules and the Narrator script, with three-minute daytime discussions and a 15-minute overall limit. If you leave active play, silently jot or sketch public events. Keep secret information to yourself until the game ends.',check:'The narrator follows the order; players wait their turns and vote together.'},
  {title:'Retell what happened',minutes:'10 min',action:'When play ends, reveal roles. In pairs, each person gives a 30-second retelling: first, then, finally. Include one public statement that changed your thinking and label a guess as a guess. Story trackers share their notes now.',model:'“First, player 9 left. Then someone claimed to be the Seer. I believed the claim, but it was not confirmed. Finally, our vote was tied.”',check:'Your partner can separate an event, a claim and your interpretation.'},
  {title:'Repair one habit',minutes:'9 min',action:'Answer the check question. Then rehearse a 30-second discussion with a partner, using one clearer question or a better turn-taking habit. Save that goal for the next game.',check:'Name an actual listening move you will try; winning is not the learning check.'},
 ]},
 {id:'werewolf-story',title:'Werewolf 3 · Build a story worth hearing',focus:'Create a setting, a change and an unanswered question using precise details.',product:'An original 45–60 second opening, three cue words and a revised telling.',prep:'40 minutes. No cards or full game needed. Students work in pairs with paper. The opening below contains atmosphere, not evidence about player roles. Preserve the separate attributed Semiahmoo story lesson; this activity uses original fiction.',question:'Which is fair atmosphere during a game: “Rain rattled the roof” or “Player 4’s muddy boots prove they are a wolf”? Why?',answer:'Rain creates atmosphere without changing game information. The boots sentence invents evidence and reveals an unsupported role, so it is not fair narration.',steps:[
  {title:'Hear a story opening',minutes:'7 min',action:'Listen to the model read aloud. Name the setting, what changes and the unanswered question. Explain which detail helped you picture the place.',model:'“At dusk, rain tapped the village roofs. One lantern glowed beside the bridge. Suddenly, the bell rang once, then fell silent. The villagers gathered in the square. What would the morning bring?”',check:'You can identify a place, a change and a question without inventing a suspect.'},
  {title:'Plan three story beats',minutes:'10 min',action:'Choose a forest village, mountain village or island village. On the cue planner, write a setting, a change and a question. Add one sound or movement. Underline three cue words to help you remember.',model:'Setting: a windy island square. Change: the lighthouse beam goes dark. Question: what will the village discover at dawn? Cue words: wind / light / dawn.',check:'The change grows from the setting and does not give a player an invented clue.'},
  {title:'Tell from cues',minutes:'15 min',action:'Partner A tells for 45–60 seconds using cue words rather than reading sentences. Partner B retells the three beats and asks one clarity question. Swap roles. Allow a quiet partner audience or extra rehearsal time.',check:'Everyone tells and listens; a partner can follow the events in order.'},
  {title:'Revise and tell again',minutes:'8 min',action:'Change one confusing detail and retell the revised part. Answer the check question. Mark which words changed and explain how the change helped the listener.',check:'Your revision responds to feedback and keeps the story coherent.'},
 ]},
 {id:'werewolf-voice',title:'Werewolf 4 · Practise voice, pace and pauses',focus:'Use vocal expression and gesture to guide a listener without shouting.',product:'Two tellings of the same short scene and feedback about a deliberate voice choice.',prep:'40 minutes. Use the provided model and cue planner. No game required. Offer seated delivery, a partner audience and co-narration; do not require eye contact or a dramatic accent.',question:'What makes a pause useful? How is it different from simply speaking more slowly throughout?',answer:'A purposeful pause highlights a change or gives the audience time to picture something. Changing pace selectively keeps instructions clear; slowing every word can obscure the important moment.',steps:[
  {title:'Hear the difference',minutes:'7 min',action:'Listen as the teacher tells the same model once at an even pace and again with a pause at each slash. Say which version makes the change easier to follow.',model:'“The village settled for the night. / A bell rang. / Once. / Then silence. The lantern keeper turned towards the square.”',check:'Name the exact pause or change in pace and its effect.'},
  {title:'Mark your voice choices',minutes:'8 min',action:'Take your opening from Lesson 3, or use today’s model. Mark one slash for a pause, underline one word for emphasis and choose one small gesture. Keep instructions in your clear everyday voice.',check:'You know why each voice or gesture choice belongs in that moment.'},
  {title:'Rehearse twice',minutes:'17 min',action:'In pairs, tell your opening for 45–60 seconds, or use 15–20 seconds for today’s shorter model. Your listener names a clear moment and a moment that was hard to follow. Change one choice and tell again. Swap so both people practise twice.',model:'Feedback: “Your pause after ‘once’ made me wait for the next sound. The last sentence was rushed; leave time for me to picture the square.”',check:'Your second telling makes a deliberate improvement that your listener can describe.'},
  {title:'Explain your craft',minutes:'8 min',action:'Answer the check question. Each person demonstrates 15–20 seconds and explains one choice: “I paused at __ so the listener could __.” Keep the note with your cues.',check:'Explain the effect on the listener, not just that the voice sounded dramatic.'},
 ]},
 {id:'werewolf-narrate',title:'Werewolf 5 · Rehearse as narrator',focus:'Join clear game directions with atmosphere while keeping events accurate.',product:'A rehearsed opening, night-to-day transition and ending using a narrator cue sheet.',prep:'40 minutes. Work in trios: narrator, host and listener. Rotate all three jobs. Use the same fixed practice events below; this is a rehearsal, not hidden-role play. Print the script and cue planner. Do not display a real game’s private role list.',question:'The real vote is tied. Your planned ending says the village discovers a wolf. What should you say?',answer:'Say that the vote is tied and everyone stays. You can add atmosphere, but cannot change the outcome. Save the discovery ending for a game where that event actually happens.',steps:[
  {title:'Separate story from directions',minutes:'7 min',action:'Hear the model. Point out the story sentence and the exact game instruction. Read the Narrator script to learn what must stay accurate.',model:'Story: “Clouds covered the moon.” Direction: “Everyone, close your eyes.” Story: “Morning light reached the square.” Direction: “Player 9 has left the village and is now a story tracker.”',check:'A listener knows when to imagine and when to act.'},
  {title:'Make a narrator cue sheet',minutes:'10 min',action:'Use the cue planner. Add an opening, the night cues, a morning transition and two possible endings: a team wins, or time runs out. Keep the printed script beside you for exact instructions.',check:'Your plan includes both possible endings and does not predict the winner.'},
  {title:'Rehearse fixed events',minutes:'17 min',action:'In trios, rehearse these fictional events: wolves choose player 9; the Seer checks player 1, a wolf; at daybreak 9 leaves; the daytime vote is tied. No side has won and time then runs out. The host manages a brief pretend discussion; the listener checks the order. Rotate jobs after each four-minute rehearsal.',check:'Each person narrates once. Keep the Seer answer private within the pretend night and announce the tie accurately.'},
  {title:'Repair a transition',minutes:'6 min',action:'Use listener feedback to repeat one unclear instruction or transition. Answer the check question. Explain what stayed fixed and what you could improvise.',check:'You improve clarity without adding a false clue or changing a result.'},
 ]},
 {id:'werewolf-host',title:'Werewolf 6 · Host, retell and improve',focus:'Apply storytelling and listening skills in a game, then show individual growth.',product:'A short hosted game plus each student’s 45–60 second retelling and one revised passage.',prep:'45 minutes. Begin with the teacher checking narrator readiness from Lesson 5. Captains may coordinate materials and turns; rotate narrator opportunities beyond captains. Use supervised small circles when practical, otherwise one teacher-supported circle with rotating players and active story trackers. Assess individual speaking and listening, not bluffing or winning.',question:'What evidence shows that your storytelling improved, even if your team did not win?',answer:'A listener can follow the order more easily, identify the effect of a purposeful voice choice, or explain how your revised passage resolved confusion. A specific example is stronger than “I spoke well.”',steps:[
  {title:'Set one speaking goal',minutes:'5 min',action:'Choose clear order, pace, pauses or expression. Share your goal with a partner. The narrator and host check the script, cards and timer; every person prepares to retell afterwards.',check:'Everyone has a speaking goal, including people who are not narrating the game.'},
  {title:'Host a short game',minutes:'15 min',action:'Use the starter rules and a 15-minute limit. The narrator gives a brief original opening and accurate transitions. The host invites different voices. Story trackers record public events quietly. At the end, reveal roles and thank the group.',check:'The story follows the game; directions remain clear and discussion stays about fictional roles.'},
  {title:'Everyone tells',minutes:'12 min',action:'In pairs, each person gives a 45–60 second retelling from three to five cue words. Name the beginning, a change and the actual ending. Use your chosen voice skill. Your partner names one effective moment and asks one question.',check:'Every student produces their own oral evidence, whether they played, narrated or tracked.'},
  {title:'Revise and reflect',minutes:'13 min',action:'Retell 20 seconds with one improvement. On the listener sheet, note your goal, the feedback and the change. Answer the check question. Compare with an earlier cue sheet; keep most work in class.',check:'You can demonstrate and explain one improvement. An occasional chosen example can join an existing SpacesEDU reflection.'},
 ]},
];
export const werewolfExperiences:ProgramExperience[] = werewolfLessons.map((l)=>({id:l.id,arcId:'ela-werewolf',title:l.title,kind:'Oral storytelling lesson',duration:l.prep.split('.')[0],question:l.focus,hook:l.steps[0].model??l.steps[0].action,studentMission:l.focus,steps:l.steps.map(s=>s.action),product:l.product,learningModes:['Teacher model','Partner rehearsal','Oral storytelling','Listening and revision'],connections:['Career: optional reflection on hosting'],materials:['Supplied role cards, rules, narrator script and cue planner','Paper, pencils and a timer'],teacherPrep:[l.prep],lookFors:['Clear sequence','Purposeful vocal expression','Listening and a useful question','Revision after feedback'],spacesUse:'none',spacesPrompt:'Keep practice in class; choose an occasional example for an existing reflection.'}));
export const werewolfContracts:Record<string,StudentLessonContract> = Object.fromEntries(werewolfLessons.map(l=>[l.id,{id:l.id,reviewState:'reviewed',challenge:l.focus,why:l.focus,firstAction:l.steps[0].action,materials:['Supplied rules and narrator script','Role cards for game sessions','Cue planner, paper and pencil'],choices:[],steps:l.steps.map(s=>({title:s.title,action:[s.action,s.model?`Model: ${s.model}`:''].filter(Boolean).join(' '),minutes:s.minutes,finishCheck:s.check})),finishEvidence:[l.product,l.steps[2].check,l.steps[3].check],saveAction:{kind:'keep-in-class',message:'Keep your cue sheet and feedback in class. No new upload is required.'},readiness:'teach'}]));
export const werewolfLessonFor=(id:string)=>werewolfLessons.find(l=>l.id===id);
