'use client';
import {useState} from 'react';
import {werewolfLessons,werewolfRules,narratorScript,werewolfDeck,werewolfDeckNote,werewolfRoleRoutine,type WerewolfLesson} from './werewolf-lessons';
import './werewolf-studio.css';
const asset=(file:string)=>`./werewolf/${file}`;
export function WerewolfUnitLink(){return <section className="ww-unit-link"><h2>Werewolf · learn the game and tell the story</h2><p>Six lessons: rules, practice, story structure, voice, narrator rehearsal and a hosted game with individual retelling.</p><a href="?subject=English+Language+Arts&experience=werewolf-learn">Open Werewolf lessons →</a><p>Use 1–2 lessons a week over 3–6 weeks when the class is ready. Then revisit one skill during occasional ELA practice. In a busy week, choose a 10-minute partner rehearsal instead of a full game.</p></section>}
export function WerewolfDeckSetup(){return <section><h2>25-player setup · your Ultimate Werewolf deck</h2><p>{werewolfDeckNote}</p><table className="ww-deck-table"><thead><tr><th scope="col">Candidate role</th><th scope="col">Cards</th><th scope="col">Explain before play</th></tr></thead><tbody>{werewolfDeck.map(r=><tr key={r.role}><th scope="row">{r.role}</th><td>{r.count}</td><td>{r.learn}</td></tr>)}</tbody><tfoot><tr><th scope="row">Total student players</th><td>25</td><td>Teacher moderates separately.</td></tr></tfoot></table><h3>Learn roles now and in later games</h3>{werewolfRoleRoutine.map(p=><p key={p}>{p}</p>)}<p>Role reference checked against <a href="https://www.rulespal.com/ultimate-werewolf-ultimate-edition/rulebook" target="_blank" rel="noreferrer">Ultimate Edition rules</a>. Your physical edition governs the selected abilities; this is a proposed teaching mix.</p></section>}
export function WerewolfRules(){return <section><h2>Whole-class game routine</h2><p>Use the 25-player setup and your physical role cards. These classroom procedures support the selected edition; the moderator prepares its exact night order before play.</p>{werewolfRules.map((r,i)=><article key={r.title}><h3>{i+1}. {r.title}</h3><p>{r.text}</p></article>)}</section>}
export function WerewolfNarratorScript(){return <section><h2>Narrator script</h2><p>Use a calm, clear voice for instructions. Add one short story sentence between actions; never invent a clue about a player.</p>{narratorScript.map(s=><article key={s.title}><h3>{s.title}</h3><p>{s.text}</p></article>)}</section>}
export function WerewolfCuePlanner(){return <section className="ww-cue-planner"><h2>Storyteller cue planner</h2><p>Name: ____________________ Date: ____________</p>{['Setting: Where are we? Choose one sound or movement.','Change: What interrupts the ordinary moment?','Question: What will the listener want to know?','Three to five cue words: remember the story without reading sentences.','Voice choice: where will you pause, change pace or add emphasis?','Game narrator: opening → night directions → morning transition → actual ending.','Two possible endings: a team wins / time runs out with no winner.'].map(p=><div className="ww-write" key={p}><strong>{p}</strong><div aria-hidden="true">________________________________________________</div></div>)}<h2>Listen, retell and revise</h2>{['Story order: First… Then… Finally…','One clear moment I heard or noticed…','One question I asked my partner…','Feedback I received…','The part I changed and how it helped…'].map(p=><div className="ww-write" key={p}><strong>{p}</strong><div aria-hidden="true">________________________________________________</div></div>)}</section>}
export function WerewolfPrintPack(){return <main className="ww-print-pack"><h1>Werewolf · classroom print pack</h1><p>Print only the pages you need. Rules and script are reusable. Cue sheets support each student’s speaking and listening.</p><WerewolfRules/><section className="ww-new-page"><WerewolfNarratorScript/><h3>Private narrator record</h3><p>Keep this off the projector. Do not show hidden roles during play.</p><p>Player number / role / active or tracker</p>{Array.from({length:25},(_,i)=><p key={i}>{i+1}. ________________________________</p>)}</section><section className="ww-new-page"><WerewolfCuePlanner/></section><section className="ww-new-page"><WerewolfDeckSetup/><h3>Prepare the moderator’s role order</h3><p>First night: __________________________________________</p><p>Later nights: _________________________________________</p><p>Limited abilities / departure triggers: _____________________</p><p>Use your physical deck. The nine-card illustration and old illustrated rules poster are only a three-role demonstration reference.</p></section><section className="ww-new-page"><h2>Storytelling models and practice tasks</h2>{werewolfLessons.map(l=><article key={l.id}><h3>{l.title}</h3><p>{l.product}</p>{l.steps.map(s=><div key={s.title}><h4>{s.title} · {s.minutes}</h4><p>{s.action}</p>{s.model&&<blockquote>{s.model}</blockquote>}<p><b>Check:</b> {s.check}</p></div>)}<p><b>Think and explain:</b> {l.question}</p></article>)}</section></main>}
export function WerewolfLessonStudio({lesson,projector=false}:{lesson:WerewolfLesson;projector?:boolean}){
 const [tab,setTab]=useState('lesson');const [step,setStep]=useState(0);const [answer,setAnswer]=useState(false);
 const active=lesson.steps[step];
 return <section className={`ww-studio ${projector?'ww-projector':''}`}>
  <header><p>LANGUAGE ARTS · ORAL STORYTELLING</p><h1>{lesson.title}</h1><p>{lesson.focus}</p></header>
  <div className="ww-toolbar">
   {!projector&&<a className="ww-primary" href={`?subject=English+Language+Arts&experience=${lesson.id}&mode=student`}>Open student screens</a>}
   <a href={asset('role-cards.png')} target="_blank" rel="noreferrer">Demo cards · 9 players</a><a href={asset('rules-poster.png')} target="_blank" rel="noreferrer">Three-role demo poster</a><a href={asset('classroom-pack.pdf')} target="_blank" rel="noreferrer">Printable PDF & cue sheets</a><a href={asset('print.html')} target="_blank" rel="noreferrer">Read the complete pack</a>
  </div>
  {!projector&&<details className="ww-prep" open><summary>Prepare and assess this lesson</summary><p>{lesson.prep}</p><p><b>Finish with:</b> {lesson.product}</p><p>Observe story order, clear expression, listening and revision. Give a specific strength and one manageable next step. Game success and leadership chores do not determine the ELA assessment.</p></details>}
  <nav className="ww-tabs" aria-label="Werewolf materials">{[['lesson','Lesson steps'],['deck','25-player setup'],['rules','Rules'],['script','Narrator script'],['cues','Cue planner'],['cards','Card gallery']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {tab==='lesson'&&<>
   <nav className="ww-steps" aria-label="Werewolf lesson steps">{lesson.steps.map((s,i)=><button key={s.title} aria-current={step===i?'step':undefined} onClick={()=>{setStep(i);setAnswer(false);}}>{i+1}. {s.title}</button>)}</nav>
   <article className="ww-active"><small>{active.minutes}</small><h2>{active.title}</h2><p>{active.action}</p>{active.model&&<blockquote><b>Model</b><p>{active.model}</p></blockquote>}<p className="ww-check"><b>Check:</b> {active.check}</p></article>
   <div className="ww-toolbar"><button disabled={step===0} onClick={()=>{setStep(step-1);setAnswer(false);}}>← Previous step</button><span>Step {step+1} of {lesson.steps.length}</span><button disabled={step===lesson.steps.length-1} onClick={()=>{setStep(step+1);setAnswer(false);}}>Next step →</button></div>
   {step===lesson.steps.length-1&&<section className="ww-exit"><h2>Think and explain</h2><p>{lesson.question}</p><button aria-expanded={answer} onClick={()=>setAnswer(!answer)}>{answer?'Hide explanation':'Reveal explanation after discussing'}</button>{answer&&<p>{lesson.answer}</p>}<p><b>Finish with:</b> {lesson.product}</p></section>}
  </>}
  {tab==='deck'&&<WerewolfDeckSetup/>}{tab==='rules'&&<WerewolfRules/>}{tab==='script'&&<WerewolfNarratorScript/>}{tab==='cues'&&<WerewolfCuePlanner/>}
  {tab==='cards'&&<section><h2>Optional illustration · three-role demonstration</h2><p>This nine-card illustration shows six Villagers, two Werewolves and one Seer for a small open demonstration. For this week’s whole-class game, use your Ultimate Werewolf deck and the 25-player setup. The illustrated demo poster also covers only those three roles; it is not the mixed-role game’s full rules.</p><img className="ww-card-image" src={asset('role-cards.png')} alt="Nine illustrated role cards: six Villagers, two Werewolves and one Seer. Accessible card text is in the print pack."/><p><a href={asset('role-cards.png')} download>Download illustrated card sheet</a></p></section>}
  <details><summary>Choose another Werewolf lesson</summary><ol>{werewolfLessons.map(l=><li key={l.id}><a href={`?subject=English+Language+Arts&experience=${l.id}${projector?'&mode=student':''}`}>{l.title}</a></li>)}</ol></details>
  {!projector&&<details><summary>Sequence, sources and captain connection</summary><p>Teach these six lessons in order, at 1–2 per week over 3–6 weeks. Thereafter, choose a brief skill rehearsal or a familiar game within existing ELA time. Later focuses can include character voice, viewpoint and improvisation. Rotate narrator opportunities so all students can practise. Captains help prepare and host; Career reflections can draw on that experience separately.</p><p>Use the owned Ultimate Werewolf multi-night deck. Classroom adaptations include simultaneous plurality voting, no selection on a top tie, hidden departed roles unless a card requires a reveal, and a timed ending without an automatic winner. Special-role effects take precedence over the simple demonstration. Confirm the inventory and card abilities before finalising a game; the proposed mix is not yet play-tested.</p><p><a href="https://playwerewolf.co/pages/rules" target="_blank" rel="noreferrer">Stellar Factory: a published Werewolf version</a> · <a href="https://curriculum.gov.bc.ca/curriculum/english-language-arts/6/core" target="_blank" rel="noreferrer">BC Grade 6 ELA: oral language and storytelling</a>. Checked September 13, 2026. Illustrations and classroom text are original; images are AI-generated. The separate Semiahmoo source lesson remains attributed source learning.</p></details>}
 </section>
}
