import type { ProgramExperience } from './program-types';
import type { StudentLessonContract } from './student-lesson-contract';
export type WerewolfStep = {title:string; minutes:string; action:string; model?:string; check:string};
export type WerewolfLesson = {id:string; title:string; focus:string; product:string; prep:string; steps:WerewolfStep[]; question:string; answer:string};
export const werewolfDeck = [
 {role:'Werewolf',count:5,learn:'Explain the shared night choice and the wolf team goal.'},
 {role:'Seer',count:1,learn:'Explain the private question and what the answer does and does not reveal.'},
 {role:'Bodyguard',count:1,learn:'Read who can be protected, what protection stops and any repeat-target restriction.'},
 {role:'Witch',count:1,learn:'Read each ability, its use limit and when the narrator asks for a choice.'},
 {role:'Hunter',count:1,learn:'Read the departure trigger and resolve the resulting action before checking a winner.'},
 {role:'Mason',count:2,learn:'Read how the pair recognises each other and any restrictions on sharing that information.'},
 {role:'Prince',count:1,learn:'Read what happens when the vote selects this role and whether that protection has a limit.'},
 {role:'Apprentice Seer',count:1,learn:'Read when the role becomes active and how the moderator privately signals the change.'},
 {role:'Villager',count:12,learn:'Listen, question, compare claims and vote. No night action does not mean no part in the story.'},
];
export const werewolfDeckNote = 'Suggested selection for 25 student players plus the teacher as neutral moderator: 12 plain Villagers and 13 other roles. Use your physical Ultimate Werewolf deck. These are candidate cards, not a confirmed inventory or a tested balance. Check your edition’s cards, rules and balance guidance before dealing. If a named card is absent, choose a familiar village-team replacement and teach its rule; keep exactly one card per player. With one of 25 students narrating, deal 24 cards by removing one Villager.';
export const werewolfRoleRoutine = [
 'Before this week: lay out the selected physical cards. Confirm each role’s team, action, timing, limits and win condition from your edition. Write a first-night order and a later-night order on the moderator sheet; include departures and triggered abilities. Announce any classroom adaptations before dealing.',
 'Teach before hiding: partners each explain a selected role using “My team is __. I act when __. I can __, but I cannot __.” Share all role explanations. Demonstrate a protected night target, a vote that selects the Prince and a Hunter departure using the actual card rules. Repair misunderstandings before shuffling.',
 'Later games: choose one unfamiliar role at a time. Read its card, explain it in everyday language, model one legal move and one non-example, and rehearse the new narrator cue. Replace a card rather than adding an extra player; reconsider team balance and endings if the role changes them.',
 'After play: note whether nights were manageable and both teams had meaningful choices. Adjust the next selection using the edition’s balance guidance and class experience. Change roles between games, never halfway through a game without a role rule that requires it.',
];
export const werewolfRules = [
 {
  "title": "Choose and explain the deck",
  "text": "Use the 25-player setup with your physical Ultimate Werewolf cards. The teacher moderates so all 25 students receive a role. Before dealing, explain every selected role and agree on the night order, role-reveal policy and time limit. Keep secret assignments off the projector. The illustrated nine-card sheet is a three-role demonstration only."
 },
 {
  "title": "Night: use the selected role order",
  "text": "Everyone closes their eyes and responds only to their role’s cue. The moderator follows the first-night or later-night order prepared from the actual rulebook. Resolve protection, wolf choices, other abilities and triggered changes before announcing the outcome. The short wolves-then-Seer demonstration is not the full night order for a mixed deck."
 },
 {
  "title": "Day: announce resolved events",
  "text": "Everyone opens their eyes. Announce only the final public outcome: there may be no departures, one or more. Complete triggered actions such as the Hunter’s before checking a winner. Departed players become quiet story trackers after any permitted role action. Keep their cards hidden unless the selected card requires a reveal; agree on these classroom adaptations before play."
 },
 {
  "title": "Discuss and vote",
  "text": "Use 3–4 minutes for discussion. Take turns, ask for reasons and allow a response. A role claim is not proof. For our classroom vote, every active player simultaneously points to one other active player. Highest vote selects that player; a top tie selects nobody. Apply the selected role’s protection or triggered action before confirming departures. Discuss game events, not friendships or personalities."
 },
 {
  "title": "Check the ending",
  "text": "For the suggested two-team selection, check after all immediate effects finish: no active wolves means the village wins; wolves equal to or outnumbering all other active players means the wolves win. Count special village roles with the village. Follow the selected card rules for pending abilities. Agree on a 25–35 minute play window; a whole-class game may not finish. At time, finish the action and otherwise close without a winner."
 },
 {
  "title": "Retell and change roles",
  "text": "Story trackers record public events silently; they do not advise, signal or vote unless their selected role explicitly allows an action. The moderator keeps hidden departed-role cues consistent so silence does not disclose information. At the end, reveal roles and include everyone in retelling and feedback. Re-deal for the next game. Learn unfamiliar expansion roles before adding them."
 }
];
export const narratorScript = [
 {
  "title": "Prepare the moderator sheet",
  "text": "Privately record all 25 player numbers and roles. From the selected cards and your edition’s rulebook, write the first-night order, later-night order, action limits and departure triggers. Explain those rules publicly without identifying anyone’s secret card. Say: “Act only when your role is called.”"
 },
 {
  "title": "Close the village and call roles",
  "text": "“Night falls. Everyone, close your eyes.” Follow your prepared order, including first-night recognition roles. For each: “[Role], open your eyes. [Exact allowed choice.]” Confirm the choice privately, then say: “[Role], close your eyes.” Keep used or departed-role cues consistent when their status is hidden."
 },
 {
  "title": "Resolve before morning",
  "text": "Privately apply protection and other abilities in the rulebook’s order. Record used abilities and any newly active role. In a three-role demonstration only: wolves choose a non-wolf player, then the Seer checks another player; thumbs up means wolf, thumbs down means not wolf. Add every selected role’s cue for real play."
 },
 {
  "title": "Open the day",
  "text": "“Morning comes. Everyone, open your eyes.” Announce the resolved departures, or “Everyone remains in the village.” Complete any triggered card action and update your record before checking for a winner. Invite departed players to track public story events quietly; reveal a card only when the agreed rules require it."
 },
 {
  "title": "Host discussion and vote",
  "text": "“We have three to four minutes. What changed your thinking? Who has a different explanation?” Invite responses and quieter voices. “Three, two, one, point.” Count votes accurately. Announce the selected player or the top tie. Apply role exceptions before announcing who leaves."
 },
 {
  "title": "Close or continue",
  "text": "Update roles and active players after all immediate effects. Check the agreed win conditions. Begin another night or announce the actual ending. At the time limit, finish the current action; if neither team has won, say so. Reveal cards only once play has ended. Everyone retells, receives feedback and revises."
 }
];
export const werewolfLessons:WerewolfLesson[] = [
 {id:'werewolf-learn',title:'Werewolf 1 · Learn the game',focus:'Explain the roles and follow night, day, discussion and voting.',product:'A spoken explanation of one role and the order of a complete round.',prep:'45 minutes. Use your physical Ultimate Werewolf deck for about 25 students, with the teacher moderating. Open the 25-player setup and confirm the candidate cards against your collection. Prepare the night order from your edition. Teach the selected roles before dealing; demonstrate the three core roles first, then special-role exceptions. This is the multi-night game.',question:'Two wolves and two other active players remain, with no pending role effects. What happens? What if two players tie for the highest vote?',answer:'The wolves win: they equal the other active players. In a tied vote, nobody leaves active play; check the time limit, then continue to night if play continues.',steps:[
  {title:'Meet the roles',minutes:'12 min',action:'Open the 25-player setup. Lay out the selected physical cards. First explain Villager, Werewolf and Seer; then partners prepare and share the other role explanations using the cards. Say each role’s team, action, timing and limit. The teacher is the neutral moderator.',model:'“I am a Villager. I sleep at night. During the day, I listen, discuss and vote. My team tries to find every werewolf.”',check:'Both partners can explain a role and say which team it belongs to.'},
  {title:'Watch an open demonstration',minutes:'15 min',action:'Use face-up cards for a short three-role demonstration, then rehearse the selected special roles with the whole class. Try a protected target, a Prince vote and a Hunter departure using your actual cards. Name who acts next. This is open rehearsal; shuffle before hidden-role play.',model:'Example only: players 1 and 2 are wolves, 3 is the Seer, and 4–9 are villagers. Wolves choose 9. Seer asks about 1 and receives thumbs up. At daybreak, 9 becomes a story tracker. The remaining players discuss and vote.',check:'You can explain why player 9 does not vote and why the Seer receives a private answer.'},
  {title:'Rehearse the order',minutes:'12 min',action:'Close or hide the script. With a partner, say the prepared role order from dealing cards to checking a winner. Swap speakers. Reopen Rules to repair any missed step. Try a tied-vote example together.',check:'Your explanation includes night actions, day result, discussion, simultaneous vote and a winner check.'},
  {title:'Explain before playing',minutes:'6 min',action:'Each person explains one role and the next action after a tied vote. Answer the check question below before revealing the explanation.',check:'You can follow the rules without relying on a captain to decide what happens.'},
 ]},
 {id:'werewolf-practise',title:'Werewolf 2 · Practise playing and listening',focus:'Follow a hidden-role game and separate a claim from a known event.',product:'A short public-event retelling and one question that helped discussion.',prep:'50 minutes. Use one whole-class circle of about 25 players with the teacher moderating. Use the physical cards and role order learned in Lesson 1. Read the 25-player setup before dealing. Reserve 25 minutes for play; this may be a partial game. Re-deal between games, not between nights.',question:'“Player 4 says they are the Seer.” Is that proof? How could you ask for useful information?',answer:'It is a claim, not proof: roles are hidden and players can bluff. Ask what information they are willing to share, compare public statements and keep uncertainty in your explanation.',steps:[
  {title:'Practise useful discussion',minutes:'6 min',action:'Read the example. With a partner, replace a comment about someone’s personality with a question about this game. Agree that quietness, eye contact and friendships do not prove a role.',model:'Instead of “You always lie,” try “Earlier you suggested player 2. What made you change your vote to player 5?” A reply can be “I changed my mind because __. I am still unsure about __.”',check:'Your question names a game statement or action and gives someone room to reply.'},
  {title:'Play as a whole class',minutes:'25 min',action:'Deal one physical role card to each student. Use the prepared mixed-role night order, 3–4 minute daytime discussions and a 25-minute play window. Finish the current action at time; if neither team has won, close without a winner. If you leave active play, silently jot or sketch public events. Keep secret information to yourself until the game ends.',check:'The narrator follows the order; players wait their turns and vote together.'},
  {title:'Retell what happened',minutes:'10 min',action:'When play ends, reveal roles. In pairs, each person gives a 30-second retelling: first, then, finally. Include one public statement that changed your thinking and label a guess as a guess. Story trackers share their notes now.',model:'“First, player 9 left. Then someone claimed to be the Seer. I believed the claim, but it was not confirmed. Finally, our vote was tied.”',check:'Your partner can separate an event, a claim and your interpretation.'},
  {title:'Repair one habit',minutes:'9 min',action:'Answer the check question. Then rehearse a 30-second discussion with a partner, using one clearer question or a better turn-taking habit. Save that goal for the next game.',check:'Name an actual listening move you will try; winning is not the learning check.'},
 ]},
 {id:'werewolf-story',title:'Werewolf 3 · Build a story worth hearing',focus:'Create a setting, a change and an unanswered question using precise details.',product:'An original 45–60 second opening, three cue words and a revised telling.',prep:'40 minutes. No cards or full game needed. Students work in pairs with paper. The opening below contains atmosphere, not evidence about player roles. Preserve the separate attributed Semiahmoo story lesson; this activity uses original fiction.',question:'Which is fair atmosphere during a game: “Rain rattled the roof” or “Player 4’s muddy boots prove they are a wolf”? Why?',answer:'Rain creates atmosphere without changing game information. The boots sentence invents evidence and reveals an unsupported role, so it is not fair narration.',steps:[
  {title:'Hear a story opening',minutes:'7 min',action:'Listen to the model read aloud. Name the setting, what changes and the unanswered question. Explain which detail helped you picture the place.',model:'“At dusk, rain tapped the village roofs. One lantern glowed beside the bridge. Suddenly, the bell rang once, then fell silent. The villagers gathered in the square. What would the morning bring?”',check:'You can identify a place, a change and a question without inventing a suspect.'},
  {title:'Plan three story beats',minutes:'10 min',action:'Choose a forest village, mountain village or island village. On the cue planner, write a setting, a change and a question. Add one sound or movement. Underline three cue words to help you remember.',model:'Setting: a windy island square. Change: the lighthouse beam goes dark. Question: what will the village discover at dawn? Cue words: wind / light / dawn.',check:'The change grows from the setting and does not give a player an invented clue.'},
  {title:'Tell from cues',minutes:'15 min',action:'Partner A tells for 45–60 seconds using cue words rather than reading sentences. Partner B retells the three beats and asks one clarity question. Swap roles. Allow a quiet partner audience or extra rehearsal time.',check:'Everyone tells and listens; a partner can follow the events in order.'},
  {title:'Revise and tell again',minutes:'8 min',action:'Change one confusing detail and retell the revised part. Answer the check question. Mark which words changed and explain how the change helped the listener.',check:'Your revision responds to feedback and keeps the story coherent.'},
 ]},
 {id:'werewolf-voice',title:'Werewolf 4 · Practise voice, pace and pauses',focus:'Use vocal expression and gesture to guide a listener without shouting.',product:'Two tellings of the same short scene and feedback about a deliberate voice choice.',prep:'40 minutes. Use the provided model and cue planner. No game required. Offer seated delivery, a partner audience and co-narration; do not require eye contact or a dramatic accent.',question:'What makes a pause useful? How is it different from simply speaking more slowly throughout?',answer:'A purposeful pause highlights a change or gives the audience time to picture something. Changing pace selectively keeps instructions clear; slowing every word can obscure the important moment.',steps:[
  {title:'Hear the difference',minutes:'7 min',action:'Listen as the teacher tells the same model once at an even pace and again with a pause at each slash. Say which version makes the change easier to follow.',model:'“The village settled for the night. / A bell rang. / Once. / Then silence. The lantern keeper turned towards the square.”',check:'Name the exact pause or change in pace and its effect.'},
  {title:'Mark your voice choices',minutes:'8 min',action:'Take your opening from Lesson 3, or use today’s model. Mark one slash for a pause, underline one word for emphasis and choose one small gesture. Keep instructions in your clear everyday voice.',check:'You know why each voice or gesture choice belongs in that moment.'},
  {title:'Rehearse twice',minutes:'17 min',action:'In pairs, tell your opening for 45–60 seconds, or use 15–20 seconds for today’s shorter model. Your listener names a clear moment and a moment that was hard to follow. Change one choice and tell again. Swap so both people practise twice.',model:'Feedback: “Your pause after ‘once’ made me wait for the next sound. The last sentence was rushed; leave time for me to picture the square.”',check:'Your second telling makes a deliberate improvement that your listener can describe.'},
  {title:'Explain your craft',minutes:'8 min',action:'Answer the check question. Each person demonstrates 15–20 seconds and explains one choice: “I paused at __ so the listener could __.” Keep the note with your cues.',check:'Explain the effect on the listener, not just that the voice sounded dramatic.'},
 ]},
 {id:'werewolf-narrate',title:'Werewolf 5 · Rehearse as narrator',focus:'Join clear game directions with atmosphere while keeping events accurate.',product:'A rehearsed opening, night-to-day transition and ending using a narrator cue sheet.',prep:'40 minutes. Work in trios: narrator, host and listener. Rotate all three jobs. Use the fixed three-role practice events below, then rehearse the selected deck’s extra cues; this is rehearsal, not hidden-role play. Print the script and cue planner. Do not display a real game’s private role list.',question:'The real vote is tied. Your planned ending says the village discovers a wolf. What should you say?',answer:'Say that the vote is tied and everyone stays. You can add atmosphere, but cannot change the outcome. Save the discovery ending for a game where that event actually happens.',steps:[
  {title:'Separate story from directions',minutes:'7 min',action:'Hear the model. Point out the story sentence and the exact game instruction. Read the Narrator script to learn what must stay accurate.',model:'Story: “Clouds covered the moon.” Direction: “Everyone, close your eyes.” Story: “Morning light reached the square.” Direction: “Player 9 has left the village and is now a story tracker.”',check:'A listener knows when to imagine and when to act.'},
  {title:'Make a narrator cue sheet',minutes:'10 min',action:'Use the cue planner. Add an opening, the night cues, a morning transition and two possible endings: a team wins, or time runs out. Keep the selected physical cards and prepared role order beside the printed script for exact instructions.',check:'Your plan includes both possible endings and does not predict the winner.'},
  {title:'Rehearse fixed events',minutes:'17 min',action:'In trios, rehearse these fictional events: wolves choose player 9; the Seer checks player 1, a wolf; at daybreak 9 leaves; the daytime vote is tied. No side has won and time then runs out. The host manages a brief pretend discussion; the listener checks the order. Rotate jobs after each four-minute rehearsal.',check:'Each person narrates once. Keep the Seer answer private within the pretend night and announce the tie accurately.'},
  {title:'Repair a transition',minutes:'6 min',action:'Use listener feedback to repeat one unclear instruction or transition. Answer the check question. Explain what stayed fixed and what you could improvise.',check:'You improve clarity without adding a false clue or changing a result.'},
 ]},
 {id:'werewolf-host',title:'Werewolf 6 · Host, retell and improve',focus:'Apply storytelling and listening skills in a game, then show individual growth.',product:'A short hosted game plus each student’s 45–60 second retelling and one revised passage.',prep:'55 minutes. The teacher checks narrator readiness from Lesson 5 and supervises special-role decisions. Captains may coordinate materials and turns; narration opportunities extend to everyone. Use 25 player cards with a teacher moderator, or 24 if one of 25 students moderates. Allow 25 minutes of play; finishing the game is not required. Assess speaking and listening, not bluffing or winning.',question:'What evidence shows that your storytelling improved, even if your team did not win?',answer:'A listener can follow the order more easily, identify the effect of a purposeful voice choice, or explain how your revised passage resolved confusion. A specific example is stronger than “I spoke well.”',steps:[
  {title:'Set one speaking goal',minutes:'5 min',action:'Choose clear order, pace, pauses or expression. Share your goal with a partner. The narrator and host check the script, cards and timer; every person prepares to retell afterwards.',check:'Everyone has a speaking goal, including people who are not narrating the game.'},
  {title:'Host the class game',minutes:'25 min',action:'Use the selected deck, its prepared night order and a 25-minute play window. Resolve special-role effects before announcing results. At time, finish the current action and close without a winner if needed. The narrator gives a brief original opening and accurate transitions. The host invites different voices. Story trackers record public events quietly. At the end, reveal roles and thank the group.',check:'The story follows the game; directions remain clear and discussion stays about fictional roles.'},
  {title:'Everyone tells',minutes:'12 min',action:'In pairs, each person gives a 45–60 second retelling from three to five cue words. Name the beginning, a change and the actual ending. Use your chosen voice skill. Your partner names one effective moment and asks one question.',check:'Every student produces their own oral evidence, whether they played, narrated or tracked.'},
  {title:'Revise and reflect',minutes:'13 min',action:'Retell 20 seconds with one improvement. On the listener sheet, note your goal, the feedback and the change. Answer the check question. Compare with an earlier cue sheet; keep most work in class.',check:'You can demonstrate and explain one improvement. An occasional chosen example can join an existing SpacesEDU reflection.'},
 ]},
];
export const werewolfExperiences:ProgramExperience[] = werewolfLessons.map((l)=>({id:l.id,arcId:'ela-werewolf',title:l.title,kind:'Oral storytelling lesson',duration:l.prep.split('.')[0],question:l.focus,hook:l.steps[0].model??l.steps[0].action,studentMission:l.focus,steps:l.steps.map(s=>s.action),product:l.product,learningModes:['Teacher model','Partner rehearsal','Oral storytelling','Listening and revision'],connections:['Career: optional reflection on hosting'],materials:['Your Ultimate Werewolf deck; selected role order; supplied cue planner and moderator framework','Paper, pencils and a timer'],teacherPrep:[l.prep],lookFors:['Clear sequence','Purposeful vocal expression','Listening and a useful question','Revision after feedback'],spacesUse:'none',spacesPrompt:'Keep practice in class; choose an occasional example for an existing reflection.'}));
export const werewolfContracts:Record<string,StudentLessonContract> = Object.fromEntries(werewolfLessons.map(l=>[l.id,{id:l.id,reviewState:'reviewed',challenge:l.focus,why:l.focus,firstAction:l.steps[0].action,materials:['Supplied rules and narrator script','Role cards for game sessions','Cue planner, paper and pencil'],choices:[],steps:l.steps.map(s=>({title:s.title,action:[s.action,s.model?`Model: ${s.model}`:''].filter(Boolean).join(' '),minutes:s.minutes,finishCheck:s.check})),finishEvidence:[l.product,l.steps[2].check,l.steps[3].check],saveAction:{kind:'keep-in-class',message:'Keep your cue sheet and feedback in class. No new upload is required.'},readiness:'teach'}]));
export const werewolfLessonFor=(id:string)=>werewolfLessons.find(l=>l.id===id);
