import React from "react";
import ReactDOM from "react-dom/client";
import Home from "../app/page";
import "../app/globals.css";
import "../app/readability.css";
import "../app/unit2-mixtures.css";
import "../app/forces-audit.css";
import "../app/social-studies.css";
import "../app/social-unit2.css";
import "../app/social-unit3.css";
import "../app/social-unit4.css";
import "../app/surrey-election-2026.css";
import "../app/surrey-election-2026-activities.css";
import "../app/public-window-bridge.css";
import "../app/recent-updates.css";
import "../app/learning-program.css";
import "../app/readiness-launch.css";
import "../app/math-program.css";
import "../app/infographic-system.css";
import "../app/cross-curricular-projects.css";
import "../app/unit-worlds.css";
import "../app/student-mission.css";
import "../app/projector-lesson.css";
import "../app/projector-case-deck.css";
import "../app/teacher-run-sheet.css";
import "../app/ttoc-day-plan.css";
import "../app/weekly-plan.css";
import "../app/first-week-mission.css";
import "../app/current-connection.css";
import "../app/site-search.css";
import "../app/student-teacher-layer.css";
import "../app/student-agency-hub.css";
import "../app/ela-source-mosaic-lab.css";
import "../app/ela-edit-room-lab.css";
import "../app/four-arts-lab.css";
import "../app/math-pattern-lab.css";
import "../app/math-equation-lab.css";
import "../app/math-geometry-screen-lab.css";
import "../app/math-scoreboard-lab.css";
import "../app/math-number-scale-lab.css";
import "../app/science-mission-log.css";
import "../app/social-unit2-workbench.css";
import "../app/classroom-audit.css";
import "../app/teaching-os-map.css";
import "../app/teacher-now.css";
import "../app/ai-activity-studio.css";
import "../app/ai-tensions-lab.css";
import "../app/teacher-home-operations.css";
import "../app/monthly-calendar.css";
import "../app/visual-review-studio.css";

document.documentElement.style.setProperty("--font-geist-sans", "Inter, ui-sans-serif, system-ui, sans-serif");
document.documentElement.style.setProperty("--font-geist-mono", "ui-monospace, SFMono-Regular, Menlo, monospace");

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode><Home /></React.StrictMode>,
);
